import type { Subject } from "./types";

export type TopicEntry = {
  topic: string;
  description: string;
  emoji: string;
  grades: { min: number; max: number };
};

export const TOPIC_MAP: Record<Subject, TopicEntry[]> = {
  "Social Studies": [
    { topic: "Our World",              description: "Maps, globes, directions, continents, and oceans",                       emoji: "🌍", grades: { min: 3, max: 5 } },
    { topic: "Indian Geography",       description: "States, rivers, mountains, deserts, and climate zones of India",          emoji: "🗺️", grades: { min: 4, max: 10 } },
    { topic: "World Geography",        description: "Continents, countries, capitals, oceans, and world landmarks",            emoji: "🌐", grades: { min: 5, max: 10 } },
    { topic: "Ancient Indian History", description: "Indus Valley, Vedic era, Mauryan and Gupta empires",                     emoji: "🏛️", grades: { min: 4, max: 10 } },
    { topic: "Medieval Indian History",description: "Delhi Sultanate, Mughal Empire, Vijayanagara, Maratha empire",           emoji: "🕌", grades: { min: 5, max: 10 } },
    { topic: "Modern Indian History",  description: "British rule, freedom struggle, independence movement, key leaders",     emoji: "🇮🇳", grades: { min: 5, max: 10 } },
    { topic: "Indian Civics",          description: "Constitution, fundamental rights, Parliament, government structure",      emoji: "⚖️", grades: { min: 6, max: 10 } },
    { topic: "Environment & Ecology",  description: "Ecosystems, food chains, conservation, climate change, natural resources", emoji: "🌿", grades: { min: 3, max: 8 } },
    { topic: "Culture & Heritage",     description: "Indian festivals, art forms, dance, music, and traditions",               emoji: "🎭", grades: { min: 4, max: 8 } },
    { topic: "Natural Disasters",      description: "Earthquakes, floods, volcanoes, cyclones, tsunamis, and disaster management", emoji: "🌪️", grades: { min: 4, max: 8 } },
    { topic: "Economics Basics",       description: "Markets, supply-demand, resources, money, and trade concepts",           emoji: "💰", grades: { min: 8, max: 10 } },
    { topic: "Current Affairs",        description: "Recent events, world affairs, national news, and global issues",          emoji: "📰", grades: { min: 5, max: 10 } },
  ],
  Math: [
    { topic: "Shapes and Patterns",     description: "Basic 2D shapes, patterns, counting",             emoji: "🔷", grades: { min: 1, max: 3 } },
    { topic: "Number Systems",          description: "Natural, whole, rational, prime numbers",           emoji: "🔢", grades: { min: 1, max: 8 } },
    { topic: "Addition and Subtraction",description: "Mental math, carrying, word problems",              emoji: "➕", grades: { min: 1, max: 4 } },
    { topic: "Multiplication",          description: "Tables, long multiplication, properties",           emoji: "✖️", grades: { min: 2, max: 5 } },
    { topic: "Division",                description: "Long division, remainders, word problems",          emoji: "➗", grades: { min: 2, max: 6 } },
    { topic: "Fractions",               description: "Types, operations, comparison of fractions",        emoji: "½", grades: { min: 3, max: 7 } },
    { topic: "Decimals",                description: "Decimal notation, place value, operations",         emoji: "🔟", grades: { min: 3, max: 8 } },
    { topic: "Integers",                description: "Negative numbers, number line, operations",         emoji: "🔴", grades: { min: 5, max: 8 } },
    { topic: "Ratio and Proportion",    description: "Ratios, proportions, unitary method, %",           emoji: "⚖️", grades: { min: 5, max: 10 } },
    { topic: "Mensuration",             description: "Perimeter, area, volume of 2D and 3D shapes",      emoji: "📏", grades: { min: 4, max: 12 } },
    { topic: "Geometry",                description: "Shapes, angles, lines, polygons, symmetry",        emoji: "📐", grades: { min: 1, max: 12 } },
    { topic: "Data Handling",           description: "Bar graphs, pie charts, averages, probability",    emoji: "📊", grades: { min: 3, max: 12 } },
    { topic: "Time and Work",           description: "Speed, distance, time, pipes and cisterns",        emoji: "⏱️", grades: { min: 4, max: 10 } },
    { topic: "Algebra",                 description: "Variables, linear equations, expressions",          emoji: "🔣", grades: { min: 6, max: 12 } },
    { topic: "Exponents and Powers",    description: "Laws of exponents, scientific notation",           emoji: "⚡", grades: { min: 7, max: 10 } },
    { topic: "Polynomials",             description: "Expressions, factoring, roots, identities",         emoji: "📈", grades: { min: 8, max: 12 } },
    { topic: "Quadratic Equations",     description: "Roots, discriminant, vertex form",                 emoji: "🎯", grades: { min: 9, max: 12 } },
    { topic: "Coordinate Geometry",     description: "Plotting points, distance, slope, midpoint",       emoji: "🗺️", grades: { min: 9, max: 12 } },
    { topic: "Trigonometry",            description: "Sin, cos, tan, heights and distances",             emoji: "📡", grades: { min: 9, max: 12 } },
    { topic: "Statistics",              description: "Mean, median, mode, standard deviation",            emoji: "📉", grades: { min: 9, max: 12 } },
    { topic: "Probability",             description: "Basic probability, events, sample space",           emoji: "🎲", grades: { min: 8, max: 12 } },
    { topic: "Permutations and Combinations", description: "Counting principles, nPr, nCr",             emoji: "🔀", grades: { min: 11, max: 12 } },
    { topic: "Limits and Calculus",     description: "Limits, derivatives, basic integration",           emoji: "∞", grades: { min: 11, max: 12 } },
  ],
  Science: [
    { topic: "Plants",             description: "Photosynthesis, parts of a plant, nutrition",           emoji: "🌱", grades: { min: 1, max: 8 } },
    { topic: "Animals",            description: "Classification, habitats, food chains",                  emoji: "🦁", grades: { min: 1, max: 8 } },
    { topic: "Human Body",         description: "Organs, systems, nutrition, health",                    emoji: "🫀", grades: { min: 1, max: 10 } },
    { topic: "Environment",        description: "Pollution, ecosystems, conservation",                   emoji: "🌍", grades: { min: 1, max: 8 } },
    { topic: "Force and Motion",   description: "Types of force, Newton's laws, friction",               emoji: "🏃", grades: { min: 3, max: 12 } },
    { topic: "Light",              description: "Reflection, refraction, lenses, colours",               emoji: "💡", grades: { min: 3, max: 12 } },
    { topic: "Sound",              description: "Properties of sound, echo, noise",                      emoji: "🔊", grades: { min: 3, max: 10 } },
    { topic: "Electricity",        description: "Circuits, conductors, cells, appliances",               emoji: "⚡", grades: { min: 4, max: 12 } },
    { topic: "Magnetism",          description: "Magnets, poles, compasses, electromagnets",             emoji: "🧲", grades: { min: 4, max: 10 } },
    { topic: "Matter",             description: "States of matter, changes, properties",                 emoji: "🧪", grades: { min: 4, max: 10 } },
    { topic: "Space and Universe", description: "Solar system, stars, planets, moon phases",             emoji: "🚀", grades: { min: 4, max: 10 } },
    { topic: "Cells",              description: "Cell structure, plant vs animal cells, functions",       emoji: "🔬", grades: { min: 6, max: 12 } },
    { topic: "Chemistry Basics",   description: "Elements, compounds, mixtures, reactions",              emoji: "⚗️", grades: { min: 6, max: 12 } },
    { topic: "Atoms and Molecules",description: "Atomic structure, periodic table, bonding",             emoji: "⚛️", grades: { min: 8, max: 12 } },
    { topic: "Acids and Bases",    description: "pH, indicators, neutralisation reactions",              emoji: "🧫", grades: { min: 7, max: 12 } },
    { topic: "Genetics and Evolution", description: "DNA, heredity, natural selection",                  emoji: "🧬", grades: { min: 9, max: 12 } },
    { topic: "Thermodynamics",     description: "Heat, temperature, laws of thermodynamics",             emoji: "🔥", grades: { min: 9, max: 12 } },
    { topic: "Waves and Optics",   description: "Wave properties, interference, diffraction",            emoji: "🌊", grades: { min: 9, max: 12 } },
    { topic: "Work and Energy",    description: "Kinetic, potential energy, power, conservation",        emoji: "💪", grades: { min: 6, max: 12 } },
  ],
  English: [
    { topic: "Vocabulary",          description: "Word meanings, usage, word families",                  emoji: "📚", grades: { min: 1, max: 12 } },
    { topic: "Synonyms",            description: "Words with similar meanings",                          emoji: "🟰", grades: { min: 2, max: 12 } },
    { topic: "Antonyms",            description: "Words with opposite meanings",                         emoji: "↔️", grades: { min: 2, max: 12 } },
    { topic: "Tenses",              description: "Present, past, future and their forms",                emoji: "🕐", grades: { min: 3, max: 12 } },
    { topic: "Articles",            description: "A, an, the — rules and exceptions",                   emoji: "🔤", grades: { min: 3, max: 10 } },
    { topic: "Prepositions",        description: "In, on, at, by, with and their usage",                emoji: "📍", grades: { min: 3, max: 10 } },
    { topic: "Spelling",            description: "Correct spelling, common errors",                      emoji: "🔡", grades: { min: 1, max: 6 } },
    { topic: "Sentence Completion", description: "Completing sentences with correct words",              emoji: "✍️", grades: { min: 4, max: 12 } },
    { topic: "Comprehension",       description: "Reading passages and answering questions",             emoji: "📖", grades: { min: 4, max: 12 } },
    { topic: "Grammar",             description: "Parts of speech, punctuation, sentence types",         emoji: "🔤", grades: { min: 1, max: 12 } },
    { topic: "Active Passive Voice",description: "Converting between active and passive",                emoji: "🔄", grades: { min: 6, max: 12 } },
    { topic: "Reported Speech",     description: "Direct to indirect speech conversion",                 emoji: "💬", grades: { min: 7, max: 12 } },
    { topic: "Reading Skills",      description: "Inference, main idea, author's purpose",               emoji: "🧩", grades: { min: 8, max: 12 } },
  ],
  Hindi: [
    { topic: "Varnamala",          description: "स्वर, व्यंजन, मात्राएँ",                               emoji: "अ", grades: { min: 3, max: 5 } },
    { topic: "Grammar",            description: "संज्ञा, सर्वनाम, क्रिया, विशेषण",                     emoji: "📝", grades: { min: 3, max: 10 } },
    { topic: "Vocabulary",         description: "शब्द भंडार और प्रयोग",                                  emoji: "📚", grades: { min: 3, max: 10 } },
    { topic: "Synonyms",           description: "समानार्थी शब्द",                                         emoji: "🟰", grades: { min: 4, max: 10 } },
    { topic: "Antonyms",           description: "विलोम शब्द",                                             emoji: "↔️", grades: { min: 4, max: 10 } },
    { topic: "Comprehension",      description: "गद्यांश पढ़कर प्रश्नोत्तर",                              emoji: "📖", grades: { min: 5, max: 10 } },
    { topic: "Idioms",             description: "मुहावरे और लोकोक्तियाँ",                                emoji: "💬", grades: { min: 6, max: 10 } },
    { topic: "Sandhi",             description: "स्वर, व्यंजन और विसर्ग संधि",                           emoji: "🔗", grades: { min: 7, max: 10 } },
    { topic: "Samaas",             description: "समास के भेद और उदाहरण",                                 emoji: "🔣", grades: { min: 7, max: 10 } },
    { topic: "Sentence Correction",description: "वाक्य-शुद्धि और अशुद्धि",                               emoji: "✅", grades: { min: 5, max: 10 } },
  ],
  "General Knowledge": [
    { topic: "My World",              description: "Family, school, community basics",                   emoji: "🏠", grades: { min: 1, max: 4 } },
    { topic: "Animals and Plants",    description: "Birds, insects, trees, habitats",                    emoji: "🌿", grades: { min: 1, max: 5 } },
    { topic: "Indian History",        description: "Ancient, medieval, modern India",                    emoji: "🏛️", grades: { min: 4, max: 10 } },
    { topic: "Geography",             description: "Maps, rivers, mountains, capitals",                  emoji: "🗺️", grades: { min: 4, max: 10 } },
    { topic: "Indian Polity",         description: "Constitution, government, parliament",               emoji: "🏛️", grades: { min: 6, max: 10 } },
    { topic: "Sports",                description: "Famous players, tournaments, records",               emoji: "🏆", grades: { min: 3, max: 10 } },
    { topic: "Science and Inventions",description: "Discoveries, scientists, inventions",                emoji: "🔭", grades: { min: 4, max: 10 } },
    { topic: "Books and Authors",     description: "Famous works, Nobel laureates",                     emoji: "📗", grades: { min: 5, max: 10 } },
    { topic: "Famous Personalities",  description: "Leaders, artists, achievers",                       emoji: "🌟", grades: { min: 4, max: 10 } },
    { topic: "World Facts",           description: "Countries, capitals, oceans, landmarks",             emoji: "🌐", grades: { min: 5, max: 10 } },
    { topic: "Awards and Honours",    description: "Padma, Bharat Ratna, Nobel, Oscar",                 emoji: "🎖️", grades: { min: 6, max: 10 } },
  ],
  "Logical Reasoning": [
    { topic: "Patterns",            description: "Visual and number patterns, sequences",                emoji: "🔷", grades: { min: 1, max: 12 } },
    { topic: "Number Series",       description: "Find the next term in a number pattern",               emoji: "🔢", grades: { min: 2, max: 12 } },
    { topic: "Odd One Out",         description: "Find the item that doesn't belong",                   emoji: "🔍", grades: { min: 1, max: 12 } },
    { topic: "Mirror Images",       description: "Identify the mirror or water image",                  emoji: "🪞", grades: { min: 3, max: 12 } },
    { topic: "Analogies",           description: "Word pairs and relationships",                         emoji: "🔗", grades: { min: 4, max: 12 } },
    { topic: "Coding-Decoding",     description: "Encode and decode messages using rules",               emoji: "🔐", grades: { min: 4, max: 12 } },
    { topic: "Direction Sense",     description: "Navigate using N/S/E/W directions",                   emoji: "🧭", grades: { min: 4, max: 12 } },
    { topic: "Blood Relations",     description: "Family tree and relationship problems",                emoji: "👨‍👩‍👧", grades: { min: 5, max: 12 } },
    { topic: "Syllogisms",          description: "Logical conclusions from given statements",            emoji: "🧠", grades: { min: 6, max: 12 } },
    { topic: "Ranking",             description: "Ordering items by rank from given clues",              emoji: "🏅", grades: { min: 5, max: 12 } },
    { topic: "Data Interpretation", description: "Tables, bar/pie charts, case-based questions",        emoji: "📊", grades: { min: 7, max: 12 } },
    { topic: "Puzzles",             description: "Grid puzzles, seating arrangement, scheduling",       emoji: "🧩", grades: { min: 8, max: 12 } },
  ],
  Computers: [
    { topic: "Basic Computer Skills",description: "Mouse, keyboard, desktop, files and folders",        emoji: "🖥️", grades: { min: 1, max: 4 } },
    { topic: "Hardware",             description: "CPU, RAM, storage, input/output devices",            emoji: "💻", grades: { min: 3, max: 10 } },
    { topic: "MS Word",              description: "Document creation, formatting, shortcuts",            emoji: "📄", grades: { min: 4, max: 10 } },
    { topic: "MS Excel",             description: "Spreadsheets, formulas, charts",                     emoji: "📊", grades: { min: 5, max: 10 } },
    { topic: "Internet Safety",      description: "Passwords, privacy, cyber threats",                  emoji: "🔒", grades: { min: 3, max: 10 } },
    { topic: "Networking Basics",    description: "LAN, WAN, IP, routers, browsers",                   emoji: "🌐", grades: { min: 6, max: 10 } },
    { topic: "Binary and Logic",     description: "Binary numbers, AND/OR/NOT gates",                  emoji: "🔡", grades: { min: 6, max: 10 } },
    { topic: "Algorithms",           description: "Step-by-step problem solving, flowcharts",           emoji: "📋", grades: { min: 5, max: 10 } },
    { topic: "Flowcharts",           description: "Symbols, decision boxes, loops in flowcharts",       emoji: "🔀", grades: { min: 5, max: 10 } },
    { topic: "Python Basics",        description: "Variables, loops, conditionals, functions",          emoji: "🐍", grades: { min: 7, max: 10 } },
    { topic: "HTML Basics",          description: "Tags, structure, links, images",                     emoji: "🌐", grades: { min: 8, max: 10 } },
  ],
  AI: [
    { topic: "AI Concepts",                    description: "What is AI, types, real-world uses",       emoji: "🤖", grades: { min: 1, max: 10 } },
    { topic: "Smart Devices",                  description: "IoT, smart homes, wearables",             emoji: "📱", grades: { min: 1, max: 6 } },
    { topic: "Chatbots and Voice Assistants",  description: "How Alexa, Siri, chatbots work",          emoji: "🎙️", grades: { min: 3, max: 10 } },
    { topic: "Machine Learning Basics",        description: "Training, datasets, predictions",          emoji: "📈", grades: { min: 5, max: 10 } },
    { topic: "Computer Vision",                description: "Image recognition, cameras, OCR",         emoji: "👁️", grades: { min: 6, max: 10 } },
    { topic: "Natural Language Processing",    description: "Text understanding, chatbots, speech",    emoji: "💬", grades: { min: 6, max: 10 } },
    { topic: "Robotics",                       description: "Sensors, actuators, automation",          emoji: "🦾", grades: { min: 4, max: 10 } },
    { topic: "Neural Networks",                description: "Layers, neurons, deep learning basics",   emoji: "🧠", grades: { min: 8, max: 10 } },
    { topic: "AI Ethics",                      description: "Bias, fairness, privacy, safety",         emoji: "⚖️", grades: { min: 6, max: 10 } },
    { topic: "Data and Bias",                  description: "Data collection, bias in AI models",      emoji: "📂", grades: { min: 7, max: 10 } },
  ],
  "Spell Bee": [
    { topic: "Spelling Rules",                 description: "Phonics, silent letters, and common rules",emoji: "📝", grades: { min: 1, max: 12 } },
    { topic: "Vocabulary",                     description: "Word meanings, synonyms, and antonyms",    emoji: "📚", grades: { min: 1, max: 12 } },
    { topic: "Word Usage",                     description: "Correct usage of words in sentences",      emoji: "✍️", grades: { min: 1, max: 12 } },
    { topic: "Prefixes & Suffixes",            description: "Root words and affixes",                   emoji: "🔗", grades: { min: 3, max: 12 } },
    { topic: "Homophones & Homonyms",          description: "Words that sound or look the same",        emoji: "🔄", grades: { min: 2, max: 12 } },
    { topic: "Idioms & Phrases",               description: "Common English idioms and expressions",    emoji: "💬", grades: { min: 4, max: 12 } },
  ],
};
