import type { Subject } from "./types";

export type TopicEntry = {
  topic: string;
  description: string;
  emoji: string;
};

export const TOPIC_MAP: Record<Subject, TopicEntry[]> = {
  Math: [
    { topic: "Number Systems",       description: "Natural, whole, rational, prime & composite numbers", emoji: "🔢" },
    { topic: "Fractions",            description: "Types, operations, comparison of fractions",           emoji: "½" },
    { topic: "Decimals",             description: "Decimal notation, place value, operations",            emoji: "🔟" },
    { topic: "Integers",             description: "Negative numbers, number line, operations",            emoji: "➕" },
    { topic: "Ratio and Proportion", description: "Ratios, proportions, unitary method, percentages",     emoji: "⚖️" },
    { topic: "Algebra",              description: "Variables, linear equations, expressions",             emoji: "🔣" },
    { topic: "Geometry",             description: "Shapes, angles, lines, polygons, symmetry",           emoji: "📐" },
    { topic: "Mensuration",          description: "Perimeter, area, volume of 2D and 3D shapes",         emoji: "📏" },
    { topic: "Data Handling",        description: "Bar graphs, pie charts, averages, probability",        emoji: "📊" },
    { topic: "Time and Work",        description: "Speed, distance, time, pipes and cisterns",            emoji: "⏱️" },
    { topic: "Polynomials",          description: "Expressions, factoring, roots, identities",            emoji: "📈" },
    { topic: "Trigonometry",         description: "Sin, cos, tan, heights and distances",                 emoji: "📡" },
    { topic: "Statistics",           description: "Mean, median, mode, standard deviation",               emoji: "📉" },
    { topic: "Probability",          description: "Basic probability, events, sample space",              emoji: "🎲" },
  ],
  Science: [
    { topic: "Plants",             description: "Photosynthesis, parts of a plant, nutrition",           emoji: "🌱" },
    { topic: "Human Body",         description: "Organs, systems, nutrition, health",                    emoji: "🫀" },
    { topic: "Animals",            description: "Classification, habitats, food chains",                  emoji: "🦁" },
    { topic: "Force and Motion",   description: "Types of force, Newton's laws, friction",               emoji: "🏃" },
    { topic: "Light",              description: "Reflection, refraction, lenses, colours",               emoji: "💡" },
    { topic: "Sound",              description: "Properties of sound, echo, noise",                     emoji: "🔊" },
    { topic: "Electricity",        description: "Circuits, conductors, cells, appliances",               emoji: "⚡" },
    { topic: "Magnetism",          description: "Magnets, poles, compasses, electromagnets",             emoji: "🧲" },
    { topic: "Matter",             description: "States of matter, changes, properties",                 emoji: "🧪" },
    { topic: "Cells",              description: "Cell structure, plant vs animal cells, functions",       emoji: "🔬" },
    { topic: "Chemistry Basics",   description: "Elements, compounds, mixtures, reactions",              emoji: "⚗️" },
    { topic: "Environment",        description: "Pollution, ecosystems, conservation",                   emoji: "🌍" },
    { topic: "Space and Universe", description: "Solar system, stars, planets, moon phases",             emoji: "🚀" },
  ],
  English: [
    { topic: "Vocabulary",          description: "Word meanings, usage, word families",                  emoji: "📚" },
    { topic: "Synonyms",            description: "Words with similar meanings",                          emoji: "🟰" },
    { topic: "Antonyms",            description: "Words with opposite meanings",                         emoji: "↔️" },
    { topic: "Tenses",              description: "Present, past, future and their forms",                emoji: "🕐" },
    { topic: "Articles",            description: "A, an, the — rules and exceptions",                    emoji: "🔤" },
    { topic: "Prepositions",        description: "In, on, at, by, with and their usage",                emoji: "📍" },
    { topic: "Sentence Completion", description: "Completing sentences with correct words",              emoji: "✍️" },
    { topic: "Comprehension",       description: "Reading passages and answering questions",             emoji: "📖" },
    { topic: "Grammar",             description: "Parts of speech, punctuation, sentence types",         emoji: "🔤" },
    { topic: "Spelling",            description: "Correct spelling, common errors",                      emoji: "🔡" },
  ],
  Hindi: [
    { topic: "Grammar",            description: "व्याकरण — संज्ञा, सर्वनाम, क्रिया, विशेषण",           emoji: "📝" },
    { topic: "Vocabulary",         description: "शब्द भंडार और प्रयोग",                                  emoji: "📚" },
    { topic: "Synonyms",           description: "समानार्थी शब्द",                                         emoji: "🟰" },
    { topic: "Antonyms",           description: "विलोम शब्द",                                             emoji: "↔️" },
    { topic: "Comprehension",      description: "गद्यांश पढ़कर प्रश्नोत्तर",                              emoji: "📖" },
    { topic: "Idioms",             description: "मुहावरे और लोकोक्तियाँ",                                emoji: "💬" },
    { topic: "Sandhi",             description: "स्वर, व्यंजन और विसर्ग संधि",                          emoji: "🔗" },
    { topic: "Samaas",             description: "समास के भेद और उदाहरण",                                 emoji: "🔣" },
    { topic: "Sentence Correction",description: "वाक्य-शुद्धि",                                          emoji: "✅" },
  ],
  "General Knowledge": [
    { topic: "Indian History",        description: "Ancient, medieval, modern India",                    emoji: "🏛️" },
    { topic: "Geography",             description: "Maps, rivers, mountains, capitals",                  emoji: "🗺️" },
    { topic: "Indian Polity",         description: "Constitution, government, parliament",               emoji: "🏛️" },
    { topic: "Sports",                description: "Famous players, tournaments, records",               emoji: "🏆" },
    { topic: "Science and Inventions",description: "Discoveries, scientists, inventions",               emoji: "🔭" },
    { topic: "Books and Authors",     description: "Famous works, Nobel laureates",                     emoji: "📗" },
    { topic: "Famous Personalities",  description: "Leaders, artists, achievers",                       emoji: "🌟" },
    { topic: "World Facts",           description: "Countries, capitals, oceans, landmarks",            emoji: "🌐" },
    { topic: "Awards and Honours",    description: "Padma, Bharat Ratna, Nobel, Oscar",                 emoji: "🎖️" },
  ],
  "Logical Reasoning": [
    { topic: "Number Series",   description: "Find the next term in a pattern",                         emoji: "🔢" },
    { topic: "Patterns",        description: "Visual patterns, shape sequences",                         emoji: "🔷" },
    { topic: "Analogies",       description: "Word pairs and relationships",                             emoji: "🔗" },
    { topic: "Coding-Decoding", description: "Encode and decode messages using rules",                  emoji: "🔐" },
    { topic: "Direction Sense", description: "Navigate using N/S/E/W directions",                       emoji: "🧭" },
    { topic: "Blood Relations", description: "Family tree and relationship problems",                    emoji: "👨‍👩‍👧" },
    { topic: "Syllogisms",      description: "Logical conclusions from statements",                     emoji: "🧠" },
    { topic: "Mirror Images",   description: "Identify the mirror/water image",                         emoji: "🪞" },
    { topic: "Odd One Out",     description: "Find the item that doesn't belong",                       emoji: "🔍" },
    { topic: "Ranking",         description: "Ordering items by rank from given clues",                 emoji: "🏅" },
  ],
  Computers: [
    { topic: "Hardware",         description: "CPU, RAM, storage, input/output devices",                emoji: "💻" },
    { topic: "MS Word",          description: "Document creation, formatting, shortcuts",               emoji: "📄" },
    { topic: "MS Excel",         description: "Spreadsheets, formulas, charts",                         emoji: "📊" },
    { topic: "Internet Safety",  description: "Passwords, privacy, cyber threats",                      emoji: "🔒" },
    { topic: "Networking Basics",description: "LAN, WAN, IP, routers, browsers",                       emoji: "🌐" },
    { topic: "Binary and Logic", description: "Binary numbers, AND/OR/NOT gates",                       emoji: "🔡" },
    { topic: "Algorithms",       description: "Step-by-step problem solving, flowcharts",               emoji: "📋" },
    { topic: "Python Basics",    description: "Variables, loops, conditionals, functions",               emoji: "🐍" },
    { topic: "HTML Basics",      description: "Tags, structure, links, images",                         emoji: "🌐" },
    { topic: "Flowcharts",       description: "Symbols, decision boxes, loops",                         emoji: "🔀" },
  ],
  AI: [
    { topic: "AI Concepts",                    description: "What is AI, types, real-world uses",       emoji: "🤖" },
    { topic: "Machine Learning Basics",        description: "Training, datasets, predictions",          emoji: "📈" },
    { topic: "Neural Networks",                description: "Layers, neurons, deep learning basics",    emoji: "🧠" },
    { topic: "Computer Vision",                description: "Image recognition, cameras, OCR",         emoji: "👁️" },
    { topic: "Natural Language Processing",    description: "Text understanding, chatbots, speech",    emoji: "💬" },
    { topic: "Robotics",                       description: "Sensors, actuators, automation",          emoji: "🦾" },
    { topic: "Smart Devices",                  description: "IoT, smart homes, wearables",             emoji: "📱" },
    { topic: "Chatbots and Voice Assistants",  description: "How Alexa, Siri, chatbots work",          emoji: "🎙️" },
    { topic: "AI Ethics",                      description: "Bias, fairness, privacy, safety",         emoji: "⚖️" },
    { topic: "Data and Bias",                  description: "Data collection, bias in AI models",      emoji: "📂" },
  ],
};
