export const LANDING_FAQS = [
  {
    q: "Is OlympiadReady free to use?",
    a: "Yes. Every student gets 5 free practice papers across any subject and class, plus 10 free AI chatbot sessions — no credit card required. Paid plans unlock unlimited practice for ₹129 per subject per month."
  },
  {
    q: "Which Olympiads does OlympiadReady cover?",
    a: "OlympiadReady covers all major school Olympiads — IMO (Maths), NSO (Science), IEO (English), IGKO (GK), ICSO (Computer Science), Spell Bee, Hindi Olympiad, Social Studies, and AI Olympiad, for Classes 1–12."
  },
  {
    q: "How are the questions generated?",
    a: "Questions are generated by AI trained on the official syllabi of SOF, Silverzone, Unified Council and other Olympiad bodies. Every paper is unique — the same questions never repeat."
  },
  {
    q: "Can I prepare for both Level 1 and Level 2?",
    a: "Yes. You can select the difficulty level when generating a paper, including a dedicated Olympiad Level setting calibrated to Level 1 or Level 2 pattern and difficulty."
  },
  {
    q: "Does it work for all classes from 1 to 12?",
    a: "Yes. Content is available for every class from 1 to 12, with questions matched to the exact syllabus and difficulty appropriate for that class."
  },
  {
    q: "What is the AI doubt chatbot?",
    a: "After each question, students can open an interactive AI chatbot to ask follow-up questions, request a step-by-step explanation, or explore the concept further. Free users get 10 chatbot sessions; subscribers get unlimited."
  },
  {
    q: "Can I download practice papers as PDFs?",
    a: "Yes. Subscribers can download up to 10 full-length 50-question PDF papers per week per subscribed subject. The limit resets every Monday."
  },
  {
    q: "Is there a mock exam feature?",
    a: "Yes. The Mock Exams section offers full-length, timed papers in exam-hall simulation mode — including an OMR sheet view on completion — so students experience the real exam environment."
  }
];
