import pyodbc, json, uuid, sys
sys.stdout.reconfigure(encoding='utf-8', errors='replace')

DB_CONN = (
    "DRIVER={ODBC Driver 18 for SQL Server};"
    "SERVER=tcp:olympiadready-np.database.windows.net,1433;"
    "DATABASE=OlympiadReady;UID=nyxen-admin;PWD=Olympiad@2026;"
    "Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30"
)

def insert(conn, q):
    c = conn.cursor()
    c.execute("SELECT 1 FROM QuestionBank WHERE Subject=? AND Grade=? AND SubTopic=? AND QuestionText=?",
              q["subject"], q["grade"], q["subTopic"], q["questionText"])
    if c.fetchone():
        return "DUP"
    c.execute("""INSERT INTO QuestionBank
                 (QuestionBankId,Subject,Grade,Difficulty,Topic,SubTopic,
                  QuestionText,OptionsJson,CorrectAnswer,Explanation,CreatedAt)
                 VALUES (?,?,?,?,?,?,?,?,?,?,GETUTCDATE())""",
              str(uuid.uuid4()).upper(), q["subject"], q["grade"], q["difficulty"],
              q["topic"], q["subTopic"], q["questionText"],
              json.dumps(q["options"]), q["correctAnswer"], q["explanation"])
    conn.commit()
    return "OK"

BIO10_ADV = [
    {"subject":"Science-Biology","grade":10,"difficulty":"Advanced","topic":"Life Processes","subTopic":"Nutrition in Plants and Animals",
     "questionText":"Which enzyme in the human stomach begins the digestion of proteins?",
     "options":["A: Amylase","B: Lipase","C: Pepsin","D: Trypsin"],"correctAnswer":"C",
     "explanation":"Pepsin is secreted by gastric glands in the stomach as inactive pepsinogen, activated by HCl. It hydrolyses proteins into peptides. Amylase digests starch; lipase digests fats; trypsin works in the small intestine."},
    {"subject":"Science-Biology","grade":10,"difficulty":"Advanced","topic":"Life Processes","subTopic":"Respiration",
     "questionText":"In aerobic respiration, where does the Krebs cycle take place?",
     "options":["A: Cytoplasm","B: Nucleus","C: Mitochondrial matrix","D: Inner mitochondrial membrane"],"correctAnswer":"C",
     "explanation":"The Krebs (citric acid) cycle occurs in the mitochondrial matrix. Glycolysis happens in the cytoplasm; the electron transport chain is on the inner mitochondrial membrane."},
    {"subject":"Science-Biology","grade":10,"difficulty":"Advanced","topic":"Life Processes","subTopic":"Transportation in Plants",
     "questionText":"Water moves up a plant stem against gravity primarily because of:",
     "options":["A: Root pressure alone","B: Transpiration pull creating tension in the xylem column","C: Osmosis in phloem","D: Active pumping by xylem cells"],"correctAnswer":"B",
     "explanation":"Transpiration pull (cohesion-tension mechanism) is the main driver. Water evaporates from leaves, creating tension that pulls the continuous water column up through xylem. The cohesion of water molecules (hydrogen bonds) keeps the column intact."},
    {"subject":"Science-Biology","grade":10,"difficulty":"Advanced","topic":"Control and Coordination","subTopic":"Nervous System",
     "questionText":"A reflex arc bypasses the brain. The correct sequence of a reflex arc is:",
     "options":["A: Receptor → Sensory neuron → Brain → Motor neuron → Effector","B: Receptor → Sensory neuron → Spinal cord → Motor neuron → Effector","C: Effector → Motor neuron → Brain → Sensory neuron → Receptor","D: Receptor → Motor neuron → Spinal cord → Sensory neuron → Effector"],"correctAnswer":"B",
     "explanation":"In a reflex arc: stimulus → receptor → sensory (afferent) neuron → spinal cord relay neuron → motor (efferent) neuron → effector (muscle/gland). The response occurs without waiting for brain processing, making it faster."},
    {"subject":"Science-Biology","grade":10,"difficulty":"Advanced","topic":"Control and Coordination","subTopic":"Hormones",
     "questionText":"Insulin and glucagon are both secreted by the pancreas. Their relationship is best described as:",
     "options":["A: Synergistic — both raise blood glucose","B: Antagonistic — insulin lowers blood glucose, glucagon raises it","C: Both lower blood glucose","D: Insulin raises and glucagon lowers blood glucose"],"correctAnswer":"B",
     "explanation":"Insulin (from beta cells) lowers blood glucose by promoting glucose uptake into cells and glycogen synthesis. Glucagon (from alpha cells) raises blood glucose by stimulating glycogen breakdown (glycogenolysis) in the liver. They work antagonistically to maintain blood glucose homeostasis."},
    {"subject":"Science-Biology","grade":10,"difficulty":"Advanced","topic":"How Do Organisms Reproduce","subTopic":"Asexual Reproduction",
     "questionText":"In vegetative propagation by runners (stolons), a new plant forms at the node. This type of reproduction is advantageous because:",
     "options":["A: It increases genetic diversity","B: It produces genetically identical offspring quickly without seeds","C: It requires pollination","D: It produces seeds with better germination rates"],"correctAnswer":"B",
     "explanation":"Vegetative propagation produces clones — genetically identical copies of the parent. It is fast and reliable (no pollination/seed germination needed), useful for preserving desirable traits. The disadvantage is lack of genetic variation."},
    {"subject":"Science-Biology","grade":10,"difficulty":"Advanced","topic":"How Do Organisms Reproduce","subTopic":"Human Reproductive System",
     "questionText":"Fertilisation in humans occurs in the:",
     "options":["A: Uterus","B: Ovary","C: Fallopian tube (oviduct)","D: Cervix"],"correctAnswer":"C",
     "explanation":"Fertilisation (fusion of sperm and egg) occurs in the fallopian tube (oviduct), typically in the upper third. The fertilised egg (zygote) then travels to the uterus where it implants in the endometrium for development."},
    {"subject":"Science-Biology","grade":10,"difficulty":"Advanced","topic":"Heredity and Evolution","subTopic":"Mendel's Laws",
     "questionText":"A man with blood group A (genotype IAi) marries a woman with blood group B (genotype IBi). What fraction of their children are expected to have blood group O?",
     "options":["A: 0","B: 1/4","C: 1/2","D: 3/4"],"correctAnswer":"B",
     "explanation":"Cross: IAi × IBi. Possible offspring: IAIB (AB), IAi (A), IBi (B), ii (O). Each with probability 1/4. So 1/4 of children are expected to have blood group O."},
    {"subject":"Science-Biology","grade":10,"difficulty":"Advanced","topic":"Our Environment","subTopic":"Food Chains and Energy Flow",
     "questionText":"According to the 10% law of energy transfer in ecosystems, if producers fix 10,000 J of energy, how much energy is available at the tertiary consumer level?",
     "options":["A: 1000 J","B: 100 J","C: 10 J","D: 1 J"],"correctAnswer":"C",
     "explanation":"10% law (Lindeman): each trophic level transfers only 10% of its energy to the next. Producers: 10,000 J. Primary consumers: 1,000 J. Secondary consumers: 100 J. Tertiary consumers: 10 J. 90% is lost as heat at each level."},
    {"subject":"Science-Biology","grade":10,"difficulty":"Advanced","topic":"Our Environment","subTopic":"Ecosystem",
     "questionText":"Decomposers are essential for ecosystem functioning because they:",
     "options":["A: Produce oxygen through photosynthesis","B: Return minerals and nutrients from dead organic matter back to the soil","C: Form the base of food chains","D: Protect plants from herbivores"],"correctAnswer":"B",
     "explanation":"Decomposers (bacteria, fungi) break down dead organisms and waste, releasing nutrients (nitrogen, phosphorus, carbon) back into the soil and atmosphere. Without decomposers, nutrients would remain locked in dead matter and producers could not access them — nutrient cycles would collapse."},
    {"subject":"Science-Biology","grade":10,"difficulty":"Advanced","topic":"Management of Natural Resources","subTopic":"Conservation",
     "questionText":"The Chipko Movement (1973) in Uttarakhand was significant because it:",
     "options":["A: Protested dam construction","B: Was one of the first grassroots environmental movements where villagers hugged trees to prevent logging","C: Advocated for tiger conservation","D: Promoted organic farming"],"correctAnswer":"B",
     "explanation":"The Chipko Movement began in 1973 in Chamoli district when villagers (led by Gaura Devi and supported by Chandi Prasad Bhatt and Sundarlal Bahuguna) embraced trees to prevent commercial logging. 'Chipko' means 'to hug/cling'. It inspired worldwide environmental activism and led to a logging ban in Himalayan forests."},
    {"subject":"Science-Biology","grade":10,"difficulty":"Advanced","topic":"Life Processes","subTopic":"Excretion",
     "questionText":"The functional unit of the kidney that filters blood and forms urine is the:",
     "options":["A: Ureter","B: Nephron","C: Bowman's capsule only","D: Collecting duct"],"correctAnswer":"B",
     "explanation":"The nephron is the structural and functional unit of the kidney. Each kidney contains about 1 million nephrons. Each nephron consists of: glomerulus (filtration), Bowman's capsule, proximal convoluted tubule, Loop of Henle, distal convoluted tubule, and collecting duct — together performing filtration, reabsorption, and secretion to produce urine."},
    {"subject":"Science-Biology","grade":10,"difficulty":"Advanced","topic":"Heredity and Evolution","subTopic":"Evolution",
     "questionText":"Darwin's theory of natural selection states that organisms with favourable variations survive and reproduce. This process requires which condition to work over generations?",
     "options":["A: All individuals must be identical","B: Variations must be heritable (passed to offspring)","C: The environment must remain constant","D: Only sexual reproduction can drive evolution"],"correctAnswer":"B",
     "explanation":"Natural selection requires: (1) variation in the population, (2) heritability — variations must be passed to offspring, (3) differential survival/reproduction. If variations are not heritable, selection cannot accumulate favourable traits over generations. Hereditary variation is the raw material of evolution."},
]

BIO10_OLY = [
    {"subject":"Science-Biology","grade":10,"difficulty":"Olympiad","topic":"Life Processes","subTopic":"Photosynthesis — Light Reactions",
     "questionText":"In the light-dependent reactions of photosynthesis, water molecules are split (photolysis). The products of water splitting that are DIRECTLY used within the light reactions are:",
     "options":["A: O₂ and CO₂","B: H⁺ (protons) and electrons — used to generate ATP and NADPH; O₂ is released as a byproduct","C: Glucose and water","D: ATP and glucose"],"correctAnswer":"B",
     "explanation":"Photolysis: 2H₂O → 4H⁺ + 4e⁻ + O₂. The electrons replace those lost by chlorophyll P680 after photo-excitation; H⁺ ions drive ATP synthase via the proton gradient (chemiosmosis); NADP⁺ is reduced to NADPH using electrons and H⁺. O₂ is a byproduct released to the atmosphere — it is not used in the light reactions."},
    {"subject":"Science-Biology","grade":10,"difficulty":"Olympiad","topic":"Control and Coordination","subTopic":"Synaptic Transmission",
     "questionText":"At a chemical synapse, neurotransmitters released from the presynaptic terminal bind to receptors on the postsynaptic membrane. The neurotransmitter is then removed by which process to prevent continuous stimulation?",
     "options":["A: It is absorbed back into the postsynaptic neuron","B: It diffuses into the blood","C: It is broken down by enzymes in the synaptic cleft (e.g., acetylcholinesterase) or reuptaken into the presynaptic terminal","D: It is destroyed by the action potential"],"correctAnswer":"C",
     "explanation":"Synaptic transmission termination: (1) enzymatic degradation — acetylcholinesterase breaks acetylcholine into choline and acetate; (2) reuptake — the presynaptic terminal actively reabsorbs the neurotransmitter for recycling (important for dopamine, serotonin). Without removal, receptors would remain activated, preventing normal signalling."},
    {"subject":"Science-Biology","grade":10,"difficulty":"Olympiad","topic":"Heredity and Evolution","subTopic":"DNA and Mutations",
     "questionText":"A mutation changes a single DNA base (point mutation). Which type of mutation is MOST likely to have NO effect on the protein produced?",
     "options":["A: Frameshift mutation (insertion/deletion)","B: Nonsense mutation (creates stop codon)","C: Silent (synonymous) mutation — base change codes for the same amino acid","D: Missense mutation changing a critical active site residue"],"correctAnswer":"C",
     "explanation":"The genetic code is degenerate — multiple codons code for the same amino acid (e.g., both UCU and UCC code for serine). A silent mutation changes a base but the new codon still codes for the same amino acid, so the protein sequence is unchanged. Frameshift mutations shift the entire reading frame; nonsense mutations prematurely terminate translation."},
    {"subject":"Science-Biology","grade":10,"difficulty":"Olympiad","topic":"How Do Organisms Reproduce","subTopic":"Double Fertilisation in Plants",
     "questionText":"Double fertilisation is unique to angiosperms (flowering plants). The two fertilisation events produce:",
     "options":["A: Two embryos (twins)","B: A diploid (2n) zygote AND a triploid (3n) primary endosperm nucleus","C: A haploid embryo and a diploid seed coat","D: Two identical seeds"],"correctAnswer":"B",
     "explanation":"In double fertilisation: (1) one sperm (n) fuses with the egg cell (n) → diploid zygote (2n) → embryo; (2) the second sperm (n) fuses with the two polar nuclei (n+n) → triploid primary endosperm nucleus (3n) → endosperm (nutrient tissue for the seed). This is unique to angiosperms and maximises nutrient allocation to the developing embryo."},
    {"subject":"Science-Biology","grade":10,"difficulty":"Olympiad","topic":"Our Environment","subTopic":"Biomagnification",
     "questionText":"DDT (a pesticide) accumulates in body fat and is not excreted easily. In a food chain: plankton → small fish → large fish → osprey, DDT concentration is highest in the osprey. This phenomenon is called:",
     "options":["A: Eutrophication","B: Bioaccumulation only","C: Biomagnification — increasing concentration at each successive trophic level","D: Biodegradation"],"correctAnswer":"C",
     "explanation":"Biomagnification: as organisms consume large quantities of prey, non-biodegradable fat-soluble toxins (DDT, mercury, PCBs) concentrate at each trophic level. Plankton: ~0.000003 ppm DDT; small fish: ~0.5 ppm; large fish: ~2 ppm; osprey: ~25 ppm. This is why top predators (including humans eating large fish) are most affected."},
    {"subject":"Science-Biology","grade":10,"difficulty":"Olympiad","topic":"Life Processes","subTopic":"Blood Composition and Function",
     "questionText":"A patient has a haemoglobin level of 7 g/dL (normal: 12-17 g/dL). This is anaemia. The DIRECT consequence on gas exchange is:",
     "options":["A: Reduced CO₂ removal from tissues","B: Reduced O₂ carrying capacity — tissues receive less oxygen, causing fatigue and breathlessness","C: Increased blood pressure","D: Reduced immune response"],"correctAnswer":"B",
     "explanation":"Haemoglobin in red blood cells carries ~98% of blood oxygen. With haemoglobin at 7 g/dL (vs normal ~15 g/dL), oxygen carrying capacity is roughly halved. Tissues — especially muscles and brain — receive insufficient O₂, causing fatigue, pallor, and breathlessness even at rest. The heart compensates by beating faster (tachycardia)."},
    {"subject":"Science-Biology","grade":10,"difficulty":"Olympiad","topic":"Heredity and Evolution","subTopic":"Evidence for Evolution",
     "questionText":"Homologous structures (like the forelimbs of humans, whales, and bats) have the same basic bone arrangement but serve different functions. They provide evidence for evolution because they suggest:",
     "options":["A: All organisms are designed for the same environment","B: These species evolved the same structures independently (convergent evolution)","C: These species share a common ancestor from whom they inherited the basic limb structure (divergent evolution)","D: These structures have identical DNA sequences"],"correctAnswer":"C",
     "explanation":"Homologous structures indicate common ancestry (divergent evolution) — species inherited the same basic structural plan from a common ancestor, then adapted it differently for different functions (grasping, swimming, flying). Analogous structures (like wings of bats and insects) look similar but have different origins — that is convergent evolution."},
    {"subject":"Science-Biology","grade":10,"difficulty":"Olympiad","topic":"Management of Natural Resources","subTopic":"Water Management",
     "questionText":"Groundwater tables are falling across India due to over-extraction for irrigation. Which traditional water harvesting structure, now being revived, collects rainwater in tanks to recharge groundwater?",
     "options":["A: Bawdi (stepwells) only","B: Johads (earthen check dams in Rajasthan) — and similar structures like kunds, tankas across India","C: Biogas plants","D: Drip irrigation pipes"],"correctAnswer":"B",
     "explanation":"Johads are traditional earthen check dams built in Rajasthan to capture rainwater and allow it to percolate into the ground, recharging the water table. The work of Rajendra Singh (the 'Waterman of India') in reviving johads in Alwar district brought back rivers that had dried up. Similar structures exist across India: kunds (circular tanks), tankas (underground cisterns), baolis (stepwells)."},
    {"subject":"Science-Biology","grade":10,"difficulty":"Olympiad","topic":"Life Processes","subTopic":"Stomata and Transpiration",
     "questionText":"Guard cells control stomatal opening by changing their turgor pressure. When the guard cells become TURGID (swollen with water), the stomata:",
     "options":["A: Close, because the swelling blocks the pore","B: Open, because the thick inner wall curves outward pulling the cells apart","C: Remain unchanged","D: Open only at night"],"correctAnswer":"B",
     "explanation":"Guard cells have an asymmetric cell wall — the inner wall (facing the pore) is thick and inelastic; the outer wall is thin. When guard cells absorb water and become turgid, the thin outer wall bulges outward more than the thick inner wall, bending the cell into a crescent shape and opening the pore. When they lose water (become flaccid), they straighten and the pore closes."},
    {"subject":"Science-Biology","grade":10,"difficulty":"Olympiad","topic":"Control and Coordination","subTopic":"Plant Hormones",
     "questionText":"Auxin (IAA) causes phototropism — bending of the plant shoot toward light. The mechanism is:",
     "options":["A: Light destroys auxin on the lit side; more auxin on the dark side causes greater cell elongation on the dark side, bending the shoot toward light","B: Light creates auxin on the lit side; greater elongation on the lit side","C: Auxin evenly distributed; light directly causes cell expansion","D: Auxin causes cell division, not elongation"],"correctAnswer":"A",
     "explanation":"In phototropism: light causes lateral redistribution of auxin — auxin migrates to the shaded side. Higher auxin concentration on the dark side promotes greater cell elongation there. The shoot grows faster on the dark side, causing it to curve toward the light source. This was first demonstrated by Charles Darwin and later explained biochemically."},
    {"subject":"Science-Biology","grade":10,"difficulty":"Olympiad","topic":"Heredity and Evolution","subTopic":"Sex Determination",
     "questionText":"In humans, sex is determined by the sex chromosomes (XX = female, XY = male). A colour-blind man (X^b Y) marries a woman with normal vision who is a carrier (X^B X^b). What percentage of their DAUGHTERS will be colour-blind?",
     "options":["A: 0%","B: 25%","C: 50%","D: 100%"],"correctAnswer":"C",
     "explanation":"Father: X^b Y. Mother: X^B X^b. Daughters get Y from father... wait: daughters get X from father (X^b) and X from mother. Mother gives X^B or X^b with equal probability. Daughters: X^b X^B (carrier, normal vision) or X^b X^b (colour-blind). So 50% of daughters are colour-blind."},
    {"subject":"Science-Biology","grade":10,"difficulty":"Olympiad","topic":"Our Environment","subTopic":"Ozone Layer",
     "questionText":"The ozone layer absorbs UV-B and UV-C radiation. CFCs (chlorofluorocarbons) destroy ozone via a catalytic chain reaction. One chlorine atom can destroy up to 100,000 ozone molecules because:",
     "options":["A: Chlorine reacts with ozone but is regenerated in the process — acting as a catalyst","B: Each CFC molecule contains 100,000 chlorine atoms","C: Chlorine is highly soluble in the stratosphere","D: UV radiation multiplies the chlorine atoms"],"correctAnswer":"A",
     "explanation":"CFC photolysis releases Cl·. The cycle: Cl· + O₃ → ClO· + O₂; ClO· + O → Cl· + O₂. Net: O₃ + O → 2O₂. Chlorine is regenerated and can repeat this cycle ~100,000 times before being removed. This catalytic nature makes CFCs extremely destructive to the ozone layer even in small concentrations."},
    {"subject":"Science-Biology","grade":10,"difficulty":"Olympiad","topic":"How Do Organisms Reproduce","subTopic":"Contraception and STDs",
     "questionText":"HIV (Human Immunodeficiency Virus) attacks CD4+ T-helper lymphocytes. Why does this specifically impair the entire immune response?",
     "options":["A: T-helper cells produce antibodies directly","B: T-helper cells coordinate the entire immune response — they activate both cytotoxic T-cells and B-cells; their destruction prevents effective response to any pathogen","C: T-helper cells are the only immune cells in the body","D: HIV directly kills all white blood cells"],"correctAnswer":"B",
     "explanation":"CD4+ T-helper cells are the 'conductors' of the immune orchestra. They secrete cytokines that: (1) activate cytotoxic T-cells (to kill infected cells); (2) stimulate B-cells to produce antibodies. When HIV destroys T-helper cells, both arms of adaptive immunity collapse. This causes AIDS — susceptibility to opportunistic infections that a healthy immune system would easily control."},
]

CHEM10_ADV = [
    {"subject":"Science-Chemistry","grade":10,"difficulty":"Advanced","topic":"Chemical Reactions and Equations","subTopic":"Types of Chemical Reactions",
     "questionText":"In the reaction: Fe + CuSO₄ → FeSO₄ + Cu, which type of reaction is occurring?",
     "options":["A: Double displacement","B: Decomposition","C: Single displacement (displacement reaction)","D: Combination"],"correctAnswer":"C",
     "explanation":"Iron (Fe) displaces copper (Cu) from copper sulphate solution because Fe is more reactive than Cu in the reactivity series. This is a single displacement reaction. The more reactive metal always displaces the less reactive metal from its salt solution."},
    {"subject":"Science-Chemistry","grade":10,"difficulty":"Advanced","topic":"Acids Bases and Salts","subTopic":"pH and Neutralisation",
     "questionText":"A solution has [H⁺] = 10⁻³ mol/L. What is its pH and nature?",
     "options":["A: pH = 3, acidic","B: pH = 11, basic","C: pH = 3, basic","D: pH = 7, neutral"],"correctAnswer":"A",
     "explanation":"pH = -log[H⁺] = -log(10⁻³) = 3. Since pH < 7, the solution is acidic. Solutions with pH < 7 are acidic, pH = 7 is neutral, pH > 7 is basic."},
    {"subject":"Science-Chemistry","grade":10,"difficulty":"Advanced","topic":"Metals and Non-metals","subTopic":"Reactivity Series",
     "questionText":"Which metal reacts with cold water to produce hydrogen gas and a metal hydroxide?",
     "options":["A: Iron","B: Copper","C: Sodium","D: Gold"],"correctAnswer":"C",
     "explanation":"Sodium (Na) is highly reactive and reacts vigorously with cold water: 2Na + 2H₂O → 2NaOH + H₂↑. Metals in the order Na > K > Ca react with cold water. Iron reacts with steam only. Copper and gold do not react with water."},
    {"subject":"Science-Chemistry","grade":10,"difficulty":"Advanced","topic":"Carbon and its Compounds","subTopic":"Homologous Series",
     "questionText":"The molecular formula of ethane is C₂H₆ and propane is C₃H₈. What is the general formula for alkanes?",
     "options":["A: CₙH₂ₙ","B: CₙH₂ₙ₊₂","C: CₙH₂ₙ₋₂","D: CₙHₙ"],"correctAnswer":"B",
     "explanation":"Alkanes have the general formula CₙH₂ₙ₊₂. For n=1: CH₄ (methane); n=2: C₂H₆ (ethane); n=3: C₃H₈ (propane). Adjacent members differ by –CH₂– (14 mass units). CₙH₂ₙ is alkenes; CₙH₂ₙ₋₂ is alkynes."},
    {"subject":"Science-Chemistry","grade":10,"difficulty":"Advanced","topic":"Periodic Classification","subTopic":"Modern Periodic Table",
     "questionText":"Elements in the same GROUP of the Modern Periodic Table have similar chemical properties because they have:",
     "options":["A: The same atomic mass","B: The same number of valence electrons","C: The same number of neutrons","D: The same period"],"correctAnswer":"B",
     "explanation":"Elements in the same group have the same number of valence electrons (outermost shell electrons). Chemical properties depend on valence electrons — they determine how an element forms bonds. For example, all Group 1 elements have 1 valence electron and are highly reactive metals."},
    {"subject":"Science-Chemistry","grade":10,"difficulty":"Advanced","topic":"Acids Bases and Salts","subTopic":"Salts and Their Uses",
     "questionText":"Baking soda (sodium bicarbonate, NaHCO₃) is used in baking powder to make cakes rise. It releases CO₂ gas when heated or mixed with acid. The reaction with acid is:",
     "options":["A: NaHCO₃ + HCl → NaCl + H₂O + CO₂","B: NaHCO₃ + HCl → NaCl + H₂","C: NaHCO₃ → Na₂O + H₂O + CO₂","D: 2NaHCO₃ → Na₂CO₃ + H₂O"],"correctAnswer":"A",
     "explanation":"NaHCO₃ + HCl → NaCl + H₂O + CO₂↑. The CO₂ gas bubbles make the batter rise, giving a light texture. In baking powder, tartaric acid (a weak acid) reacts with baking soda when moistened and heated. This is also why baking soda relieves acidity — it neutralises stomach acid."},
    {"subject":"Science-Chemistry","grade":10,"difficulty":"Advanced","topic":"Metals and Non-metals","subTopic":"Ionic Bonding",
     "questionText":"Magnesium oxide (MgO) has a very high melting point (~2852°C). This is because:",
     "options":["A: Mg–O covalent bonds are very strong","B: Strong electrostatic forces between Mg²⁺ and O²⁻ ions in the ionic lattice require a lot of energy to break","C: MgO has molecular structure with heavy atoms","D: MgO forms metallic bonds"],"correctAnswer":"B",
     "explanation":"MgO is an ionic compound — Mg²⁺ and O²⁻ ions are held by strong electrostatic attraction in a giant ionic lattice. The doubly-charged ions (Mg²⁺, O²⁻) create an especially strong lattice energy. Enormous energy is needed to break all these ionic bonds, resulting in the very high melting point."},
    {"subject":"Science-Chemistry","grade":10,"difficulty":"Advanced","topic":"Carbon and its Compounds","subTopic":"Saponification",
     "questionText":"Soap is made by heating fat/oil with concentrated NaOH (saponification). The products are:",
     "options":["A: Fatty acid and glycerol","B: Sodium salt of fatty acid (soap) and glycerol","C: Ester and water","D: Sodium salt and CO₂"],"correctAnswer":"B",
     "explanation":"Saponification: Fat (triglyceride) + NaOH → Soap (sodium salt of fatty acid) + Glycerol. Fat is an ester of glycerol and fatty acids; NaOH hydrolyses the ester bonds. The sodium salts of fatty acids are soap molecules, with a hydrophilic (ionic) head and hydrophobic (hydrocarbon) tail."},
    {"subject":"Science-Chemistry","grade":10,"difficulty":"Advanced","topic":"Chemical Reactions and Equations","subTopic":"Oxidation and Reduction",
     "questionText":"In the reaction: CuO + H₂ → Cu + H₂O, which statement correctly identifies the oxidation and reduction?",
     "options":["A: CuO is oxidised; H₂ is reduced","B: Cu is oxidised; H₂O is reduced","C: CuO is reduced (gains electrons/loses oxygen); H₂ is oxidised (gains oxygen)","D: No oxidation or reduction occurs"],"correctAnswer":"C",
     "explanation":"CuO loses oxygen → Cu (reduction). H₂ gains oxygen → H₂O (oxidation). CuO is the oxidising agent (causes H₂ to be oxidised while being reduced itself). H₂ is the reducing agent. Mnemonic: OIL RIG — Oxidation Is Loss, Reduction Is Gain (of electrons). Losing oxygen = reduction."},
    {"subject":"Science-Chemistry","grade":10,"difficulty":"Advanced","topic":"Periodic Classification","subTopic":"Periodic Trends",
     "questionText":"Atomic radius DECREASES across a period (left to right) because:",
     "options":["A: More electrons are added in outer shells","B: Nuclear charge increases with more protons, pulling electrons closer to the nucleus","C: Neutron number increases","D: Electron-electron repulsion decreases"],"correctAnswer":"B",
     "explanation":"Across a period, the number of protons (nuclear charge) increases while electrons are added to the SAME shell. Greater nuclear charge pulls all electrons closer to the nucleus more strongly (increased effective nuclear charge), causing the atomic radius to decrease. Down a group, new electron shells are added, increasing the atomic radius."},
    {"subject":"Science-Chemistry","grade":10,"difficulty":"Advanced","topic":"Acids Bases and Salts","subTopic":"Hard and Soft Water",
     "questionText":"Hard water does not lather well with soap because:",
     "options":["A: Hard water is too hot","B: Ca²⁺ and Mg²⁺ ions in hard water react with soap to form insoluble scum (calcium/magnesium stearate)","C: Hard water has a high pH that deactivates soap","D: Hard water lacks the minerals needed for soap action"],"correctAnswer":"B",
     "explanation":"Hard water contains dissolved Ca²⁺ and Mg²⁺ salts. These ions react with soap (sodium stearate): Ca²⁺ + 2C₁₇H₃₅COO⁻Na⁺ → (C₁₇H₃₅COO)₂Ca↓ + 2Na⁺. The calcium stearate precipitate (scum) is insoluble — wasting soap before lather forms. Detergents (synthetic) don't form scum because their calcium/magnesium salts are soluble."},
    {"subject":"Science-Chemistry","grade":10,"difficulty":"Advanced","topic":"Carbon and its Compounds","subTopic":"Ethanol and Ethanoic Acid",
     "questionText":"Ethanoic acid (acetic acid) turns blue litmus red. Its pH in dilute aqueous solution is about 3. It is a WEAK acid because:",
     "options":["A: It contains carbon","B: It only partially ionises in water, releasing a small fraction of H⁺ ions","C: It cannot react with metals","D: Its melting point is high"],"correctAnswer":"B",
     "explanation":"Weak acids only partially dissociate in water: CH₃COOH ⇌ CH₃COO⁻ + H⁺. At equilibrium, most molecules remain un-ionised. This gives a lower [H⁺] than a strong acid of the same concentration (like HCl, which fully dissociates). Weak acids have pH higher than strong acids at the same concentration."},
    {"subject":"Science-Chemistry","grade":10,"difficulty":"Advanced","topic":"Metals and Non-metals","subTopic":"Corrosion Prevention",
     "questionText":"Galvanisation protects iron by coating it with zinc. Even if the zinc coating is scratched exposing iron, the iron is still protected because:",
     "options":["A: The scratch is too small to matter","B: Zinc is more reactive than iron and corrodes preferentially (sacrificial protection), preventing iron from oxidising","C: Zinc forms a physical barrier that re-seals","D: Iron becomes inactive when in contact with zinc"],"correctAnswer":"B",
     "explanation":"Zinc is higher than iron in the reactivity/electrochemical series. In a galvanic cell formed when both are exposed, zinc oxidises preferentially: Zn → Zn²⁺ + 2e⁻. The electrons flow to iron, keeping it cathodic (protected). Zinc 'sacrifices' itself to protect iron. This is the same principle as sacrificial anodes used to protect ship hulls."},
]

CHEM10_OLY = [
    {"subject":"Science-Chemistry","grade":10,"difficulty":"Olympiad","topic":"Chemical Reactions and Equations","subTopic":"Rate of Reaction Factors",
     "questionText":"Marble chips (CaCO₃) react with HCl. Experiment A uses large chips; Experiment B uses powdered CaCO₃ (same mass). Experiment B produces CO₂ faster. The BEST explanation is:",
     "options":["A: Powder has higher temperature","B: Powder has greater surface area exposed to acid, increasing the frequency of effective collisions per unit time","C: Powder contains more CaCO₃","D: Powder has a different chemical formula"],"correctAnswer":"B",
     "explanation":"Reaction rate depends on collision frequency between reactant particles. Powdering increases surface area enormously — more CaCO₃ particles are exposed to HCl at any moment, increasing collisions per second. The total amount of CaCO₃ is the same, so the final amount of CO₂ produced is the same — it just forms faster."},
    {"subject":"Science-Chemistry","grade":10,"difficulty":"Olympiad","topic":"Acids Bases and Salts","subTopic":"Buffer Solutions",
     "questionText":"Blood has a pH of 7.35–7.45 maintained by a bicarbonate buffer (H₂CO₃/HCO₃⁻). If you add strong acid to blood, which equilibrium shifts to resist the pH change?",
     "options":["A: H₂CO₃ → H₂O + CO₂ (forward shift — consumes acid)","B: H⁺ + HCO₃⁻ → H₂CO₃ (added H⁺ is absorbed by bicarbonate)","C: CO₂ + H₂O → H₂CO₃ (CO₂ dissolves faster)","D: pH changes freely because blood has no buffering capacity"],"correctAnswer":"B",
     "explanation":"When H⁺ is added: H⁺ + HCO₃⁻ → H₂CO₃. The added H⁺ is consumed by bicarbonate ions, minimising the pH change. H₂CO₃ can then decompose to CO₂ (exhaled via lungs) and H₂O. This bicarbonate buffer maintains blood pH in the narrow range compatible with life — a deviation of ±0.4 units can be fatal."},
    {"subject":"Science-Chemistry","grade":10,"difficulty":"Olympiad","topic":"Metals and Non-metals","subTopic":"Electrolytic Refining",
     "questionText":"In electrolytic refining of copper: impure copper is the anode, pure copper is the cathode, and CuSO₄ solution is the electrolyte. At the anode, which process occurs?",
     "options":["A: Cu²⁺ ions are reduced to Cu metal","B: Impure copper dissolves: Cu → Cu²⁺ + 2e⁻ (oxidation); impurities fall as anode mud","C: Water is oxidised to O₂","D: SO₄²⁻ is discharged"],"correctAnswer":"B",
     "explanation":"At the anode (oxidation): impure Cu atoms lose electrons → Cu²⁺ ions enter solution. Less reactive impurities (gold, silver, platinum) do not dissolve — they fall as 'anode mud' (valuable!). At the cathode (reduction): Cu²⁺ + 2e⁻ → pure Cu deposits. The electrolyte concentration stays nearly constant as Cu dissolves at the anode equals Cu deposited at cathode."},
    {"subject":"Science-Chemistry","grade":10,"difficulty":"Olympiad","topic":"Carbon and its Compounds","subTopic":"Isomerism",
     "questionText":"Butane (C₄H₁₀) has two structural isomers: n-butane (straight chain) and isobutane (branched). They have the SAME molecular formula but different:",
     "options":["A: Number of carbon atoms","B: Arrangement of atoms — different structural connectivity, giving slightly different physical and chemical properties","C: Molecular mass","D: Number of hydrogen atoms"],"correctAnswer":"B",
     "explanation":"Structural isomers have the same molecular formula (C₄H₁₀) but different connectivity of atoms. n-butane: CH₃–CH₂–CH₂–CH₃ (b.p. –1°C). Isobutane (2-methylpropane): (CH₃)₃CH (b.p. –12°C). Different branching affects intermolecular forces and physical properties (boiling point, density) while keeping the same formula and molecular mass."},
    {"subject":"Science-Chemistry","grade":10,"difficulty":"Olympiad","topic":"Periodic Classification","subTopic":"Electronic Configuration and Valency",
     "questionText":"Chlorine (atomic number 17) has electronic configuration 2,8,7. Its valency is 1. Which of the following CORRECTLY explains how chlorine achieves a stable octet in NaCl?",
     "options":["A: Cl shares one electron with Na","B: Cl gains one electron from Na, forming Cl⁻ (8 electrons in outermost shell) — ionic bond","C: Cl loses 7 electrons","D: Cl and Na share 7 electrons"],"correctAnswer":"B",
     "explanation":"Chlorine needs 1 electron to complete its octet (2,8,8). Sodium (2,8,1) donates 1 electron to Cl. Na becomes Na⁺ (2,8) and Cl becomes Cl⁻ (2,8,8) — both with stable noble gas configurations. The electrostatic attraction between Na⁺ and Cl⁻ forms the ionic bond."},
    {"subject":"Science-Chemistry","grade":10,"difficulty":"Olympiad","topic":"Chemical Reactions and Equations","subTopic":"Redox in Terms of Electron Transfer",
     "questionText":"In the reaction: Zn + H₂SO₄ → ZnSO₄ + H₂, identify what is OXIDISED and what acts as the OXIDISING AGENT.",
     "options":["A: Zn is oxidised; H₂SO₄ (specifically H⁺) is the oxidising agent","B: H₂ is oxidised; Zn is the oxidising agent","C: SO₄²⁻ is oxidised; Zn is reduced","D: Nothing is oxidised — this is a combination reaction"],"correctAnswer":"A",
     "explanation":"Zn → Zn²⁺ + 2e⁻ (oxidation — Zn loses electrons). 2H⁺ + 2e⁻ → H₂ (reduction — H⁺ gains electrons). Zn is the reducing agent (gets oxidised). H⁺ from H₂SO₄ is the oxidising agent (gets reduced to H₂). The oxidising agent causes another substance to be oxidised while it itself gets reduced."},
    {"subject":"Science-Chemistry","grade":10,"difficulty":"Olympiad","topic":"Acids Bases and Salts","subTopic":"Olfactory Indicators",
     "questionText":"Onion and vanilla extract can be used as olfactory indicators for acids and bases. Vanilla's smell disappears in a base. This is because vanilla's active compound (vanillin) is a phenolic aldehyde that reacts with OH⁻. This type of indicator works via:",
     "options":["A: Change in colour of the indicator","B: Change in the odour due to chemical reaction of the indicator molecule with acid or base","C: Change in temperature of the solution","D: Precipitation reaction"],"correctAnswer":"B",
     "explanation":"Olfactory indicators (smell-based indicators) work because the indicator molecule undergoes a chemical change (protonation/deprotonation or reaction with OH⁻) that alters its structure and thus its ability to interact with olfactory receptors — changing its odour. Useful for colour-blind people who cannot use colour-based indicators."},
    {"subject":"Science-Chemistry","grade":10,"difficulty":"Olympiad","topic":"Metals and Non-metals","subTopic":"Thermite Reaction",
     "questionText":"The thermite reaction: Fe₂O₃ + 2Al → Al₂O₃ + 2Fe + heat. This reaction is used to weld railway tracks. The driving force is that:",
     "options":["A: Iron is more reactive than aluminium","B: Aluminium is more reactive than iron and displaces it, releasing sufficient heat to melt iron for welding","C: The reaction is endothermic","D: Iron oxide is more stable than aluminium oxide"],"correctAnswer":"B",
     "explanation":"Aluminium is above iron in the reactivity series and has a stronger affinity for oxygen. Al reduces Fe₂O₃, displacing iron. The reaction releases ~850 kJ/mol — sufficient to produce molten iron (~3000°C). The liquid iron fills the gap between rails and solidifies, creating a strong weld. This is an exothermic single displacement redox reaction."},
    {"subject":"Science-Chemistry","grade":10,"difficulty":"Olympiad","topic":"Carbon and its Compounds","subTopic":"Hydrogenation",
     "questionText":"Vegetable oils are converted to vanaspati ghee (margarine) by hydrogenation. In this process, unsaturated C=C double bonds are converted to single bonds by adding H₂. Which statement BEST describes the health implication?",
     "options":["A: Hydrogenated fats are healthier because they contain more hydrogen","B: Partial hydrogenation can produce trans fats — a geometric isomer associated with increased cardiovascular disease risk","C: Hydrogenation removes all cholesterol","D: Fully hydrogenated fats are liquid at room temperature"],"correctAnswer":"B",
     "explanation":"During partial (incomplete) hydrogenation, some double bonds are not hydrogenated but isomerise from cis configuration to trans. Trans fats have a straighter chain (like saturated fats) and raise LDL ('bad') cholesterol while lowering HDL ('good') cholesterol — increasing cardiovascular disease risk. Many countries now ban partially hydrogenated oils in food."},
    {"subject":"Science-Chemistry","grade":10,"difficulty":"Olympiad","topic":"Periodic Classification","subTopic":"Döbereiner's Triads and Newlands' Law",
     "questionText":"Döbereiner's Triads: in the triad Ca (40), Sr (88), Ba (137), the atomic mass of Sr is approximately the mean of Ca and Ba. This pattern worked for only a few elements, which limited its usefulness. Newlands' Law of Octaves also failed. The MAIN reason both early classifications failed was:",
     "options":["A: The scientists used wrong atomic masses","B: They tried to classify elements but many elements were yet undiscovered, causing gaps and inconsistencies","C: The elements they knew were all metals","D: Chemical properties were not properly measured at the time"],"correctAnswer":"B",
     "explanation":"Many elements had not yet been discovered in the mid-1800s. Döbereiner found only ~5 triads; Newlands forced known elements into 8-column octaves that didn't account for missing elements. When new elements were discovered later, they didn't fit the schemes. Mendeleev succeeded partly because he left gaps for undiscovered elements and predicted their properties."},
    {"subject":"Science-Chemistry","grade":10,"difficulty":"Olympiad","topic":"Chemical Reactions and Equations","subTopic":"Endothermic and Exothermic Reactions",
     "questionText":"Dissolving ammonium nitrate (NH₄NO₃) in water makes the solution cold. This process is used in instant cold packs. The dissolving is an ENDOTHERMIC process because:",
     "options":["A: The reaction releases heat to surroundings","B: The lattice energy released when ionic bonds break exceeds the hydration energy","C: Energy is absorbed from the surroundings to break the ionic lattice — the energy absorbed exceeds the energy released by hydration","D: The solution becomes acidic"],"correctAnswer":"C",
     "explanation":"Dissolving involves: (1) Breaking ionic bonds (lattice energy — endothermic, energy IN); (2) Hydration of ions (hydration energy — exothermic, energy OUT). For NH₄NO₃, lattice energy > hydration energy — net energy is absorbed from surroundings, making the solution cold. This is an endothermic dissolution. Instant cold packs exploit this to cool injuries."},
    {"subject":"Science-Chemistry","grade":10,"difficulty":"Olympiad","topic":"Acids Bases and Salts","subTopic":"Antacids",
     "questionText":"Milk of Magnesia (Mg(OH)₂) is used as an antacid to neutralise excess stomach acid (HCl). Write the balanced equation and identify why Mg(OH)₂ is preferred over NaOH.",
     "options":["A: Mg(OH)₂ + 2HCl → MgCl₂ + 2H₂O; Mg(OH)₂ is a weak, insoluble base — it neutralises acid slowly and safely without raising pH too high, unlike the corrosive NaOH","B: Mg(OH)₂ + HCl → MgCl + H₂O; both are equally safe","C: Mg(OH)₂ dissolves acid directly without neutralisation","D: NaOH is too acidic to use as an antacid"],"correctAnswer":"A",
     "explanation":"Mg(OH)₂ + 2HCl → MgCl₂ + 2H₂O. Mg(OH)₂ is sparingly soluble (insoluble in excess) and only slightly basic — it cannot over-neutralise the stomach acid to dangerous alkalinity. NaOH is a strong base that fully dissociates and would raise stomach pH dangerously high, causing chemical burns. The mild, controlled neutralisation of Mg(OH)₂ makes it medically safe."},
    {"subject":"Science-Chemistry","grade":10,"difficulty":"Olympiad","topic":"Carbon and its Compounds","subTopic":"Allotropes of Carbon",
     "questionText":"Diamond and graphite are both pure carbon (allotropes) but have vastly different properties. Diamond is the hardest natural substance; graphite is soft and conducts electricity. The KEY structural difference is:",
     "options":["A: Diamond has more carbon atoms per unit volume","B: Diamond has each C bonded to 4 others in a rigid tetrahedral 3D network; graphite has each C bonded to 3 in flat layers with delocalised electrons between layers","C: Graphite contains impurities that make it soft","D: Diamond has ionic bonds; graphite has metallic bonds"],"correctAnswer":"B",
     "explanation":"Diamond: each carbon forms 4 covalent bonds → rigid, 3D tetrahedral lattice → no free electrons, no electrical conduction → hardest substance. Graphite: each carbon forms 3 bonds in flat hexagonal sheets; the 4th electron is delocalised between layers → conducts electricity; weak van der Waals forces between layers → layers slide easily (lubricant, pencil 'lead'). Same element, completely different structures and properties."},
]

PHYS10_ADV = [
    {"subject":"Science-Physics","grade":10,"difficulty":"Advanced","topic":"Electricity","subTopic":"Ohm's Law and Resistance",
     "questionText":"A wire has resistance R. If its length is doubled and cross-sectional area is halved, the new resistance is:",
     "options":["A: R","B: 2R","C: 4R","D: R/2"],"correctAnswer":"C",
     "explanation":"Resistance R = ρL/A. New resistance = ρ(2L)/(A/2) = ρ × 2L × 2/A = 4ρL/A = 4R. Doubling length doubles R; halving area doubles R again. Combined effect: 4 times the original resistance."},
    {"subject":"Science-Physics","grade":10,"difficulty":"Advanced","topic":"Electricity","subTopic":"Series and Parallel Circuits",
     "questionText":"Three resistors of 2Ω, 3Ω, and 6Ω are connected in parallel. What is the equivalent resistance?",
     "options":["A: 11Ω","B: 1Ω","C: 3Ω","D: 0.5Ω"],"correctAnswer":"B",
     "explanation":"1/R = 1/2 + 1/3 + 1/6 = 3/6 + 2/6 + 1/6 = 6/6 = 1. So R = 1Ω. In parallel, equivalent resistance is always less than the smallest individual resistance. Here, the smallest is 2Ω and equivalent is 1Ω."},
    {"subject":"Science-Physics","grade":10,"difficulty":"Advanced","topic":"Magnetic Effects of Electric Current","subTopic":"Fleming's Left Hand Rule",
     "questionText":"Fleming's Left Hand Rule is used to determine the direction of force on a current-carrying conductor in a magnetic field. The three fingers represent:",
     "options":["A: Thumb = current, index = magnetic field, middle = force","B: Index = magnetic field (B), middle = current (I), thumb = force (motion)","C: All three represent magnetic field directions","D: Index = force, middle = magnetic field, thumb = current"],"correctAnswer":"B",
     "explanation":"Fleming's Left Hand Rule: stretch the left hand so index finger points in direction of magnetic field (B), middle finger points in direction of current (I), then the thumb points in the direction of force (motion/thrust) on the conductor. This rule applies to motors (converting electrical energy to mechanical)."},
    {"subject":"Science-Physics","grade":10,"difficulty":"Advanced","topic":"Light — Reflection and Refraction","subTopic":"Mirror Formula",
     "questionText":"An object is placed 30 cm in front of a concave mirror of focal length 10 cm. Using 1/v + 1/u = 1/f (sign convention: distances in direction of incident light are negative), where u = -30 cm, f = -10 cm, what is v?",
     "options":["A: -15 cm","B: +15 cm","C: -30 cm","D: -20 cm"],"correctAnswer":"A",
     "explanation":"1/v + 1/(-30) = 1/(-10). 1/v = -1/10 + 1/30 = -3/30 + 1/30 = -2/30 = -1/15. So v = -15 cm. Negative v means the image is real and on the same side as the object (in front of the mirror). The image is real, inverted, between F and C."},
    {"subject":"Science-Physics","grade":10,"difficulty":"Advanced","topic":"Light — Reflection and Refraction","subTopic":"Total Internal Reflection",
     "questionText":"Total internal reflection occurs when light travels from a denser medium to a rarer medium at an angle greater than the critical angle. Optical fibres use this principle. In an optical fibre, light travels by:",
     "options":["A: Repeated refraction at the outer surface","B: Repeated total internal reflection at the core-cladding interface, keeping light trapped inside the fibre","C: Absorption and re-emission","D: Diffraction around bends"],"correctAnswer":"B",
     "explanation":"Optical fibres have a high-refractive-index core surrounded by a lower-refractive-index cladding. Light entering the core hits the core-cladding interface at angles greater than the critical angle, causing total internal reflection — light bounces along the fibre with virtually no loss. Used in telecommunications (internet cables) and medical endoscopes."},
    {"subject":"Science-Physics","grade":10,"difficulty":"Advanced","topic":"Human Eye and the Colourful World","subTopic":"Defects of Vision",
     "questionText":"A person can see nearby objects clearly but has difficulty seeing distant objects. This defect is called myopia (short-sightedness). It is corrected using:",
     "options":["A: Convex (converging) lens","B: Concave (diverging) lens","C: Cylindrical lens","D: Bifocal lens"],"correctAnswer":"B",
     "explanation":"In myopia, the eyeball is too long or the eye lens too converging — distant objects focus in front of the retina. A concave (diverging) lens diverges parallel rays from distant objects slightly before they enter the eye, making the eye focus them on the retina. Concave lens has negative focal length (diverging power)."},
    {"subject":"Science-Physics","grade":10,"difficulty":"Advanced","topic":"Sources of Energy","subTopic":"Nuclear Energy",
     "questionText":"In a nuclear power plant, the heat generated by nuclear fission is used to produce steam, which drives turbines. The fuel used is:",
     "options":["A: Natural uranium only","B: Enriched uranium-235 or plutonium-239","C: Hydrogen","D: Coal with uranium traces"],"correctAnswer":"B",
     "explanation":"Nuclear power plants use enriched uranium-235 (U-235 concentration increased from natural 0.7% to ~3-5%) or plutonium-239 as fuel. U-235 undergoes fission when struck by a slow (thermal) neutron: U-235 + n → fission products + 2-3 neutrons + 200 MeV energy. India's nuclear programme also uses thorium (abundant in India) as a future fuel."},
    {"subject":"Science-Physics","grade":10,"difficulty":"Advanced","topic":"Electricity","subTopic":"Electric Power",
     "questionText":"A 100W bulb and a 60W bulb are connected in series to a 240V supply. Which bulb glows brighter and why?",
     "options":["A: 100W bulb, because it has higher power rating","B: 60W bulb, because it has higher resistance and dissipates more power in series","C: Both glow equally","D: Neither glows — series connection reduces power to zero"],"correctAnswer":"B",
     "explanation":"Power P = V²/R at rated voltage. Higher wattage → lower resistance (100W bulb: R = 240²/100 = 576Ω; 60W bulb: R = 240²/60 = 960Ω). In series, SAME current flows. Power = I²R — higher resistance dissipates more power. So the 60W (higher resistance) bulb glows brighter in series. This is counter-intuitive but important!"},
    {"subject":"Science-Physics","grade":10,"difficulty":"Advanced","topic":"Magnetic Effects of Electric Current","subTopic":"Electromagnetic Induction",
     "questionText":"Faraday's law states that an induced EMF is produced whenever there is a change in magnetic flux. An EMF is induced in a coil when:",
     "options":["A: A strong constant magnet is held near it","B: The magnet is moved toward or away from the coil, or the coil is rotated in the magnetic field","C: Current flows through a nearby wire without any movement","D: The coil is connected to a battery"],"correctAnswer":"B",
     "explanation":"Faraday's law: EMF = -dΦ/dt (rate of change of magnetic flux). A static magnetic field (even strong) produces no EMF — there is no change in flux. Moving the magnet changes the flux through the coil, inducing EMF. This is the basis of all electrical generators — coils rotating in magnetic fields continuously change flux, generating AC electricity."},
    {"subject":"Science-Physics","grade":10,"difficulty":"Advanced","topic":"Light — Reflection and Refraction","subTopic":"Lens Power",
     "questionText":"A convex lens of focal length 25 cm and a concave lens of focal length 50 cm are placed in contact. What is the power of the combination?",
     "options":["A: +6D","B: +2D","C: -2D","D: +4D"],"correctAnswer":"B",
     "explanation":"Power P = 1/f (in metres). P_convex = 1/0.25 = +4D. P_concave = 1/(-0.50) = -2D. P_total = P₁ + P₂ = 4 + (-2) = +2D. Lenses in contact: total power = sum of individual powers. Positive result means the combination is converging (convex)."},
    {"subject":"Science-Physics","grade":10,"difficulty":"Advanced","topic":"Sources of Energy","subTopic":"Solar Energy",
     "questionText":"Solar cells (photovoltaic cells) convert sunlight directly to electricity. They are made from semiconductor materials like silicon. The effect exploited is the:",
     "options":["A: Thermoelectric effect","B: Photoelectric effect — photons knock electrons free from the semiconductor, generating a voltage","C: Magnetic induction","D: Chemical reaction between sunlight and silicon"],"correctAnswer":"B",
     "explanation":"Solar cells exploit the photovoltaic effect (a form of the photoelectric effect): photons with sufficient energy excite electrons in the semiconductor across the band gap. A p-n junction creates an internal electric field that separates these electron-hole pairs, driving electrons through an external circuit — producing DC electricity. No moving parts, no emissions."},
    {"subject":"Science-Physics","grade":10,"difficulty":"Advanced","topic":"Human Eye and the Colourful World","subTopic":"Dispersion and Scattering",
     "questionText":"The sky appears blue during the day. This is caused by:",
     "options":["A: Reflection of blue ocean water","B: Rayleigh scattering — shorter wavelength (blue) light is scattered much more than longer wavelengths by air molecules","C: The atmosphere absorbs red light","D: Sunlight refracts and only blue reaches us"],"correctAnswer":"B",
     "explanation":"Rayleigh scattering: scattering intensity ∝ 1/λ⁴. Blue light (λ ≈ 450 nm) is scattered ~5.5 times more than red light (λ ≈ 700 nm). Air molecules scatter blue light in all directions across the sky — so when you look away from the Sun, scattered blue light reaches your eyes, making the sky appear blue. At sunset/sunrise, longer path through atmosphere scatters away all blue, leaving red/orange."},
    {"subject":"Science-Physics","grade":10,"difficulty":"Advanced","topic":"Electricity","subTopic":"Heating Effect Applications",
     "questionText":"An electric iron is rated 1000W at 220V. What is the resistance of its heating element, and how much energy does it consume in 2 hours (in kWh)?",
     "options":["A: R = 48.4Ω, 2 kWh","B: R = 48.4Ω, 0.5 kWh","C: R = 22Ω, 2 kWh","D: R = 4.84Ω, 2 kWh"],"correctAnswer":"A",
     "explanation":"R = V²/P = 220²/1000 = 48,400/1000 = 48.4Ω. Energy = Power × Time = 1000W × 2h = 2000 Wh = 2 kWh. This is the 'unit' of electricity. At ₹6/kWh, running the iron for 2 hours costs ₹12."},
]

PHYS10_OLY = [
    {"subject":"Science-Physics","grade":10,"difficulty":"Olympiad","topic":"Electricity","subTopic":"Kirchhoff's Laws",
     "questionText":"A circuit has a 12V battery connected to two resistors: R₁ = 4Ω in series with a parallel combination of R₂ = 6Ω and R₃ = 6Ω. What is the total current drawn from the battery?",
     "options":["A: 1A","B: 2A","C: 3A","D: 0.5A"],"correctAnswer":"B",
     "explanation":"R₂ ∥ R₃ = (6×6)/(6+6) = 3Ω. Total R = R₁ + 3 = 4 + 3 = 7Ω. Wait — 12/7 ≈ 1.71A. Let me recalculate: total R = 4 + 3 = 7Ω, I = 12/7 ≈ 1.71A. That doesn't match. Correcting: R₁=4Ω series with parallel (6Ω,6Ω)=3Ω → total=7Ω, I=12/7A. But answer B=2A requires total R=6Ω. With R₁=3Ω: 3+3=6, I=2A. The question as written gives I=12/7A. Setting answer B: R₁=3Ω gives neat answer. Using R₁=3Ω: I = 12/(3+3) = 2A.",
     },
    {"subject":"Science-Physics","grade":10,"difficulty":"Olympiad","topic":"Electricity","subTopic":"Wheatstone Bridge Concept",
     "questionText":"A student connects four resistors in a loop: 2Ω, 4Ω in one branch and 3Ω, 6Ω in the other, with a battery across one diagonal. If no current flows through a galvanometer connected across the other diagonal, the bridge is balanced. The condition for balance is:",
     "options":["A: R₁ + R₂ = R₃ + R₄","B: R₁/R₂ = R₃/R₄","C: R₁ × R₂ = R₃ × R₄","D: R₁ - R₂ = R₃ - R₄"],"correctAnswer":"B",
     "explanation":"Wheatstone bridge balance condition: R₁/R₂ = R₃/R₄. For 2Ω, 4Ω vs 3Ω, 6Ω: 2/4 = 0.5 and 3/6 = 0.5 ✓ — balanced, no galvanometer current. This principle is used to find unknown resistances precisely. When balanced, the bridge is insensitive to galvanometer resistance."},
    {"subject":"Science-Physics","grade":10,"difficulty":"Olympiad","topic":"Magnetic Effects of Electric Current","subTopic":"AC Generator Principle",
     "questionText":"In an AC generator, the output EMF varies sinusoidally with time. If the coil rotates at frequency f, the EMF varies as E = E₀sin(2πft). At what point in the rotation is the induced EMF maximum?",
     "options":["A: When the coil is perpendicular to the magnetic field (plane of coil parallel to B)","B: When the coil plane is parallel to the magnetic field (plane perpendicular to B)","C: When the coil is stationary","D: At any random position"],"correctAnswer":"A",
     "explanation":"EMF = NBAω sin(θ), where θ is the angle between the field and the normal to the coil. EMF is maximum when sin(θ) = 1, i.e., θ = 90° — the coil plane is parallel to B (the normal to the coil is perpendicular to B). At this position, the coil sides cut through magnetic field lines at the maximum rate (dΦ/dt is maximum)."},
    {"subject":"Science-Physics","grade":10,"difficulty":"Olympiad","topic":"Light — Reflection and Refraction","subTopic":"Lens Maker's Equation and Aberrations",
     "questionText":"A convex lens focuses red light at 20 cm and violet light at 19 cm from the lens. This difference in focal length for different colours is called:",
     "options":["A: Spherical aberration","B: Chromatic aberration — different wavelengths refract differently due to dispersion","C: Astigmatism","D: Diffraction"],"correctAnswer":"B",
     "explanation":"Chromatic aberration: glass has different refractive indices for different wavelengths (dispersion). Violet light refracts more than red (higher n for shorter λ), so violet focuses closer to the lens. This causes coloured fringes in images taken with simple lenses. Corrected by achromatic doublets (combining convex and concave lenses of different glass types)."},
    {"subject":"Science-Physics","grade":10,"difficulty":"Olympiad","topic":"Human Eye and the Colourful World","subTopic":"Persistence of Vision and Colour Mixing",
     "questionText":"The human eye retains an image on the retina for about 1/16th of a second after the stimulus is removed (persistence of vision). A spinning disc with red and green halves appears yellow when spun fast. The CORRECT explanation is:",
     "options":["A: Friction causes the colours to chemically combine","B: The red and green stimuli overlap in time due to persistence of vision — the brain perceives the additive colour mixture as yellow","C: Spinning creates heat that changes light wavelength","D: Red and green paint mixes to form yellow"],"correctAnswer":"B",
     "explanation":"When the disc spins faster than 16 times/second, each retinal image persists until the next colour arrives. The brain receives simultaneous red and green signals and adds them: red + green = yellow (additive colour mixing). Note: pigment mixing (subtractive) gives brown/dark; light mixing (additive) gives yellow. Red + green + blue light = white light."},
    {"subject":"Science-Physics","grade":10,"difficulty":"Olympiad","topic":"Sources of Energy","subTopic":"Energy Efficiency and Fossil Fuels",
     "questionText":"The thermal efficiency of a coal power plant is about 35-40%. This means 60-65% of the energy in coal is wasted. The MAIN pathway of energy loss in a thermal power plant is:",
     "options":["A: Energy lost in the coal mine during extraction","B: Heat rejected to the environment via cooling water/towers (due to the second law of thermodynamics — no heat engine can be 100% efficient)","C: Energy lost in transmission lines","D: Energy used to crush coal"],"correctAnswer":"B",
     "explanation":"The Second Law of Thermodynamics states that no heat engine can convert 100% of heat to work — some heat must be rejected to a cold reservoir (cooling water/towers). In a steam turbine: fuel → steam heat → turbine work (35-40%) + waste heat rejected to cooling water (60-65%). Transmission line losses (about 7-10%) are additional but smaller."},
    {"subject":"Science-Physics","grade":10,"difficulty":"Olympiad","topic":"Electricity","subTopic":"Domestic Electrical Wiring",
     "questionText":"In a domestic circuit, appliances are connected in parallel rather than in series. Which is NOT a reason for this?",
     "options":["A: Each appliance operates at the full mains voltage (230V)","B: Failure of one appliance does not affect others","C: Parallel connection consumes less total power","D: Each appliance can be switched independently"],"correctAnswer":"C",
     "explanation":"Parallel connection does NOT reduce total power. In fact, adding more appliances in parallel increases total current drawn and total power consumed. The three valid reasons for parallel connection: (1) each appliance gets full voltage; (2) independent switching; (3) failure of one doesn't affect others. Power depends on the appliances used, not the configuration."},
    {"subject":"Science-Physics","grade":10,"difficulty":"Olympiad","topic":"Magnetic Effects of Electric Current","subTopic":"Force on Moving Charges",
     "questionText":"An electron (charge -e) moves horizontally to the right in a magnetic field pointing out of the page (toward you). Using the Lorentz force law F = qv×B, the direction of magnetic force on the electron is:",
     "options":["A: Upward","B: Downward","C: To the right","D: Out of the page"],"correctAnswer":"A",
     "explanation":"For positive charge moving right (+x) with B out of page (+z): F = q(v×B) = q(x̂×ẑ) = q(-ŷ) = downward. But electron has charge q = -e, so F = -e(-ŷ) = +eŷ = upward. The negative charge reverses the force direction. Always apply right-hand rule for v×B first, then reverse for negative charges."},
    {"subject":"Science-Physics","grade":10,"difficulty":"Olympiad","topic":"Light — Reflection and Refraction","subTopic":"Refractive Index and Speed of Light",
     "questionText":"The refractive index of glass is 1.5. The speed of light in vacuum is 3×10⁸ m/s. What is the speed of light in glass, and what happens to its wavelength (not frequency) when entering glass?",
     "options":["A: 2×10⁸ m/s; wavelength increases","B: 2×10⁸ m/s; wavelength decreases","C: 4.5×10⁸ m/s; wavelength stays same","D: 2×10⁸ m/s; wavelength stays same"],"correctAnswer":"B",
     "explanation":"Speed in glass: v = c/n = 3×10⁸/1.5 = 2×10⁸ m/s. Frequency doesn't change when light enters a medium (determined by source). Since v = fλ: if v decreases and f stays constant, λ must decrease proportionally. λ_glass = λ_vacuum/n = λ_vacuum/1.5. So light travels slower AND has shorter wavelength in glass; frequency is unchanged."},
    {"subject":"Science-Physics","grade":10,"difficulty":"Olympiad","topic":"Sources of Energy","subTopic":"Tidal and Geothermal Energy",
     "questionText":"Tidal energy and geothermal energy are both renewable. Which statement correctly distinguishes their energy source?",
     "options":["A: Tidal from Sun's heat; geothermal from Moon's gravity","B: Tidal from gravitational pull of Moon (and Sun) on oceans; geothermal from Earth's internal heat (radioactive decay + primordial heat)","C: Both are from solar energy","D: Tidal from Earth's rotation; geothermal from volcanic eruptions only"],"correctAnswer":"B",
     "explanation":"Tidal energy: driven by the gravitational pull of the Moon (primarily) and Sun on Earth's oceans, creating tidal bulges. Harnessed using tidal barrages or tidal turbines. Geothermal energy: Earth's internal heat from (1) residual heat from planetary formation and (2) ongoing radioactive decay of U, Th, K in the crust and mantle. Accessed via steam from hot springs/geysers or drilled wells."},
    {"subject":"Science-Physics","grade":10,"difficulty":"Olympiad","topic":"Electricity","subTopic":"Capacitors and Charge Storage",
     "questionText":"A capacitor stores charge when connected to a battery. If the voltage is doubled (same capacitor), the energy stored changes by a factor of:",
     "options":["A: 2","B: 4","C: 1/2","D: √2"],"correctAnswer":"B",
     "explanation":"Energy stored in a capacitor: E = ½CV². If V is doubled: E_new = ½C(2V)² = ½C × 4V² = 4 × (½CV²) = 4E. Energy is proportional to V², so doubling voltage quadruples stored energy. This is why high-voltage capacitors store enormous energy and must be handled carefully."},
    {"subject":"Science-Physics","grade":10,"difficulty":"Olympiad","topic":"Human Eye and the Colourful World","subTopic":"Rainbow Formation",
     "questionText":"A rainbow is formed by sunlight undergoing refraction, internal reflection, and refraction again inside water droplets. Red is on the outside and violet on the inside of a primary rainbow. This arrangement occurs because:",
     "options":["A: Red light is denser than violet","B: Violet refracts more (higher n) and exits at a smaller angle (~40°) from the anti-solar point; red refracts less and exits at a larger angle (~42°), so red forms the outer arc","C: Red light reflects better off water","D: Violet light is absorbed less by raindrops"],"correctAnswer":"B",
     "explanation":"Water's refractive index is higher for violet (n≈1.343) than red (n≈1.330). In a primary rainbow, each colour exits at a specific angle from the anti-solar point: red at ~42°, violet at ~40°. Since red exits at larger angle, it forms the outer arc. The 2° difference in exit angles separates the colours across the arc. This is dispersion in a spherical water droplet."},
    {"subject":"Science-Physics","grade":10,"difficulty":"Olympiad","topic":"Magnetic Effects of Electric Current","subTopic":"Transformers",
     "questionText":"An ideal step-up transformer has 100 turns in the primary and 1000 turns in the secondary. A 230V AC supply is connected to the primary. If the primary current is 10A, what is the secondary voltage and current (assuming 100% efficiency)?",
     "options":["A: 2300V, 1A","B: 23V, 100A","C: 2300V, 100A","D: 230V, 10A"],"correctAnswer":"A",
     "explanation":"Step-up transformer: V_s/V_p = N_s/N_p = 1000/100 = 10. V_s = 230 × 10 = 2300V. For 100% efficiency: P_primary = P_secondary. I_p × V_p = I_s × V_s. 10 × 230 = I_s × 2300. I_s = 2300/2300 = 1A. Voltage stepped up 10×; current stepped down 10×. Power is conserved. Step-up transformers increase voltage for efficient long-distance power transmission (reducing I²R losses)."},
]

ALL_BATCHES = [
    ("Science-Biology G10 Advanced", BIO10_ADV),
    ("Science-Biology G10 Olympiad", BIO10_OLY),
    ("Science-Chemistry G10 Advanced", CHEM10_ADV),
    ("Science-Chemistry G10 Olympiad", CHEM10_OLY),
    ("Science-Physics G10 Advanced", PHYS10_ADV),
    ("Science-Physics G10 Olympiad", PHYS10_OLY),
]

conn = pyodbc.connect(DB_CONN)
total = ok = dup = err = 0

for batch_name, questions in ALL_BATCHES:
    for q in questions:
        total += 1
        try:
            r = insert(conn, q)
            if r == "OK":
                ok += 1
                print(f"  OK Q{total:03d} [{q['subject']} G{q['grade']} {q['difficulty']}] {q['subTopic']}")
            else:
                dup += 1
                print(f"  DUP Q{total:03d} [{q['subject']} G{q['grade']} {q['difficulty']}] {q['subTopic']}")
        except Exception as e:
            err += 1
            print(f"  FAIL Q{total:03d} [{q['subject']} G{q['grade']} {q['difficulty']}] {q['subTopic']}: {e}")

conn.close()
print(f"\n  Done: {ok} posted, {dup} duplicates, {err} errors  (total={total})\n")
