"""
G4 Olympiad Sweep — all 7 subjects
CS (15) + English (15) + GK (15) + Hindi (15) + Maths (15) + Science (15) + SS (15) = 105 questions
"""
import pyodbc, json, uuid, sys
sys.stdout.reconfigure(encoding='utf-8', errors='replace')

DB_CONN = (
    "DRIVER={ODBC Driver 18 for SQL Server};"
    "SERVER=tcp:olympiadready-np.database.windows.net,1433;"
    "DATABASE=OlympiadReady;UID=nyxen-admin;PWD=Olympiad@2026;"
    "Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30"
)

def insert(conn, q):
    c = conn.cursor()
    c.execute("SELECT 1 FROM QuestionBank WHERE Subject=? AND Grade=? AND SubTopic=? AND QuestionText=?",
              q["subject"], q["grade"], q["subTopic"], q["questionText"])
    if c.fetchone():
        return "DUP"
    c.execute("""INSERT INTO QuestionBank
                 (QuestionBankId,Subject,Grade,Difficulty,Topic,SubTopic,
                  QuestionText,OptionsJson,CorrectAnswer,Explanation,CreatedAt)
                 VALUES (?,?,?,?,?,?,?,?,?,?,GETUTCDATE())""",
              str(uuid.uuid4()).upper(), q["subject"], q["grade"], q["difficulty"],
              q["topic"], q["subTopic"], q["questionText"],
              json.dumps(q["options"]), q["correctAnswer"], q["explanation"])
    conn.commit()
    return "OK"

# ── COMPUTER SCIENCE G4 OLYMPIAD ──────────────────────────
CS4_OLY = [
    {"subject":"Computer Science","grade":4,"difficulty":"Olympiad",
     "topic":"Basics of Computer","subTopic":"Storage Units",
     "questionText":"A file is 2 MB in size. How many such files can be stored on a 1 GB pen drive (1 GB = 1024 MB)?",
     "options":["A: 256 files","B: 512 files","C: 1024 files","D: 2048 files"],"correctAnswer":"B",
     "explanation":"1 GB = 1024 MB. Number of files = 1024 ÷ 2 = 512 files. Storage units: 1 KB = 1024 bytes, 1 MB = 1024 KB, 1 GB = 1024 MB, 1 TB = 1024 GB."},
    {"subject":"Computer Science","grade":4,"difficulty":"Olympiad",
     "topic":"Basics of Computer","subTopic":"Binary Numbers",
     "questionText":"What is the decimal value of binary 111?",
     "options":["A: 5","B: 6","C: 7","D: 8"],"correctAnswer":"C",
     "explanation":"Binary 111 = (1×4) + (1×2) + (1×1) = 4+2+1 = 7. Each bit from right to left represents 1, 2, 4, 8..."},
    {"subject":"Computer Science","grade":4,"difficulty":"Olympiad",
     "topic":"Input and Output","subTopic":"Types of Devices",
     "questionText":"A touch screen is special because it is BOTH an input and output device. Which other device also works as both?",
     "options":["A: Keyboard","B: Printer","C: Interactive Whiteboard (Smart Board)","D: Scanner"],"correctAnswer":"C",
     "explanation":"An interactive whiteboard (Smart Board) displays information (output) AND accepts touch/stylus input. A keyboard is only input. A printer is only output. A scanner is only input. Touch-based devices like smartphones and tablets are also both input and output."},
    {"subject":"Computer Science","grade":4,"difficulty":"Olympiad",
     "topic":"Software","subTopic":"Types of Software",
     "questionText":"Which of the following is SYSTEM SOFTWARE?",
     "options":["A: MS Paint","B: VLC Media Player","C: Windows 11","D: Google Chrome"],"correctAnswer":"C",
     "explanation":"System software manages the computer's hardware and provides a platform for other software. Windows 11 is an Operating System — system software. MS Paint, VLC, and Chrome are all application software (programs that help users do specific tasks)."},
    {"subject":"Computer Science","grade":4,"difficulty":"Olympiad",
     "topic":"MS Word","subTopic":"Word Processing",
     "questionText":"In MS Word, which keyboard shortcut is used to SELECT ALL the text in a document?",
     "options":["A: Ctrl + S","B: Ctrl + A","C: Ctrl + C","D: Ctrl + X"],"correctAnswer":"B",
     "explanation":"Ctrl + A = Select All. Ctrl + S = Save. Ctrl + C = Copy. Ctrl + X = Cut. Ctrl + V = Paste. Ctrl + Z = Undo. These shortcuts work in most applications, not just MS Word."},
    {"subject":"Computer Science","grade":4,"difficulty":"Olympiad",
     "topic":"Internet","subTopic":"Email Etiquette",
     "questionText":"You want to send an email to your teacher but also want your classmate to receive a copy WITHOUT the teacher knowing. Which field do you use for your classmate's email?",
     "options":["A: To","B: CC (Carbon Copy)","C: BCC (Blind Carbon Copy)","D: Subject"],"correctAnswer":"C",
     "explanation":"BCC (Blind Carbon Copy) sends a copy to that person without others seeing their address. CC (Carbon Copy) is visible to all recipients. Use BCC when you want to keep the recipient's email address private from other recipients."},
    {"subject":"Computer Science","grade":4,"difficulty":"Olympiad",
     "topic":"Basics of Computer","subTopic":"Computer Memory",
     "questionText":"Which type of memory is used by the CPU to store data it is CURRENTLY working on, and is much faster than hard disk?",
     "options":["A: ROM","B: Hard Disk","C: RAM","D: CD-ROM"],"correctAnswer":"C",
     "explanation":"RAM (Random Access Memory) is the computer's working memory — the CPU reads and writes to it constantly during processing. It is much faster than hard disk storage. However, RAM is volatile (data lost when power off). The more RAM a computer has, the more programs it can run smoothly."},
    {"subject":"Computer Science","grade":4,"difficulty":"Olympiad",
     "topic":"MS Paint","subTopic":"Drawing Tools",
     "questionText":"In MS Paint, if you want to fill a closed shape with colour without painting manually, which tool would you use?",
     "options":["A: Pencil tool","B: Fill with colour (Paint Bucket) tool","C: Eraser tool","D: Text tool"],"correctAnswer":"B",
     "explanation":"The 'Fill with colour' (paint bucket) tool fills any closed area with the selected colour in one click. The pencil draws freehand. The eraser removes colour. This tool only works properly if the shape is fully closed — any gap will cause colour to flood outside the shape."},
    {"subject":"Computer Science","grade":4,"difficulty":"Olympiad",
     "topic":"Internet","subTopic":"Web Browsers",
     "questionText":"The address bar of a web browser shows 'https://www.google.com'. What does the 'https' tell you?",
     "options":["A: The website is hosted in USA","B: The connection is secure and encrypted","C: The website is only for search engines","D: You need a password to visit it"],"correctAnswer":"B",
     "explanation":"HTTPS (HyperText Transfer Protocol Secure) means data between your browser and website is encrypted — no one can easily spy on what you type (like passwords). HTTP (without S) is unsecure. The padlock symbol in the browser address bar also indicates HTTPS."},
    {"subject":"Computer Science","grade":4,"difficulty":"Olympiad",
     "topic":"Basics of Computer","subTopic":"Generations of Computer",
     "questionText":"The first generation computers (1940s–1950s) used vacuum tubes and were very large — filling entire rooms. What was a major DISADVANTAGE of vacuum tubes?",
     "options":["A: They were too small to see","B: They generated enormous heat, consumed huge amounts of electricity, and failed frequently","C: They were made of wood","D: They could only do addition"],"correctAnswer":"B",
     "explanation":"First-generation computers like ENIAC had about 18,000 vacuum tubes. Problems: generated intense heat (needed special cooling), consumed enormous electricity, and tubes frequently burnt out causing failures. Transistors (2nd gen) solved these problems — smaller, cooler, cheaper, more reliable."},
    {"subject":"Computer Science","grade":4,"difficulty":"Olympiad",
     "topic":"Programming","subTopic":"Algorithms and Flowcharts",
     "questionText":"An algorithm is a step-by-step set of instructions to solve a problem. Which property is MOST important for a good algorithm?",
     "options":["A: It must use a computer","B: It must be written in English","C: Each step must be clear, unambiguous, and the algorithm must eventually stop (terminate)","D: It must have exactly 10 steps"],"correctAnswer":"C",
     "explanation":"A good algorithm must be: (1) Unambiguous — each step is clear with only one interpretation; (2) Finite — must end after a certain number of steps (not run forever); (3) Effective — each step can actually be carried out. Algorithms can be for any task, not just computer programs (e.g., a recipe is an algorithm)."},
    {"subject":"Computer Science","grade":4,"difficulty":"Olympiad",
     "topic":"MS Word","subTopic":"Formatting",
     "questionText":"In MS Word, text that appears like THIS is called:",
     "options":["A: Bold","B: Italic","C: Underlined","D: Strikethrough"],"correctAnswer":"A",
     "explanation":"Bold text appears thicker/darker: THIS. Italic text slants: *this*. Underlined text has a line beneath: this. Strikethrough has a line through: ~~this~~. Shortcuts: Ctrl+B (Bold), Ctrl+I (Italic), Ctrl+U (Underline)."},
    {"subject":"Computer Science","grade":4,"difficulty":"Olympiad",
     "topic":"Internet","subTopic":"Online Safety",
     "questionText":"You receive an email saying 'You won a prize! Click here and enter your bank details to claim.' What should you do?",
     "options":["A: Click immediately and fill in your details","B: Forward it to all your friends","C: Delete the email — it is almost certainly a phishing scam","D: Reply asking for more details"],"correctAnswer":"C",
     "explanation":"This is a classic phishing scam. Warning signs: unexpected prize, urgency, asking for personal/financial information. Legitimate organisations never ask for bank details via email. Always tell a trusted adult, do not click any links, and delete such emails. If unsure, verify directly on the official website."},
    {"subject":"Computer Science","grade":4,"difficulty":"Olympiad",
     "topic":"Basics of Computer","subTopic":"Output Devices",
     "questionText":"Which type of printer sprays tiny droplets of ink onto paper to create images and text?",
     "options":["A: Laser printer","B: Dot matrix printer","C: Inkjet printer","D: 3D printer"],"correctAnswer":"C",
     "explanation":"Inkjet printers spray microscopic droplets of liquid ink through tiny nozzles onto paper. Laser printers use a laser beam to create an electrostatic pattern that attracts toner powder. Dot matrix printers use pins striking an ink ribbon. Inkjet printers produce high-quality colour photos at lower cost than laser."},
    {"subject":"Computer Science","grade":4,"difficulty":"Olympiad",
     "topic":"Spreadsheet","subTopic":"Spreadsheet Basics",
     "questionText":"In a spreadsheet, the cell at column C and row 5 is named:",
     "options":["A: 5C","B: C5","C: C,5","D: Row5Col3"],"correctAnswer":"B",
     "explanation":"Cells in a spreadsheet are named by Column letter first, then Row number: C5 means column C, row 5. A1 is the top-left cell. This naming convention (column letter + row number) is used in all spreadsheet software including Excel and Google Sheets."},
]

# ── ENGLISH G4 OLYMPIAD ───────────────────────────────────
ENG4_OLY = [
    {"subject":"English","grade":4,"difficulty":"Olympiad",
     "topic":"Grammar","subTopic":"Parts of Speech — Adverbs",
     "questionText":"Choose the sentence where the underlined word is used as an ADVERB:\n(A) She is a fast runner.\n(B) He ran fast to catch the bus.\n(C) The fast train arrived on time.\n(D) Fast food is popular.",
     "options":["A: Sentence A","B: Sentence B","C: Sentence C","D: Sentence D"],"correctAnswer":"B",
     "explanation":"In sentence B, 'fast' modifies the verb 'ran' — it tells HOW he ran. That makes it an adverb. In sentences A and C, 'fast' describes a noun (runner, train) — making it an adjective. In D, 'fast' also works as an adjective modifying 'food'. Adverbs modify verbs, adjectives, or other adverbs."},
    {"subject":"English","grade":4,"difficulty":"Olympiad",
     "topic":"Grammar","subTopic":"Tenses",
     "questionText":"Choose the correct sentence:\n(A) She have been reading for two hours.\n(B) She has been reading for two hours.\n(C) She is been reading for two hours.\n(D) She was been reading for two hours.",
     "options":["A: A","B: B","C: C","D: D"],"correctAnswer":"B",
     "explanation":"Present Perfect Continuous: has/have + been + verb-ing. With 'she' (third person singular), use 'has' not 'have'. 'She has been reading' — correct. This tense describes an action that started in the past and is still continuing (for two hours)."},
    {"subject":"English","grade":4,"difficulty":"Olympiad",
     "topic":"Vocabulary","subTopic":"Homophones",
     "questionText":"Choose the correct words to fill the blanks: 'The baker used _____ cups of flour, which was more than _____ needed.'",
     "options":["A: four / they're","B: for / their","C: four / they're","D: four / their"],"correctAnswer":"D",
     "explanation":"'Four' (the number 4) vs 'for' (preposition). 'Their' (belonging to them) vs 'they're' (they are) vs 'there' (place). 'Four cups' ✓. 'More than their [bakers] needed' ✓. Homophones sound the same but have different spellings and meanings — a common Olympiad trap."},
    {"subject":"English","grade":4,"difficulty":"Olympiad",
     "topic":"Comprehension","subTopic":"Inference",
     "questionText":"Read: 'Maya pulled her coat tighter and looked at the dark sky. The leaves skittered across the empty pavement. She quickened her pace.'\nWhat can we INFER from this passage?",
     "options":["A: Maya is happy and enjoying a summer day","B: It is cold and windy, and Maya is in a hurry — possibly because a storm is coming","C: Maya is lost in an unknown city","D: Maya is running a race"],"correctAnswer":"B",
     "explanation":"Clues: 'pulled coat tighter' → cold; 'dark sky' → possible rain/storm; 'leaves skittered' → wind; 'quickened her pace' → hurrying. Inference means reading between the lines — using clues in the text to reach a conclusion the author hasn't directly stated."},
    {"subject":"English","grade":4,"difficulty":"Olympiad",
     "topic":"Grammar","subTopic":"Active and Passive Voice",
     "questionText":"Convert to passive voice: 'The gardener waters the plants every morning.'",
     "options":["A: The plants are watered every morning by the gardener.","B: The plants were watered every morning by the gardener.","C: The plants is watered every morning by the gardener.","D: The plants watered every morning by the gardener."],"correctAnswer":"A",
     "explanation":"Simple Present active → Simple Present passive: Subject + is/are + past participle + by + agent. 'Plants' (plural) → 'are watered'. 'Every morning' is a time expression (stays unchanged). 'By the gardener' is added. The tense stays present."},
    {"subject":"English","grade":4,"difficulty":"Olympiad",
     "topic":"Vocabulary","subTopic":"Idioms",
     "questionText":"What does the idiom 'It's raining cats and dogs' mean?",
     "options":["A: Animals are falling from the sky","B: It is raining very heavily","C: The weather is changing quickly","D: The rain is soft and gentle"],"correctAnswer":"B",
     "explanation":"'Raining cats and dogs' is an idiom meaning it is raining very heavily. Idioms are phrases whose meaning cannot be understood from the literal meaning of the individual words. Other rain idioms: 'under the weather' (feeling unwell), 'every cloud has a silver lining' (something good in every bad situation)."},
    {"subject":"English","grade":4,"difficulty":"Olympiad",
     "topic":"Grammar","subTopic":"Reported Speech",
     "questionText":"Change to indirect speech: Riya said, 'I am going to the library.'",
     "options":["A: Riya said that she is going to the library.","B: Riya said that she was going to the library.","C: Riya said that I am going to the library.","D: Riya said that she goes to the library."],"correctAnswer":"B",
     "explanation":"Indirect speech rules: (1) 'said' stays (no 'to' = no change needed for said); (2) tense back-shift: 'am going' → 'was going'; (3) 'I' → 'she'. So: 'Riya said that she was going to the library.' When the reporting verb is past tense, the reported verb shifts back one tense."},
    {"subject":"English","grade":4,"difficulty":"Olympiad",
     "topic":"Vocabulary","subTopic":"Word Meanings in Context",
     "questionText":"'The old man was very frugal — he never wasted money and always looked for the best deals.' The word 'frugal' means:",
     "options":["A: Generous with money","B: Careless about money","C: Careful and not wasteful with money","D: Rich and successful"],"correctAnswer":"C",
     "explanation":"'Frugal' means careful and sparing with money, not wasteful. The context clues 'never wasted money' and 'looked for best deals' confirm this meaning. Context clues are hints in the surrounding text that help you understand an unfamiliar word."},
    {"subject":"English","grade":4,"difficulty":"Olympiad",
     "topic":"Grammar","subTopic":"Punctuation",
     "questionText":"Which sentence is CORRECTLY punctuated?",
     "options":["A: Its a beautiful day isnt it.","B: It's a beautiful day, isn't it?","C: Its a beautiful day, isnt it?","D: It's a beautiful day isn't it."],"correctAnswer":"B",
     "explanation":"'It's' needs an apostrophe (contraction of 'It is'). 'Isn't' needs an apostrophe. A comma before a tag question is required. The sentence ends with '?' because it is a question. 'Its' (without apostrophe) = possessive (the cat licked its paw). 'It's' = it is."},
    {"subject":"English","grade":4,"difficulty":"Olympiad",
     "topic":"Comprehension","subTopic":"Main Idea",
     "questionText":"'Bees are incredibly important to our ecosystem. They pollinate flowers, fruits, and vegetables, helping plants reproduce. Without bees, much of the food we eat simply wouldn't exist.'\nWhat is the MAIN IDEA of this paragraph?",
     "options":["A: Bees make honey","B: Flowers are beautiful","C: Bees play a vital role in our ecosystem by pollinating plants that produce our food","D: We should keep bees as pets"],"correctAnswer":"C",
     "explanation":"The main idea is the central point the paragraph makes. The passage focuses on bees' role in pollination and food production — not honey (not mentioned) or keeping bees. The main idea is usually in the topic sentence (first sentence), but always check if the whole paragraph supports it."},
    {"subject":"English","grade":4,"difficulty":"Olympiad",
     "topic":"Grammar","subTopic":"Figures of Speech",
     "questionText":"'The thunder was an angry giant stomping across the sky.' What figure of speech is used?",
     "options":["A: Simile","B: Metaphor","C: Alliteration","D: Onomatopoeia"],"correctAnswer":"B",
     "explanation":"A metaphor directly says one thing IS another (no 'like' or 'as'). 'Thunder WAS an angry giant' — thunder is described as a giant, not compared to one. A simile would say 'thunder was LIKE an angry giant.' Alliteration repeats the same sound. Onomatopoeia uses sound words (crash, bang)."},
    {"subject":"English","grade":4,"difficulty":"Olympiad",
     "topic":"Vocabulary","subTopic":"Prefixes and Suffixes",
     "questionText":"The word 'uncomfortable' has a prefix 'un-' and suffix '-able'. What is the ROOT word?",
     "options":["A: Uncomfort","B: Comfortabl","C: Comfort","D: Uncomfortabl"],"correctAnswer":"C",
     "explanation":"Root word = the base word without any prefix or suffix. Remove 'un-' and '-able' from 'uncomfortable' → 'comfort'. Prefix 'un-' means 'not'. Suffix '-able' means 'capable of'. So 'uncomfortable' = 'not capable of being comforted/at ease'."},
    {"subject":"English","grade":4,"difficulty":"Olympiad",
     "topic":"Grammar","subTopic":"Subject-Verb Agreement",
     "questionText":"Choose the correct sentence:",
     "options":["A: Neither the students nor the teacher were present.","B: Neither the students nor the teacher was present.","C: Neither the students nor the teacher are present.","D: Neither the students nor the teacher have been present."],"correctAnswer":"B",
     "explanation":"With 'neither...nor', the verb agrees with the CLOSER subject. The closer subject here is 'the teacher' (singular) → 'was'. If it were 'neither the teacher nor the students', the closer subject 'students' is plural → 'were'. This is the 'proximity rule'."},
    {"subject":"English","grade":4,"difficulty":"Olympiad",
     "topic":"Grammar","subTopic":"Clauses",
     "questionText":"Identify the TYPE of clause underlined: 'I will come to the party IF you invite me.'",
     "options":["A: Main clause","B: Relative clause","C: Adverb clause (conditional)","D: Noun clause"],"correctAnswer":"C",
     "explanation":"'If you invite me' is an adverb clause — specifically a conditional clause. It modifies the verb 'will come', explaining the condition under which the action will occur. It begins with a subordinating conjunction 'if'. Adverb clauses answer questions: when? where? why? how? under what condition?"},
    {"subject":"English","grade":4,"difficulty":"Olympiad",
     "topic":"Vocabulary","subTopic":"Antonyms and Synonyms",
     "questionText":"Choose the word that is MOST OPPOSITE in meaning to 'METICULOUS':",
     "options":["A: Careful","B: Thorough","C: Careless","D: Detailed"],"correctAnswer":"C",
     "explanation":"Meticulous means extremely careful and precise, paying great attention to detail. Its antonym (opposite) is 'careless' — showing no attention to detail. 'Careful', 'thorough', and 'detailed' are synonyms of meticulous, not antonyms."},
]

# ── GK G4 OLYMPIAD ────────────────────────────────────────
GK4_OLY = [
    {"subject":"General Knowledge","grade":4,"difficulty":"Olympiad",
     "topic":"Science","subTopic":"Human Body",
     "questionText":"The human heart beats about 70 times per minute. How many times does it beat approximately in one day (24 hours)?",
     "options":["A: 4,200","B: 10,080","C: 100,800","D: 1,680"],"correctAnswer":"C",
     "explanation":"70 beats/min × 60 min/hour × 24 hours = 70 × 1440 = 100,800 beats per day. In a lifetime of 70 years, the heart beats about 2.5 billion times — without ever stopping for rest. The heart is the hardest-working muscle in the body."},
    {"subject":"General Knowledge","grade":4,"difficulty":"Olympiad",
     "topic":"India","subTopic":"States and Capitals",
     "questionText":"Which Indian state has the longest coastline?",
     "options":["A: Kerala","B: Tamil Nadu","C: Maharashtra","D: Gujarat"],"correctAnswer":"D",
     "explanation":"Gujarat has the longest coastline of any Indian state — approximately 1,600 km. It has an irregular, jagged coastline due to the Gulf of Kutch and Gulf of Khambhat. Gujarat is followed by Andhra Pradesh (~974 km) and Tamil Nadu (~906 km)."},
    {"subject":"General Knowledge","grade":4,"difficulty":"Olympiad",
     "topic":"Science","subTopic":"Plants",
     "questionText":"A plant that can grow in very dry, desert conditions stores water in its thick stem. What type of plant is this?",
     "options":["A: Hydrophyte","B: Mesophyte","C: Xerophyte","D: Epiphyte"],"correctAnswer":"C",
     "explanation":"Xerophytes are plants adapted to survive in dry (arid) environments, like cacti. They store water in thick stems or leaves, have waxy surfaces to reduce water loss, and have deep or widespread root systems. Hydrophytes live in water; mesophytes live in moderate conditions; epiphytes grow on other plants."},
    {"subject":"General Knowledge","grade":4,"difficulty":"Olympiad",
     "topic":"World","subTopic":"Inventions",
     "questionText":"Who invented the telephone?",
     "options":["A: Thomas Edison","B: Alexander Graham Bell","C: Nikola Tesla","D: Guglielmo Marconi"],"correctAnswer":"B",
     "explanation":"Alexander Graham Bell patented the telephone in 1876. He made the first successful telephone call to his assistant: 'Mr. Watson, come here — I want to see you.' Thomas Edison invented the light bulb and phonograph. Marconi invented the radio. Tesla worked on AC electricity."},
    {"subject":"General Knowledge","grade":4,"difficulty":"Olympiad",
     "topic":"India","subTopic":"Freedom Fighters",
     "questionText":"Sardar Vallabhbhai Patel is known as the 'Iron Man of India'. Why did he earn this title?",
     "options":["A: He was a wrestler","B: He unified over 560 princely states into the Indian Union after independence through determination and diplomacy","C: He built iron bridges across India","D: He led the Indian army"],"correctAnswer":"B",
     "explanation":"After independence in 1947, India had 562 princely states that were technically independent. Sardar Patel, as Home Minister, persuaded — and when necessary pressured — almost all of them to join India. His firm ('iron') determination and diplomatic skill in this enormous task earned him the title 'Iron Man of India' and 'Unifier of India'."},
    {"subject":"General Knowledge","grade":4,"difficulty":"Olympiad",
     "topic":"Science","subTopic":"Space",
     "questionText":"Which planet is called the 'Red Planet'?",
     "options":["A: Venus","B: Jupiter","C: Mars","D: Saturn"],"correctAnswer":"C",
     "explanation":"Mars appears red because its surface is covered in reddish iron oxide (rust). It is the fourth planet from the Sun. Mars has the tallest volcano in the solar system (Olympus Mons — 3 times taller than Mount Everest). Scientists are studying Mars as a possible future home for humans."},
    {"subject":"General Knowledge","grade":4,"difficulty":"Olympiad",
     "topic":"India","subTopic":"National Symbols",
     "questionText":"The Indian National Calendar (Saka Calendar) is the official civil calendar of India alongside the Gregorian calendar. The first month of the Saka Calendar is:",
     "options":["A: January","B: Chaitra","C: Baisakh","D: Kartik"],"correctAnswer":"B",
     "explanation":"The Saka Calendar, adopted by India in 1957, has Chaitra as its first month (starting around March 22). It has 365 days. The calendar begins with the Saka Era starting from 78 CE. This is used in official government communications alongside the Gregorian calendar."},
    {"subject":"General Knowledge","grade":4,"difficulty":"Olympiad",
     "topic":"World","subTopic":"Geography",
     "questionText":"The Amazon River flows through which continent and is the largest river by water volume in the world?",
     "options":["A: Africa","B: Asia","C: South America","D: North America"],"correctAnswer":"C",
     "explanation":"The Amazon River flows through South America (primarily Brazil, with parts in Peru and Colombia). It carries about 20% of all the freshwater that flows into the world's oceans. The Amazon rainforest around it is the world's largest tropical rainforest."},
    {"subject":"General Knowledge","grade":4,"difficulty":"Olympiad",
     "topic":"Science","subTopic":"Animals",
     "questionText":"Which animal has the longest neck and is the tallest land animal on Earth?",
     "options":["A: Elephant","B: Ostrich","C: Giraffe","D: Camel"],"correctAnswer":"C",
     "explanation":"Giraffes are the tallest land animals, reaching up to 5.5-6 metres. Their long neck (about 1.8 metres) has the same number of vertebrae as a human neck — just 7, but each is much larger. They live in African savannahs and their height helps them eat leaves from tall acacia trees."},
    {"subject":"General Knowledge","grade":4,"difficulty":"Olympiad",
     "topic":"India","subTopic":"Rivers",
     "questionText":"The river Ganga originates from which glacier in the Himalayas?",
     "options":["A: Siachen Glacier","B: Gangotri Glacier","C: Zemu Glacier","D: Baltoro Glacier"],"correctAnswer":"B",
     "explanation":"The Ganga originates from the Gangotri Glacier in Uttarakhand. The actual source point is called Gaumukh (cow's mouth), about 18 km from Gangotri town. At the source, it is called the Bhagirathi River. It officially becomes the Ganga at Devprayag, where Bhagirathi meets Alaknanda."},
    {"subject":"General Knowledge","grade":4,"difficulty":"Olympiad",
     "topic":"World","subTopic":"Countries",
     "questionText":"Which country has the most number of countries sharing its border?",
     "options":["A: India","B: Russia","C: China","D: Brazil"],"correctAnswer":"C",
     "explanation":"China shares land borders with 14 countries — the most of any nation: Russia, Mongolia, Kazakhstan, Kyrgyzstan, Tajikistan, Afghanistan, Pakistan, India, Nepal, Bhutan, Myanmar, Laos, Vietnam, and North Korea. Russia shares land borders with 14 countries too (tied). China has the world's longest land border."},
    {"subject":"General Knowledge","grade":4,"difficulty":"Olympiad",
     "topic":"Science","subTopic":"Weather",
     "questionText":"A rainbow appears in the sky after rain. You can only see a rainbow when the Sun is:",
     "options":["A: Directly overhead","B: Behind you (the Sun must be behind you, with rain in front)","C: In front of you","D: Below the horizon"],"correctAnswer":"B",
     "explanation":"To see a rainbow: the Sun must be behind you and raindrops must be in front of you. Sunlight enters a raindrop, reflects inside, and exits at an angle creating the spectrum of colours. The rainbow always appears in the direction opposite to the Sun. That's why you see rainbows in the morning (looking west) or evening (looking east)."},
    {"subject":"General Knowledge","grade":4,"difficulty":"Olympiad",
     "topic":"India","subTopic":"Famous Personalities",
     "questionText":"Dr. A.P.J. Abdul Kalam was India's 11th President (2002–2007). He was also known as the 'Missile Man of India' because he:",
     "options":["A: Played cricket","B: Led India's ballistic missile development programme including Agni and Prithvi missiles","C: Wrote books about missiles","D: Taught physics at IIT"],"correctAnswer":"B",
     "explanation":"Dr. Kalam was a scientist at DRDO and ISRO who played a pivotal role in India's civilian space programme and military missile development (Agni, Prithvi, Trishul, Akash, Nag). He was also involved in India's 1974 and 1998 nuclear tests. His book 'Wings of Fire' is his autobiography. He is beloved for his simplicity and inspiring youth."},
    {"subject":"General Knowledge","grade":4,"difficulty":"Olympiad",
     "topic":"World","subTopic":"Environment",
     "questionText":"Coral reefs are called the 'rainforests of the sea' because they:",
     "options":["A: Grow in rainforests","B: Cover 70% of the Earth like rainforests","C: Are extremely biodiverse, supporting about 25% of all marine species despite covering less than 1% of the ocean floor","D: Look like trees underwater"],"correctAnswer":"C",
     "explanation":"Coral reefs cover less than 1% of the ocean floor but support about 25% of all marine species (over 4,000 fish species alone). Like rainforests, they are biodiversity hotspots. Coral reefs are threatened by warming oceans (coral bleaching) and ocean acidification from CO₂ emissions."},
    {"subject":"General Knowledge","grade":4,"difficulty":"Olympiad",
     "topic":"India","subTopic":"Awards and Achievements",
     "questionText":"The Nobel Prize is awarded in how many categories (fields)?",
     "options":["A: 4","B: 5","C: 6","D: 7"],"correctAnswer":"C",
     "explanation":"The Nobel Prize is awarded in 6 fields: Physics, Chemistry, Medicine (Physiology or Medicine), Literature, Peace, and Economic Sciences (officially: The Sveriges Riksbank Prize in Economic Sciences, added in 1969). The first five were established by Alfred Nobel in 1895. India's Nobel laureates include Rabindranath Tagore (Literature, 1913) and Amartya Sen (Economics, 1998)."},
]

# ── HINDI G4 OLYMPIAD ─────────────────────────────────────
HINDI4_OLY = [
    {"subject":"Hindi","grade":4,"difficulty":"Olympiad",
     "topic":"Vyakaran","subTopic":"Sangya ke Bhed",
     "questionText":"'बचपन' किस प्रकार की संज्ञा है?",
     "options":["A: व्यक्तिवाचक संज्ञा","B: जातिवाचक संज्ञा","C: भाववाचक संज्ञा","D: समूहवाचक संज्ञा"],"correctAnswer":"C",
     "explanation":"भाववाचक संज्ञा किसी भाव, गुण, अवस्था या दशा का बोध कराती है — जिसे हम महसूस कर सकते हैं पर देख नहीं सकते। 'बचपन' एक अवस्था है। अन्य उदाहरण: बुढ़ापा, मिठास, ईमानदारी, प्रेम।"},
    {"subject":"Hindi","grade":4,"difficulty":"Olympiad",
     "topic":"Vyakaran","subTopic":"Vilom Shabd",
     "questionText":"'आलस्य' का विलोम शब्द क्या है?",
     "options":["A: सुस्ती","B: परिश्रम","C: निद्रा","D: थकान"],"correctAnswer":"B",
     "explanation":"आलस्य = काम न करने की प्रवृत्ति, सुस्ती। विलोम = परिश्रम (मेहनत करना)। 'सुस्ती' और 'निद्रा' तो आलस्य के पर्यायवाची हैं, विलोम नहीं।"},
    {"subject":"Hindi","grade":4,"difficulty":"Olympiad",
     "topic":"Vyakaran","subTopic":"Muhavare",
     "questionText":"'नौ दो ग्यारह होना' मुहावरे का सही अर्थ है:",
     "options":["A: गणित में नौ और दो का जोड़ करना","B: भाग जाना / रफूचक्कर हो जाना","C: बहुत तेज दौड़ना","D: बहुत चालाक होना"],"correctAnswer":"B",
     "explanation":"'नौ दो ग्यारह होना' का अर्थ है चुपचाप भाग जाना। जैसे — पुलिस देखते ही चोर नौ दो ग्यारह हो गया। यह एक प्रसिद्ध हिन्दी मुहावरा है।"},
    {"subject":"Hindi","grade":4,"difficulty":"Olympiad",
     "topic":"Vyakaran","subTopic":"Paryayvachi Shabd",
     "questionText":"'आकाश' के पर्यायवाची शब्दों का सही समूह कौन-सा है?",
     "options":["A: नभ, गगन, अम्बर","B: धरा, भूमि, धरती","C: सागर, समुद्र, जलधि","D: पवन, वायु, समीर"],"correctAnswer":"A",
     "explanation":"आकाश के पर्यायवाची: नभ, गगन, अम्बर, आसमान, व्योम, अनन्त। धरा-भूमि-धरती पर्थ्वी के पर्यायवाची हैं। सागर-समुद्र-जलधि जल के। पवन-वायु-समीर हवा के।"},
    {"subject":"Hindi","grade":4,"difficulty":"Olympiad",
     "topic":"Vyakaran","subTopic":"Sandhi",
     "questionText":"'विद्या + अर्थी' की सन्धि होगी:",
     "options":["A: विद्यार्थी","B: विद्याअर्थी","C: विद्यार्थि","D: विद्यर्थी"],"correctAnswer":"A",
     "explanation":"'आ + अ = आ' — यह दीर्घ स्वर सन्धि है। विद्या (आ) + अर्थी (अ) = विद्यार्थी। दो समान या सजातीय स्वर मिलकर दीर्घ बनते हैं। 'विद्यार्थी' का अर्थ है — विद्या प्राप्त करने का इच्छुक, यानी विद्यार्थी (छात्र)।"},
    {"subject":"Hindi","grade":4,"difficulty":"Olympiad",
     "topic":"Kavita","subTopic":"Kavita Bodh",
     "questionText":"'मीठी-मीठी बोली बोलकर, पंछी बहका लेती है।\nपेड़ की शाखा पर बैठी, गाना गाती रहती है।'\nइन पंक्तियों में किस पक्षी का वर्णन है?",
     "options":["A: कोयल","B: मोर","C: तोता","D: कौआ"],"correctAnswer":"A",
     "explanation":"मीठी बोली और गाना — ये कोयल के विशेष गुण हैं। कोयल की मीठी आवाज़ के कारण उसे 'वसंत की देवी' भी कहते हैं। कोयल का वर्णन हिंदी कविताओं में बहुत होता है।"},
    {"subject":"Hindi","grade":4,"difficulty":"Olympiad",
     "topic":"Vyakaran","subTopic":"Ling Badlo",
     "questionText":"'अभिनेता' का स्त्रीलिंग क्या है?",
     "options":["A: अभिनेती","B: अभिनेत्री","C: अभिनेताइन","D: स्त्री-अभिनेता"],"correctAnswer":"B",
     "explanation":"अभिनेता (पुल्लिंग) का स्त्रीलिंग 'अभिनेत्री' है। ऐसे अन्य शब्द: नेता → नेत्री, धाता → धात्री। यह स्त्रीप्रत्यय 'त्री' का प्रयोग है।"},
    {"subject":"Hindi","grade":4,"difficulty":"Olympiad",
     "topic":"Vyakaran","subTopic":"Vachan Badlo",
     "questionText":"'चिड़िया' का बहुवचन क्या है?",
     "options":["A: चिड़ियाएँ","B: चिड़ियें","C: चिड़ियाँ","D: चिड़ियों"],"correctAnswer":"C",
     "explanation":"'चिड़िया' का बहुवचन 'चिड़ियाँ' है। 'आ' अंत वाले स्त्रीलिंग शब्दों में 'आ' को 'आँ' कर देते हैं: चिड़िया → चिड़ियाँ, गुड़िया → गुड़ियाँ, डिबिया → डिबियाँ।"},
    {"subject":"Hindi","grade":4,"difficulty":"Olympiad",
     "topic":"Vyakaran","subTopic":"Kaal",
     "questionText":"'राहुल कल विद्यालय जाएगा।' — इस वाक्य में कौन-सा काल है?",
     "options":["A: भूतकाल","B: वर्तमानकाल","C: भविष्यकाल","D: सामान्य वर्तमान"],"correctAnswer":"C",
     "explanation":"'कल जाएगा' — यह भविष्यकाल है। भविष्यकाल = आनेवाले समय की घटना। 'कल' और 'एगा/एगी/एंगे' भविष्यकाल के संकेत हैं। भूतकाल = बीती बात (गया, आया), वर्तमान = अभी (जाता है, जा रहा है)।"},
    {"subject":"Hindi","grade":4,"difficulty":"Olympiad",
     "topic":"Gadya","subTopic":"Anuched Lekhan",
     "questionText":"एक अनुच्छेद में सबसे पहली पंक्ति को क्या कहते हैं जो मुख्य विचार प्रस्तुत करती है?",
     "options":["A: निष्कर्ष वाक्य","B: विषय वाक्य (Topic Sentence)","C: विस्तार वाक्य","D: समापन वाक्य"],"correctAnswer":"B",
     "explanation":"अनुच्छेद की पहली पंक्ति 'विषय वाक्य' (Topic Sentence) होती है जो पूरे अनुच्छेद का मुख्य विचार बताती है। उसके बाद विस्तार वाक्य आते हैं, और अंत में निष्कर्ष।"},
    {"subject":"Hindi","grade":4,"difficulty":"Olympiad",
     "topic":"Vyakaran","subTopic":"Karak",
     "questionText":"'राम ने सेब खाया।' — इस वाक्य में 'ने' किस कारक की विभक्ति है?",
     "options":["A: कर्म कारक","B: करण कारक","C: कर्ता कारक","D: सम्प्रदान कारक"],"correctAnswer":"C",
     "explanation":"कर्ता कारक = वह जो काम करे। 'राम ने' — राम काम कर रहा है (खाना)। कर्ता कारक की विभक्ति 'ने' है (सकर्मक क्रिया के साथ)। कर्म कारक = 'को', करण कारक = 'से/के द्वारा', सम्प्रदान = 'के लिए'।"},
    {"subject":"Hindi","grade":4,"difficulty":"Olympiad",
     "topic":"Vyakaran","subTopic":"Alankar",
     "questionText":"'पीपर पात सरिस मन डोला' — इस पंक्ति में कौन-सा अलंकार है?",
     "options":["A: उपमा","B: रूपक","C: अनुप्रास","D: उत्प्रेक्षा"],"correctAnswer":"A",
     "explanation":"'मन डोला पीपर के पत्ते की तरह' — यहाँ मन की तुलना पीपर पात से 'सरिस' (जैसे/समान) शब्द के साथ की गई है। जहाँ उपमेय की तुलना उपमान से की जाए — उपमा अलंकार।"},
    {"subject":"Hindi","grade":4,"difficulty":"Olympiad",
     "topic":"Vyakaran","subTopic":"Upsarg aur Pratyay",
     "questionText":"'अन-पढ़' में 'अन' क्या है?",
     "options":["A: प्रत्यय","B: उपसर्ग","C: मूल शब्द","D: संधि"],"correctAnswer":"B",
     "explanation":"उपसर्ग = शब्द के पहले लगकर अर्थ बदलने वाले अंश। 'अन' एक उपसर्ग है जिसका अर्थ है 'नहीं' या 'अभाव'। अन + पढ़ = अनपढ़ (जो पढ़ा न हो)। अन्य उदाहरण: अन + जान = अनजान, अन + देखा = अनदेखा।"},
    {"subject":"Hindi","grade":4,"difficulty":"Olympiad",
     "topic":"Vyakaran","subTopic":"Kriya ke Bhed",
     "questionText":"'मोहन बाज़ार गया।' — इस वाक्य में क्रिया का भेद क्या है?",
     "options":["A: सकर्मक क्रिया","B: अकर्मक क्रिया","C: द्विकर्मक क्रिया","D: प्रेरणार्थक क्रिया"],"correctAnswer":"B",
     "explanation":"अकर्मक क्रिया = जिसे कर्म की आवश्यकता नहीं। 'गया' — यहाँ कोई कर्म (object) नहीं है। सकर्मक क्रिया में कर्म होता है: 'मोहन ने सेब खाया' — यहाँ 'सेब' कर्म है।"},
    {"subject":"Hindi","grade":4,"difficulty":"Olympiad",
     "topic":"Gadya","subTopic":"Patra Lekhan",
     "questionText":"औपचारिक पत्र (Formal Letter) में 'सेवा में' के बाद क्या लिखा जाता है?",
     "options":["A: पत्र लेखक का नाम","B: दिनाँक","C: पत्र पाने वाले का पद और पता","D: विषय"],"correctAnswer":"C",
     "explanation":"औपचारिक पत्र की रचना: सेवा में → (प्राप्तकर्ता का पद जैसे 'प्रधानाचार्य जी') → (संस्था का नाम और पता) → दिनाँक → विषय → महोदय → मुख्य सामग्री → भवदीय/आपका आज्ञाकारी → हस्ताक्षर।"},
]

# ── MATHS G4 OLYMPIAD ─────────────────────────────────────
MATH4_OLY = [
    {"subject":"Mathematics","grade":4,"difficulty":"Olympiad",
     "topic":"Numbers","subTopic":"Large Numbers and Place Value",
     "questionText":"What is the place value of digit 7 in the number 3,47,25,681?",
     "options":["A: 7,000","B: 70,000","C: 7,00,000","D: 70,00,000"],"correctAnswer":"C",
     "explanation":"Reading 3,47,25,681 from right: ones(1), tens(8), hundreds(6), thousands(5), ten-thousands(2), lakhs(7), ten-lakhs(4), crores(3). The digit 7 is in the lakhs place. Place value = 7 × 1,00,000 = 7,00,000."},
    {"subject":"Mathematics","grade":4,"difficulty":"Olympiad",
     "topic":"Operations","subTopic":"Multiplication Word Problem",
     "questionText":"A factory produces 1,248 toys per day. How many toys does it produce in 15 days?",
     "options":["A: 17,820","B: 18,720","C: 18,270","D: 17,280"],"correctAnswer":"B",
     "explanation":"1,248 × 15 = 1,248 × 10 + 1,248 × 5 = 12,480 + 6,240 = 18,720 toys. Always verify: 18,720 ÷ 15 = 1,248 ✓. Breaking multiplication into parts (distributive property) makes it easier."},
    {"subject":"Mathematics","grade":4,"difficulty":"Olympiad",
     "topic":"Fractions","subTopic":"Comparing and Ordering Fractions",
     "questionText":"Arrange these fractions in ASCENDING order (smallest to largest): 3/4, 2/3, 5/6, 7/12",
     "options":["A: 2/3, 7/12, 3/4, 5/6","B: 7/12, 2/3, 3/4, 5/6","C: 5/6, 3/4, 2/3, 7/12","D: 2/3, 3/4, 7/12, 5/6"],"correctAnswer":"B",
     "explanation":"Convert to same denominator (12): 3/4=9/12, 2/3=8/12, 5/6=10/12, 7/12=7/12. Order: 7/12 < 8/12 < 9/12 < 10/12 → 7/12 < 2/3 < 3/4 < 5/6. Always convert to same denominator to compare fractions."},
    {"subject":"Mathematics","grade":4,"difficulty":"Olympiad",
     "topic":"Geometry","subTopic":"Angles",
     "questionText":"The angles of a triangle are in the ratio 2:3:4. What are the three angles?",
     "options":["A: 20°, 30°, 40°","B: 40°, 60°, 80°","C: 36°, 54°, 90°","D: 45°, 60°, 75°"],"correctAnswer":"B",
     "explanation":"Sum of angles in a triangle = 180°. Ratio 2:3:4 → parts = 2+3+4 = 9. Each part = 180° ÷ 9 = 20°. Angles: 2×20=40°, 3×20=60°, 4×20=80°. Check: 40+60+80 = 180° ✓."},
    {"subject":"Mathematics","grade":4,"difficulty":"Olympiad",
     "topic":"Measurement","subTopic":"Perimeter and Area",
     "questionText":"A rectangular garden has length 25 m and breadth 18 m. It is to be fenced with wire. If wire costs ₹12 per metre, what is the total cost of fencing?",
     "options":["A: ₹900","B: ₹1,032","C: ₹1,032","D: ₹1,032"],"correctAnswer":"C",
     "explanation":"Perimeter = 2(l+b) = 2(25+18) = 2×43 = 86 m. Cost = 86 × ₹12 = ₹1,032. Always use perimeter for fencing/framing questions (boundary) and area for painting/covering questions (surface)."},
    {"subject":"Mathematics","grade":4,"difficulty":"Olympiad",
     "topic":"Numbers","subTopic":"Divisibility Rules",
     "questionText":"Which of these numbers is divisible by BOTH 3 and 4?",
     "options":["A: 34","B: 42","C: 48","D: 50"],"correctAnswer":"C",
     "explanation":"Divisible by 3: sum of digits divisible by 3. Divisible by 4: last 2 digits divisible by 4. Check 48: 4+8=12 (÷3 ✓); last 2 digits = 48 ÷ 4 = 12 ✓. Check 42: 4+2=6 ✓ but 42÷4=10.5 ✗. A number divisible by both 3 and 4 is divisible by 12."},
    {"subject":"Mathematics","grade":4,"difficulty":"Olympiad",
     "topic":"Patterns","subTopic":"Number Patterns and Sequences",
     "questionText":"Find the MISSING number in the sequence: 2, 6, 12, 20, __, 42",
     "options":["A: 28","B: 30","C: 32","D: 36"],"correctAnswer":"B",
     "explanation":"Pattern: differences are 4, 6, 8, 10, 12... (increasing by 2 each time). 2+4=6, 6+6=12, 12+8=20, 20+10=30, 30+12=42. The missing number is 30. Another way to see it: terms are n(n+1) for n=1,2,3,4,5,6: 1×2=2, 2×3=6, 3×4=12, 4×5=20, 5×6=30, 6×7=42."},
    {"subject":"Mathematics","grade":4,"difficulty":"Olympiad",
     "topic":"Operations","subTopic":"LCM and HCF Word Problem",
     "questionText":"Bells A, B, and C ring every 3, 4, and 6 minutes respectively. If all three ring together at 9:00 AM, when will they next all ring together?",
     "options":["A: 9:06 AM","B: 9:12 AM","C: 9:24 AM","D: 9:36 AM"],"correctAnswer":"B",
     "explanation":"LCM(3,4,6): LCM(3,4)=12; LCM(12,6)=12. They ring together every 12 minutes. 9:00 AM + 12 minutes = 9:12 AM. For 'when do events next coincide', always use LCM."},
    {"subject":"Mathematics","grade":4,"difficulty":"Olympiad",
     "topic":"Fractions","subTopic":"Mixed Numbers",
     "questionText":"Priya has 3½ kg of flour. She uses 1¾ kg for a cake. How much flour is left?",
     "options":["A: 1¾ kg","B: 1½ kg","C: 2¼ kg","D: 2 kg"],"correctAnswer":"A",
     "explanation":"3½ - 1¾ = 7/2 - 7/4 = 14/4 - 7/4 = 7/4 = 1¾ kg. Convert mixed numbers to improper fractions: 3½ = 7/2 = 14/4; 1¾ = 7/4. Difference = 7/4 = 1¾ kg."},
    {"subject":"Mathematics","grade":4,"difficulty":"Olympiad",
     "topic":"Geometry","subTopic":"Lines and Symmetry",
     "questionText":"How many lines of symmetry does a regular hexagon have?",
     "options":["A: 3","B: 4","C: 6","D: 8"],"correctAnswer":"C",
     "explanation":"A regular hexagon has 6 lines of symmetry: 3 connecting opposite vertices and 3 connecting midpoints of opposite sides. In general, a regular polygon with n sides has n lines of symmetry. Square: 4, equilateral triangle: 3, regular hexagon: 6."},
    {"subject":"Mathematics","grade":4,"difficulty":"Olympiad",
     "topic":"Data Handling","subTopic":"Mean (Average)",
     "questionText":"A student scored 72, 85, 68, 90, and 75 in five subjects. What is the mean (average) score?",
     "options":["A: 76","B: 78","C: 80","D: 82"],"correctAnswer":"B",
     "explanation":"Mean = Sum ÷ Number of items = (72+85+68+90+75) ÷ 5 = 390 ÷ 5 = 78. Check sum: 72+85=157, 157+68=225, 225+90=315, 315+75=390. 390÷5=78."},
    {"subject":"Mathematics","grade":4,"difficulty":"Olympiad",
     "topic":"Numbers","subTopic":"Roman Numerals",
     "questionText":"What is the value of XLVII − XIX in Hindu-Arabic numerals?",
     "options":["A: 26","B: 28","C: 30","D: 32"],"correctAnswer":"B",
     "explanation":"XLVII = 40+5+2 = 47. XIX = 10+9 = 19. 47 − 19 = 28. XL = 40 (10 before 50), IX = 9 (1 before 10). Roman numeral subtraction rules: I before V or X means subtract; X before L or C means subtract."},
    {"subject":"Mathematics","grade":4,"difficulty":"Olympiad",
     "topic":"Measurement","subTopic":"Time Word Problem",
     "questionText":"A train departs at 11:45 PM and arrives at its destination at 4:20 AM the next day. What is the duration of the journey?",
     "options":["A: 4 h 25 min","B: 4 h 35 min","C: 5 h 25 min","D: 5 h 35 min"],"correctAnswer":"B",
     "explanation":"From 11:45 PM to midnight (12:00 AM) = 15 minutes. From 12:00 AM to 4:20 AM = 4 hours 20 minutes. Total = 4 hours 35 minutes. When calculating time across midnight, split at 12:00 AM."},
    {"subject":"Mathematics","grade":4,"difficulty":"Olympiad",
     "topic":"Operations","subTopic":"Multi-step Word Problem",
     "questionText":"A shopkeeper buys 120 pens at ₹8 each and sells them at ₹11 each. He also pays ₹60 for transportation. What is his net profit?",
     "options":["A: ₹300","B: ₹360","C: ₹300","D: ₹300"],"correctAnswer":"A",
     "explanation":"Cost price = 120 × 8 = ₹960. Transport = ₹60. Total cost = ₹1,020. Selling price = 120 × 11 = ₹1,320. Net profit = 1,320 − 1,020 = ₹300."},
    {"subject":"Mathematics","grade":4,"difficulty":"Olympiad",
     "topic":"Geometry","subTopic":"Volume and Capacity",
     "questionText":"A cuboid box has length 10 cm, breadth 8 cm, and height 5 cm. How many 1 cm³ cubes can fit inside it?",
     "options":["A: 23 cubes","B: 46 cubes","C: 400 cubes","D: 4,000 cubes"],"correctAnswer":"C",
     "explanation":"Volume of cuboid = l × b × h = 10 × 8 × 5 = 400 cm³. Each unit cube has volume 1 cm³. So 400 unit cubes fit inside. Volume = space enclosed inside a 3D shape. Units: cm³ or ml (1 cm³ = 1 ml)."},
]

# ── SCIENCE G4 OLYMPIAD ───────────────────────────────────
SCI4_OLY = [
    {"subject":"Science","grade":4,"difficulty":"Olympiad",
     "topic":"Plants","subTopic":"Parts of a Flower",
     "questionText":"The anther is part of the stamen (male part) of a flower. What does the anther produce?",
     "options":["A: Seeds","B: Nectar","C: Pollen grains","D: Fruits"],"correctAnswer":"C",
     "explanation":"The anther produces pollen grains, which contain the male reproductive cells. The stamen has two parts: the anther (pollen-producing tip) and the filament (stalk). When pollen is transferred to the pistil (female part) of the same or another flower, fertilisation occurs."},
    {"subject":"Science","grade":4,"difficulty":"Olympiad",
     "topic":"Animals","subTopic":"Animal Classification",
     "questionText":"Which of the following is a COLD-BLOODED animal whose body temperature changes with the surrounding environment?",
     "options":["A: Dog","B: Whale","C: Eagle","D: Crocodile"],"correctAnswer":"D",
     "explanation":"Cold-blooded (ectothermic) animals cannot regulate their own body temperature — it matches the environment. Reptiles (crocodile, lizard, snake) and fish are cold-blooded. They are sluggish in cold weather and active in warmth. Warm-blooded animals (mammals like dog, whale; birds like eagle) maintain constant body temperature."},
    {"subject":"Science","grade":4,"difficulty":"Olympiad",
     "topic":"Food","subTopic":"Nutrition and Deficiency",
     "questionText":"A child who does not eat enough Vitamin D and calcium may develop weak, bent bones — a condition called Rickets. What is the BEST natural source of Vitamin D?",
     "options":["A: Oranges","B: Sunlight on skin","C: Rice","D: Spinach"],"correctAnswer":"B",
     "explanation":"Our skin produces Vitamin D when exposed to sunlight (UV-B rays). This is why Vitamin D is called the 'sunshine vitamin'. Food sources include fish, egg yolk, and fortified milk. Vitamin D is essential for calcium absorption — without it, bones become soft despite adequate calcium intake."},
    {"subject":"Science","grade":4,"difficulty":"Olympiad",
     "topic":"Water","subTopic":"States of Water",
     "questionText":"When water vapour in the air comes in contact with a cold surface (like a glass of cold water), tiny water droplets form on the outside of the glass. This process is called:",
     "options":["A: Evaporation","B: Condensation","C: Precipitation","D: Transpiration"],"correctAnswer":"B",
     "explanation":"Condensation occurs when water vapour (gas) cools and changes to liquid water. The cold glass cools the nearby air, and the water vapour in the air condenses into liquid droplets on the glass surface. Clouds, fog, and dew are also examples of condensation. The reverse (liquid to gas) is evaporation."},
    {"subject":"Science","grade":4,"difficulty":"Olympiad",
     "topic":"Air","subTopic":"Properties of Air",
     "questionText":"When you squeeze a rubber ball, it gets compressed (squashed). When you release it, it springs back. This shows that air:",
     "options":["A: Has no mass","B: Takes up space and can be compressed — it has elasticity","C: Is invisible","D: Has no weight"],"correctAnswer":"B",
     "explanation":"Air occupies space (it is inside the ball). It can be compressed (squeezed into smaller volume) unlike liquids and solids, which are nearly incompressible. The compressed air pushes outward, causing the ball to spring back (elasticity). This property is used in tyres, footballs, and air brakes."},
    {"subject":"Science","grade":4,"difficulty":"Olympiad",
     "topic":"Light","subTopic":"Shadows",
     "questionText":"When the Moon comes between the Earth and the Sun, blocking sunlight, it causes a:",
     "options":["A: Lunar eclipse","B: Solar eclipse","C: Full moon","D: Harvest moon"],"correctAnswer":"B",
     "explanation":"Solar eclipse: Moon comes between Earth and Sun → Moon's shadow falls on Earth → day becomes dark. Lunar eclipse: Earth comes between Sun and Moon → Earth's shadow falls on Moon → Moon appears dark or reddish. A solar eclipse can only happen on a new moon; a lunar eclipse only on a full moon."},
    {"subject":"Science","grade":4,"difficulty":"Olympiad",
     "topic":"Materials","subTopic":"Properties of Materials",
     "questionText":"Iron is used to make bridges and buildings because it is STRONG. However, iron has a major problem. What is it and how is it solved?",
     "options":["A: Iron melts easily — solved by keeping it cool","B: Iron rusts when exposed to air and water — solved by painting, galvanising, or making stainless steel (adding chromium)","C: Iron is too heavy — solved by using hollow tubes","D: Iron is magnetic — solved by using plastic coatings"],"correctAnswer":"B",
     "explanation":"Iron reacts with oxygen and moisture to form iron oxide (rust) — Fe₂O₃. Rust weakens iron structures. Prevention: painting (blocks air/water), galvanising (coating with zinc), making stainless steel (iron + chromium + nickel, which forms a protective oxide layer). The Eiffel Tower is repainted every 7 years to prevent rust!"},
    {"subject":"Science","grade":4,"difficulty":"Olympiad",
     "topic":"Human Body","subTopic":"Sense Organs",
     "questionText":"The tongue can taste four basic tastes in different regions. Where is the BITTER taste detected?",
     "options":["A: Tip of the tongue","B: Sides of the tongue","C: Back of the tongue","D: Middle of the tongue"],"correctAnswer":"C",
     "explanation":"The tongue has taste buds sensitive to: sweet (tip), salty and sour (sides), and bitter (back/rear). The detection of bitter at the back is important — it triggers a gag reflex, warning us before we swallow potentially poisonous substances (many poisons are bitter). This is an important protective adaptation."},
    {"subject":"Science","grade":4,"difficulty":"Olympiad",
     "topic":"Environment","subTopic":"Pollution",
     "questionText":"Burning plastics is harmful. Which DANGEROUS gas is produced when PVC plastic is burnt?",
     "options":["A: Oxygen","B: Carbon dioxide only","C: Dioxins and hydrogen chloride — toxic gases","D: Water vapour"],"correctAnswer":"C",
     "explanation":"Burning PVC (polyvinyl chloride) — used in pipes, packaging — releases dioxins (extremely toxic, carcinogenic) and hydrogen chloride (HCl) gas. Dioxins persist in the environment and accumulate in the food chain. This is why burning plastics outdoors is illegal and very harmful — causing respiratory diseases and cancer."},
    {"subject":"Science","grade":4,"difficulty":"Olympiad",
     "topic":"Simple Machines","subTopic":"Types of Simple Machines",
     "questionText":"A bottle opener is an example of which simple machine?",
     "options":["A: Pulley","B: Wedge","C: Lever","D: Screw"],"correctAnswer":"C",
     "explanation":"A bottle opener is a lever — it uses a pivot (fulcrum) point to multiply force. When you push down one end, the other end pries upward with greater force. Other lever examples: scissors, see-saw, nutcracker, crowbar. The three classes of levers differ in the positions of load, effort, and fulcrum."},
    {"subject":"Science","grade":4,"difficulty":"Olympiad",
     "topic":"Rocks and Soil","subTopic":"Types of Soil",
     "questionText":"Which type of soil is BEST for growing most crops and retains water while also allowing drainage?",
     "options":["A: Sandy soil","B: Clay soil","C: Loamy soil","D: Rocky soil"],"correctAnswer":"C",
     "explanation":"Loamy soil — a mixture of sand, silt, and clay — is ideal for most farming. Sandy soil drains too quickly (water doesn't stay). Clay soil retains too much water (waterlogged, no aeration). Loam balances both: enough water retention for plants, enough drainage to prevent waterlogging, and it is rich in organic matter (humus)."},
    {"subject":"Science","grade":4,"difficulty":"Olympiad",
     "topic":"Plants","subTopic":"Photosynthesis",
     "questionText":"A plant was kept in complete darkness for 3 days and then tested for starch using iodine. What result would you expect and why?",
     "options":["A: Blue-black colour — starch present because plants make starch at night","B: No blue-black colour — no starch, because photosynthesis requires light and the plant could not make starch without light","C: Orange colour — all starch was converted to sugar","D: No change — iodine doesn't work on dark-grown plants"],"correctAnswer":"B",
     "explanation":"Photosynthesis requires light: CO₂ + H₂O → glucose + O₂ (needs light + chlorophyll). No light → no photosynthesis → no glucose made → no starch stored → iodine stays orange-brown (iodine turns blue-black only in presence of starch). This is a classic experiment demonstrating that light is essential for photosynthesis."},
    {"subject":"Science","grade":4,"difficulty":"Olympiad",
     "topic":"Human Body","subTopic":"Skeletal System",
     "questionText":"The backbone (vertebral column or spine) is made of small bones stacked on top of each other. These individual small bones are called:",
     "options":["A: Femur","B: Vertebrae","C: Ribs","D: Cartilage"],"correctAnswer":"B",
     "explanation":"The backbone consists of 33 vertebrae stacked in a column: 7 cervical (neck), 12 thoracic (chest), 5 lumbar (lower back), 5 sacral (fused), 4 coccygeal (fused tail bone). Between vertebrae are intervertebral discs (cartilage) that act as shock absorbers. The backbone protects the spinal cord."},
    {"subject":"Science","grade":4,"difficulty":"Olympiad",
     "topic":"Water","subTopic":"Water Conservation",
     "questionText":"A dripping tap loses about 14,000 litres of water per year. Which practice MOST effectively conserves water at home?",
     "options":["A: Using bottled water instead","B: Fixing leaking taps and pipes immediately — preventing invisible water loss","C: Watering plants only during rainfall","D: Drinking less water"],"correctAnswer":"B",
     "explanation":"Leaking taps are a massive, often-ignored source of water waste. A single dripping tap can waste 5,000-15,000 litres per year. Fixing all leaks (taps, pipes, toilet flushes) is the single most impactful conservation step. Other methods: using a bucket instead of a shower, turning off taps while brushing teeth, rainwater harvesting."},
    {"subject":"Science","grade":4,"difficulty":"Olympiad",
     "topic":"Force","subTopic":"Friction",
     "questionText":"Friction is the force that opposes motion between surfaces in contact. Why are the soles of sports shoes made with deep grooves and rough patterns?",
     "options":["A: To make shoes look stylish","B: To INCREASE friction between shoe and ground — preventing slipping during fast movement","C: To decrease friction so athletes run faster","D: To make shoes lighter"],"correctAnswer":"B",
     "explanation":"Rough, grooved soles increase friction (grip) between shoe and floor/field. This prevents slipping during sudden starts, stops, and turns in sports. Too little friction = slipping and falling. On icy roads, we put sand/gravel for the same reason. Tyres have treads for increased grip. Smooth soles (like dress shoes) have less grip."},
]

# ── SOCIAL STUDIES G4 OLYMPIAD ────────────────────────────
SS4_OLY = [
    {"subject":"Social Studies","grade":4,"difficulty":"Olympiad",
     "topic":"Maps and Directions","subTopic":"Reading Maps",
     "questionText":"On a map, a scale of 1 cm = 50 km is given. The distance between two cities on the map is 6 cm. What is the actual distance between them?",
     "options":["A: 56 km","B: 300 km","C: 30 km","D: 600 km"],"correctAnswer":"B",
     "explanation":"Actual distance = Map distance × Scale value = 6 cm × 50 km = 300 km. The map scale allows us to calculate real distances from the small distances on paper. A larger scale (e.g., 1 cm = 1 km) shows more detail; a smaller scale (1 cm = 1000 km) covers larger areas with less detail."},
    {"subject":"Social Studies","grade":4,"difficulty":"Olympiad",
     "topic":"Our Country India","subTopic":"Union Territories",
     "questionText":"India has 28 states and 8 Union Territories. Union Territories are different from states because:",
     "options":["A: They are larger than states","B: They are directly administered by the Central (Union) Government, unlike states which have their own elected governments","C: They don't have any residents","D: They are independent countries within India"],"correctAnswer":"B",
     "explanation":"States have their own elected governments (Chief Minister, Legislative Assembly). Union Territories are governed directly by the Central Government through a Lieutenant Governor (appointed by the President). Some UTs (Delhi, Puducherry, J&K) have their own legislatures. The 8 UTs: Delhi, J&K, Ladakh, Chandigarh, D&NH & DD, Lakshadweep, Andaman & Nicobar, Puducherry."},
    {"subject":"Social Studies","grade":4,"difficulty":"Olympiad",
     "topic":"Government","subTopic":"Levels of Government",
     "questionText":"The Municipal Corporation is responsible for governance of:",
     "options":["A: Villages","B: Large cities","C: Districts","D: States"],"correctAnswer":"B",
     "explanation":"Municipal Corporations (also called Nagar Nigam or Mahanagar Palika) govern large cities. They are responsible for roads, drains, parks, street lights, garbage collection, water supply, and building permissions. Examples: Brihanmumbai Municipal Corporation (BMC), Delhi MCD. Villages are governed by Gram Panchayats; districts by Collectors."},
    {"subject":"Social Studies","grade":4,"difficulty":"Olympiad",
     "topic":"Natural Resources","subTopic":"Types of Resources",
     "questionText":"Coal, petroleum, and natural gas are called 'fossil fuels' because they were formed from:",
     "options":["A: Ancient volcanic eruptions","B: Remains of prehistoric plants and animals buried and compressed for millions of years","C: Chemical reactions between rocks and water","D: Meteorites hitting the Earth"],"correctAnswer":"B",
     "explanation":"Fossil fuels formed over 300 million years when living organisms (plants, animals, marine organisms) died and were buried under layers of sediment. Heat and pressure over millions of years converted them into coal (from land plants), petroleum and natural gas (from marine organisms). They are non-renewable — once used, they cannot be replaced for millions of years."},
    {"subject":"Social Studies","grade":4,"difficulty":"Olympiad",
     "topic":"Indian History","subTopic":"Ancient Civilisations",
     "questionText":"The Indus Valley Civilisation was one of the world's earliest civilisations. It flourished around 2500 BCE. Its two most famous cities were:",
     "options":["A: Pataliputra and Vaishali","B: Mohenjo-daro and Harappa","C: Taxila and Nalanda","D: Ujjain and Kashi"],"correctAnswer":"B",
     "explanation":"Mohenjo-daro (in present Pakistan's Sindh) and Harappa (in Pakistan's Punjab) were the two largest cities of the Indus Valley (Harappan) Civilisation. They had advanced urban planning: grid-pattern streets, covered drains, multi-storey buildings, and standardised weights and measures. The civilisation declined around 1900 BCE."},
    {"subject":"Social Studies","grade":4,"difficulty":"Olympiad",
     "topic":"Agriculture","subTopic":"Types of Farming",
     "questionText":"Terrace farming is practiced on hillsides to:",
     "options":["A: Look beautiful on mountains","B: Prevent soil erosion and create flat planting surfaces on steep slopes where flat land is unavailable","C: Grow only tea and coffee","D: Water crops more easily"],"correctAnswer":"B",
     "explanation":"Terrace farming cuts steps into hillsides, creating flat 'terraces' for farming. This prevents rainwater from rushing down and washing away topsoil (erosion). The terraces also hold rainwater, allowing it to seep into the ground. Common in hilly regions of Uttarakhand, Nagaland, Philippines (Banaue Rice Terraces), and China."},
    {"subject":"Social Studies","grade":4,"difficulty":"Olympiad",
     "topic":"Environment","subTopic":"Natural Disasters",
     "questionText":"Which natural disaster is caused by the shaking of the Earth's crust due to movement of tectonic plates?",
     "options":["A: Cyclone","B: Flood","C: Earthquake","D: Drought"],"correctAnswer":"C",
     "explanation":"Earthquakes occur when tectonic plates (huge sections of Earth's crust) move, collide, or slide past each other. The point underground where the earthquake starts is the 'focus' (or hypocenter). The point on the surface directly above is the 'epicentre' — where the shaking is strongest. Earthquakes are measured on the Richter scale."},
    {"subject":"Social Studies","grade":4,"difficulty":"Olympiad",
     "topic":"Famous Places","subTopic":"UNESCO World Heritage",
     "questionText":"The Taj Mahal was built by Mughal Emperor Shah Jahan in memory of his wife Mumtaz Mahal. It is located in which city?",
     "options":["A: Delhi","B: Jaipur","C: Agra","D: Lucknow"],"correctAnswer":"C",
     "explanation":"The Taj Mahal is located in Agra, Uttar Pradesh. It was completed in 1653 and is made of white marble. It is a UNESCO World Heritage Site and one of the Seven Wonders of the World. About 20,000 workers from across India and Central Asia spent 22 years building it."},
    {"subject":"Social Studies","grade":4,"difficulty":"Olympiad",
     "topic":"Water Bodies","subTopic":"Rivers and Lakes",
     "questionText":"The Brahmaputra is one of the world's great rivers. It originates in Tibet (China), flows through Arunachal Pradesh and Assam, and then enters Bangladesh. In Bangladesh, it is known as the:",
     "options":["A: Meghna","B: Jamuna","C: Surma","D: Padma"],"correctAnswer":"B",
     "explanation":"The Brahmaputra is called Yarlung Tsangpo in Tibet, Siang/Dihang in Arunachal, Brahmaputra in Assam, and Jamuna in Bangladesh. In Bangladesh it merges with the Ganga (called Padma in Bangladesh) to form the Meghna, which finally empties into the Bay of Bengal. It is one of the largest rivers by water discharge."},
    {"subject":"Social Studies","grade":4,"difficulty":"Olympiad",
     "topic":"Indian History","subTopic":"Major Religions",
     "questionText":"Buddhism and Jainism both arose in the 6th century BCE in India. Both were founded as a protest against what aspect of society?",
     "options":["A: Foreign invasions","B: The dominance of Brahmin priests and rigid caste discrimination in Vedic religion","C: The decline of trade and commerce","D: The lack of written scripts"],"correctAnswer":"B",
     "explanation":"Both Mahavira (Jainism) and the Buddha (Buddhism) were Kshatriyas who rejected the Brahmin-dominated Vedic religion's caste hierarchy and expensive sacrificial rituals. Both preached that salvation could be achieved by anyone regardless of birth — through right conduct, meditation, and non-violence. This democratic message attracted many followers, including merchants and lower castes."},
    {"subject":"Social Studies","grade":4,"difficulty":"Olympiad",
     "topic":"Government","subTopic":"Rights and Duties",
     "questionText":"The Right to Education (RTE) Act 2009 makes free and compulsory education available for children aged:",
     "options":["A: 0-5 years","B: 6-14 years","C: 5-18 years","D: 14-18 years"],"correctAnswer":"B",
     "explanation":"The RTE Act 2009 guarantees free and compulsory education for all children between 6 and 14 years (Classes 1-8). Schools cannot charge fees from these children. The government must also ensure schools exist within 1 km of every child's home. The Act also reserves 25% seats in private schools for economically weaker sections."},
    {"subject":"Social Studies","grade":4,"difficulty":"Olympiad",
     "topic":"Our Country India","subTopic":"Climate Zones",
     "questionText":"Assam receives some of the HIGHEST rainfall in the world. Mawsynram in Meghalaya holds the world record for highest annual rainfall. Why does this region receive so much rain?",
     "options":["A: It is near the ocean","B: The Bay of Bengal monsoon winds are funnelled into the Brahmaputra valley and hit the Meghalaya hills, causing intense orographic rainfall","C: It is always cloudy due to forests","D: Nearby rivers evaporate a lot"],"correctAnswer":"B",
     "explanation":"Orographic rainfall: when moist monsoon winds from the Bay of Bengal blow northward and hit the steep Meghalaya hills (Khasi Hills), they are forced upward rapidly, cooling and releasing rain. Mawsynram receives ~11,872 mm/year. The funnel-effect of the Brahmaputra valley concentrates moisture. This is why Northeast India is one of the wettest regions on Earth."},
    {"subject":"Social Studies","grade":4,"difficulty":"Olympiad",
     "topic":"Transport","subTopic":"Means of Transport",
     "questionText":"India's Golden Quadrilateral — a major highway project — connects which four major cities?",
     "options":["A: Delhi, Mumbai, Bangalore, Hyderabad","B: Delhi, Mumbai, Chennai, Kolkata","C: Delhi, Agra, Jaipur, Amritsar","D: Mumbai, Pune, Nashik, Aurangabad"],"correctAnswer":"B",
     "explanation":"The Golden Quadrilateral is a network of National Highways connecting India's four largest metro cities: Delhi (north), Mumbai (west), Chennai (south), and Kolkata (east) — forming a quadrilateral shape. At 5,846 km, it is India's longest highway project and was largely completed by 2012 under the National Highway Development Project."},
    {"subject":"Social Studies","grade":4,"difficulty":"Olympiad",
     "topic":"Natural Resources","subTopic":"Forest Resources",
     "questionText":"Jim Corbett National Park was established in 1936 and was India's first national park. It was named after which famous conservationist?",
     "options":["A: Salim Ali","B: M.S. Swaminathan","C: Jim Corbett","D: R.K. Pachauri"],"correctAnswer":"C",
     "explanation":"Jim Corbett (1875-1955) was a British-Indian hunter who later became a famous conservationist and wildlife author. He hunted man-eating tigers and leopards to protect villagers, then worked to create India's first national park. His books ('Man-Eaters of Kumaon') made him famous. After independence, the park was renamed from Hailey National Park to Jim Corbett National Park in his honour."},
    {"subject":"Social Studies","grade":4,"difficulty":"Olympiad",
     "topic":"Indian History","subTopic":"Monuments",
     "questionText":"Qutub Minar in Delhi is the world's tallest brick minaret at 72.5 metres. It was built by:",
     "options":["A: Akbar","B: Shah Jahan","C: Qutb ud-Din Aibak (Delhi Sultanate)","D: Aurangzeb"],"correctAnswer":"C",
     "explanation":"Qutub Minar was begun by Qutb ud-Din Aibak (founder of the Delhi Sultanate) around 1193 CE and completed by his successor Iltutmish. It was built in the Indo-Islamic style using red sandstone and marble. It is a UNESCO World Heritage Site. The complex also includes the Iron Pillar of Delhi — a 1,600-year-old iron pillar that has not rusted."},
]

ALL_BATCHES = [
    ("CS G4 Olympiad",       CS4_OLY),
    ("English G4 Olympiad",  ENG4_OLY),
    ("GK G4 Olympiad",       GK4_OLY),
    ("Hindi G4 Olympiad",    HINDI4_OLY),
    ("Maths G4 Olympiad",    MATH4_OLY),
    ("Science G4 Olympiad",  SCI4_OLY),
    ("SS G4 Olympiad",       SS4_OLY),
]

conn = pyodbc.connect(DB_CONN)
total = ok = dup = err = 0

for batch_name, questions in ALL_BATCHES:
    for q in questions:
        total += 1
        try:
            r = insert(conn, q)
            if r == "OK":
                ok += 1
                print(f"  OK  Q{total:03d} [{q['subject']:22} G{q['grade']} OLY] {q['subTopic']}")
            else:
                dup += 1
                print(f"  DUP Q{total:03d} [{q['subject']:22} G{q['grade']} OLY] {q['subTopic']}")
        except Exception as e:
            err += 1
            print(f"  ERR Q{total:03d} [{q['subject']:22} G{q['grade']} OLY] {q['subTopic']}: {e}")

conn.close()
print(f"\n  Done: {ok} posted, {dup} duplicates, {err} errors  (total={total})\n")
