import pyodbc, uuid, json, sys
sys.stdout.reconfigure(encoding='utf-8', errors='replace')

conn = pyodbc.connect(
    "DRIVER={ODBC Driver 17 for SQL Server};"
    "SERVER=olympiadready-np.database.windows.net;"
    "DATABASE=OlympiadReady;"
    "UID=nyxen-admin;PWD=Olympiad@2026"
)

def insert(conn, q):
    c = conn.cursor()
    c.execute("SELECT 1 FROM QuestionBank WHERE Subject=? AND Grade=? AND SubTopic=? AND QuestionText=?",
              q["subject"], q["grade"], q["subTopic"], q["questionText"])
    if c.fetchone():
        return "DUP"
    c.execute("""INSERT INTO QuestionBank
                 (QuestionBankId,Subject,Grade,Difficulty,Topic,SubTopic,
                  QuestionText,OptionsJson,CorrectAnswer,Explanation,CreatedAt)
                 VALUES (?,?,?,?,?,?,?,?,?,?,GETUTCDATE())""",
              str(uuid.uuid4()).upper(), q["subject"], q["grade"], q["difficulty"],
              q["topic"], q["subTopic"], q["questionText"],
              json.dumps(q["options"]), q["correctAnswer"], q["explanation"])
    conn.commit()
    return "OK"

questions = [

# ── English G2 Olympiad (+20, 24→44) ─────────────────────────────────────────
{"subject":"English","grade":2,"difficulty":"Olympiad","topic":"English Language","subTopic":"Vocabulary",
 "questionText":"Which word means the opposite of 'noisy'?",
 "options":["A: Loud","B: Silent","C: Busy","D: Fast"],"correctAnswer":"B",
 "explanation":"'Noisy' means making a lot of sound. Its opposite is 'silent' — making no sound."},
{"subject":"English","grade":2,"difficulty":"Olympiad","topic":"English Language","subTopic":"Grammar",
 "questionText":"Choose the correct sentence:",
 "options":["A: He go to school every day","B: She goes to school every day","C: They goes to school every day","D: I goes to school every day"],"correctAnswer":"B",
 "explanation":"With third-person singular subjects (she/he/it), we add -s to the verb: 'She goes'."},
{"subject":"English","grade":2,"difficulty":"Olympiad","topic":"English Language","subTopic":"Comprehension",
 "questionText":"'The sun rises in the East.' What does 'rises' mean here?",
 "options":["A: Sets","B: Goes up","C: Disappears","D: Shines brightly"],"correctAnswer":"B",
 "explanation":"'Rises' means to go up or appear above the horizon — the sun comes up in the East."},
{"subject":"English","grade":2,"difficulty":"Olympiad","topic":"English Language","subTopic":"Rhyming Words",
 "questionText":"Which word rhymes with 'bright'?",
 "options":["A: Bring","B: Blight","C: Bridge","D: Brick"],"correctAnswer":"B",
 "explanation":"'Blight' ends in the same '-ight' sound as 'bright', making them rhyming words."},
{"subject":"English","grade":2,"difficulty":"Olympiad","topic":"English Language","subTopic":"Nouns",
 "questionText":"Which of these is a collective noun?",
 "options":["A: Dog","B: Run","C: Flock","D: Blue"],"correctAnswer":"C",
 "explanation":"A collective noun names a group: 'flock' refers to a group of birds/sheep."},
{"subject":"English","grade":2,"difficulty":"Olympiad","topic":"English Language","subTopic":"Adjectives",
 "questionText":"Fill in the blank: 'She is the __ girl in the class.' (tall)",
 "options":["A: more tall","B: tallest","C: taller","D: most tall"],"correctAnswer":"B",
 "explanation":"For superlative degree (comparing more than two), short adjectives add -est: 'tallest'."},
{"subject":"English","grade":2,"difficulty":"Olympiad","topic":"English Language","subTopic":"Prepositions",
 "questionText":"The cat sat __ the mat.",
 "options":["A: above","B: behind","C: on","D: through"],"correctAnswer":"C",
 "explanation":"'On' is the correct preposition here — the cat is placed upon (on top of) the mat."},
{"subject":"English","grade":2,"difficulty":"Olympiad","topic":"English Language","subTopic":"Punctuation",
 "questionText":"Which punctuation mark ends a question?",
 "options":["A: Full stop","B: Comma","C: Exclamation mark","D: Question mark"],"correctAnswer":"D",
 "explanation":"A question mark (?) is placed at the end of a sentence that asks a question."},
{"subject":"English","grade":2,"difficulty":"Olympiad","topic":"English Language","subTopic":"Synonyms",
 "questionText":"Choose the synonym for 'happy':",
 "options":["A: Sad","B: Angry","C: Joyful","D: Tired"],"correctAnswer":"C",
 "explanation":"'Joyful' means feeling great happiness — it is a synonym for 'happy'."},
{"subject":"English","grade":2,"difficulty":"Olympiad","topic":"English Language","subTopic":"Verbs",
 "questionText":"The past tense of 'eat' is:",
 "options":["A: Eated","B: Ate","C: Eats","D: Eaten"],"correctAnswer":"B",
 "explanation":"'Eat' is an irregular verb. Its simple past tense is 'ate'."},
{"subject":"English","grade":2,"difficulty":"Olympiad","topic":"English Language","subTopic":"Sentence Types",
 "questionText":"Which of these is an exclamatory sentence?",
 "options":["A: Where are you going?","B: Please sit down.","C: What a beautiful day!","D: The sky is blue."],"correctAnswer":"C",
 "explanation":"An exclamatory sentence expresses strong feeling and ends with an exclamation mark: 'What a beautiful day!'"},
{"subject":"English","grade":2,"difficulty":"Olympiad","topic":"English Language","subTopic":"Word Families",
 "questionText":"Which word belongs to the same family as 'write', 'writing', 'written'?",
 "options":["A: Right","B: Writer","C: Ride","D: Wide"],"correctAnswer":"B",
 "explanation":"'Writer' comes from the same root word 'write' — it is a noun meaning one who writes."},
{"subject":"English","grade":2,"difficulty":"Olympiad","topic":"English Language","subTopic":"Compound Words",
 "questionText":"Which pair forms a compound word? __ + __ = butterfly?",
 "options":["A: Butter + fly","B: But + terfly","C: Butt + erfly","D: B + utterfly"],"correctAnswer":"A",
 "explanation":"'Butterfly' is a compound word formed by joining 'butter' + 'fly'."},
{"subject":"English","grade":2,"difficulty":"Olympiad","topic":"English Language","subTopic":"Articles",
 "questionText":"Choose the correct article: 'I saw __ elephant at the zoo.'",
 "options":["A: a","B: an","C: the","D: no article"],"correctAnswer":"B",
 "explanation":"Use 'an' before words beginning with a vowel sound. 'Elephant' starts with a vowel 'e', so 'an elephant'."},
{"subject":"English","grade":2,"difficulty":"Olympiad","topic":"English Language","subTopic":"Pronouns",
 "questionText":"Replace the underlined word: 'Riya lost Riya's bag.' Correct sentence:",
 "options":["A: Riya lost her bag.","B: Riya lost his bag.","C: Riya lost its bag.","D: Riya lost their bag."],"correctAnswer":"A",
 "explanation":"'Riya' is feminine, so the possessive pronoun is 'her': 'Riya lost her bag.'"},
{"subject":"English","grade":2,"difficulty":"Olympiad","topic":"English Language","subTopic":"Reading",
 "questionText":"In the story, the tortoise beat the hare because the tortoise was:",
 "options":["A: Faster","B: Smarter","C: Slow and steady","D: Cheating"],"correctAnswer":"C",
 "explanation":"In the fable 'The Tortoise and the Hare', the tortoise wins by being consistent and steady, while the hare is overconfident."},
{"subject":"English","grade":2,"difficulty":"Olympiad","topic":"English Language","subTopic":"Homophones",
 "questionText":"Which pair are homophones (sound alike but different meaning)?",
 "options":["A: Sun / Son","B: Big / Large","C: Run / Walk","D: Cat / Dog"],"correctAnswer":"A",
 "explanation":"'Sun' (the star) and 'Son' (a male child) sound exactly the same but have different meanings and spellings — they are homophones."},
{"subject":"English","grade":2,"difficulty":"Olympiad","topic":"English Language","subTopic":"Spelling",
 "questionText":"Which word is spelled correctly?",
 "options":["A: Beutiful","B: Beautifull","C: Beautiful","D: Beautifil"],"correctAnswer":"C",
 "explanation":"The correct spelling is 'Beautiful' — B-E-A-U-T-I-F-U-L."},
{"subject":"English","grade":2,"difficulty":"Olympiad","topic":"English Language","subTopic":"Alphabetical Order",
 "questionText":"Arrange in alphabetical order: Apple, Mango, Banana, Cherry",
 "options":["A: Apple, Banana, Cherry, Mango","B: Apple, Cherry, Banana, Mango","C: Mango, Cherry, Banana, Apple","D: Apple, Mango, Banana, Cherry"],"correctAnswer":"A",
 "explanation":"Alphabetical order: A (Apple), B (Banana), C (Cherry), M (Mango)."},
{"subject":"English","grade":2,"difficulty":"Olympiad","topic":"English Language","subTopic":"Creative Writing",
 "questionText":"Which sentence uses the word 'run' as a noun?",
 "options":["A: I run every morning","B: She runs fast","C: He went for a run","D: They will run tomorrow"],"correctAnswer":"C",
 "explanation":"In 'He went for a run', 'run' is used as a noun (the activity of running). In other options, 'run/runs' is a verb."},

# ── General Knowledge G2 Olympiad (+20, 24→44) ───────────────────────────────
{"subject":"General Knowledge","grade":2,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"Animals",
 "questionText":"Which animal is called the 'Ship of the Desert'?",
 "options":["A: Horse","B: Camel","C: Elephant","D: Buffalo"],"correctAnswer":"B",
 "explanation":"The camel is called the 'Ship of the Desert' because it is used for transportation in desert regions."},
{"subject":"General Knowledge","grade":2,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"Plants",
 "questionText":"What do plants need to make their own food?",
 "options":["A: Sunlight, water, and air","B: Soil, rain, and sand","C: Wind, fire, and water","D: Rocks, mud, and sun"],"correctAnswer":"A",
 "explanation":"Plants make food through photosynthesis using sunlight, water, and carbon dioxide from the air."},
{"subject":"General Knowledge","grade":2,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"Human Body",
 "questionText":"How many bones does an adult human body have?",
 "options":["A: 106","B: 206","C: 306","D: 406"],"correctAnswer":"B",
 "explanation":"An adult human body has 206 bones. Babies are born with about 270–300 bones that fuse as they grow."},
{"subject":"General Knowledge","grade":2,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"Geography",
 "questionText":"Which is the largest ocean in the world?",
 "options":["A: Atlantic Ocean","B: Indian Ocean","C: Arctic Ocean","D: Pacific Ocean"],"correctAnswer":"D",
 "explanation":"The Pacific Ocean is the largest, covering about one-third of Earth's surface."},
{"subject":"General Knowledge","grade":2,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"Science",
 "questionText":"What does a thermometer measure?",
 "options":["A: Weight","B: Temperature","C: Height","D: Speed"],"correctAnswer":"B",
 "explanation":"A thermometer is an instrument used to measure temperature."},
{"subject":"General Knowledge","grade":2,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"India",
 "questionText":"What is the national animal of India?",
 "options":["A: Lion","B: Elephant","C: Tiger","D: Peacock"],"correctAnswer":"C",
 "explanation":"The Bengal Tiger is the national animal of India."},
{"subject":"General Knowledge","grade":2,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"Space",
 "questionText":"Which planet is closest to the Sun?",
 "options":["A: Earth","B: Venus","C: Mercury","D: Mars"],"correctAnswer":"C",
 "explanation":"Mercury is the closest planet to the Sun in our solar system."},
{"subject":"General Knowledge","grade":2,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"Inventions",
 "questionText":"Who invented the light bulb?",
 "options":["A: Alexander Bell","B: Thomas Edison","C: Isaac Newton","D: Benjamin Franklin"],"correctAnswer":"B",
 "explanation":"Thomas Edison invented the practical incandescent light bulb in 1879."},
{"subject":"General Knowledge","grade":2,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"Seasons",
 "questionText":"How many seasons are there in India?",
 "options":["A: 2","B: 3","C: 4","D: 6"],"correctAnswer":"D",
 "explanation":"India has 6 seasons: Spring (Vasanta), Summer (Grishma), Monsoon (Varsha), Autumn (Sharad), Pre-winter (Hemanta), and Winter (Shishira)."},
{"subject":"General Knowledge","grade":2,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"Food",
 "questionText":"Which vitamin is obtained from sunlight?",
 "options":["A: Vitamin A","B: Vitamin B","C: Vitamin C","D: Vitamin D"],"correctAnswer":"D",
 "explanation":"Vitamin D is produced in the skin when exposed to sunlight (ultraviolet rays)."},
{"subject":"General Knowledge","grade":2,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"Community Helpers",
 "questionText":"Who fights fires and saves people from burning buildings?",
 "options":["A: Police officer","B: Doctor","C: Firefighter","D: Postman"],"correctAnswer":"C",
 "explanation":"Firefighters are trained to extinguish fires and rescue people from emergencies."},
{"subject":"General Knowledge","grade":2,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"Directions",
 "questionText":"The Sun sets in which direction?",
 "options":["A: East","B: North","C: South","D: West"],"correctAnswer":"D",
 "explanation":"The Sun rises in the East and sets in the West."},
{"subject":"General Knowledge","grade":2,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"Transport",
 "questionText":"What is the fastest mode of transport?",
 "options":["A: Train","B: Ship","C: Aeroplane","D: Car"],"correctAnswer":"C",
 "explanation":"Aeroplanes are the fastest mode of transport for humans, travelling at hundreds of kilometres per hour."},
{"subject":"General Knowledge","grade":2,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"Famous Landmarks",
 "questionText":"The Eiffel Tower is located in which city?",
 "options":["A: London","B: Paris","C: Rome","D: Berlin"],"correctAnswer":"B",
 "explanation":"The Eiffel Tower is an iconic iron lattice tower located in Paris, France."},
{"subject":"General Knowledge","grade":2,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"Environment",
 "questionText":"Which gas do trees absorb from the air to help them grow?",
 "options":["A: Oxygen","B: Nitrogen","C: Carbon dioxide","D: Hydrogen"],"correctAnswer":"C",
 "explanation":"Trees (plants) absorb carbon dioxide (CO₂) from the air during photosynthesis and release oxygen."},
{"subject":"General Knowledge","grade":2,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"Musical Instruments",
 "questionText":"How many strings does a guitar typically have?",
 "options":["A: 4","B: 5","C: 6","D: 7"],"correctAnswer":"C",
 "explanation":"A standard guitar has 6 strings (E, A, D, G, B, E from lowest to highest)."},
{"subject":"General Knowledge","grade":2,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"Sports",
 "questionText":"How many players are in a cricket team?",
 "options":["A: 9","B: 10","C: 11","D: 12"],"correctAnswer":"C",
 "explanation":"A cricket team has 11 players in the playing XI."},
{"subject":"General Knowledge","grade":2,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"Science Wonders",
 "questionText":"What causes day and night on Earth?",
 "options":["A: Earth's revolution around the Sun","B: Earth's rotation on its axis","C: Moon blocking the Sun","D: Clouds covering the Sun"],"correctAnswer":"B",
 "explanation":"Day and night are caused by Earth spinning (rotating) on its own axis once every 24 hours."},
{"subject":"General Knowledge","grade":2,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"Colours in Nature",
 "questionText":"How many colours are there in a rainbow?",
 "options":["A: 5","B: 6","C: 7","D: 8"],"correctAnswer":"C",
 "explanation":"A rainbow has 7 colours: Violet, Indigo, Blue, Green, Yellow, Orange, Red (VIBGYOR)."},
{"subject":"General Knowledge","grade":2,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"Countries",
 "questionText":"Which country is known as the 'Land of the Rising Sun'?",
 "options":["A: China","B: Japan","C: Korea","D: India"],"correctAnswer":"B",
 "explanation":"Japan is called the 'Land of the Rising Sun' because it is one of the easternmost countries in Asia and the name Japan (Nihon) means 'origin of the sun'."},

# ── English G1 Olympiad (+20, 30→50) ─────────────────────────────────────────
{"subject":"English","grade":1,"difficulty":"Olympiad","topic":"English Language","subTopic":"Phonics",
 "questionText":"Which word starts with the same sound as 'ship'?",
 "options":["A: Chip","B: Shoe","C: Sip","D: Hip"],"correctAnswer":"B",
 "explanation":"'Ship' and 'Shoe' both begin with the 'sh' blend/digraph sound."},
{"subject":"English","grade":1,"difficulty":"Olympiad","topic":"English Language","subTopic":"Vocabulary",
 "questionText":"What is the opposite of 'hot'?",
 "options":["A: Warm","B: Cold","C: Soft","D: Smooth"],"correctAnswer":"B",
 "explanation":"The opposite (antonym) of 'hot' is 'cold'."},
{"subject":"English","grade":1,"difficulty":"Olympiad","topic":"English Language","subTopic":"Sentence Building",
 "questionText":"Arrange to form a correct sentence: [the / is / sky / blue]",
 "options":["A: Blue sky the is","B: Is the sky blue","C: The sky is blue","D: Sky the blue is"],"correctAnswer":"C",
 "explanation":"The correct word order is: The sky is blue (subject + verb + complement)."},
{"subject":"English","grade":1,"difficulty":"Olympiad","topic":"English Language","subTopic":"Rhyming Words",
 "questionText":"Which word rhymes with 'cat'?",
 "options":["A: Cup","B: Bat","C: Car","D: Coat"],"correctAnswer":"B",
 "explanation":"'Cat' and 'bat' both end with the '-at' sound, making them rhyming words."},
{"subject":"English","grade":1,"difficulty":"Olympiad","topic":"English Language","subTopic":"Nouns",
 "questionText":"Which is a proper noun?",
 "options":["A: City","B: River","C: Mumbai","D: Mountain"],"correctAnswer":"C",
 "explanation":"'Mumbai' is a proper noun — it names a specific city. 'City', 'river', 'mountain' are common nouns."},
{"subject":"English","grade":1,"difficulty":"Olympiad","topic":"English Language","subTopic":"Verbs",
 "questionText":"Which word is an action word (verb)?",
 "options":["A: Beautiful","B: Quickly","C: Jump","D: Flower"],"correctAnswer":"C",
 "explanation":"'Jump' is a verb — it shows an action."},
{"subject":"English","grade":1,"difficulty":"Olympiad","topic":"English Language","subTopic":"Alphabet",
 "questionText":"How many vowels are there in the English alphabet?",
 "options":["A: 4","B: 5","C: 6","D: 7"],"correctAnswer":"B",
 "explanation":"There are 5 vowels in English: A, E, I, O, U."},
{"subject":"English","grade":1,"difficulty":"Olympiad","topic":"English Language","subTopic":"Plurals",
 "questionText":"What is the plural of 'child'?",
 "options":["A: Childs","B: Childes","C: Children","D: Childrens"],"correctAnswer":"C",
 "explanation":"'Child' has an irregular plural form: 'children'."},
{"subject":"English","grade":1,"difficulty":"Olympiad","topic":"English Language","subTopic":"Colours and Shapes",
 "questionText":"A ball is which shape?",
 "options":["A: Square","B: Triangle","C: Sphere","D: Cube"],"correctAnswer":"C",
 "explanation":"A ball is spherical in shape — a 3D round object called a sphere."},
{"subject":"English","grade":1,"difficulty":"Olympiad","topic":"English Language","subTopic":"Animals",
 "questionText":"What do we call a baby dog?",
 "options":["A: Kitten","B: Calf","C: Puppy","D: Foal"],"correctAnswer":"C",
 "explanation":"A baby dog is called a puppy."},
{"subject":"English","grade":1,"difficulty":"Olympiad","topic":"English Language","subTopic":"Body Parts",
 "questionText":"With which body part do we smell?",
 "options":["A: Eyes","B: Ears","C: Tongue","D: Nose"],"correctAnswer":"D",
 "explanation":"We smell using our nose, which contains olfactory receptors."},
{"subject":"English","grade":1,"difficulty":"Olympiad","topic":"English Language","subTopic":"Days and Months",
 "questionText":"How many months are there in a year?",
 "options":["A: 7","B: 10","C: 12","D: 365"],"correctAnswer":"C",
 "explanation":"There are 12 months in a year: January through December."},
{"subject":"English","grade":1,"difficulty":"Olympiad","topic":"English Language","subTopic":"Opposites",
 "questionText":"What is the opposite of 'open'?",
 "options":["A: Wide","B: Shut","C: Empty","D: Light"],"correctAnswer":"B",
 "explanation":"The opposite of 'open' is 'shut' (or 'closed')."},
{"subject":"English","grade":1,"difficulty":"Olympiad","topic":"English Language","subTopic":"Colours",
 "questionText":"Which colour do you get by mixing red and blue?",
 "options":["A: Orange","B: Green","C: Purple","D: Brown"],"correctAnswer":"C",
 "explanation":"Mixing red and blue paint produces purple (or violet)."},
{"subject":"English","grade":1,"difficulty":"Olympiad","topic":"English Language","subTopic":"Numbers in Words",
 "questionText":"How is the number 15 written in words?",
 "options":["A: Fifty","B: Fifteen","C: Five-one","D: Fiveteen"],"correctAnswer":"B",
 "explanation":"The number 15 is written as 'Fifteen'."},
{"subject":"English","grade":1,"difficulty":"Olympiad","topic":"English Language","subTopic":"Word Order",
 "questionText":"Which sentence is correct?",
 "options":["A: Runs fast she","B: She fast runs","C: She runs fast","D: Fast she runs"],"correctAnswer":"C",
 "explanation":"In English, standard word order is: Subject + Verb + Adverb → 'She runs fast'."},
{"subject":"English","grade":1,"difficulty":"Olympiad","topic":"English Language","subTopic":"Animals Sounds",
 "questionText":"What sound does a cow make?",
 "options":["A: Bark","B: Moo","C: Roar","D: Bleat"],"correctAnswer":"B",
 "explanation":"A cow makes the 'moo' sound."},
{"subject":"English","grade":1,"difficulty":"Olympiad","topic":"English Language","subTopic":"Sight Words",
 "questionText":"Which of these is a sight word?",
 "options":["A: Elephant","B: Because","C: Butterfly","D: Umbrella"],"correctAnswer":"B",
 "explanation":"'Because' is a common high-frequency sight word that children are taught to recognize immediately. Sight words are short, common words."},
{"subject":"English","grade":1,"difficulty":"Olympiad","topic":"English Language","subTopic":"Simple Addition in Words",
 "questionText":"One cat and two cats make how many cats?",
 "options":["A: Two","B: Three","C: Four","D: One"],"correctAnswer":"B",
 "explanation":"1 + 2 = 3 — one cat and two cats make three cats."},
{"subject":"English","grade":1,"difficulty":"Olympiad","topic":"English Language","subTopic":"Story Sequence",
 "questionText":"Put in order: [3-She laughed, 1-She saw a joke, 2-She read it]",
 "options":["A: 1,3,2","B: 3,1,2","C: 1,2,3","D: 2,1,3"],"correctAnswer":"C",
 "explanation":"Logical sequence: She saw a joke → She read it → She laughed (1→2→3)."},

# ── Science G1 Olympiad (+20, 30→50) ─────────────────────────────────────────
{"subject":"Science","grade":1,"difficulty":"Olympiad","topic":"Science","subTopic":"Living and Non-living",
 "questionText":"Which of these is a living thing?",
 "options":["A: Rock","B: Water","C: Tree","D: Car"],"correctAnswer":"C",
 "explanation":"A tree is a living thing — it grows, breathes, and reproduces. Rocks, water, and cars are non-living."},
{"subject":"Science","grade":1,"difficulty":"Olympiad","topic":"Science","subTopic":"Animals",
 "questionText":"Which animal lays eggs AND can fly?",
 "options":["A: Dog","B: Eagle","C: Whale","D: Tiger"],"correctAnswer":"B",
 "explanation":"An eagle is a bird that lays eggs and can fly."},
{"subject":"Science","grade":1,"difficulty":"Olympiad","topic":"Science","subTopic":"Plants",
 "questionText":"Which part of the plant makes food using sunlight?",
 "options":["A: Root","B: Stem","C: Leaf","D: Flower"],"correctAnswer":"C",
 "explanation":"Leaves make food through photosynthesis using sunlight, water, and air."},
{"subject":"Science","grade":1,"difficulty":"Olympiad","topic":"Science","subTopic":"Water",
 "questionText":"In which form is water when it is very cold?",
 "options":["A: Liquid","B: Gas","C: Ice (solid)","D: Steam"],"correctAnswer":"C",
 "explanation":"When water gets very cold (below 0°C), it turns into ice, which is the solid form of water."},
{"subject":"Science","grade":1,"difficulty":"Olympiad","topic":"Science","subTopic":"Sky Objects",
 "questionText":"Which gives us light at night?",
 "options":["A: Sun","B: Moon","C: Cloud","D: Rainbow"],"correctAnswer":"B",
 "explanation":"The Moon reflects sunlight and lights up the night sky."},
{"subject":"Science","grade":1,"difficulty":"Olympiad","topic":"Science","subTopic":"Seasons",
 "questionText":"In which season do trees lose their leaves?",
 "options":["A: Summer","B: Spring","C: Autumn","D: Winter — after Autumn"],"correctAnswer":"C",
 "explanation":"Trees (deciduous) shed their leaves in Autumn (Fall) to prepare for winter."},
{"subject":"Science","grade":1,"difficulty":"Olympiad","topic":"Science","subTopic":"Food",
 "questionText":"Which food comes from a plant?",
 "options":["A: Egg","B: Milk","C: Rice","D: Meat"],"correctAnswer":"C",
 "explanation":"Rice is obtained from a plant (rice paddy). Eggs and meat come from animals; milk is from cows."},
{"subject":"Science","grade":1,"difficulty":"Olympiad","topic":"Science","subTopic":"Senses",
 "questionText":"Which sense organ helps us hear?",
 "options":["A: Eyes","B: Nose","C: Tongue","D: Ears"],"correctAnswer":"D",
 "explanation":"We hear using our ears, which detect sound vibrations."},
{"subject":"Science","grade":1,"difficulty":"Olympiad","topic":"Science","subTopic":"Weather",
 "questionText":"What is the tool used to measure rainfall?",
 "options":["A: Barometer","B: Thermometer","C: Rain gauge","D: Compass"],"correctAnswer":"C",
 "explanation":"A rain gauge is an instrument used to measure the amount of rainfall."},
{"subject":"Science","grade":1,"difficulty":"Olympiad","topic":"Science","subTopic":"Animals",
 "questionText":"A frog can live on land and in water. It is called an:",
 "options":["A: Reptile","B: Amphibian","C: Insect","D: Mammal"],"correctAnswer":"B",
 "explanation":"Animals that can live both in water and on land are called amphibians (e.g., frogs, salamanders)."},
{"subject":"Science","grade":1,"difficulty":"Olympiad","topic":"Science","subTopic":"Materials",
 "questionText":"Which material is transparent (you can see through it)?",
 "options":["A: Wood","B: Metal","C: Glass","D: Cloth"],"correctAnswer":"C",
 "explanation":"Glass is transparent — light passes through it, allowing us to see through it."},
{"subject":"Science","grade":1,"difficulty":"Olympiad","topic":"Science","subTopic":"Magnets",
 "questionText":"What do magnets attract?",
 "options":["A: Wood","B: Plastic","C: Iron","D: Paper"],"correctAnswer":"C",
 "explanation":"Magnets attract materials containing iron (and other ferromagnetic materials like nickel and cobalt)."},
{"subject":"Science","grade":1,"difficulty":"Olympiad","topic":"Science","subTopic":"Light",
 "questionText":"We can see things because of:",
 "options":["A: Air","B: Sound","C: Light","D: Heat"],"correctAnswer":"C",
 "explanation":"We see because light reflects off objects and enters our eyes."},
{"subject":"Science","grade":1,"difficulty":"Olympiad","topic":"Science","subTopic":"Body Parts",
 "questionText":"Which organ pumps blood through our body?",
 "options":["A: Lungs","B: Brain","C: Heart","D: Stomach"],"correctAnswer":"C",
 "explanation":"The heart is the muscular organ that pumps blood throughout the body."},
{"subject":"Science","grade":1,"difficulty":"Olympiad","topic":"Science","subTopic":"Air",
 "questionText":"We breathe in __ to survive.",
 "options":["A: Carbon dioxide","B: Oxygen","C: Nitrogen","D: Smoke"],"correctAnswer":"B",
 "explanation":"Humans and animals breathe in oxygen (O₂) which is used by cells to produce energy."},
{"subject":"Science","grade":1,"difficulty":"Olympiad","topic":"Science","subTopic":"Insects",
 "questionText":"How many legs does an insect have?",
 "options":["A: 4","B: 6","C: 8","D: 10"],"correctAnswer":"B",
 "explanation":"All insects have 6 legs. (Spiders have 8 legs and are arachnids, not insects.)"},
{"subject":"Science","grade":1,"difficulty":"Olympiad","topic":"Science","subTopic":"Soil",
 "questionText":"Plants grow in:",
 "options":["A: Water only","B: Soil","C: Air","D: Sand only"],"correctAnswer":"B",
 "explanation":"Most plants grow in soil, which provides nutrients, water, and support for their roots."},
{"subject":"Science","grade":1,"difficulty":"Olympiad","topic":"Science","subTopic":"Day and Night",
 "questionText":"Earth completes one full rotation in approximately:",
 "options":["A: 1 hour","B: 12 hours","C: 24 hours","D: 365 days"],"correctAnswer":"C",
 "explanation":"Earth completes one full rotation on its axis in approximately 24 hours (one day)."},
{"subject":"Science","grade":1,"difficulty":"Olympiad","topic":"Science","subTopic":"Animals",
 "questionText":"Which animal is the fastest on land?",
 "options":["A: Lion","B: Cheetah","C: Horse","D: Deer"],"correctAnswer":"B",
 "explanation":"The cheetah is the fastest land animal, reaching speeds up to 112 km/h."},
{"subject":"Science","grade":1,"difficulty":"Olympiad","topic":"Science","subTopic":"Environment",
 "questionText":"Planting trees helps because trees:",
 "options":["A: Produce carbon dioxide","B: Use all water","C: Give us oxygen and shade","D: Cause pollution"],"correctAnswer":"C",
 "explanation":"Trees absorb CO₂, produce oxygen through photosynthesis, provide shade, and help maintain ecological balance."},

# ── General Knowledge G4 Olympiad (+15, 30→45) ───────────────────────────────
{"subject":"General Knowledge","grade":4,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"Indian History",
 "questionText":"Who is known as the 'Iron Man of India'?",
 "options":["A: Jawaharlal Nehru","B: Bhagat Singh","C: Sardar Vallabhbhai Patel","D: Subhash Chandra Bose"],"correctAnswer":"C",
 "explanation":"Sardar Vallabhbhai Patel is called the 'Iron Man of India' for his role in unifying India's princely states."},
{"subject":"General Knowledge","grade":4,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"Science",
 "questionText":"The gas responsible for the greenhouse effect is:",
 "options":["A: Oxygen","B: Nitrogen","C: Carbon dioxide","D: Hydrogen"],"correctAnswer":"C",
 "explanation":"Carbon dioxide (CO₂) is the primary greenhouse gas responsible for trapping heat in Earth's atmosphere."},
{"subject":"General Knowledge","grade":4,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"World Geography",
 "questionText":"Which country is the largest in the world by area?",
 "options":["A: USA","B: China","C: Russia","D: Canada"],"correctAnswer":"C",
 "explanation":"Russia is the largest country in the world by area, covering about 17.1 million km²."},
{"subject":"General Knowledge","grade":4,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"Space",
 "questionText":"What is the name of our galaxy?",
 "options":["A: Andromeda","B: Milky Way","C: Triangulum","D: Whirlpool"],"correctAnswer":"B",
 "explanation":"Our solar system is part of the Milky Way galaxy, a spiral galaxy with billions of stars."},
{"subject":"General Knowledge","grade":4,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"Sports",
 "questionText":"How many gold medals has India won at the Olympics? (as of 2020 Tokyo Olympics)",
 "options":["A: 5","B: 7","C: 10","D: 15"],"correctAnswer":"C",
 "explanation":"India has won 10 Olympic gold medals as of Tokyo 2020. (Hockey 8 + Shooter Abhinav Bindra 2008 + Wrestler Sushil Kumar had silver... Actually: India has won 10 gold medals total in Olympics: 8 in field hockey, 1 by Abhinav Bindra, 1 by Neeraj Chopra.)"},
{"subject":"General Knowledge","grade":4,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"Technology",
 "questionText":"Who is known as the founder of Microsoft?",
 "options":["A: Steve Jobs","B: Mark Zuckerberg","C: Bill Gates","D: Elon Musk"],"correctAnswer":"C",
 "explanation":"Bill Gates co-founded Microsoft with Paul Allen in 1975."},
{"subject":"General Knowledge","grade":4,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"Environment",
 "questionText":"Which of these is a non-renewable resource?",
 "options":["A: Wind","B: Solar","C: Coal","D: Water"],"correctAnswer":"C",
 "explanation":"Coal is a non-renewable resource — once used, it cannot be replenished within a human lifespan."},
{"subject":"General Knowledge","grade":4,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"Indian Culture",
 "questionText":"Diwali is celebrated as the festival of:",
 "options":["A: Colours","B: Lights","C: Harvest","D: Spring"],"correctAnswer":"B",
 "explanation":"Diwali, the Festival of Lights, is celebrated by lighting lamps (diyas) and fireworks."},
{"subject":"General Knowledge","grade":4,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"Famous Scientists",
 "questionText":"Who discovered gravity when an apple fell from a tree?",
 "options":["A: Albert Einstein","B: Galileo Galilei","C: Isaac Newton","D: Stephen Hawking"],"correctAnswer":"C",
 "explanation":"Isaac Newton formulated the law of universal gravitation inspired by observing a falling apple."},
{"subject":"General Knowledge","grade":4,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"Books",
 "questionText":"'Harry Potter' was written by:",
 "options":["A: Roald Dahl","B: J.K. Rowling","C: Enid Blyton","D: C.S. Lewis"],"correctAnswer":"B",
 "explanation":"The Harry Potter series was written by British author J.K. Rowling, beginning in 1997."},
{"subject":"General Knowledge","grade":4,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"Human Body",
 "questionText":"The strongest muscle in the human body is the:",
 "options":["A: Bicep","B: Heart","C: Tongue","D: Jaw (masseter)"],"correctAnswer":"D",
 "explanation":"The masseter (jaw muscle) is considered the strongest muscle relative to its size, capable of exerting tremendous force."},
{"subject":"General Knowledge","grade":4,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"Indian Geography",
 "questionText":"Which is the capital city of India?",
 "options":["A: Mumbai","B: Kolkata","C: Chennai","D: New Delhi"],"correctAnswer":"D",
 "explanation":"New Delhi is the capital of India and the seat of the national government."},
{"subject":"General Knowledge","grade":4,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"World Records",
 "questionText":"Which is the tallest building in the world (as of 2024)?",
 "options":["A: One World Trade Center","B: Shanghai Tower","C: Burj Khalifa","D: Makkah Clock Tower"],"correctAnswer":"C",
 "explanation":"The Burj Khalifa in Dubai, UAE (829.8 m tall), is the world's tallest building."},
{"subject":"General Knowledge","grade":4,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"Economics",
 "questionText":"What is currency?",
 "options":["A: Natural resources","B: Money used in a country","C: Types of crops","D: Roads and bridges"],"correctAnswer":"B",
 "explanation":"Currency is the money system used in a country for financial transactions (e.g., Indian Rupee, US Dollar)."},
{"subject":"General Knowledge","grade":4,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"Animals",
 "questionText":"What is a group of lions called?",
 "options":["A: Pack","B: Herd","C: Pride","D: Flock"],"correctAnswer":"C",
 "explanation":"A group of lions is called a pride."},

# ── Hindi G4 Olympiad (+15, 30→45) ───────────────────────────────────────────
{"subject":"Hindi","grade":4,"difficulty":"Olympiad","topic":"Hindi Language","subTopic":"Paryayvachi",
 "questionText":"'वर्षा' का पर्यायवाची शब्द है:",
 "options":["A: गर्मी","B: बारिश","C: ठंड","D: धूप"],"correctAnswer":"B",
 "explanation":"'वर्षा' के पर्यायवाची शब्द हैं — बारिश, मेघ, पावस, वृष्टि।"},
{"subject":"Hindi","grade":4,"difficulty":"Olympiad","topic":"Hindi Language","subTopic":"Vilom",
 "questionText":"'लाभ' का विलोम शब्द है:",
 "options":["A: मुनाफा","B: प्राप्ति","C: हानि","D: सफलता"],"correctAnswer":"C",
 "explanation":"'लाभ' (gain) का विलोम शब्द 'हानि' (loss) है।"},
{"subject":"Hindi","grade":4,"difficulty":"Olympiad","topic":"Hindi Language","subTopic":"Sandhi",
 "questionText":"'विद्यालय' किन दो शब्दों से मिलकर बना है?",
 "options":["A: विद्या + लय","B: वि + द्यालय","C: विद्या + आलय","D: विद्या + अलय"],"correctAnswer":"C",
 "explanation":"विद्यालय = विद्या + आलय (आ + आ = आ — दीर्घ संधि)।"},
{"subject":"Hindi","grade":4,"difficulty":"Olympiad","topic":"Hindi Language","subTopic":"Kaal",
 "questionText":"'राम खाना खाएगा' — यह किस काल का वाक्य है?",
 "options":["A: भूतकाल","B: वर्तमान काल","C: भविष्यत काल","D: सामान्य वर्तमान"],"correctAnswer":"C",
 "explanation":"'खाएगा' भविष्यत काल की क्रिया है — यह काम आगे होगा।"},
{"subject":"Hindi","grade":4,"difficulty":"Olympiad","topic":"Hindi Language","subTopic":"Vachan",
 "questionText":"'पत्ता' का बहुवचन है:",
 "options":["A: पत्ताएं","B: पत्ते","C: पत्तियाँ","D: पत्ताओं"],"correctAnswer":"B",
 "explanation":"'पत्ता' का बहुवचन 'पत्ते' होता है।"},
{"subject":"Hindi","grade":4,"difficulty":"Olympiad","topic":"Hindi Language","subTopic":"Muhavare",
 "questionText":"'दाँत खट्टे करना' मुहावरे का अर्थ है:",
 "options":["A: मीठा खाना","B: हराना","C: दाँत दर्द होना","D: बहुत हँसना"],"correctAnswer":"B",
 "explanation":"'दाँत खट्टे करना' मुहावरे का अर्थ है — किसी को हरा देना / पराजित करना।"},
{"subject":"Hindi","grade":4,"difficulty":"Olympiad","topic":"Hindi Language","subTopic":"Samas",
 "questionText":"'राजपुत्र' में कौन-सा समास है?",
 "options":["A: द्वंद्व","B: तत्पुरुष","C: बहुव्रीहि","D: द्विगु"],"correctAnswer":"B",
 "explanation":"राज का पुत्र = राजपुत्र — यह तत्पुरुष (सम्बन्ध तत्पुरुष) समास है।"},
{"subject":"Hindi","grade":4,"difficulty":"Olympiad","topic":"Hindi Language","subTopic":"Alankar",
 "questionText":"'पीपर पात सरिस मन डोला' — इसमें कौन-सा अलंकार है?",
 "options":["A: रूपक","B: उपमा","C: यमक","D: अनुप्रास"],"correctAnswer":"B",
 "explanation":"'सरिस' (समान) शब्द का प्रयोग हुआ है — इसलिए यह 'उपमा' अलंकार है।"},
{"subject":"Hindi","grade":4,"difficulty":"Olympiad","topic":"Hindi Language","subTopic":"Ling",
 "questionText":"'विद्यार्थी' का स्त्रीलिंग क्या है?",
 "options":["A: विद्यार्थिनी","B: विद्यार्थिन","C: विद्यार्थी","D: विद्यार्थीनी"],"correctAnswer":"A",
 "explanation":"'विद्यार्थी' का स्त्रीलिंग 'विद्यार्थिनी' होता है।"},
{"subject":"Hindi","grade":4,"difficulty":"Olympiad","topic":"Hindi Language","subTopic":"Upsarg",
 "questionText":"'सुलभ' में कौन-सा उपसर्ग है?",
 "options":["A: स","B: सु","C: सुल","D: लभ"],"correctAnswer":"B",
 "explanation":"'सुलभ' में 'सु' उपसर्ग है — सु + लभ = सुलभ (आसानी से मिलने वाला)।"},
{"subject":"Hindi","grade":4,"difficulty":"Olympiad","topic":"Hindi Language","subTopic":"Vyakaran",
 "questionText":"हिंदी वर्णमाला में व्यंजनों की संख्या है:",
 "options":["A: 33","B: 34","C: 35","D: 36"],"correctAnswer":"A",
 "explanation":"हिंदी वर्णमाला में 33 मूल व्यंजन होते हैं।"},
{"subject":"Hindi","grade":4,"difficulty":"Olympiad","topic":"Hindi Language","subTopic":"Rachna",
 "questionText":"'जो कभी नहीं हारता' — इसके लिए एक शब्द है:",
 "options":["A: अजेय","B: विजेता","C: अभय","D: सदाशय"],"correctAnswer":"A",
 "explanation":"'अजेय' का अर्थ है जिसे जीता न जा सके — जो कभी नहीं हारता।"},
{"subject":"Hindi","grade":4,"difficulty":"Olympiad","topic":"Hindi Language","subTopic":"Nibandh",
 "questionText":"'स्वच्छता' पर निबंध लिखते समय किस बारे में लिखा जाएगा?",
 "options":["A: खेल का मैदान","B: साफ-सफाई का महत्व","C: कंप्यूटर की उपयोगिता","D: वायु प्रदूषण"],"correctAnswer":"B",
 "explanation":"'स्वच्छता' पर निबंध में साफ-सफाई के महत्व, स्वच्छ भारत अभियान आदि लिखा जाएगा।"},
{"subject":"Hindi","grade":4,"difficulty":"Olympiad","topic":"Hindi Language","subTopic":"Proverbs",
 "questionText":"'करत करत अभ्यास ते, जड़मति होत सुजान' — इस दोहे का क्या अर्थ है?",
 "options":["A: अभ्यास से मूर्ख भी बुद्धिमान बन सकता है","B: पढ़ाई कठिन होती है","C: मेहनत व्यर्थ जाती है","D: जड़मति बुद्धिमान नहीं हो सकता"],"correctAnswer":"A",
 "explanation":"लगातार अभ्यास (practice) से एक मूर्ख व्यक्ति भी बुद्धिमान बन जाता है — यही इस दोहे का अर्थ है।"},
{"subject":"Hindi","grade":4,"difficulty":"Olympiad","topic":"Hindi Language","subTopic":"Lokokti",
 "questionText":"'जैसी करनी वैसी भरनी' का अर्थ है:",
 "options":["A: जो करते हो वही पाते हो","B: सब काम करना पड़ता है","C: मेहनत का फल मीठा होता है","D: किस्मत पर भरोसा रखो"],"correctAnswer":"A",
 "explanation":"'जैसी करनी वैसी भरनी' — जैसा कर्म करोगे, वैसा ही फल मिलेगा।"},

# ── General Knowledge G5 Olympiad (+15, 30→45) ───────────────────────────────
{"subject":"General Knowledge","grade":5,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"Science",
 "questionText":"The chemical formula of water is:",
 "options":["A: HO","B: H₂O","C: H₂O₂","D: HO₂"],"correctAnswer":"B",
 "explanation":"Water consists of 2 hydrogen atoms and 1 oxygen atom: H₂O."},
{"subject":"General Knowledge","grade":5,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"Space",
 "questionText":"The first Indian woman in space was:",
 "options":["A: Sunita Williams","B: Kalpana Chawla","C: Ritu Karidhal","D: Tessy Thomas"],"correctAnswer":"B",
 "explanation":"Kalpana Chawla was the first Indian-born woman in space (1997, STS-87 mission). She was of Indian origin but was an American astronaut."},
{"subject":"General Knowledge","grade":5,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"Indian History",
 "questionText":"The Indian National Congress was founded in:",
 "options":["A: 1857","B: 1875","C: 1885","D: 1905"],"correctAnswer":"C",
 "explanation":"The Indian National Congress was founded in 1885 by A.O. Hume, Dadabhai Naoroji, and Dinshaw Wacha."},
{"subject":"General Knowledge","grade":5,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"Environment",
 "questionText":"The Amazon rainforest is called the 'lungs of the Earth' because it:",
 "options":["A: Has many rivers","B: Produces vast amounts of oxygen","C: Is the hottest place","D: Has the most animals"],"correctAnswer":"B",
 "explanation":"The Amazon rainforest produces about 20% of Earth's oxygen through photosynthesis, earning the 'lungs of the Earth' title."},
{"subject":"General Knowledge","grade":5,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"World Records",
 "questionText":"Mount Everest is located in which mountain range?",
 "options":["A: Alps","B: Andes","C: Himalayas","D: Rockies"],"correctAnswer":"C",
 "explanation":"Mount Everest is in the Himalayan mountain range, on the border between Nepal and Tibet."},
{"subject":"General Knowledge","grade":5,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"Technology",
 "questionText":"What does 'AI' stand for in technology?",
 "options":["A: Automated Internet","B: Artificial Intelligence","C: Automated Input","D: Advanced Information"],"correctAnswer":"B",
 "explanation":"AI stands for Artificial Intelligence — the simulation of human intelligence processes by machines and computer systems."},
{"subject":"General Knowledge","grade":5,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"Famous Scientists",
 "questionText":"Albert Einstein is famous for the theory of:",
 "options":["A: Gravity","B: Evolution","C: Relativity","D: Quantum Mechanics"],"correctAnswer":"C",
 "explanation":"Albert Einstein developed the Special Theory of Relativity (1905) and General Theory of Relativity (1915)."},
{"subject":"General Knowledge","grade":5,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"Indian Constitution",
 "questionText":"The Indian Constitution is the __ constitution in the world.",
 "options":["A: Shortest","B: Oldest","C: Longest written","D: Most amended"],"correctAnswer":"C",
 "explanation":"India has the longest written constitution in the world, originally with 395 articles."},
{"subject":"General Knowledge","grade":5,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"Awards",
 "questionText":"The Bharat Ratna is India's highest:",
 "options":["A: Military honour","B: Civilian honour","C: Sports award","D: Literary award"],"correctAnswer":"B",
 "explanation":"The Bharat Ratna is India's highest civilian honour, awarded for exceptional service to the nation."},
{"subject":"General Knowledge","grade":5,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"World Events",
 "questionText":"The headquarters of the United Nations is in:",
 "options":["A: London","B: Washington D.C.","C: Geneva","D: New York City"],"correctAnswer":"D",
 "explanation":"The UN headquarters is located in New York City, USA (on the East River, Manhattan)."},
{"subject":"General Knowledge","grade":5,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"Sports",
 "questionText":"The 'Grand Slam' in tennis consists of how many major tournaments?",
 "options":["A: 3","B: 4","C: 5","D: 6"],"correctAnswer":"B",
 "explanation":"Tennis Grand Slam: Australian Open, French Open (Roland Garros), Wimbledon, US Open — 4 tournaments."},
{"subject":"General Knowledge","grade":5,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"Indian Economy",
 "questionText":"India's currency is the Rupee. Its symbol (₹) was designed by:",
 "options":["A: Udaya Kumar","B: Amartya Sen","C: Ratan Tata","D: Nandan Nilekani"],"correctAnswer":"A",
 "explanation":"The Indian Rupee symbol (₹) was designed by D. Udaya Kumar, adopted in 2010."},
{"subject":"General Knowledge","grade":5,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"Famous Landmarks",
 "questionText":"The Taj Mahal was built by Mughal Emperor Shah Jahan in memory of his wife:",
 "options":["A: Nur Jahan","B: Mumtaz Mahal","C: Jodha Bai","D: Razia Sultana"],"correctAnswer":"B",
 "explanation":"The Taj Mahal was built between 1631–1648 by Shah Jahan as a mausoleum for his beloved wife Mumtaz Mahal."},
{"subject":"General Knowledge","grade":5,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"Books and Literature",
 "questionText":"'The Jungle Book' was written by:",
 "options":["A: Charles Dickens","B: Rudyard Kipling","C: Mark Twain","D: Lewis Carroll"],"correctAnswer":"B",
 "explanation":"'The Jungle Book' (1894) was written by Rudyard Kipling, featuring Mowgli the jungle boy."},
{"subject":"General Knowledge","grade":5,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"World Geography",
 "questionText":"The Suez Canal connects which two seas?",
 "options":["A: Mediterranean and Red Sea","B: Black Sea and Caspian Sea","C: Red Sea and Arabian Sea","D: Atlantic and Pacific"],"correctAnswer":"A",
 "explanation":"The Suez Canal (Egypt) connects the Mediterranean Sea to the Red Sea, shortening the sea route between Europe and Asia."},

]

ok = dup = err = 0
for i, q in enumerate(questions, 1):
    try:
        r = insert(conn, q)
        if r == "OK": ok += 1
        else: dup += 1
        diff_short = q["difficulty"][:3].upper()
        print(f"  {r:4s}  Q{i:03d} [{q['subject']:25s} G{q['grade']:02d} {diff_short}] {q['subTopic']}")
    except Exception as e:
        err += 1
        print(f"  ERR   Q{i:03d} {e}")

print(f"\n  Done: {ok} posted, {dup} duplicates, {err} errors  (total={ok+dup+err})")
