import pyodbc, uuid, json, sys
sys.stdout.reconfigure(encoding='utf-8', errors='replace')

conn = pyodbc.connect(
    "DRIVER={ODBC Driver 17 for SQL Server};"
    "SERVER=olympiadready-np.database.windows.net;"
    "DATABASE=OlympiadReady;"
    "UID=nyxen-admin;PWD=Olympiad@2026"
)

def insert(conn, q):
    c = conn.cursor()
    c.execute("SELECT 1 FROM QuestionBank WHERE Subject=? AND Grade=? AND SubTopic=? AND QuestionText=?",
              q["subject"], q["grade"], q["subTopic"], q["questionText"])
    if c.fetchone():
        return "DUP"
    c.execute("""INSERT INTO QuestionBank
                 (QuestionBankId,Subject,Grade,Difficulty,Topic,SubTopic,
                  QuestionText,OptionsJson,CorrectAnswer,Explanation,CreatedAt)
                 VALUES (?,?,?,?,?,?,?,?,?,?,GETUTCDATE())""",
              str(uuid.uuid4()).upper(), q["subject"], q["grade"], q["difficulty"],
              q["topic"], q["subTopic"], q["questionText"],
              json.dumps(q["options"]), q["correctAnswer"], q["explanation"])
    conn.commit()
    return "OK"

questions = [

# ── Computer Science G4 Olympiad (+15, 30→45) ─────────────────────────────────
{"subject":"Computer Science","grade":4,"difficulty":"Olympiad","topic":"Computer Science","subTopic":"Algorithms",
 "questionText":"An algorithm is best described as:",
 "options":["A: A computer program","B: A step-by-step procedure to solve a problem","C: A type of software","D: A computer language"],"correctAnswer":"B",
 "explanation":"An algorithm is a finite set of well-defined instructions (step-by-step procedure) for solving a problem."},
{"subject":"Computer Science","grade":4,"difficulty":"Olympiad","topic":"Computer Science","subTopic":"Number Systems",
 "questionText":"What is 7 in binary?",
 "options":["A: 101","B: 110","C: 111","D: 100"],"correctAnswer":"C",
 "explanation":"7 = 4+2+1 = 1×2²+1×2¹+1×2⁰ = 111 in binary."},
{"subject":"Computer Science","grade":4,"difficulty":"Olympiad","topic":"Computer Science","subTopic":"Logic Gates",
 "questionText":"An AND gate output is 1 only when:",
 "options":["A: At least one input is 1","B: Both inputs are 1","C: Both inputs are 0","D: Inputs are different"],"correctAnswer":"B",
 "explanation":"AND gate: output is 1 only when ALL inputs are 1."},
{"subject":"Computer Science","grade":4,"difficulty":"Olympiad","topic":"Computer Science","subTopic":"Programming",
 "questionText":"A loop that never ends is called an:",
 "options":["A: Finite loop","B: For loop","C: Infinite loop","D: While loop"],"correctAnswer":"C",
 "explanation":"An infinite loop runs forever because its exit condition is never met."},
{"subject":"Computer Science","grade":4,"difficulty":"Olympiad","topic":"Computer Science","subTopic":"Data Types",
 "questionText":"Which data type stores True or False values?",
 "options":["A: Integer","B: String","C: Float","D: Boolean"],"correctAnswer":"D",
 "explanation":"Boolean data type stores only two values: True or False (1 or 0)."},
{"subject":"Computer Science","grade":4,"difficulty":"Olympiad","topic":"Computer Science","subTopic":"File Management",
 "questionText":"Which operation permanently removes a file from the Recycle Bin?",
 "options":["A: Delete","B: Cut","C: Empty Recycle Bin","D: Move"],"correctAnswer":"C",
 "explanation":"Files in the Recycle Bin can be restored. 'Empty Recycle Bin' permanently deletes them."},
{"subject":"Computer Science","grade":4,"difficulty":"Olympiad","topic":"Computer Science","subTopic":"Networking",
 "questionText":"LAN stands for:",
 "options":["A: Large Area Network","B: Local Area Network","C: Light Area Network","D: Linked Area Node"],"correctAnswer":"B",
 "explanation":"LAN (Local Area Network) connects computers within a limited area such as a school, office, or building."},
{"subject":"Computer Science","grade":4,"difficulty":"Olympiad","topic":"Computer Science","subTopic":"Internet",
 "questionText":"A website address is called a:",
 "options":["A: IP address","B: URL","C: Domain name only","D: MAC address"],"correctAnswer":"B",
 "explanation":"URL (Uniform Resource Locator) is the complete web address used to access a specific page on the internet."},
{"subject":"Computer Science","grade":4,"difficulty":"Olympiad","topic":"Computer Science","subTopic":"Software",
 "questionText":"Which is an example of system software?",
 "options":["A: MS Paint","B: Windows OS","C: VLC Player","D: Google Chrome"],"correctAnswer":"B",
 "explanation":"Windows OS is system software — it manages hardware and provides a platform for other software to run."},
{"subject":"Computer Science","grade":4,"difficulty":"Olympiad","topic":"Computer Science","subTopic":"Flowcharts",
 "questionText":"A diamond shape in a flowchart represents:",
 "options":["A: Start/End","B: Process","C: Decision","D: Input/Output"],"correctAnswer":"C",
 "explanation":"In a flowchart, a diamond (rhombus) shape represents a decision point (Yes/No question)."},
{"subject":"Computer Science","grade":4,"difficulty":"Olympiad","topic":"Computer Science","subTopic":"Cybersafety",
 "questionText":"What should you NEVER share online with strangers?",
 "options":["A: Your favourite colour","B: Your password and personal address","C: Your favourite movie","D: Your hobby"],"correctAnswer":"B",
 "explanation":"Never share personal information like passwords, home address, phone number, or school name with strangers online."},
{"subject":"Computer Science","grade":4,"difficulty":"Olympiad","topic":"Computer Science","subTopic":"Memory",
 "questionText":"Which stores data permanently even when the computer is off?",
 "options":["A: RAM","B: Cache","C: ROM","D: Registers"],"correctAnswer":"C",
 "explanation":"ROM (Read Only Memory) and storage devices (like hard drives) retain data permanently without power."},
{"subject":"Computer Science","grade":4,"difficulty":"Olympiad","topic":"Computer Science","subTopic":"Spreadsheet",
 "questionText":"In Excel, cell B3 means:",
 "options":["A: Column B, Row 3","B: Row B, Column 3","C: Block B3","D: Both row and column 3"],"correctAnswer":"A",
 "explanation":"In Excel, columns are labelled with letters (B) and rows with numbers (3). B3 = Column B, Row 3."},
{"subject":"Computer Science","grade":4,"difficulty":"Olympiad","topic":"Computer Science","subTopic":"Programming Concepts",
 "questionText":"A variable in programming is best described as:",
 "options":["A: A fixed number","B: A named storage location whose value can change","C: A type of loop","D: A method to print output"],"correctAnswer":"B",
 "explanation":"A variable is a named container in memory that can store data values that may change during program execution."},
{"subject":"Computer Science","grade":4,"difficulty":"Olympiad","topic":"Computer Science","subTopic":"Output",
 "questionText":"What is the output of: print(3 + 4 * 2) in Python?",
 "options":["A: 14","B: 11","C: 10","D: 24"],"correctAnswer":"B",
 "explanation":"BODMAS/PEMDAS: multiplication first → 4×2=8, then 3+8=11."},

# ── Social Studies G4 Olympiad (+15, 30→45) ──────────────────────────────────
{"subject":"Social Studies","grade":4,"difficulty":"Olympiad","topic":"Social Studies","subTopic":"Indian History",
 "questionText":"Who started the 'Dandi March' (Salt March) in 1930?",
 "options":["A: Jawaharlal Nehru","B: Bal Gangadhar Tilak","C: Mahatma Gandhi","D: Bhagat Singh"],"correctAnswer":"C",
 "explanation":"Mahatma Gandhi led the Dandi March (Salt Satyagraha) in March 1930, walking 241 miles to protest the British salt tax."},
{"subject":"Social Studies","grade":4,"difficulty":"Olympiad","topic":"Social Studies","subTopic":"Indian Geography",
 "questionText":"Which river is the longest in India?",
 "options":["A: Godavari","B: Yamuna","C: Ganga","D: Brahmaputra"],"correctAnswer":"C",
 "explanation":"The Ganga (Ganges) is the longest river entirely in India at approximately 2,525 km."},
{"subject":"Social Studies","grade":4,"difficulty":"Olympiad","topic":"Social Studies","subTopic":"Government",
 "questionText":"The legislative body of India is called:",
 "options":["A: Cabinet","B: Parliament","C: Supreme Court","D: President's House"],"correctAnswer":"B",
 "explanation":"Parliament is the supreme legislative body of India, consisting of Lok Sabha, Rajya Sabha, and the President."},
{"subject":"Social Studies","grade":4,"difficulty":"Olympiad","topic":"Social Studies","subTopic":"World Geography",
 "questionText":"Which continent has no permanent human settlements?",
 "options":["A: Arctic","B: Antarctica","C: Greenland","D: Sahara"],"correctAnswer":"B",
 "explanation":"Antarctica has no permanent human residents — only scientists at research stations stay there temporarily."},
{"subject":"Social Studies","grade":4,"difficulty":"Olympiad","topic":"Social Studies","subTopic":"Civics",
 "questionText":"The minimum age to vote in India is:",
 "options":["A: 16","B: 18","C: 21","D: 25"],"correctAnswer":"B",
 "explanation":"The voting age in India is 18 years, as per the 61st Constitutional Amendment (1988)."},
{"subject":"Social Studies","grade":4,"difficulty":"Olympiad","topic":"Social Studies","subTopic":"Climate",
 "questionText":"The hottest continent on Earth is:",
 "options":["A: Asia","B: Australia","C: Africa","D: South America"],"correctAnswer":"C",
 "explanation":"Africa is the hottest continent on Earth, with the Sahara Desert recording some of the world's highest temperatures."},
{"subject":"Social Studies","grade":4,"difficulty":"Olympiad","topic":"Social Studies","subTopic":"World History",
 "questionText":"The Great Wall of China was primarily built to:",
 "options":["A: Trade goods","B: Transport water","C: Defend against invasions","D: Measure distance"],"correctAnswer":"C",
 "explanation":"The Great Wall of China was constructed to protect against northern nomadic invasions."},
{"subject":"Social Studies","grade":4,"difficulty":"Olympiad","topic":"Social Studies","subTopic":"Indian Culture",
 "questionText":"'Vande Mataram' was composed by:",
 "options":["A: Rabindranath Tagore","B: Bankim Chandra Chatterjee","C: Subhash Chandra Bose","D: Lala Lajpat Rai"],"correctAnswer":"B",
 "explanation":"'Vande Mataram' was written by Bankim Chandra Chatterjee in 1882 in his novel 'Anandamath'."},
{"subject":"Social Studies","grade":4,"difficulty":"Olympiad","topic":"Social Studies","subTopic":"Natural Disasters",
 "questionText":"An earthquake's intensity is measured on the:",
 "options":["A: Beaufort scale","B: Richter scale","C: Celsius scale","D: Decibel scale"],"correctAnswer":"B",
 "explanation":"Earthquake magnitude is measured on the Richter scale (or moment magnitude scale)."},
{"subject":"Social Studies","grade":4,"difficulty":"Olympiad","topic":"Social Studies","subTopic":"Economy",
 "questionText":"When a country sells goods to another country, it is called:",
 "options":["A: Import","B: Trade deficit","C: Export","D: Barter"],"correctAnswer":"C",
 "explanation":"Export is the sale of goods and services from one country to another country."},
{"subject":"Social Studies","grade":4,"difficulty":"Olympiad","topic":"Social Studies","subTopic":"Indian States",
 "questionText":"How many states does India currently have?",
 "options":["A: 25","B: 28","C: 29","D: 30"],"correctAnswer":"B",
 "explanation":"As of 2024, India has 28 states and 8 Union Territories (after J&K was split into 2 UTs in 2019)."},
{"subject":"Social Studies","grade":4,"difficulty":"Olympiad","topic":"Social Studies","subTopic":"Crops",
 "questionText":"Kharif crops are grown in which season?",
 "options":["A: Winter","B: Summer","C: Monsoon","D: Spring"],"correctAnswer":"C",
 "explanation":"Kharif crops (rice, cotton, maize) are sown at the start of the monsoon season (June) and harvested in autumn."},
{"subject":"Social Studies","grade":4,"difficulty":"Olympiad","topic":"Social Studies","subTopic":"World Organizations",
 "questionText":"UNICEF works primarily for:",
 "options":["A: Nuclear disarmament","B: Children's rights and welfare","C: Trade between nations","D: Climate change"],"correctAnswer":"B",
 "explanation":"UNICEF (United Nations Children's Fund) works to protect and promote the rights and well-being of children worldwide."},
{"subject":"Social Studies","grade":4,"difficulty":"Olympiad","topic":"Social Studies","subTopic":"Transport",
 "questionText":"The first railway line in India was laid in:",
 "options":["A: 1837","B: 1853","C: 1857","D: 1869"],"correctAnswer":"B",
 "explanation":"India's first railway line ran from Bori Bunder (Mumbai) to Thane, a distance of 34 km, on April 16, 1853."},
{"subject":"Social Studies","grade":4,"difficulty":"Olympiad","topic":"Social Studies","subTopic":"Famous Leaders",
 "questionText":"Who was the first Prime Minister of India?",
 "options":["A: Sardar Patel","B: B.R. Ambedkar","C: Jawaharlal Nehru","D: Rajendra Prasad"],"correctAnswer":"C",
 "explanation":"Jawaharlal Nehru was India's first Prime Minister, serving from 1947 to 1964."},

# ── Spell Bee G4 Advanced (+15, 30→45) ───────────────────────────────────────
{"subject":"Spell Bee","grade":4,"difficulty":"Advanced","topic":"Spell Bee","subTopic":"Difficult Spellings",
 "questionText":"Which spelling is correct?",
 "options":["A: Necessary","B: Necesary","C: Neccessary","D: Necessery"],"correctAnswer":"A",
 "explanation":"The correct spelling is 'Necessary' — one C, double S (Ne-cess-a-ry)."},
{"subject":"Spell Bee","grade":4,"difficulty":"Advanced","topic":"Spell Bee","subTopic":"Tricky Words",
 "questionText":"Choose the correctly spelled word:",
 "options":["A: Tommorrow","B: Tommorow","C: Tomorrow","D: Tomorrrow"],"correctAnswer":"C",
 "explanation":"'Tomorrow' has one M and one R: To-mor-row."},
{"subject":"Spell Bee","grade":4,"difficulty":"Advanced","topic":"Spell Bee","subTopic":"Science Words",
 "questionText":"Which spelling is correct for the green pigment in leaves?",
 "options":["A: Clorophyll","B: Chlorophyl","C: Chlorofyll","D: Chlorophyll"],"correctAnswer":"D",
 "explanation":"'Chlorophyll' is the correct spelling — Chlo-ro-phyll (double L at the end)."},
{"subject":"Spell Bee","grade":4,"difficulty":"Advanced","topic":"Spell Bee","subTopic":"Geography Words",
 "questionText":"Select the correct spelling of the world's largest ocean:",
 "options":["A: Paciffic","B: Pacific","C: Pasific","D: Pacefic"],"correctAnswer":"B",
 "explanation":"'Pacific' is spelled P-A-C-I-F-I-C."},
{"subject":"Spell Bee","grade":4,"difficulty":"Advanced","topic":"Spell Bee","subTopic":"Homophones Spelling",
 "questionText":"Which word means 'to know something in your mind'?",
 "options":["A: Know","B: No","C: Now","D: Knoe"],"correctAnswer":"A",
 "explanation":"'Know' (with silent K) means to be aware or informed. 'No' means negative. They are homophones."},
{"subject":"Spell Bee","grade":4,"difficulty":"Advanced","topic":"Spell Bee","subTopic":"Double Letters",
 "questionText":"Which word is spelled correctly?",
 "options":["A: Balloon","B: Balloun","C: Baloon","D: Ballone"],"correctAnswer":"A",
 "explanation":"'Balloon' has double L and double O: Bal-loon."},
{"subject":"Spell Bee","grade":4,"difficulty":"Advanced","topic":"Spell Bee","subTopic":"Silent Letters",
 "questionText":"Which word has a silent letter?",
 "options":["A: Pen","B: Cup","C: Knee","D: Bag"],"correctAnswer":"C",
 "explanation":"'Knee' has a silent 'k' — it is pronounced 'nee'. The k is not sounded."},
{"subject":"Spell Bee","grade":4,"difficulty":"Advanced","topic":"Spell Bee","subTopic":"Animal Names",
 "questionText":"Choose the correct spelling:",
 "options":["A: Girafe","B: Giraffe","C: Girafee","D: Girrafe"],"correctAnswer":"B",
 "explanation":"'Giraffe' is spelled G-I-R-A-F-F-E (double F)."},
{"subject":"Spell Bee","grade":4,"difficulty":"Advanced","topic":"Spell Bee","subTopic":"Compound Words",
 "questionText":"How do you spell the day before Saturday?",
 "options":["A: Fryday","B: Friday","C: Freiday","D: Fridday"],"correctAnswer":"B",
 "explanation":"The day before Saturday is 'Friday' — F-R-I-D-A-Y."},
{"subject":"Spell Bee","grade":4,"difficulty":"Advanced","topic":"Spell Bee","subTopic":"Commonly Misspelled",
 "questionText":"Choose the correct spelling:",
 "options":["A: Freind","B: Frend","C: Friend","D: Frieend"],"correctAnswer":"C",
 "explanation":"'Friend' follows the 'i before e except after c' rule: F-R-I-E-N-D."},
{"subject":"Spell Bee","grade":4,"difficulty":"Advanced","topic":"Spell Bee","subTopic":"Body Parts Spelling",
 "questionText":"Spell the organ that pumps blood:",
 "options":["A: Haert","B: Heart","C: Heartt","D: Herat"],"correctAnswer":"B",
 "explanation":"'Heart' is spelled H-E-A-R-T."},
{"subject":"Spell Bee","grade":4,"difficulty":"Advanced","topic":"Spell Bee","subTopic":"Country Names",
 "questionText":"Which is the correct spelling of a country in South Asia?",
 "options":["A: Bangledesh","B: Bangladash","C: Bangladesh","D: Bangaldesh"],"correctAnswer":"C",
 "explanation":"'Bangladesh' is spelled B-A-N-G-L-A-D-E-S-H."},
{"subject":"Spell Bee","grade":4,"difficulty":"Advanced","topic":"Spell Bee","subTopic":"Colour Spelling",
 "questionText":"Choose the correct British English spelling of a colour:",
 "options":["A: Colour","B: Color","C: Coulor","D: Collour"],"correctAnswer":"A",
 "explanation":"'Colour' is the British English spelling; 'Color' is the American English spelling."},
{"subject":"Spell Bee","grade":4,"difficulty":"Advanced","topic":"Spell Bee","subTopic":"Weather Words",
 "questionText":"How do you spell the word for frozen water that falls from the sky?",
 "options":["A: Snou","B: Snow","C: Sno","D: Snoww"],"correctAnswer":"B",
 "explanation":"'Snow' is spelled S-N-O-W."},
{"subject":"Spell Bee","grade":4,"difficulty":"Advanced","topic":"Spell Bee","subTopic":"Food Spelling",
 "questionText":"Choose the correctly spelled vegetable:",
 "options":["A: Brocolli","B: Broccoli","C: Broccoly","D: Brocoli"],"correctAnswer":"B",
 "explanation":"'Broccoli' is spelled B-R-O-C-C-O-L-I (double C)."},

# ── Computer Science G6 Advanced (+15, 30→45) ────────────────────────────────
{"subject":"Computer Science","grade":6,"difficulty":"Advanced","topic":"Computer Science","subTopic":"Python Basics",
 "questionText":"What is the output of: print(10 % 3) in Python?",
 "options":["A: 3","B: 1","C: 0","D: 3.33"],"correctAnswer":"B",
 "explanation":"% is the modulo operator (remainder). 10 ÷ 3 = 3 remainder 1. So 10 % 3 = 1."},
{"subject":"Computer Science","grade":6,"difficulty":"Advanced","topic":"Computer Science","subTopic":"HTML",
 "questionText":"What does HTML stand for?",
 "options":["A: High-level Text Markup Language","B: HyperText Markup Language","C: HyperTransfer Markup Logic","D: High-Tech Markup Language"],"correctAnswer":"B",
 "explanation":"HTML stands for HyperText Markup Language — the standard language for creating web pages."},
{"subject":"Computer Science","grade":6,"difficulty":"Advanced","topic":"Computer Science","subTopic":"Data Structures",
 "questionText":"An array stores elements:",
 "options":["A: In random memory locations","B: In linked nodes","C: In contiguous (consecutive) memory locations","D: As key-value pairs"],"correctAnswer":"C",
 "explanation":"An array stores elements in contiguous (consecutive) memory locations, allowing direct index-based access."},
{"subject":"Computer Science","grade":6,"difficulty":"Advanced","topic":"Computer Science","subTopic":"Sorting",
 "questionText":"Which sorting algorithm repeatedly finds the minimum element and places it at the beginning?",
 "options":["A: Bubble Sort","B: Insertion Sort","C: Selection Sort","D: Merge Sort"],"correctAnswer":"C",
 "explanation":"Selection Sort scans the unsorted portion for the minimum element and swaps it to the sorted boundary."},
{"subject":"Computer Science","grade":6,"difficulty":"Advanced","topic":"Computer Science","subTopic":"Networking",
 "questionText":"What does HTTP stand for?",
 "options":["A: HyperText Transfer Protocol","B: High Transfer Text Protocol","C: HyperText Transmission Program","D: High Tech Transfer Protocol"],"correctAnswer":"A",
 "explanation":"HTTP (HyperText Transfer Protocol) is the foundation of data communication on the World Wide Web."},
{"subject":"Computer Science","grade":6,"difficulty":"Advanced","topic":"Computer Science","subTopic":"Database",
 "questionText":"Which of the following is a primary key characteristic?",
 "options":["A: Can be NULL","B: Can have duplicate values","C: Uniquely identifies each record","D: Must be numeric"],"correctAnswer":"C",
 "explanation":"A primary key uniquely identifies each record in a database table — no two rows can have the same primary key value."},
{"subject":"Computer Science","grade":6,"difficulty":"Advanced","topic":"Computer Science","subTopic":"Boolean Logic",
 "questionText":"What is the result of: True AND False in Python?",
 "options":["A: True","B: False","C: None","D: Error"],"correctAnswer":"B",
 "explanation":"AND operator: both conditions must be True for result to be True. True AND False = False."},
{"subject":"Computer Science","grade":6,"difficulty":"Advanced","topic":"Computer Science","subTopic":"Functions",
 "questionText":"A function that calls itself is called:",
 "options":["A: A nested function","B: A recursive function","C: A lambda function","D: An inline function"],"correctAnswer":"B",
 "explanation":"A recursive function calls itself within its definition to solve sub-problems of the original problem."},
{"subject":"Computer Science","grade":6,"difficulty":"Advanced","topic":"Computer Science","subTopic":"OOP",
 "questionText":"In OOP, a blueprint for creating objects is called a:",
 "options":["A: Method","B: Function","C: Class","D: Variable"],"correctAnswer":"C",
 "explanation":"A class is a blueprint/template that defines the attributes and methods of objects."},
{"subject":"Computer Science","grade":6,"difficulty":"Advanced","topic":"Computer Science","subTopic":"Memory Units",
 "questionText":"1 Kilobyte (KB) = how many bytes?",
 "options":["A: 100","B: 512","C: 1000","D: 1024"],"correctAnswer":"D",
 "explanation":"1 Kilobyte = 1024 bytes (2¹⁰ = 1024) in binary computing."},
{"subject":"Computer Science","grade":6,"difficulty":"Advanced","topic":"Computer Science","subTopic":"Encryption",
 "questionText":"The process of converting readable data into an unreadable format for security is called:",
 "options":["A: Compression","B: Encryption","C: Formatting","D: Compiling"],"correctAnswer":"B",
 "explanation":"Encryption converts plaintext data into ciphertext to prevent unauthorized access."},
{"subject":"Computer Science","grade":6,"difficulty":"Advanced","topic":"Computer Science","subTopic":"Operating System",
 "questionText":"Multi-tasking in computers means:",
 "options":["A: Using multiple keyboards","B: Running multiple programs simultaneously","C: Having multiple users","D: Using multiple monitors"],"correctAnswer":"B",
 "explanation":"Multi-tasking allows a computer to execute multiple programs or processes seemingly simultaneously."},
{"subject":"Computer Science","grade":6,"difficulty":"Advanced","topic":"Computer Science","subTopic":"Internet Protocols",
 "questionText":"DNS stands for:",
 "options":["A: Data Network System","B: Domain Name System","C: Digital Network Service","D: Direct Name Server"],"correctAnswer":"B",
 "explanation":"DNS (Domain Name System) translates human-readable domain names (like google.com) into IP addresses."},
{"subject":"Computer Science","grade":6,"difficulty":"Advanced","topic":"Computer Science","subTopic":"Programming",
 "questionText":"Which Python function converts a string to an integer?",
 "options":["A: str()","B: float()","C: int()","D: chr()"],"correctAnswer":"C",
 "explanation":"int() converts a string or number to an integer in Python: int('42') returns 42."},
{"subject":"Computer Science","grade":6,"difficulty":"Advanced","topic":"Computer Science","subTopic":"Search",
 "questionText":"Binary search works only on __ arrays.",
 "options":["A: Unsorted","B: Sorted","C: Integer-only","D: Even-length"],"correctAnswer":"B",
 "explanation":"Binary search requires a sorted array to work correctly, dividing the search space in half each time."},

# ── General Knowledge G10 Olympiad (+15, 30→45) ──────────────────────────────
{"subject":"General Knowledge","grade":10,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"Science",
 "questionText":"The Large Hadron Collider (LHC) is operated by:",
 "options":["A: NASA","B: ISRO","C: CERN","D: ESA"],"correctAnswer":"C",
 "explanation":"The Large Hadron Collider is operated by CERN (European Organization for Nuclear Research) near Geneva, Switzerland."},
{"subject":"General Knowledge","grade":10,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"Indian Politics",
 "questionText":"The Anti-Defection Law in India is contained in which Schedule of the Constitution?",
 "options":["A: Seventh Schedule","B: Eighth Schedule","C: Ninth Schedule","D: Tenth Schedule"],"correctAnswer":"D",
 "explanation":"The Anti-Defection Law is in the Tenth Schedule (52nd Amendment, 1985), preventing elected members from defecting to other parties."},
{"subject":"General Knowledge","grade":10,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"Economics",
 "questionText":"The term 'Bear Market' in stock exchange means:",
 "options":["A: Rising stock prices","B: Falling stock prices over time","C: Stable market","D: New market opening"],"correctAnswer":"B",
 "explanation":"A Bear Market is characterized by declining stock prices (typically 20%+ fall), reflecting pessimism about the economy."},
{"subject":"General Knowledge","grade":10,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"World History",
 "questionText":"The Treaty of Versailles (1919) officially ended:",
 "options":["A: World War II","B: The Cold War","C: World War I","D: The Crimean War"],"correctAnswer":"C",
 "explanation":"The Treaty of Versailles was signed in June 1919, formally ending World War I and placing blame on Germany."},
{"subject":"General Knowledge","grade":10,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"Space",
 "questionText":"The James Webb Space Telescope observes primarily in which spectrum?",
 "options":["A: Visible light","B: X-ray","C: Infrared","D: Ultraviolet"],"correctAnswer":"C",
 "explanation":"The James Webb Space Telescope operates primarily in the infrared spectrum, allowing it to observe distant galaxies and early universe objects."},
{"subject":"General Knowledge","grade":10,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"Environment",
 "questionText":"The 'Chipko Movement' in India was a protest against:",
 "options":["A: River pollution","B: Deforestation","C: Mining","D: Air pollution"],"correctAnswer":"B",
 "explanation":"The Chipko Movement (1973, Uttarakhand) was a nonviolent protest where villagers hugged trees to prevent deforestation."},
{"subject":"General Knowledge","grade":10,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"Technology",
 "questionText":"The blockchain technology was originally developed for:",
 "options":["A: Social media","B: Bitcoin cryptocurrency","C: Internet browsing","D: Email encryption"],"correctAnswer":"B",
 "explanation":"Blockchain was originally developed as the underlying technology for Bitcoin, proposed by Satoshi Nakamoto in 2008."},
{"subject":"General Knowledge","grade":10,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"Indian Economy",
 "questionText":"SEBI regulates which sector in India?",
 "options":["A: Banking","B: Insurance","C: Securities and capital markets","D: Real estate"],"correctAnswer":"C",
 "explanation":"SEBI (Securities and Exchange Board of India) is the regulator for securities markets, protecting investors and promoting capital market development."},
{"subject":"General Knowledge","grade":10,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"Awards",
 "questionText":"The Fields Medal is the highest award in:",
 "options":["A: Physics","B: Mathematics","C: Economics","D: Chemistry"],"correctAnswer":"B",
 "explanation":"The Fields Medal, awarded every 4 years to mathematicians under 40, is often called the Nobel Prize of Mathematics."},
{"subject":"General Knowledge","grade":10,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"Health",
 "questionText":"The WHO declared COVID-19 a pandemic in:",
 "options":["A: January 2020","B: February 2020","C: March 2020","D: April 2020"],"correctAnswer":"C",
 "explanation":"The WHO declared COVID-19 a pandemic on March 11, 2020."},
{"subject":"General Knowledge","grade":10,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"Indian Culture",
 "questionText":"The concept of 'Vasudhaiva Kutumbakam' from Indian philosophy means:",
 "options":["A: Truth is God","B: Non-violence is supreme","C: The world is one family","D: Knowledge is power"],"correctAnswer":"C",
 "explanation":"'Vasudhaiva Kutumbakam' (from Maha Upanishad) means 'the world is one family' — a philosophy of global unity."},
{"subject":"General Knowledge","grade":10,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"Geography",
 "questionText":"The Ring of Fire is associated with:",
 "options":["A: Volcanic activity and earthquakes around the Pacific","B: Forest fires in Australia","C: Desert formation in Africa","D: Arctic ice melting"],"correctAnswer":"A",
 "explanation":"The Ring of Fire is a zone of frequent volcanic eruptions and earthquakes surrounding the Pacific Ocean."},
{"subject":"General Knowledge","grade":10,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"Physics",
 "questionText":"Schrödinger's equation is central to which field of physics?",
 "options":["A: Classical mechanics","B: Thermodynamics","C: Quantum mechanics","D: Relativity"],"correctAnswer":"C",
 "explanation":"The Schrödinger equation is the fundamental equation of quantum mechanics, describing how quantum states evolve over time."},
{"subject":"General Knowledge","grade":10,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"Literature",
 "questionText":"Gabriel García Márquez is known for the literary style called:",
 "options":["A: Surrealism","B: Magical Realism","C: Romanticism","D: Modernism"],"correctAnswer":"B",
 "explanation":"García Márquez pioneered magical realism — a literary style blending realistic narrative with fantastical elements ('One Hundred Years of Solitude')."},
{"subject":"General Knowledge","grade":10,"difficulty":"Olympiad","topic":"General Knowledge","subTopic":"Indian Science",
 "questionText":"S.N. Bose is known for his work leading to the discovery of the:",
 "options":["A: Electron","B: Boson (Higgs Boson named partly after him)","C: Neutron","D: Quark"],"correctAnswer":"B",
 "explanation":"Satyendra Nath Bose's quantum statistics work (1924) led Einstein to develop Bose-Einstein statistics. The Higgs boson is named partly in his honour."},

# ── Science-Biology G10 Olympiad (+15, 30→45) ────────────────────────────────
{"subject":"Science-Biology","grade":10,"difficulty":"Olympiad","topic":"Biology","subTopic":"Genetics",
 "questionText":"Which enzyme is responsible for DNA replication?",
 "options":["A: DNA polymerase","B: RNA polymerase","C: Ligase","D: Restriction enzyme"],"correctAnswer":"A",
 "explanation":"DNA polymerase is the enzyme that synthesizes new DNA strands during DNA replication."},
{"subject":"Science-Biology","grade":10,"difficulty":"Olympiad","topic":"Biology","subTopic":"Cell Division",
 "questionText":"Meiosis results in how many daughter cells?",
 "options":["A: 2","B: 3","C: 4","D: 8"],"correctAnswer":"C",
 "explanation":"Meiosis produces 4 haploid daughter cells (each with half the chromosome number) from one diploid parent cell."},
{"subject":"Science-Biology","grade":10,"difficulty":"Olympiad","topic":"Biology","subTopic":"Biochemistry",
 "questionText":"The primary structure of a protein refers to its:",
 "options":["A: 3D folded shape","B: Sequence of amino acids","C: Beta-pleated sheets","D: Bonding with other proteins"],"correctAnswer":"B",
 "explanation":"The primary structure of a protein is the linear sequence of amino acids in the polypeptide chain."},
{"subject":"Science-Biology","grade":10,"difficulty":"Olympiad","topic":"Biology","subTopic":"Ecology",
 "questionText":"Lichens are used as bioindicators of:",
 "options":["A: Water pollution","B: Soil pH","C: Air pollution (SO₂ levels)","D: Temperature change"],"correctAnswer":"C",
 "explanation":"Lichens (symbiosis of algae and fungi) are sensitive to SO₂ air pollution and disappear in polluted areas — making them excellent bioindicators."},
{"subject":"Science-Biology","grade":10,"difficulty":"Olympiad","topic":"Biology","subTopic":"Evolution",
 "questionText":"According to the Hardy-Weinberg principle, allele frequencies in a population remain constant if:",
 "options":["A: Selection occurs","B: Mutations happen frequently","C: Population is large with random mating and no selection","D: Gene flow occurs"],"correctAnswer":"C",
 "explanation":"Hardy-Weinberg equilibrium requires large population, random mating, no mutations, no selection, and no gene flow."},
{"subject":"Science-Biology","grade":10,"difficulty":"Olympiad","topic":"Biology","subTopic":"Human Physiology",
 "questionText":"The bundle of His in the heart is responsible for:",
 "options":["A: Pumping blood","B: Producing blood cells","C: Conducting electrical impulses to ventricles","D: Valve opening/closing"],"correctAnswer":"C",
 "explanation":"The bundle of His is part of the cardiac conduction system, transmitting electrical impulses from the AV node to the ventricles."},
{"subject":"Science-Biology","grade":10,"difficulty":"Olympiad","topic":"Biology","subTopic":"Molecular Biology",
 "questionText":"mRNA carries genetic information from:",
 "options":["A: Ribosome to cytoplasm","B: DNA in nucleus to ribosomes","C: tRNA to rRNA","D: Mitochondria to nucleus"],"correctAnswer":"B",
 "explanation":"mRNA (messenger RNA) transcribes the DNA sequence in the nucleus and carries the genetic code to ribosomes for protein synthesis."},
{"subject":"Science-Biology","grade":10,"difficulty":"Olympiad","topic":"Biology","subTopic":"Plant Physiology",
 "questionText":"Stomata open during daytime because guard cells:",
 "options":["A: Lose water (become flaccid)","B: Gain water (become turgid)","C: Die in sunlight","D: Produce sugar"],"correctAnswer":"B",
 "explanation":"In light, guard cells absorb water, become turgid (swollen), and bow outward, opening the stoma."},
{"subject":"Science-Biology","grade":10,"difficulty":"Olympiad","topic":"Biology","subTopic":"Immune System",
 "questionText":"Antibodies are produced by which cells?",
 "options":["A: T lymphocytes","B: B lymphocytes (plasma cells)","C: Red blood cells","D: Phagocytes"],"correctAnswer":"B",
 "explanation":"B lymphocytes differentiate into plasma cells that produce antibodies (immunoglobulins) against specific antigens."},
{"subject":"Science-Biology","grade":10,"difficulty":"Olympiad","topic":"Biology","subTopic":"Biotechnology",
 "questionText":"PCR (Polymerase Chain Reaction) is used to:",
 "options":["A: Separate DNA fragments","B: Amplify specific DNA sequences","C: Sequence proteins","D: Clone organisms"],"correctAnswer":"B",
 "explanation":"PCR amplifies specific DNA sequences exponentially, producing millions of copies of a target DNA segment."},
{"subject":"Science-Biology","grade":10,"difficulty":"Olympiad","topic":"Biology","subTopic":"Nervous System",
 "questionText":"The resting membrane potential of a neuron is approximately:",
 "options":["A: +70 mV","B: -70 mV","C: 0 mV","D: -40 mV"],"correctAnswer":"B",
 "explanation":"A neuron at rest has a membrane potential of approximately -70 mV (inside negative relative to outside) due to K⁺/Na⁺ distribution."},
{"subject":"Science-Biology","grade":10,"difficulty":"Olympiad","topic":"Biology","subTopic":"Hormones",
 "questionText":"Which hormone regulates blood calcium levels?",
 "options":["A: Insulin","B: Thyroxine","C: Parathyroid hormone","D: Adrenaline"],"correctAnswer":"C",
 "explanation":"Parathyroid hormone (PTH) raises blood calcium levels by stimulating bone resorption and kidney calcium reabsorption."},
{"subject":"Science-Biology","grade":10,"difficulty":"Olympiad","topic":"Biology","subTopic":"Reproduction",
 "questionText":"In human females, the egg (ovum) is fertilized in the:",
 "options":["A: Uterus","B: Ovary","C: Fallopian tube","D: Cervix"],"correctAnswer":"C",
 "explanation":"Fertilization of the egg by sperm typically occurs in the fallopian tube (oviduct), after which the zygote travels to the uterus."},
{"subject":"Science-Biology","grade":10,"difficulty":"Olympiad","topic":"Biology","subTopic":"Nutrition",
 "questionText":"Kwashiorkor is a disease caused by deficiency of:",
 "options":["A: Vitamin C","B: Iron","C: Protein","D: Carbohydrates"],"correctAnswer":"C",
 "explanation":"Kwashiorkor is a severe form of protein malnutrition, common in young children weaned to low-protein diets."},
{"subject":"Science-Biology","grade":10,"difficulty":"Olympiad","topic":"Biology","subTopic":"Microbiology",
 "questionText":"Viruses are considered non-living because they:",
 "options":["A: Have no cells","B: Cannot reproduce outside a host cell","C: Have no genetic material","D: Cannot move"],"correctAnswer":"B",
 "explanation":"Viruses cannot reproduce independently — they need a host cell's machinery to replicate, placing them on the boundary between living and non-living."},

# ── Science-Chemistry G10 Advanced (+15, 30→45) ──────────────────────────────
{"subject":"Science-Chemistry","grade":10,"difficulty":"Advanced","topic":"Chemistry","subTopic":"Electrochemistry",
 "questionText":"In an electrochemical cell, oxidation occurs at the:",
 "options":["A: Cathode","B: Anode","C: Electrolyte","D: Salt bridge"],"correctAnswer":"B",
 "explanation":"Oxidation (loss of electrons) occurs at the anode. Reduction (gain of electrons) occurs at the cathode. (Mnemonic: LEO GER, AnOx RedCat)"},
{"subject":"Science-Chemistry","grade":10,"difficulty":"Advanced","topic":"Chemistry","subTopic":"Thermochemistry",
 "questionText":"An exothermic reaction __ heat.",
 "options":["A: Absorbs","B: Neither releases nor absorbs","C: Releases","D: Only stores"],"correctAnswer":"C",
 "explanation":"Exothermic reactions release heat to surroundings (ΔH < 0), e.g., combustion, neutralization."},
{"subject":"Science-Chemistry","grade":10,"difficulty":"Advanced","topic":"Chemistry","subTopic":"Equilibrium",
 "questionText":"Le Chatelier's Principle states that a system at equilibrium, when disturbed, will:",
 "options":["A: Remain unchanged","B: Move to increase the disturbance","C: Shift to oppose the disturbance","D: Release all reactants"],"correctAnswer":"C",
 "explanation":"Le Chatelier's Principle: a system shifts its equilibrium position to counteract any imposed change (temperature, pressure, concentration)."},
{"subject":"Science-Chemistry","grade":10,"difficulty":"Advanced","topic":"Chemistry","subTopic":"Organic Chemistry",
 "questionText":"The functional group –COOH is characteristic of:",
 "options":["A: Alcohols","B: Aldehydes","C: Carboxylic acids","D: Ketones"],"correctAnswer":"C",
 "explanation":"The carboxyl group (–COOH) is the defining functional group of carboxylic acids (e.g., acetic acid, formic acid)."},
{"subject":"Science-Chemistry","grade":10,"difficulty":"Advanced","topic":"Chemistry","subTopic":"Mole Concept",
 "questionText":"How many molecules are present in 2 moles of water?",
 "options":["A: 6.022×10²³","B: 12.044×10²³","C: 3.011×10²³","D: 18×10²³"],"correctAnswer":"B",
 "explanation":"1 mole = 6.022×10²³ molecules (Avogadro's number). 2 moles = 2 × 6.022×10²³ = 12.044×10²³ molecules."},
{"subject":"Science-Chemistry","grade":10,"difficulty":"Advanced","topic":"Chemistry","subTopic":"Periodic Table",
 "questionText":"Electronegativity increases as you move across a period from left to right because:",
 "options":["A: Atomic radius increases","B: Nuclear charge increases without significant shielding increase","C: Number of neutrons increases","D: Electron shells increase"],"correctAnswer":"B",
 "explanation":"Across a period, nuclear charge (protons) increases while shielding remains similar, pulling bonding electrons closer and increasing electronegativity."},
{"subject":"Science-Chemistry","grade":10,"difficulty":"Advanced","topic":"Chemistry","subTopic":"Solutions",
 "questionText":"When salt dissolves in water, it is an example of:",
 "options":["A: Suspension","B: Colloid","C: True solution","D: Emulsion"],"correctAnswer":"C",
 "explanation":"Salt in water forms a true solution (homogeneous mixture) — particles < 1 nm, transparent, stable."},
{"subject":"Science-Chemistry","grade":10,"difficulty":"Advanced","topic":"Chemistry","subTopic":"Redox Reactions",
 "questionText":"In the reaction: 2Mg + O₂ → 2MgO, magnesium is:",
 "options":["A: Reduced","B: Oxidized","C: Unchanged","D: Catalyst"],"correctAnswer":"B",
 "explanation":"Magnesium loses electrons (goes from 0 to +2 oxidation state) — it is oxidized."},
{"subject":"Science-Chemistry","grade":10,"difficulty":"Advanced","topic":"Chemistry","subTopic":"Acids and Bases",
 "questionText":"The pH of a 0.01 M HCl solution is:",
 "options":["A: 1","B: 2","C: 3","D: 4"],"correctAnswer":"B",
 "explanation":"pH = -log[H⁺] = -log(0.01) = -log(10⁻²) = 2."},
{"subject":"Science-Chemistry","grade":10,"difficulty":"Advanced","topic":"Chemistry","subTopic":"Hydrocarbons",
 "questionText":"Alkynes contain:",
 "options":["A: Single bonds only","B: One double bond","C: One triple bond","D: Benzene ring"],"correctAnswer":"C",
 "explanation":"Alkynes (e.g., acetylene C₂H₂) contain at least one carbon-carbon triple bond (≡)."},
{"subject":"Science-Chemistry","grade":10,"difficulty":"Advanced","topic":"Chemistry","subTopic":"Gases",
 "questionText":"According to Avogadro's Law, equal volumes of gases at same T and P contain:",
 "options":["A: Equal mass","B: Equal number of molecules","C: Equal atomic radius","D: Equal density"],"correctAnswer":"B",
 "explanation":"Avogadro's Law states that equal volumes of any gas at the same temperature and pressure contain equal numbers of molecules."},
{"subject":"Science-Chemistry","grade":10,"difficulty":"Advanced","topic":"Chemistry","subTopic":"Polymers",
 "questionText":"Nylon is an example of a:",
 "options":["A: Natural polymer","B: Addition polymer","C: Condensation polymer","D: Biopolymer"],"correctAnswer":"C",
 "explanation":"Nylon is a synthetic condensation polymer formed by reaction between diamine and dicarboxylic acid with elimination of water."},
{"subject":"Science-Chemistry","grade":10,"difficulty":"Advanced","topic":"Chemistry","subTopic":"Nuclear Chemistry",
 "questionText":"Alpha particles are helium nuclei, consisting of:",
 "options":["A: 2 protons only","B: 2 neutrons only","C: 2 protons and 2 neutrons","D: 1 proton and 1 electron"],"correctAnswer":"C",
 "explanation":"An alpha particle (⁴₂He) consists of 2 protons and 2 neutrons — identical to a helium-4 nucleus."},
{"subject":"Science-Chemistry","grade":10,"difficulty":"Advanced","topic":"Chemistry","subTopic":"Reaction Rates",
 "questionText":"A catalyst increases reaction rate by:",
 "options":["A: Increasing temperature","B: Providing an alternative pathway with lower activation energy","C: Increasing reactant concentration","D: Changing the equilibrium constant"],"correctAnswer":"B",
 "explanation":"A catalyst provides an alternative reaction pathway with a lower activation energy, increasing the rate without being consumed."},
{"subject":"Science-Chemistry","grade":10,"difficulty":"Advanced","topic":"Chemistry","subTopic":"Chemical Formulas",
 "questionText":"The molecular formula of benzene is:",
 "options":["A: C₆H₁₂","B: C₆H₆","C: C₆H₁₄","D: C₆H₁₀"],"correctAnswer":"B",
 "explanation":"Benzene is an aromatic hydrocarbon with molecular formula C₆H₆, featuring a ring of 6 carbon atoms with alternating double bonds."},

# ── Science-Physics G10 Advanced (+15, 30→45) ────────────────────────────────
{"subject":"Science-Physics","grade":10,"difficulty":"Advanced","topic":"Physics","subTopic":"Mechanics",
 "questionText":"The impulse-momentum theorem states that impulse equals:",
 "options":["A: Mass × acceleration","B: Change in momentum","C: Force × distance","D: Kinetic energy"],"correctAnswer":"B",
 "explanation":"Impulse = Force × time = Δmomentum (change in momentum). This is the impulse-momentum theorem."},
{"subject":"Science-Physics","grade":10,"difficulty":"Advanced","topic":"Physics","subTopic":"Waves",
 "questionText":"A standing wave is formed by the superposition of two waves with:",
 "options":["A: Same amplitude, different frequency","B: Same frequency and amplitude, travelling in opposite directions","C: Different amplitude, same direction","D: Same wavelength, same direction"],"correctAnswer":"B",
 "explanation":"Standing waves form when two identical waves (same frequency and amplitude) travel in opposite directions and interfere."},
{"subject":"Science-Physics","grade":10,"difficulty":"Advanced","topic":"Physics","subTopic":"Electricity",
 "questionText":"In a parallel circuit, the equivalent resistance is always __ individual resistances.",
 "options":["A: Greater than all","B: Equal to the largest","C: Less than the smallest","D: Equal to sum of all"],"correctAnswer":"C",
 "explanation":"In a parallel circuit, 1/R_eq = Σ(1/Rᵢ). The equivalent resistance is always less than the smallest individual resistance."},
{"subject":"Science-Physics","grade":10,"difficulty":"Advanced","topic":"Physics","subTopic":"Thermodynamics",
 "questionText":"The second law of thermodynamics states that:",
 "options":["A: Energy is conserved","B: Entropy of the universe always increases","C: Heat flows from cold to hot","D: Work equals heat added"],"correctAnswer":"B",
 "explanation":"The second law states that the total entropy of an isolated system always increases over time in spontaneous processes."},
{"subject":"Science-Physics","grade":10,"difficulty":"Advanced","topic":"Physics","subTopic":"Optics",
 "questionText":"Total internal reflection occurs when light hits the boundary at an angle greater than the:",
 "options":["A: Angle of reflection","B: Refraction angle","C: Critical angle","D: Brewster's angle"],"correctAnswer":"C",
 "explanation":"Total internal reflection occurs when the angle of incidence exceeds the critical angle at the interface between denser and less dense media."},
{"subject":"Science-Physics","grade":10,"difficulty":"Advanced","topic":"Physics","subTopic":"Electromagnetism",
 "questionText":"Faraday's Law of Electromagnetic Induction states that the induced EMF is proportional to:",
 "options":["A: Current in circuit","B: Rate of change of magnetic flux","C: Resistance of wire","D: Temperature of conductor"],"correctAnswer":"B",
 "explanation":"Faraday's Law: EMF = -dΦ/dt. The induced EMF is proportional to the rate of change of magnetic flux."},
{"subject":"Science-Physics","grade":10,"difficulty":"Advanced","topic":"Physics","subTopic":"Nuclear Physics",
 "questionText":"The half-life of a radioactive substance is the time for half its atoms to:",
 "options":["A: Double in number","B: Decay","C: Gain energy","D: Change temperature"],"correctAnswer":"B",
 "explanation":"Half-life is the time required for exactly half of the radioactive nuclei in a sample to decay."},
{"subject":"Science-Physics","grade":10,"difficulty":"Advanced","topic":"Physics","subTopic":"Gravity",
 "questionText":"The escape velocity from Earth's surface is approximately:",
 "options":["A: 7.9 km/s","B: 11.2 km/s","C: 9.8 km/s","D: 3×10⁸ m/s"],"correctAnswer":"B",
 "explanation":"Earth's escape velocity is approximately 11.2 km/s — the minimum speed needed to escape Earth's gravitational pull."},
{"subject":"Science-Physics","grade":10,"difficulty":"Advanced","topic":"Physics","subTopic":"Fluid Mechanics",
 "questionText":"Bernoulli's Principle explains that in a fluid, faster flow corresponds to:",
 "options":["A: Higher pressure","B: Lower pressure","C: Equal pressure","D: Higher temperature"],"correctAnswer":"B",
 "explanation":"Bernoulli's Principle: in a streamlined fluid flow, increased velocity corresponds to decreased pressure and vice versa."},
{"subject":"Science-Physics","grade":10,"difficulty":"Advanced","topic":"Physics","subTopic":"Atomic Physics",
 "questionText":"The Bohr model of the atom explains atomic spectra by assuming electrons:",
 "options":["A: Are stationary","B: Move in definite orbits without losing energy","C: Vibrate around the nucleus","D: Have no fixed position"],"correctAnswer":"B",
 "explanation":"Bohr's model postulates electrons orbit in fixed energy levels (shells) without radiating energy, emitting/absorbing photons only when changing levels."},
{"subject":"Science-Physics","grade":10,"difficulty":"Advanced","topic":"Physics","subTopic":"Sound",
 "questionText":"The Doppler Effect describes the change in __ of a wave due to relative motion between source and observer.",
 "options":["A: Amplitude","B: Speed","C: Frequency","D: Wavelength direction"],"correctAnswer":"C",
 "explanation":"The Doppler Effect is the observed change in frequency of a wave when the source and observer are in relative motion."},
{"subject":"Science-Physics","grade":10,"difficulty":"Advanced","topic":"Physics","subTopic":"Energy",
 "questionText":"Which process converts mechanical energy into electrical energy?",
 "options":["A: Motor","B: Generator","C: Transformer","D: Battery"],"correctAnswer":"B",
 "explanation":"A generator (dynamo) converts mechanical energy (rotation) into electrical energy using electromagnetic induction."},
{"subject":"Science-Physics","grade":10,"difficulty":"Advanced","topic":"Physics","subTopic":"Semiconductor",
 "questionText":"A p-type semiconductor is created by doping silicon with a material that has:",
 "options":["A: 5 valence electrons","B: 3 valence electrons","C: 4 valence electrons","D: 2 valence electrons"],"correctAnswer":"B",
 "explanation":"p-type semiconductors are made by doping with trivalent impurities (3 valence electrons like boron), creating 'holes' as charge carriers."},
{"subject":"Science-Physics","grade":10,"difficulty":"Advanced","topic":"Physics","subTopic":"Projectile Motion",
 "questionText":"A ball is thrown horizontally from a cliff. Its vertical motion is due to:",
 "options":["A: Initial horizontal velocity","B: Air resistance","C: Gravity alone","D: Both gravity and initial velocity"],"correctAnswer":"C",
 "explanation":"In projectile motion, horizontal and vertical components are independent. Vertical motion is controlled by gravity alone (g = 9.8 m/s²)."},
{"subject":"Science-Physics","grade":10,"difficulty":"Advanced","topic":"Physics","subTopic":"Magnetism",
 "questionText":"The SI unit of magnetic flux density (magnetic field strength) is:",
 "options":["A: Weber","B: Tesla","C: Ampere","D: Henry"],"correctAnswer":"B",
 "explanation":"The SI unit of magnetic flux density (B) is the Tesla (T), named after Nikola Tesla."},

# ── Social Studies G12 Olympiad (+15, 30→45) ─────────────────────────────────
{"subject":"Social Studies","grade":12,"difficulty":"Olympiad","topic":"Social Studies","subTopic":"Indian Politics",
 "questionText":"The concept of 'Basic Structure Doctrine' of the Indian Constitution was established in:",
 "options":["A: A.K. Gopalan case","B: Kesavananda Bharati case","C: Minerva Mills case","D: Maneka Gandhi case"],"correctAnswer":"B",
 "explanation":"The Basic Structure Doctrine was established in the Kesavananda Bharati v. State of Kerala case (1973), limiting Parliament's amending power."},
{"subject":"Social Studies","grade":12,"difficulty":"Olympiad","topic":"Social Studies","subTopic":"International Relations",
 "questionText":"The policy of 'Non-Alignment' during the Cold War was championed by India primarily under:",
 "options":["A: Lal Bahadur Shastri","B: Jawaharlal Nehru","C: Indira Gandhi","D: Rajiv Gandhi"],"correctAnswer":"B",
 "explanation":"Jawaharlal Nehru was the chief architect of the Non-Aligned Movement, refusing to align India with either the USA or USSR blocs."},
{"subject":"Social Studies","grade":12,"difficulty":"Olympiad","topic":"Social Studies","subTopic":"Economics",
 "questionText":"The 'Washington Consensus' refers to a set of economic policy prescriptions including:",
 "options":["A: Protectionism and state control","B: Trade liberalization, privatization, and fiscal discipline","C: Welfare state expansion","D: Currency devaluation"],"correctAnswer":"B",
 "explanation":"The Washington Consensus (1990s) promoted free-market policies: trade liberalization, privatization, deregulation, and fiscal austerity for developing nations."},
{"subject":"Social Studies","grade":12,"difficulty":"Olympiad","topic":"Social Studies","subTopic":"World History",
 "questionText":"The Nuremberg Trials were held to prosecute:",
 "options":["A: World War I leaders","B: Nazi war criminals","C: Soviet leaders","D: Japanese emperors"],"correctAnswer":"B",
 "explanation":"The Nuremberg Trials (1945–46) prosecuted major Nazi war criminals for crimes against humanity and war crimes."},
{"subject":"Social Studies","grade":12,"difficulty":"Olympiad","topic":"Social Studies","subTopic":"Indian Constitution",
 "questionText":"The President of India can be removed through:",
 "options":["A: No-confidence motion","B: Supreme Court order","C: Impeachment by Parliament","D: Prime Minister's recommendation"],"correctAnswer":"C",
 "explanation":"The President of India can be removed through impeachment — a resolution passed by a two-thirds majority of both Houses of Parliament."},
{"subject":"Social Studies","grade":12,"difficulty":"Olympiad","topic":"Social Studies","subTopic":"Human Rights",
 "questionText":"The Universal Declaration of Human Rights was adopted by the UN in:",
 "options":["A: 1945","B: 1948","C: 1950","D: 1966"],"correctAnswer":"B",
 "explanation":"The UDHR was adopted by the UN General Assembly on December 10, 1948, establishing universal human rights standards."},
{"subject":"Social Studies","grade":12,"difficulty":"Olympiad","topic":"Social Studies","subTopic":"Political Science",
 "questionText":"'Separation of Powers' theory was propounded by:",
 "options":["A: Jean-Jacques Rousseau","B: John Locke","C: Montesquieu","D: Voltaire"],"correctAnswer":"C",
 "explanation":"Montesquieu, in 'The Spirit of the Laws' (1748), developed the doctrine of separation of powers into legislative, executive, and judicial branches."},
{"subject":"Social Studies","grade":12,"difficulty":"Olympiad","topic":"Social Studies","subTopic":"Indian Economy",
 "questionText":"The NITI Aayog replaced which planning body in India?",
 "options":["A: Finance Commission","B: Planning Commission","C: Economic Advisory Council","D: SEBI"],"correctAnswer":"B",
 "explanation":"NITI Aayog (National Institution for Transforming India) replaced the Planning Commission in January 2015."},
{"subject":"Social Studies","grade":12,"difficulty":"Olympiad","topic":"Social Studies","subTopic":"Sociology",
 "questionText":"Émile Durkheim's concept of 'anomie' refers to:",
 "options":["A: Social solidarity","B: Breakdown of social norms causing disorientation","C: Economic inequality","D: Cultural assimilation"],"correctAnswer":"B",
 "explanation":"Durkheim's 'anomie' describes a condition of normlessness — when societal norms are disrupted, individuals lose their sense of social cohesion."},
{"subject":"Social Studies","grade":12,"difficulty":"Olympiad","topic":"Social Studies","subTopic":"Geopolitics",
 "questionText":"The South China Sea dispute involves territorial claims by China and:",
 "options":["A: India, Pakistan, Bangladesh","B: Vietnam, Philippines, Malaysia, Taiwan, Brunei","C: Japan, South Korea, North Korea","D: Indonesia, Australia, New Zealand"],"correctAnswer":"B",
 "explanation":"The South China Sea is disputed between China and several ASEAN nations: Vietnam, Philippines, Malaysia, Taiwan, and Brunei."},
{"subject":"Social Studies","grade":12,"difficulty":"Olympiad","topic":"Social Studies","subTopic":"Environment Policy",
 "questionText":"The 'Polluter Pays Principle' means:",
 "options":["A: Governments pay for cleanup","B: Those causing pollution must bear remediation costs","C: Taxpayers fund environmental damage","D: Pollution fines go to victims"],"correctAnswer":"B",
 "explanation":"The Polluter Pays Principle (PPP) holds that those responsible for pollution should bear the costs of managing and remediating the damage."},
{"subject":"Social Studies","grade":12,"difficulty":"Olympiad","topic":"Social Studies","subTopic":"Indian Federalism",
 "questionText":"Which schedule of the Indian Constitution lists the distribution of powers between Centre and States?",
 "options":["A: Fifth Schedule","B: Sixth Schedule","C: Seventh Schedule","D: Eighth Schedule"],"correctAnswer":"C",
 "explanation":"The Seventh Schedule divides powers into Union List, State List, and Concurrent List between the Centre and States."},
{"subject":"Social Studies","grade":12,"difficulty":"Olympiad","topic":"Social Studies","subTopic":"Political Theory",
 "questionText":"John Rawls' 'veil of ignorance' thought experiment is used to argue for:",
 "options":["A: Meritocracy","B: Utilitarianism","C: Principles of justice and fairness","D: Libertarianism"],"correctAnswer":"C",
 "explanation":"Rawls' 'veil of ignorance' (A Theory of Justice, 1971) requires designing a just society without knowing your position in it, leading to fair principles."},
{"subject":"Social Studies","grade":12,"difficulty":"Olympiad","topic":"Social Studies","subTopic":"World Economy",
 "questionText":"IMF (International Monetary Fund) primarily assists countries by:",
 "options":["A: Providing military aid","B: Offering loans to stabilize balance of payments","C: Managing trade disputes","D: Regulating global banking"],"correctAnswer":"B",
 "explanation":"The IMF provides financial assistance (loans) to countries facing balance of payments crises, often with policy conditions attached."},
{"subject":"Social Studies","grade":12,"difficulty":"Olympiad","topic":"Social Studies","subTopic":"Indian History",
 "questionText":"The Partition of India in 1947 led to the largest mass migration in history, displacing approximately:",
 "options":["A: 2 million people","B: 7 million people","C: 14 million people","D: 20 million people"],"correctAnswer":"C",
 "explanation":"The 1947 Partition of India displaced approximately 14–17 million people, with an estimated 200,000–2 million deaths in the communal violence."},

]

ok = dup = err = 0
for i, q in enumerate(questions, 1):
    try:
        r = insert(conn, q)
        if r == "OK": ok += 1
        else: dup += 1
        diff_short = q["difficulty"][:3].upper()
        print(f"  {r:4s}  Q{i:03d} [{q['subject']:25s} G{q['grade']:02d} {diff_short}] {q['subTopic']}")
    except Exception as e:
        err += 1
        print(f"  ERR   Q{i:03d} {e}")

print(f"\n  Done: {ok} posted, {dup} duplicates, {err} errors  (total={ok+dup+err})")
