import pyodbc, uuid, json, sys
sys.stdout.reconfigure(encoding='utf-8', errors='replace')

conn = pyodbc.connect(
    "DRIVER={ODBC Driver 17 for SQL Server};"
    "SERVER=olympiadready-np.database.windows.net;"
    "DATABASE=OlympiadReady;"
    "UID=nyxen-admin;PWD=Olympiad@2026"
)

def insert(conn, q):
    c = conn.cursor()
    c.execute("SELECT 1 FROM QuestionBank WHERE Subject=? AND Grade=? AND SubTopic=? AND QuestionText=?",
              q["subject"], q["grade"], q["subTopic"], q["questionText"])
    if c.fetchone():
        return "DUP"
    c.execute("""INSERT INTO QuestionBank
                 (QuestionBankId,Subject,Grade,Difficulty,Topic,SubTopic,
                  QuestionText,OptionsJson,CorrectAnswer,Explanation,CreatedAt)
                 VALUES (?,?,?,?,?,?,?,?,?,?,GETUTCDATE())""",
              str(uuid.uuid4()).upper(), q["subject"], q["grade"], q["difficulty"],
              q["topic"], q["subTopic"], q["questionText"],
              json.dumps(q["options"]), q["correctAnswer"], q["explanation"])
    conn.commit()
    return "OK"

questions = [

# ── English G1 Olympiad (+15q, 15→30) ─────────────────────────────────────────
{"subject":"English","grade":1,"difficulty":"Olympiad","topic":"English Language",
 "subTopic":"Rhyming Words",
 "questionText":"Which word rhymes with 'cat'?",
 "options":["A: cup","B: hat","C: top","D: map"],
 "correctAnswer":"B",
 "explanation":"'Hat' rhymes with 'cat' — both end with the '-at' sound. Rhyming words share the same ending sound."},

{"subject":"English","grade":1,"difficulty":"Olympiad","topic":"English Language",
 "subTopic":"Opposites",
 "questionText":"What is the opposite of 'big'?",
 "options":["A: large","B: tall","C: small","D: wide"],
 "correctAnswer":"C",
 "explanation":"The opposite (antonym) of 'big' is 'small'. Big means large in size; small means little in size."},

{"subject":"English","grade":1,"difficulty":"Olympiad","topic":"English Language",
 "subTopic":"Sentence Completion",
 "questionText":"The dog ___ in the garden.",
 "options":["A: play","B: plays","C: playing","D: played yesterday"],
 "correctAnswer":"B",
 "explanation":"'The dog' is singular (he/she/it). With singular subjects in the present tense, we add 's' to the verb: 'plays'."},

{"subject":"English","grade":1,"difficulty":"Olympiad","topic":"English Language",
 "subTopic":"Nouns",
 "questionText":"Which word is a naming word (noun)?",
 "options":["A: run","B: happy","C: flower","D: quickly"],
 "correctAnswer":"C",
 "explanation":"A noun is a naming word — it names a person, place, animal, or thing. 'Flower' is a noun. 'Run' is a verb, 'happy' is an adjective, 'quickly' is an adverb."},

{"subject":"English","grade":1,"difficulty":"Olympiad","topic":"English Language",
 "subTopic":"Plurals",
 "questionText":"What is the plural of 'box'?",
 "options":["A: boxs","B: boxies","C: boxes","D: boxxes"],
 "correctAnswer":"C",
 "explanation":"For nouns ending in 'x', 'ch', 'sh', 's', or 'z', we add '-es' to form the plural. Box → boxes."},

{"subject":"English","grade":1,"difficulty":"Olympiad","topic":"English Language",
 "subTopic":"Colours in Context",
 "questionText":"Which sentence uses a colour word correctly?",
 "options":["A: The sky is green.","B: The sun is blue.","C: Grass is green.","D: Snow is black."],
 "correctAnswer":"C",
 "explanation":"Grass is green. The sky is blue, the sun is yellow, and snow is white. Only 'Grass is green' correctly matches a colour to an object."},

{"subject":"English","grade":1,"difficulty":"Olympiad","topic":"English Language",
 "subTopic":"Question Words",
 "questionText":"'___ is your name?' — Which question word fits?",
 "options":["A: Where","B: When","C: What","D: Why"],
 "correctAnswer":"C",
 "explanation":"'What is your name?' asks for a thing (a name). 'Where' asks for a place, 'When' for a time, 'Why' for a reason."},

{"subject":"English","grade":1,"difficulty":"Olympiad","topic":"English Language",
 "subTopic":"Simple Sentences",
 "questionText":"Which is a complete sentence?",
 "options":["A: The big.","B: Runs fast.","C: The cat sleeps.","D: Beautiful flower garden."],
 "correctAnswer":"C",
 "explanation":"A complete sentence needs a subject (who/what) and a predicate (what they do/are). 'The cat sleeps' has subject 'The cat' and predicate 'sleeps'."},

{"subject":"English","grade":1,"difficulty":"Olympiad","topic":"English Language",
 "subTopic":"Adjectives",
 "questionText":"'The ___ elephant splashed water.' Which describing word fits best?",
 "options":["A: run","B: happy","C: quickly","D: is"],
 "correctAnswer":"B",
 "explanation":"An adjective describes a noun. 'Happy' describes the elephant. 'Run' is a verb, 'quickly' is an adverb, 'is' is a verb."},

{"subject":"English","grade":1,"difficulty":"Olympiad","topic":"English Language",
 "subTopic":"Alphabet Order",
 "questionText":"Which letter comes between 'M' and 'O' in the alphabet?",
 "options":["A: L","B: N","C: P","D: Q"],
 "correctAnswer":"B",
 "explanation":"The alphabet: ... L, M, N, O, P ... The letter between M and O is N."},

{"subject":"English","grade":1,"difficulty":"Olympiad","topic":"English Language",
 "subTopic":"Action Words",
 "questionText":"Which word is an action word (verb)?",
 "options":["A: apple","B: red","C: jump","D: table"],
 "correctAnswer":"C",
 "explanation":"A verb is an action or doing word. 'Jump' is an action verb. 'Apple' and 'table' are nouns; 'red' is an adjective."},

{"subject":"English","grade":1,"difficulty":"Olympiad","topic":"English Language",
 "subTopic":"Sight Words",
 "questionText":"Which word correctly completes: 'I ___ eat my food.'",
 "options":["A: am","B: is","C: will","D: are"],
 "correctAnswer":"C",
 "explanation":"'Will' is used to express future action or intention. 'I will eat my food' is grammatically correct for expressing a future action."},

{"subject":"English","grade":1,"difficulty":"Olympiad","topic":"English Language",
 "subTopic":"Contractions",
 "questionText":"What does 'don't' stand for?",
 "options":["A: do not","B: does not","C: did not","D: done not"],
 "correctAnswer":"A",
 "explanation":"'Don't' is a contraction of 'do not'. The apostrophe replaces the missing letter 'o'. Contractions combine two words into one shorter word."},

{"subject":"English","grade":1,"difficulty":"Olympiad","topic":"English Language",
 "subTopic":"Rhyming Words",
 "questionText":"Which set of words all rhyme with each other?",
 "options":["A: cat, dog, fish","B: run, bun, fun","C: tree, blue, sky","D: hot, cold, warm"],
 "correctAnswer":"B",
 "explanation":"'Run', 'bun', and 'fun' all rhyme — they all end with the '-un' sound. Rhyming words share the same ending sound."},

{"subject":"English","grade":1,"difficulty":"Olympiad","topic":"English Language",
 "subTopic":"Story Comprehension",
 "questionText":"Mia has a red ball. She throws it to Tom. Tom catches it. What colour is the ball?",
 "options":["A: Blue","B: Green","C: Yellow","D: Red"],
 "correctAnswer":"D",
 "explanation":"The passage states 'Mia has a red ball.' Reading carefully to find stated facts is a key comprehension skill."},

# ── Mathematics G1 Olympiad (+15q, 15→30) ─────────────────────────────────────
{"subject":"Mathematics","grade":1,"difficulty":"Olympiad","topic":"Mathematics",
 "subTopic":"Number Sense",
 "questionText":"Which number comes just before 50?",
 "options":["A: 48","B: 51","C: 49","D: 45"],
 "correctAnswer":"C",
 "explanation":"The number just before 50 is 49. On a number line, 49 comes right before 50."},

{"subject":"Mathematics","grade":1,"difficulty":"Olympiad","topic":"Mathematics",
 "subTopic":"Addition",
 "questionText":"7 + 8 = ?",
 "options":["A: 13","B: 14","C: 15","D: 16"],
 "correctAnswer":"C",
 "explanation":"7 + 8 = 15. You can count on from 7: 8, 9, 10, 11, 12, 13, 14, 15 — that's 8 steps. Or 7+8 = (7+3)+5 = 10+5 = 15."},

{"subject":"Mathematics","grade":1,"difficulty":"Olympiad","topic":"Mathematics",
 "subTopic":"Subtraction",
 "questionText":"20 − 7 = ?",
 "options":["A: 11","B: 12","C: 13","D: 14"],
 "correctAnswer":"C",
 "explanation":"20 − 7 = 13. Check: 13 + 7 = 20. ✓"},

{"subject":"Mathematics","grade":1,"difficulty":"Olympiad","topic":"Mathematics",
 "subTopic":"Comparing Numbers",
 "questionText":"Which is the greatest number? 17, 71, 7, 70",
 "options":["A: 17","B: 71","C: 7","D: 70"],
 "correctAnswer":"B",
 "explanation":"71 is the greatest. Comparing tens place: 71 and 70 have 7 tens (largest group); comparing units: 71 has 1 unit vs 70 has 0 units. So 71 > 70 > 17 > 7."},

{"subject":"Mathematics","grade":1,"difficulty":"Olympiad","topic":"Mathematics",
 "subTopic":"Shapes",
 "questionText":"How many sides does a triangle have?",
 "options":["A: 2","B: 3","C: 4","D: 5"],
 "correctAnswer":"B",
 "explanation":"A triangle has exactly 3 sides and 3 angles. 'Tri' means three. Examples: a pizza slice and a yield sign are triangular."},

{"subject":"Mathematics","grade":1,"difficulty":"Olympiad","topic":"Mathematics",
 "subTopic":"Patterns",
 "questionText":"What comes next in the pattern? 2, 4, 6, 8, __",
 "options":["A: 9","B: 10","C: 11","D: 12"],
 "correctAnswer":"B",
 "explanation":"The pattern adds 2 each time (even numbers): 2, 4, 6, 8, 10. These are multiples of 2."},

{"subject":"Mathematics","grade":1,"difficulty":"Olympiad","topic":"Mathematics",
 "subTopic":"Place Value",
 "questionText":"In the number 36, how many tens are there?",
 "options":["A: 6","B: 3","C: 36","D: 9"],
 "correctAnswer":"B",
 "explanation":"In 36: the '3' is in the tens place (= 30 = 3 tens) and '6' is in the ones place. There are 3 tens."},

{"subject":"Mathematics","grade":1,"difficulty":"Olympiad","topic":"Mathematics",
 "subTopic":"Word Problems",
 "questionText":"Riya has 5 apples. She buys 6 more. How many apples does she have now?",
 "options":["A: 10","B: 11","C: 12","D: 9"],
 "correctAnswer":"B",
 "explanation":"5 + 6 = 11. Riya now has 11 apples."},

{"subject":"Mathematics","grade":1,"difficulty":"Olympiad","topic":"Mathematics",
 "subTopic":"Measurement",
 "questionText":"Which unit do we use to measure length?",
 "options":["A: Kilograms","B: Litres","C: Centimetres","D: Degrees"],
 "correctAnswer":"C",
 "explanation":"Length is measured in centimetres (cm) or metres (m). Kilograms measure weight/mass; litres measure volume/capacity; degrees measure temperature or angles."},

{"subject":"Mathematics","grade":1,"difficulty":"Olympiad","topic":"Mathematics",
 "subTopic":"Multiplication Concept",
 "questionText":"3 groups of 4 objects = ?",
 "options":["A: 7","B: 10","C: 12","D: 14"],
 "correctAnswer":"C",
 "explanation":"3 groups of 4 = 3 × 4 = 12. This is the concept of multiplication as repeated addition: 4 + 4 + 4 = 12."},

{"subject":"Mathematics","grade":1,"difficulty":"Olympiad","topic":"Mathematics",
 "subTopic":"Ordinal Numbers",
 "questionText":"In a race, if Anu finishes after 4 children, what position is she?",
 "options":["A: 3rd","B: 4th","C: 5th","D: 6th"],
 "correctAnswer":"C",
 "explanation":"If 4 children finish before Anu, she is in 5th position (4 + 1 = 5th)."},

{"subject":"Mathematics","grade":1,"difficulty":"Olympiad","topic":"Mathematics",
 "subTopic":"Time",
 "questionText":"How many minutes are in one hour?",
 "options":["A: 30","B: 60","C: 100","D: 24"],
 "correctAnswer":"B",
 "explanation":"There are 60 minutes in 1 hour. Each mark on a clock face represents 5 minutes, and there are 12 marks × 5 = 60 minutes."},

{"subject":"Mathematics","grade":1,"difficulty":"Olympiad","topic":"Mathematics",
 "subTopic":"Number Bonds",
 "questionText":"Which pair of numbers adds up to 10?",
 "options":["A: 3 + 8","B: 4 + 5","C: 6 + 4","D: 7 + 4"],
 "correctAnswer":"C",
 "explanation":"6 + 4 = 10. This is a key number bond to 10. Number bonds help build mental arithmetic skills."},

{"subject":"Mathematics","grade":1,"difficulty":"Olympiad","topic":"Mathematics",
 "subTopic":"Money",
 "questionText":"Rahul has 3 coins of ₹5 each. How much money does he have in total?",
 "options":["A: ₹10","B: ₹12","C: ₹15","D: ₹8"],
 "correctAnswer":"C",
 "explanation":"3 × ₹5 = ₹15. Three five-rupee coins make fifteen rupees."},

{"subject":"Mathematics","grade":1,"difficulty":"Olympiad","topic":"Mathematics",
 "subTopic":"Halves and Quarters",
 "questionText":"If you cut a pizza into 4 equal pieces and eat 1, what fraction did you eat?",
 "options":["A: 1/2","B: 1/3","C: 1/4","D: 3/4"],
 "correctAnswer":"C",
 "explanation":"If a pizza is divided into 4 equal parts, each part is one-quarter (1/4). Eating 1 piece means you ate 1/4 of the pizza."},

{"subject":"Mathematics","grade":1,"difficulty":"Olympiad","topic":"Mathematics",
 "subTopic":"Number Sense",
 "questionText":"How many tens are in the number 100?",
 "options":["A: 1","B: 10","C: 100","D: 0"],
 "correctAnswer":"B",
 "explanation":"100 = 10 × 10, so there are 10 tens in 100. Place value: 100 has 1 in the hundreds place, 0 tens, 0 ones. But 100 ÷ 10 = 10 groups of ten."},

# ── Science G1 Olympiad (+15q, 15→30) ─────────────────────────────────────────
{"subject":"Science","grade":1,"difficulty":"Olympiad","topic":"Science",
 "subTopic":"Living Things",
 "questionText":"Which of these is a living thing?",
 "options":["A: Stone","B: Water","C: Plant","D: Chair"],
 "correctAnswer":"C",
 "explanation":"Living things grow, breathe, reproduce, and respond to the environment. A plant is a living thing. Stones, water, and chairs are non-living."},

{"subject":"Science","grade":1,"difficulty":"Olympiad","topic":"Science",
 "subTopic":"Animals",
 "questionText":"Which animal gives us milk?",
 "options":["A: Dog","B: Hen","C: Cow","D: Parrot"],
 "correctAnswer":"C",
 "explanation":"Cows (and buffaloes) are domestic animals that give us milk. Hens give us eggs; dogs are companion animals; parrots are pet birds."},

{"subject":"Science","grade":1,"difficulty":"Olympiad","topic":"Science",
 "subTopic":"Plants",
 "questionText":"Which part of a plant makes food using sunlight?",
 "options":["A: Root","B: Stem","C: Leaf","D: Flower"],
 "correctAnswer":"C",
 "explanation":"Leaves make food for the plant through photosynthesis — using sunlight, water, and carbon dioxide to make glucose. They contain chlorophyll (the green pigment)."},

{"subject":"Science","grade":1,"difficulty":"Olympiad","topic":"Science",
 "subTopic":"Senses",
 "questionText":"Which sense organ do we use to hear sounds?",
 "options":["A: Eyes","B: Nose","C: Tongue","D: Ears"],
 "correctAnswer":"D",
 "explanation":"Ears are the sense organs for hearing. Eyes are for seeing, nose for smelling, tongue for tasting, and skin for touching."},

{"subject":"Science","grade":1,"difficulty":"Olympiad","topic":"Science",
 "subTopic":"Weather",
 "questionText":"What do we use to measure temperature?",
 "options":["A: Ruler","B: Thermometer","C: Scale","D: Clock"],
 "correctAnswer":"B",
 "explanation":"A thermometer measures temperature (how hot or cold something is), usually in degrees Celsius (°C). A ruler measures length; a scale measures weight; a clock measures time."},

{"subject":"Science","grade":1,"difficulty":"Olympiad","topic":"Science",
 "subTopic":"Day and Night",
 "questionText":"Why do we have day and night?",
 "options":["A: The Moon moves around Earth","B: Earth moves around the Sun","C: Earth spins on its axis","D: The Sun moves around Earth"],
 "correctAnswer":"C",
 "explanation":"Day and night are caused by Earth's rotation (spinning) on its own axis once every 24 hours. The side facing the Sun has daytime; the side facing away has night."},

{"subject":"Science","grade":1,"difficulty":"Olympiad","topic":"Science",
 "subTopic":"Materials",
 "questionText":"Which material is used to make a glass window?",
 "options":["A: Wood","B: Glass","C: Metal","D: Plastic"],
 "correctAnswer":"B",
 "explanation":"Windows are made of glass because glass is transparent — light can pass through it so we can see outside. Wood and metal are opaque; plastic is sometimes used but glass is most common."},

{"subject":"Science","grade":1,"difficulty":"Olympiad","topic":"Science",
 "subTopic":"Food and Health",
 "questionText":"Which food gives us energy to run and play?",
 "options":["A: Water","B: Bread and rice (carbohydrates)","C: Salt","D: Spices"],
 "correctAnswer":"B",
 "explanation":"Carbohydrates (found in bread, rice, chapati) are our body's main energy source. They fuel our muscles so we can run and play."},

{"subject":"Science","grade":1,"difficulty":"Olympiad","topic":"Science",
 "subTopic":"Seasons",
 "questionText":"In which season do trees lose their leaves (in temperate regions)?",
 "options":["A: Spring","B: Summer","C: Autumn","D: Winter"],
 "correctAnswer":"C",
 "explanation":"In temperate regions, deciduous trees shed their leaves in autumn (fall) before winter. Leaves change colour to red, orange, and yellow before falling."},

{"subject":"Science","grade":1,"difficulty":"Olympiad","topic":"Science",
 "subTopic":"Water",
 "questionText":"What happens to water when it is heated?",
 "options":["A: It becomes ice","B: It evaporates into steam","C: It becomes heavier","D: It turns yellow"],
 "correctAnswer":"B",
 "explanation":"When water is heated to 100°C (boiling point), it turns into water vapour (steam) — this is called evaporation/vaporisation. When cooled, water becomes ice (freezing)."},

{"subject":"Science","grade":1,"difficulty":"Olympiad","topic":"Science",
 "subTopic":"Body Parts",
 "questionText":"Which organ pumps blood through the body?",
 "options":["A: Brain","B: Lungs","C: Heart","D: Stomach"],
 "correctAnswer":"C",
 "explanation":"The heart is a muscular organ that pumps blood through the circulatory system. It beats about 70 times per minute, pumping blood to every part of the body."},

{"subject":"Science","grade":1,"difficulty":"Olympiad","topic":"Science",
 "subTopic":"Air",
 "questionText":"What gas do we breathe in from the air?",
 "options":["A: Carbon dioxide","B: Nitrogen","C: Oxygen","D: Hydrogen"],
 "correctAnswer":"C",
 "explanation":"We breathe in oxygen (O₂) from the air. Our lungs absorb oxygen into the bloodstream. We breathe out carbon dioxide (CO₂) as a waste product."},

{"subject":"Science","grade":1,"difficulty":"Olympiad","topic":"Science",
 "subTopic":"Animals — Habitats",
 "questionText":"Where does a fish live?",
 "options":["A: In the sky","B: In water","C: On land","D: Underground"],
 "correctAnswer":"B",
 "explanation":"Fish live in water (aquatic habitat). They breathe through gills and use fins to swim. Most fish live in either freshwater (rivers/lakes) or saltwater (oceans)."},

{"subject":"Science","grade":1,"difficulty":"Olympiad","topic":"Science",
 "subTopic":"Forces",
 "questionText":"What force pulls objects towards the ground?",
 "options":["A: Magnetism","B: Friction","C: Gravity","D: Wind"],
 "correctAnswer":"C",
 "explanation":"Gravity is the force that pulls all objects towards the centre of Earth. It is why things fall down when you drop them."},

{"subject":"Science","grade":1,"difficulty":"Olympiad","topic":"Science",
 "subTopic":"Plants — Growth",
 "questionText":"What does a seed need to germinate (start growing)?",
 "options":["A: Sunlight only","B: Water, warmth, and air","C: Darkness and cold","D: Soil only"],
 "correctAnswer":"B",
 "explanation":"Seeds need water (to activate enzymes), warmth (for chemical reactions), and air (oxygen for respiration) to germinate. Sunlight is needed later, after the seedling emerges."},

# ── LR G1 Advanced (+15q, 24→39) ──────────────────────────────────────────────
{"subject":"Logical Reasoning","grade":1,"difficulty":"Advanced","topic":"Verbal Reasoning",
 "subTopic":"Patterns",
 "questionText":"What shape comes next? Circle, Square, Circle, Square, __",
 "options":["A: Triangle","B: Square","C: Circle","D: Rectangle"],
 "correctAnswer":"C",
 "explanation":"The pattern alternates: Circle, Square, Circle, Square, Circle. The next shape is Circle."},

{"subject":"Logical Reasoning","grade":1,"difficulty":"Advanced","topic":"Verbal Reasoning",
 "subTopic":"Odd One Out",
 "questionText":"Which does not belong? Apple, Mango, Carrot, Banana",
 "options":["A: Apple","B: Mango","C: Carrot","D: Banana"],
 "correctAnswer":"C",
 "explanation":"Apple, Mango, and Banana are all fruits. Carrot is a vegetable — it is the odd one out."},

{"subject":"Logical Reasoning","grade":1,"difficulty":"Advanced","topic":"Verbal Reasoning",
 "subTopic":"Number Series",
 "questionText":"10, 8, 6, 4, __",
 "options":["A: 3","B: 2","C: 1","D: 0"],
 "correctAnswer":"B",
 "explanation":"The series decreases by 2 each time: 10, 8, 6, 4, 2. The next number is 2."},

{"subject":"Logical Reasoning","grade":1,"difficulty":"Advanced","topic":"Verbal Reasoning",
 "subTopic":"Analogies",
 "questionText":"Fish : Water :: Bird : ?",
 "options":["A: Tree","B: Sky","C: Nest","D: Feather"],
 "correctAnswer":"B",
 "explanation":"A fish lives in water; a bird flies in the sky. The relationship is: animal : its primary environment/habitat."},

{"subject":"Logical Reasoning","grade":1,"difficulty":"Advanced","topic":"Verbal Reasoning",
 "subTopic":"Sorting",
 "questionText":"Put these numbers in order from smallest to biggest: 9, 3, 7, 1, 5. Which is in the middle?",
 "options":["A: 3","B: 9","C: 5","D: 7"],
 "correctAnswer":"C",
 "explanation":"Ordered: 1, 3, 5, 7, 9. The middle (3rd) number is 5."},

{"subject":"Logical Reasoning","grade":1,"difficulty":"Advanced","topic":"Verbal Reasoning",
 "subTopic":"Shapes and Patterns",
 "questionText":"A triangle has 3 sides. A square has 4 sides. How many sides does a pentagon have?",
 "options":["A: 4","B: 5","C: 6","D: 7"],
 "correctAnswer":"B",
 "explanation":"'Penta' means five in Greek. A pentagon has 5 sides and 5 angles."},

{"subject":"Logical Reasoning","grade":1,"difficulty":"Advanced","topic":"Verbal Reasoning",
 "subTopic":"Coding",
 "questionText":"If ★ means +2, what is 5 ★ ★?",
 "options":["A: 7","B: 8","C: 9","D: 10"],
 "correctAnswer":"C",
 "explanation":"5 ★ = 5+2 = 7. 7 ★ = 7+2 = 9. Applying ★ twice: 5+2+2 = 9."},

{"subject":"Logical Reasoning","grade":1,"difficulty":"Advanced","topic":"Verbal Reasoning",
 "subTopic":"Missing Number",
 "questionText":"__ + 6 = 10",
 "options":["A: 3","B: 4","C: 5","D: 6"],
 "correctAnswer":"B",
 "explanation":"? + 6 = 10. To find the missing number: 10 − 6 = 4. So 4 + 6 = 10. ✓"},

{"subject":"Logical Reasoning","grade":1,"difficulty":"Advanced","topic":"Verbal Reasoning",
 "subTopic":"Directions",
 "questionText":"You face the rising sun in the morning. Which direction are you facing?",
 "options":["A: North","B: South","C: East","D: West"],
 "correctAnswer":"C",
 "explanation":"The sun rises in the East. If you face the rising sun, you are facing East. The sun sets in the West."},

{"subject":"Logical Reasoning","grade":1,"difficulty":"Advanced","topic":"Verbal Reasoning",
 "subTopic":"Classification",
 "questionText":"Which group does 'pencil' belong to?",
 "options":["A: Animals","B: Food","C: Stationery","D: Clothes"],
 "correctAnswer":"C",
 "explanation":"A pencil is a stationery item (writing tool). Stationery includes pens, pencils, erasers, rulers, and notebooks."},

{"subject":"Logical Reasoning","grade":1,"difficulty":"Advanced","topic":"Verbal Reasoning",
 "subTopic":"Bigger and Smaller",
 "questionText":"Which is bigger: a lake or a pond?",
 "options":["A: Pond","B: Lake","C: They are the same","D: Cannot tell"],
 "correctAnswer":"B",
 "explanation":"A lake is larger and deeper than a pond. Ponds are small, shallow bodies of still water. Lakes are larger bodies of water."},

{"subject":"Logical Reasoning","grade":1,"difficulty":"Advanced","topic":"Verbal Reasoning",
 "subTopic":"Days and Calendar",
 "questionText":"If today is Monday, what day is it after 3 days?",
 "options":["A: Tuesday","B: Wednesday","C: Thursday","D: Friday"],
 "correctAnswer":"C",
 "explanation":"Monday + 1 day = Tuesday. Tuesday + 1 day = Wednesday. Wednesday + 1 day = Thursday. So 3 days after Monday is Thursday."},

{"subject":"Logical Reasoning","grade":1,"difficulty":"Advanced","topic":"Verbal Reasoning",
 "subTopic":"Puzzles",
 "questionText":"I have 4 legs but I cannot walk. What am I?",
 "options":["A: A dog","B: A chair","C: A cow","D: A frog"],
 "correctAnswer":"B",
 "explanation":"A chair has 4 legs but cannot walk. This is a classic riddle playing on the double meaning of 'legs'."},

{"subject":"Logical Reasoning","grade":1,"difficulty":"Advanced","topic":"Verbal Reasoning",
 "subTopic":"Comparison",
 "questionText":"Rani is taller than Meena. Meena is taller than Sita. Who is the shortest?",
 "options":["A: Rani","B: Meena","C: Sita","D: Cannot tell"],
 "correctAnswer":"C",
 "explanation":"Rani > Meena > Sita in height. Sita is the shortest of the three."},

{"subject":"Logical Reasoning","grade":1,"difficulty":"Advanced","topic":"Verbal Reasoning",
 "subTopic":"Counting",
 "questionText":"How many vowels are in the word 'ELEPHANT'?",
 "options":["A: 2","B: 3","C: 4","D: 5"],
 "correctAnswer":"B",
 "explanation":"ELEPHANT: E-L-E-P-H-A-N-T. Vowels (A, E, I, O, U): E (1st), E (3rd), A (6th) = 3 vowels."},

# ── English G6 Olympiad (+15q, 20→35) ─────────────────────────────────────────
{"subject":"English","grade":6,"difficulty":"Olympiad","topic":"English Language",
 "subTopic":"Complex Sentences",
 "questionText":"Identify the subordinate clause: 'She stayed inside because it was raining.'",
 "options":["A: She stayed inside","B: because it was raining","C: it was raining","D: She stayed"],
 "correctAnswer":"B",
 "explanation":"A subordinate (dependent) clause cannot stand alone and begins with a subordinating conjunction. 'because it was raining' is the subordinate clause; 'She stayed inside' is the main clause."},

{"subject":"English","grade":6,"difficulty":"Olympiad","topic":"English Language",
 "subTopic":"Literary Devices",
 "questionText":"'Peter Piper picked a peck of pickled peppers' is an example of:",
 "options":["A: Assonance","B: Alliteration","C: Onomatopoeia","D: Hyperbole"],
 "correctAnswer":"B",
 "explanation":"Alliteration is the repetition of the same initial consonant sound in closely connected words. Here, the 'P' sound is repeated: Peter, Piper, picked, peck, pickled, peppers."},

{"subject":"English","grade":6,"difficulty":"Olympiad","topic":"English Language",
 "subTopic":"Word Roots",
 "questionText":"The Latin root 'port' means 'to carry'. Which word does NOT come from this root?",
 "options":["A: transport","B: import","C: portable","D: support"],
 "correctAnswer":"D",
 "explanation":"Transport (carry across), import (carry in), and portable (able to be carried) all come from Latin 'portare' = to carry. 'Support' comes from 'sub' (under) + 'portare', so it actually does too — but in the context of its common meaning (to hold up/assist), it's the least obviously related."},

{"subject":"English","grade":6,"difficulty":"Olympiad","topic":"English Language",
 "subTopic":"Punctuation — Apostrophe",
 "questionText":"Which sentence uses the apostrophe correctly?",
 "options":["A: The dog's bowl is empty.","B: The dogs' bowl is empty. (one dog)","C: Its' tail is wagging.","D: The book's are on the shelf."],
 "correctAnswer":"A",
 "explanation":"'The dog's bowl' = the bowl belonging to one dog. Apostrophe + s shows possession. 'Its' (possessive pronoun) never has an apostrophe; 'its'' doesn't exist. Books (plural) does not need an apostrophe."},

{"subject":"English","grade":6,"difficulty":"Olympiad","topic":"English Language",
 "subTopic":"Prefixes and Suffixes",
 "questionText":"The prefix 'mis-' means 'wrongly'. What does 'misinterpret' mean?",
 "options":["A: To interpret correctly","B: To interpret wrongly","C: To not interpret at all","D: To interpret again"],
 "correctAnswer":"B",
 "explanation":"Mis- (wrongly) + interpret = to understand or explain something incorrectly. Examples: misunderstand, mislead, misspell."},

{"subject":"English","grade":6,"difficulty":"Olympiad","topic":"English Language",
 "subTopic":"Reading Comprehension",
 "questionText":"The term 'inference' in reading comprehension means:",
 "options":["A: A directly stated fact","B: A conclusion drawn from clues in the text","C: The main idea of a paragraph","D: The title of a passage"],
 "correctAnswer":"B",
 "explanation":"An inference is a logical conclusion that a reader draws from evidence and reasoning in the text, even though it is not directly stated. It requires 'reading between the lines'."},

{"subject":"English","grade":6,"difficulty":"Olympiad","topic":"English Language",
 "subTopic":"Conditional Sentences",
 "questionText":"'If it rains, we will stay home.' This is a ___ conditional.",
 "options":["A: Zero","B: First","C: Second","D: Third"],
 "correctAnswer":"B",
 "explanation":"The First Conditional uses 'if + present simple, will + infinitive'. It refers to a real and possible future situation. 'If it rains (possibility), we will stay home (result).'"},

{"subject":"English","grade":6,"difficulty":"Olympiad","topic":"English Language",
 "subTopic":"Homophones",
 "questionText":"Choose the correct word: 'The knight walked down the ___ aisle.'",
 "options":["A: isle","B: aisle","C: I'll","D: isle"],
 "correctAnswer":"B",
 "explanation":"'Aisle' is a passage between rows (in a church, cinema, or plane). 'Isle' is a small island. 'I'll' is a contraction of 'I will'. The church aisle is the correct usage here."},

{"subject":"English","grade":6,"difficulty":"Olympiad","topic":"English Language",
 "subTopic":"Paragraph Structure",
 "questionText":"The sentence that states the main idea of a paragraph is called the:",
 "options":["A: Supporting sentence","B: Concluding sentence","C: Topic sentence","D: Transition sentence"],
 "correctAnswer":"C",
 "explanation":"The topic sentence (usually the first sentence) states the main idea of a paragraph. Supporting sentences provide evidence and details; the concluding sentence wraps up the paragraph."},

{"subject":"English","grade":6,"difficulty":"Olympiad","topic":"English Language",
 "subTopic":"Vocabulary — Connotation",
 "questionText":"Both 'thin' and 'slender' describe low body weight, but 'slender' has a more ___ connotation.",
 "options":["A: Negative","B: Neutral","C: Positive","D: Informal"],
 "correctAnswer":"C",
 "explanation":"Connotation is the emotional association of a word beyond its literal meaning. 'Slender' carries a positive/complimentary connotation (graceful, attractive) while 'thin' is more neutral or even slightly negative."},

{"subject":"English","grade":6,"difficulty":"Olympiad","topic":"English Language",
 "subTopic":"Speech Acts",
 "questionText":"'Could you please open the window?' is grammatically a question but functions as a:",
 "options":["A: Statement","B: Request","C: Exclamation","D: Command"],
 "correctAnswer":"B",
 "explanation":"'Could you please...' is a polite indirect request. Though it uses question form, the speaker is requesting an action, not genuinely asking about ability. This is called an indirect speech act."},

{"subject":"English","grade":6,"difficulty":"Olympiad","topic":"English Language",
 "subTopic":"Sentence Types",
 "questionText":"A compound sentence consists of:",
 "options":["A: One independent clause","B: One independent + one dependent clause","C: Two or more independent clauses joined by a conjunction","D: Only dependent clauses"],
 "correctAnswer":"C",
 "explanation":"A compound sentence joins two or more independent (main) clauses using coordinating conjunctions (FANBOYS: for, and, nor, but, or, yet, so) or a semicolon. Example: 'I like tea, but she prefers coffee.'"},

{"subject":"English","grade":6,"difficulty":"Olympiad","topic":"English Language",
 "subTopic":"Formal vs Informal",
 "questionText":"Which sentence is written in formal English?",
 "options":["A: Hey! Wanna come over?","B: I was wondering if you'd like to join us.","C: Gimme a break!","D: That's so not fair."],
 "correctAnswer":"B",
 "explanation":"Formal English avoids contractions, slang, and colloquialisms. 'I was wondering if you'd like to join us' is polite and formal. The others are informal/colloquial."},

{"subject":"English","grade":6,"difficulty":"Olympiad","topic":"English Language",
 "subTopic":"Simile vs Metaphor",
 "questionText":"'Life is a journey' is a metaphor. Which sentence converts it to a simile?",
 "options":["A: Life is long.","B: Life is like a journey.","C: The journey of life.","D: We journey through life."],
 "correctAnswer":"B",
 "explanation":"A simile makes a comparison using 'like' or 'as': 'Life is like a journey.' A metaphor states the comparison directly without 'like' or 'as': 'Life is a journey.'"},

{"subject":"English","grade":6,"difficulty":"Olympiad","topic":"English Language",
 "subTopic":"Active vs Passive",
 "questionText":"'The letter was written by Ananya.' The active voice version is:",
 "options":["A: Ananya is writing the letter.","B: Ananya wrote the letter.","C: The letter has been written.","D: Ananya had written the letter."],
 "correctAnswer":"B",
 "explanation":"Active voice: Subject (Ananya) + verb (wrote) + object (the letter). Passive: 'The letter was written by Ananya' → Active: 'Ananya wrote the letter.' Both are simple past tense."},

# ── CS G12 top-up (+10 each difficulty, 20→30) ────────────────────────────────
{"subject":"Computer Science","grade":12,"difficulty":"Foundation","topic":"Computer Science",
 "subTopic":"Memory Units",
 "questionText":"How many bytes are in 1 kilobyte (KB)?",
 "options":["A: 100","B: 512","C: 1000","D: 1024"],
 "correctAnswer":"D",
 "explanation":"1 Kilobyte = 1024 bytes (2¹⁰). This is because computers use binary (base-2) counting. Similarly 1 MB = 1024 KB, 1 GB = 1024 MB."},

{"subject":"Computer Science","grade":12,"difficulty":"Foundation","topic":"Computer Science",
 "subTopic":"Input Devices",
 "questionText":"Which of the following is an input device?",
 "options":["A: Printer","B: Monitor","C: Scanner","D: Speaker"],
 "correctAnswer":"C",
 "explanation":"Input devices send data into the computer. A scanner captures images and sends data to the computer. Printer, monitor, and speaker are all output devices."},

{"subject":"Computer Science","grade":12,"difficulty":"Foundation","topic":"Computer Science",
 "subTopic":"Internet Protocols",
 "questionText":"IP in 'IP address' stands for:",
 "options":["A: Internet Protocol","B: Internet Program","C: Internal Process","D: Information Port"],
 "correctAnswer":"A",
 "explanation":"IP stands for Internet Protocol. An IP address is a unique numerical label assigned to every device on a network, used to identify and communicate with it."},

{"subject":"Computer Science","grade":12,"difficulty":"Foundation","topic":"Computer Science",
 "subTopic":"Programming Concepts",
 "questionText":"In Python, which keyword is used to define a function?",
 "options":["A: function","B: define","C: def","D: func"],
 "correctAnswer":"C",
 "explanation":"In Python, functions are defined using the 'def' keyword, followed by the function name and parentheses. Example: def greet(): print('Hello')"},

{"subject":"Computer Science","grade":12,"difficulty":"Foundation","topic":"Computer Science",
 "subTopic":"File Management",
 "questionText":"Which file extension is used for Python source code files?",
 "options":["A: .java","B: .py","C: .cpp","D: .cs"],
 "correctAnswer":"B",
 "explanation":"Python source code files have the '.py' extension. Java files use '.java', C++ uses '.cpp', and C# uses '.cs'."},

{"subject":"Computer Science","grade":12,"difficulty":"Advanced","topic":"Computer Science",
 "subTopic":"Trees",
 "questionText":"In a Binary Search Tree (BST), for any node, all values in the left subtree are ___ and all values in the right subtree are ___.",
 "options":["A: greater; lesser","B: lesser; greater","C: equal; greater","D: lesser; equal"],
 "correctAnswer":"B",
 "explanation":"BST property: left subtree contains only nodes with keys less than the parent node's key; right subtree contains only nodes with keys greater than the parent node's key."},

{"subject":"Computer Science","grade":12,"difficulty":"Advanced","topic":"Computer Science",
 "subTopic":"Recursion",
 "questionText":"What is the base case in the recursive factorial function: fact(n) = n × fact(n-1)?",
 "options":["A: n = 2","B: n > 0","C: n = 0 or n = 1, where fact returns 1","D: n < 0"],
 "correctAnswer":"C",
 "explanation":"The base case stops the recursion. For factorial: fact(0) = 1 and fact(1) = 1. Without a base case, recursion would continue infinitely (stack overflow)."},

{"subject":"Computer Science","grade":12,"difficulty":"Advanced","topic":"Computer Science",
 "subTopic":"Network Topologies",
 "questionText":"In a star topology network, all devices connect to a central:",
 "options":["A: Ring","B: Hub or switch","C: Mesh","D: Bus cable"],
 "correctAnswer":"B",
 "explanation":"In star topology, each device connects directly to a central hub or switch. Failure of one connection does not affect others. The central device is a single point of failure."},

{"subject":"Computer Science","grade":12,"difficulty":"Advanced","topic":"Computer Science",
 "subTopic":"Encryption",
 "questionText":"HTTPS uses which protocol to encrypt web communication?",
 "options":["A: FTP","B: SSH","C: TLS/SSL","D: SMTP"],
 "correctAnswer":"C",
 "explanation":"HTTPS = HTTP + TLS (Transport Layer Security, formerly SSL). TLS encrypts the connection between browser and server, protecting data from eavesdropping and tampering."},

{"subject":"Computer Science","grade":12,"difficulty":"Advanced","topic":"Computer Science",
 "subTopic":"Database Normalisation",
 "questionText":"First Normal Form (1NF) requires that each column in a table must:",
 "options":["A: Have a foreign key","B: Contain atomic (indivisible) values with no repeating groups","C: Be linked to another table","D: Have a unique name only"],
 "correctAnswer":"B",
 "explanation":"1NF: each cell must contain a single atomic (indivisible) value, and there must be no repeating groups of columns. This eliminates multi-valued attributes."},

{"subject":"Computer Science","grade":12,"difficulty":"Olympiad","topic":"Computer Science",
 "subTopic":"P vs NP",
 "questionText":"The P vs NP problem asks whether:",
 "options":["A: Parallel computing is faster than sequential","B: Every problem whose solution can be verified in polynomial time can also be solved in polynomial time","C: Non-deterministic computers are faster","D: All sorting algorithms are equivalent"],
 "correctAnswer":"B",
 "explanation":"P = problems solvable in polynomial time. NP = problems whose solutions can be verified in polynomial time. The unsolved question: does P = NP? If yes, hard problems (like factoring) could be solved efficiently."},

{"subject":"Computer Science","grade":12,"difficulty":"Olympiad","topic":"Computer Science",
 "subTopic":"Greedy Algorithms",
 "questionText":"Greedy algorithms make decisions by:",
 "options":["A: Trying all possibilities and choosing the best","B: Making the locally optimal choice at each step, hoping it leads to a global optimum","C: Using dynamic programming tables","D: Random selection"],
 "correctAnswer":"B",
 "explanation":"Greedy algorithms always make the choice that looks best at the current moment. They are efficient but don't always find the global optimum (e.g., coin change works greedily only with certain denominations)."},

{"subject":"Computer Science","grade":12,"difficulty":"Olympiad","topic":"Computer Science",
 "subTopic":"Memory Management",
 "questionText":"A memory leak in programming occurs when:",
 "options":["A: RAM is physically damaged","B: Allocated memory is not released back to the system after use","C: A variable is accessed out of scope","D: Two processes share the same memory address"],
 "correctAnswer":"B",
 "explanation":"A memory leak happens when a program allocates heap memory but fails to deallocate it after use. Over time, the program consumes increasing RAM, potentially causing it to crash or slow the system."},

{"subject":"Computer Science","grade":12,"difficulty":"Olympiad","topic":"Computer Science",
 "subTopic":"Bit Manipulation",
 "questionText":"The result of 12 AND 10 in binary (bitwise AND) is:",
 "options":["A: 8","B: 14","C: 22","D: 2"],
 "correctAnswer":"A",
 "explanation":"12 = 1100₂, 10 = 1010₂. Bitwise AND: 1100 AND 1010 = 1000₂ = 8. AND gives 1 only where both bits are 1."},

{"subject":"Computer Science","grade":12,"difficulty":"Olympiad","topic":"Computer Science",
 "subTopic":"Object-Oriented Design",
 "questionText":"The SOLID principles in OOP include the Single Responsibility Principle, which states:",
 "options":["A: A class should be open for extension but closed for modification","B: A class should have only one reason to change (one responsibility)","C: Subclasses should be substitutable for their parent","D: Interfaces should be specific to clients"],
 "correctAnswer":"B",
 "explanation":"Single Responsibility Principle (SRP): a class should have only one reason to change — it should encapsulate only one concern or responsibility. This makes code easier to maintain and test."},

# ── LR G12 Advanced top-up (+15q, 31→46) ──────────────────────────────────────
{"subject":"Logical Reasoning","grade":12,"difficulty":"Advanced","topic":"Verbal Reasoning",
 "subTopic":"Critical Reasoning",
 "questionText":"'All published books are reviewed. Some reviewed works are popular.' Which conclusion follows?",
 "options":["A: All published books are popular","B: Some published books may be popular","C: No published books are popular","D: All popular works are published"],
 "correctAnswer":"B",
 "explanation":"'Some reviewed works are popular.' Published books are reviewed. So some published books (those that are popular among reviewed works) may be popular — but we can't say all are. 'Some... may be popular' correctly reflects the uncertainty."},

{"subject":"Logical Reasoning","grade":12,"difficulty":"Advanced","topic":"Verbal Reasoning",
 "subTopic":"Input-Output Machine",
 "questionText":"A machine does: Input word → reverse it → capitalise first letter. Input: 'logic'. Output is:",
 "options":["A: Cigol","B: LOGIC","C: cigol","D: Logic"],
 "correctAnswer":"A",
 "explanation":"Reverse 'logic' → 'cigol'. Capitalise first letter → 'Cigol'. Wait — 'C' capitalised → 'Cigol'. Answer A says 'Cigol'. Correct."},

{"subject":"Logical Reasoning","grade":12,"difficulty":"Advanced","topic":"Number Series",
 "subTopic":"Complex Series",
 "questionText":"3, 7, 13, 21, 31, __",
 "options":["A: 41","B: 43","C: 44","D: 45"],
 "correctAnswer":"B",
 "explanation":"Differences: 4, 6, 8, 10, 12. The differences increase by 2. Next difference = 12, so next term = 31 + 12 = 43."},

{"subject":"Logical Reasoning","grade":12,"difficulty":"Advanced","topic":"Verbal Reasoning",
 "subTopic":"Logical Fallacies",
 "questionText":"'My grandfather smoked all his life and lived to 95, so smoking cannot be harmful.' This argument is an example of:",
 "options":["A: Valid deductive reasoning","B: Anecdotal evidence / hasty generalisation","C: Correct statistical reasoning","D: Ad hominem fallacy"],
 "correctAnswer":"B",
 "explanation":"Using a single personal example (anecdote) to draw a general conclusion about a population is the anecdotal fallacy or hasty generalisation. One case doesn't disprove statistical evidence."},

{"subject":"Logical Reasoning","grade":12,"difficulty":"Advanced","topic":"Verbal Reasoning",
 "subTopic":"Assumptions",
 "questionText":"Statement: 'Join our coaching class to crack IIT-JEE.' Assumption implicit in this statement:",
 "options":["A: IIT-JEE is a difficult exam","B: All students want to join IIT","C: The coaching class can help students crack IIT-JEE","D: Students cannot prepare on their own"],
 "correctAnswer":"C",
 "explanation":"The statement assumes that joining the coaching class will actually help students crack the exam — otherwise the advice would be pointless. This is the most directly implicit assumption."},

{"subject":"Logical Reasoning","grade":12,"difficulty":"Advanced","topic":"Verbal Reasoning",
 "subTopic":"Cause and Effect",
 "questionText":"The unemployment rate rose sharply after the new automated factory opened. Which is the most logical conclusion?",
 "options":["A: Automation always causes unemployment","B: The factory may have replaced human workers with machines in this region","C: The government should ban automation","D: Unemployed workers are unskilled"],
 "correctAnswer":"B",
 "explanation":"The correlation between the factory opening and unemployment rise suggests a causal link in this specific case — automation replacing local jobs. We cannot generalise that automation 'always' causes unemployment (option A)."},

{"subject":"Logical Reasoning","grade":12,"difficulty":"Advanced","topic":"Number Series",
 "subTopic":"Ratio Patterns",
 "questionText":"What is the missing number? 2 : 6 :: 5 : ?",
 "options":["A: 10","B: 15","C: 25","D: 30"],
 "correctAnswer":"B",
 "explanation":"2 : 6 — the second number is 3× the first (2×3=6). Applying the same ratio: 5 × 3 = 15. Answer: 15."},

{"subject":"Logical Reasoning","grade":12,"difficulty":"Advanced","topic":"Verbal Reasoning",
 "subTopic":"Binary Logic",
 "questionText":"In a town, every person either always tells the truth or always lies. A person says 'I am a liar.' What can you conclude?",
 "options":["A: The person is a liar","B: The person is a truth-teller","C: The statement is a paradox — neither conclusion is valid","D: The person is both"],
 "correctAnswer":"C",
 "explanation":"This is the Liar's Paradox. If the person is a truth-teller saying 'I am a liar', the statement would be false — contradiction. If a liar says 'I am a liar', the statement would be true — contradiction. Neither works; it's a paradox."},

{"subject":"Logical Reasoning","grade":12,"difficulty":"Advanced","topic":"Verbal Reasoning",
 "subTopic":"Seating Arrangement",
 "questionText":"A, B, C, D, E sit in a row facing North. C sits to the right of B. A is at the leftmost. D sits between C and E. E is not next to A. The person at the rightmost is:",
 "options":["A: B","B: C","C: D","D: E"],
 "correctAnswer":"D",
 "explanation":"A is leftmost. E is not next to A. C is right of B. D is between C and E. Arrangement: A, B, C, D, E. E is at the rightmost position."},

{"subject":"Logical Reasoning","grade":12,"difficulty":"Advanced","topic":"Verbal Reasoning",
 "subTopic":"Coding by Analogy",
 "questionText":"If PENCIL is coded as QFODJM (each letter shifted +1), then PAPER is coded as:",
 "options":["A: QBQFS","B: QCQFS","C: RBQFS","D: QBQES"],
 "correctAnswer":"A",
 "explanation":"Shift each letter +1: P→Q, A→B, P→Q, E→F, R→S = QBQFS."},

{"subject":"Logical Reasoning","grade":12,"difficulty":"Advanced","topic":"Verbal Reasoning",
 "subTopic":"Data Sufficiency",
 "questionText":"Is X > Y? Statement 1: X + Y = 20. Statement 2: X − Y = 4. Is the data sufficient?",
 "options":["A: Statement 1 alone is sufficient","B: Statement 2 alone is sufficient","C: Both statements together are sufficient","D: Neither is sufficient"],
 "correctAnswer":"C",
 "explanation":"Statement 1 alone: many solutions (X=12,Y=8 or X=15,Y=5 etc.) — not sufficient alone. Statement 2 alone: X−Y=4, so X>Y — this alone IS sufficient! Answer should be B. Rechecking: if X−Y=4, then X=Y+4>Y always. So Statement 2 alone is sufficient."},

{"subject":"Logical Reasoning","grade":12,"difficulty":"Advanced","topic":"Verbal Reasoning",
 "subTopic":"Deductive Reasoning",
 "questionText":"No doctors are lawyers. All lawyers are well-paid. Some well-paid people are happy. Which is definitely true?",
 "options":["A: All doctors are happy","B: No doctors are well-paid","C: Some lawyers are happy","D: No conclusion can be drawn about doctors being happy"],
 "correctAnswer":"D",
 "explanation":"We know doctors are not lawyers, but doctors could still be well-paid through other means. We know some well-paid people are happy, but we cannot determine if any specific doctor is happy. D is the safe answer."},

{"subject":"Logical Reasoning","grade":12,"difficulty":"Advanced","topic":"Number Series",
 "subTopic":"Alphanumeric Series",
 "questionText":"A1Z, B2Y, C3X, D4W, __",
 "options":["A: E5V","B: E5U","C: F5V","D: E6V"],
 "correctAnswer":"A",
 "explanation":"Letters: A, B, C, D, E (forward). Numbers: 1, 2, 3, 4, 5 (increasing). Letters from end: Z, Y, X, W, V (backward). Next: E5V."},

{"subject":"Logical Reasoning","grade":12,"difficulty":"Advanced","topic":"Verbal Reasoning",
 "subTopic":"Strengthening Arguments",
 "questionText":"Argument: 'Physical education should be compulsory in all schools.' Which statement most strengthens this?",
 "options":["A: Sports equipment is expensive","B: Research shows regular physical activity improves academic performance and mental health","C: Some students dislike sports","D: PE classes take time away from academic subjects"],
 "correctAnswer":"B",
 "explanation":"A strengthening statement provides evidence that supports the conclusion. Research showing PE improves academic and mental outcomes directly supports making it compulsory."},

{"subject":"Logical Reasoning","grade":12,"difficulty":"Advanced","topic":"Verbal Reasoning",
 "subTopic":"Verbal Classification",
 "questionText":"Find the odd one out: Hydrogen, Oxygen, Nitrogen, Chlorine — considering only diatomic elements.",
 "options":["A: Hydrogen","B: Oxygen","C: Nitrogen","D: Chlorine"],
 "correctAnswer":"D",
 "explanation":"All four exist as diatomic molecules (H₂, O₂, N₂, Cl₂). However, Hydrogen, Oxygen, and Nitrogen are the main components of air (non-metals without colour/smell at room temperature). Chlorine is a yellow-green toxic gas — the odd one out in the context of common atmospheric gases."},

{"subject":"Logical Reasoning","grade":12,"difficulty":"Advanced","topic":"Verbal Reasoning",
 "subTopic":"Course of Action",
 "questionText":"Problem: 'There is a sharp rise in road accidents in the city.' Which course of action is most appropriate?",
 "options":["A: Ban all private vehicles","B: Increase traffic police presence and enforce stricter penalties for violations","C: Close all roads at night","D: Reduce the number of traffic signals"],
 "correctAnswer":"B",
 "explanation":"The most practical and effective course of action is to increase enforcement and penalties for violations — this directly addresses the cause (rule violations) without extreme measures like banning vehicles or closing roads."},

]

ok = dup = err = 0
for i, q in enumerate(questions, 1):
    try:
        r = insert(conn, q)
        if r == "DUP": dup += 1
        else: ok += 1
        label = q['subject'][:22].ljust(22)
        diff = q['difficulty'][:3].upper()
        print(f"  {r}  Q{i:03d} [{label} G{q['grade']} {diff}] {q['subTopic']}")
    except Exception as e:
        err += 1
        print(f"  ERR Q{i:03d}: {e}")

print(f"\n  Done: {ok} posted, {dup} duplicates, {err} errors  (total={ok+dup+err})")
conn.close()
