import pyodbc, json, uuid, sys
sys.stdout.reconfigure(encoding='utf-8', errors='replace')

DB_CONN = (
    "DRIVER={ODBC Driver 18 for SQL Server};"
    "SERVER=tcp:olympiadready-np.database.windows.net,1433;"
    "DATABASE=OlympiadReady;UID=nyxen-admin;PWD=Olympiad@2026;"
    "Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30"
)

def insert(conn, q):
    c = conn.cursor()
    c.execute("SELECT 1 FROM QuestionBank WHERE Subject=? AND Grade=? AND SubTopic=? AND QuestionText=?",
              q["subject"], q["grade"], q["subTopic"], q["questionText"])
    if c.fetchone():
        return "DUP"
    c.execute("""INSERT INTO QuestionBank
                 (QuestionBankId,Subject,Grade,Difficulty,Topic,SubTopic,
                  QuestionText,OptionsJson,CorrectAnswer,Explanation,CreatedAt)
                 VALUES (?,?,?,?,?,?,?,?,?,?,GETUTCDATE())""",
              str(uuid.uuid4()).upper(), q["subject"], q["grade"], q["difficulty"],
              q["topic"], q["subTopic"], q["questionText"],
              json.dumps(q["options"]), q["correctAnswer"], q["explanation"])
    conn.commit()
    return "OK"

# ── GK G10 FOUNDATION (15q) ────────────────────────────────
GK10_FOUND = [
    {"subject":"General Knowledge","grade":10,"difficulty":"Foundation","topic":"Science","subTopic":"Basic Science Facts",
     "questionText":"What is the chemical symbol for gold?",
     "options":["A: Gd","B: Go","C: Au","D: Ag"],"correctAnswer":"C",
     "explanation":"Gold's symbol Au comes from the Latin word 'Aurum'. Ag is silver (Argentum). Gd is gadolinium. The symbols of many elements come from their Latin names."},
    {"subject":"General Knowledge","grade":10,"difficulty":"Foundation","topic":"Indian History","subTopic":"Independence",
     "questionText":"India gained independence from British rule on which date?",
     "options":["A: 26 January 1950","B: 15 August 1947","C: 2 October 1948","D: 30 January 1948"],"correctAnswer":"B",
     "explanation":"India became independent on 15 August 1947. Jawaharlal Nehru became the first Prime Minister and delivered his famous 'Tryst with Destiny' speech at midnight. 26 January 1950 is when India became a Republic (Constitution came into effect)."},
    {"subject":"General Knowledge","grade":10,"difficulty":"Foundation","topic":"World Geography","subTopic":"Countries and Capitals",
     "questionText":"What is the capital city of Australia?",
     "options":["A: Sydney","B: Melbourne","C: Canberra","D: Brisbane"],"correctAnswer":"C",
     "explanation":"Canberra is the capital of Australia. It was purpose-built as the capital (like Chandigarh and New Delhi) as a compromise between Sydney and Melbourne, which both wanted to be the capital. Canberra became the capital in 1927."},
    {"subject":"General Knowledge","grade":10,"difficulty":"Foundation","topic":"Science","subTopic":"Human Body",
     "questionText":"How many bones are there in an adult human body?",
     "options":["A: 206","B: 305","C: 180","D: 250"],"correctAnswer":"A",
     "explanation":"An adult human body has 206 bones. Babies are born with about 270-300 bones, which fuse together as they grow. The smallest bone is the stapes (in the ear); the largest is the femur (thigh bone)."},
    {"subject":"General Knowledge","grade":10,"difficulty":"Foundation","topic":"Awards","subTopic":"Bharat Ratna",
     "questionText":"Bharat Ratna is India's highest civilian honour. The first recipients in 1954 included:",
     "options":["A: Mahatma Gandhi and Nehru","B: C. Rajagopalachari, S. Radhakrishnan, and C.V. Raman","C: Indira Gandhi and APJ Abdul Kalam","D: Lal Bahadur Shastri and Sardar Patel"],"correctAnswer":"B",
     "explanation":"The first Bharat Ratna awards in 1954 went to C. Rajagopalachari (statesman), Dr. Sarvepalli Radhakrishnan (philosopher, later President), and Dr. C.V. Raman (physicist). Mahatma Gandhi has never been given the award — he was assassinated in 1948 before it was instituted."},
    {"subject":"General Knowledge","grade":10,"difficulty":"Foundation","topic":"Sports","subTopic":"Cricket",
     "questionText":"The Cricket World Cup 2023 was held in India. Which team won the tournament?",
     "options":["A: India","B: Australia","C: England","D: South Africa"],"correctAnswer":"B",
     "explanation":"Australia won the ICC Cricket World Cup 2023, defeating India in the final played at Ahmedabad on 19 November 2023. Australia won by 6 wickets. It was Australia's sixth ODI World Cup title."},
    {"subject":"General Knowledge","grade":10,"difficulty":"Foundation","topic":"Environment","subTopic":"National Parks",
     "questionText":"Jim Corbett National Park, India's first national park, is located in which state?",
     "options":["A: Madhya Pradesh","B: Uttarakhand","C: Rajasthan","D: Assam"],"correctAnswer":"B",
     "explanation":"Jim Corbett National Park, established in 1936 (originally Hailey National Park), is located in Uttarakhand. It was renamed after the famous hunter-turned-conservationist Jim Corbett. It was the first park under Project Tiger in 1973."},
    {"subject":"General Knowledge","grade":10,"difficulty":"Foundation","topic":"Indian Constitution","subTopic":"National Symbols",
     "questionText":"What is the national flower of India?",
     "options":["A: Rose","B: Marigold","C: Lotus","D: Jasmine"],"correctAnswer":"C",
     "explanation":"The Lotus (Nelumbo nucifera) is the national flower of India. It is significant in Indian culture and religion — associated with Lakshmi, Saraswati, and Vishnu. Lotus grows in muddy water yet remains clean, symbolising purity and spiritual awakening."},
    {"subject":"General Knowledge","grade":10,"difficulty":"Foundation","topic":"Science","subTopic":"Space",
     "questionText":"The International Space Station (ISS) orbits Earth at what approximate altitude?",
     "options":["A: 400 km","B: 36,000 km","C: 100 km","D: 4,000 km"],"correctAnswer":"A",
     "explanation":"The ISS orbits at approximately 400 km altitude (about 250 miles), completing one orbit every 90 minutes. At 36,000 km is geostationary orbit (used by communication satellites). The Kármán line (boundary of space) is at 100 km."},
    {"subject":"General Knowledge","grade":10,"difficulty":"Foundation","topic":"Technology","subTopic":"Internet and Computers",
     "questionText":"What does 'www' stand for in a web address?",
     "options":["A: World Wide Web","B: World Web Works","C: Wide Web World","D: World Wire Web"],"correctAnswer":"A",
     "explanation":"www stands for World Wide Web — the system of interlinked hypertext documents (websites) accessible via the internet. It was invented by Tim Berners-Lee at CERN in 1989. The internet is the network infrastructure; the World Wide Web is a service that runs on it."},
    {"subject":"General Knowledge","grade":10,"difficulty":"Foundation","topic":"Indian Culture","subTopic":"Festivals",
     "questionText":"Pongal is a harvest festival celebrated primarily in which Indian state?",
     "options":["A: Kerala","B: Tamil Nadu","C: Andhra Pradesh","D: Karnataka"],"correctAnswer":"B",
     "explanation":"Pongal is a four-day harvest festival celebrated in Tamil Nadu, typically in January. It coincides with Makar Sankranti. 'Pongal' means 'to boil over' — rice is boiled in new pots as an offering. The four days are: Bhogi, Thai Pongal, Maattu Pongal, and Kaanum Pongal."},
    {"subject":"General Knowledge","grade":10,"difficulty":"Foundation","topic":"World History","subTopic":"World War II",
     "questionText":"The atomic bombs dropped on Hiroshima and Nagasaki (1945) were dropped by which country?",
     "options":["A: UK","B: USSR","C: USA","D: Germany"],"correctAnswer":"C",
     "explanation":"The USA dropped atomic bombs on Hiroshima (6 August 1945) and Nagasaki (9 August 1945), killing approximately 200,000 people. Japan surrendered on 15 August 1945, ending World War II in Asia. It was the first and only use of nuclear weapons in warfare."},
    {"subject":"General Knowledge","grade":10,"difficulty":"Foundation","topic":"Science","subTopic":"Units of Measurement",
     "questionText":"The SI unit of electric current is the:",
     "options":["A: Volt","B: Watt","C: Ohm","D: Ampere"],"correctAnswer":"D",
     "explanation":"The ampere (A) is the SI unit of electric current. Volt (V) is the unit of voltage (potential difference). Watt (W) is the unit of power. Ohm (Ω) is the unit of resistance. The ampere is defined as one of the seven SI base units."},
    {"subject":"General Knowledge","grade":10,"difficulty":"Foundation","topic":"Indian Economy","subTopic":"Finance",
     "questionText":"The Reserve Bank of India (RBI) was established in which year?",
     "options":["A: 1947","B: 1935","C: 1921","D: 1955"],"correctAnswer":"B",
     "explanation":"The Reserve Bank of India was established on 1 April 1935 under the Reserve Bank of India Act 1934, during British rule. It was nationalised in 1949 after independence. The RBI regulates money supply, interest rates, and oversees the banking system."},
    {"subject":"General Knowledge","grade":10,"difficulty":"Foundation","topic":"Environment","subTopic":"Climate",
     "questionText":"Which gas is primarily responsible for the 'greenhouse effect' and global warming?",
     "options":["A: Oxygen","B: Nitrogen","C: Carbon dioxide","D: Hydrogen"],"correctAnswer":"C",
     "explanation":"Carbon dioxide (CO₂) is the primary greenhouse gas driving current global warming, though water vapour is actually the most abundant greenhouse gas. CO₂ from burning fossil fuels has increased atmospheric concentration from ~280 ppm (pre-industrial) to ~420 ppm today. Methane (CH₄) is more potent per molecule but less abundant."},
]

# ── GK G10 ADVANCED (15q) ────────────────────────────────
GK10_ADV = [
    {"subject":"General Knowledge","grade":10,"difficulty":"Advanced","topic":"Science and Technology","subTopic":"Space Missions India",
     "questionText":"ISRO's Aditya-L1 mission, launched in 2023, is India's first solar observatory mission. Where is it positioned?",
     "options":["A: In Earth's low orbit","B: At the Lagrange point L1 between Earth and the Sun, about 1.5 million km from Earth","C: On the Moon's surface","D: In geostationary orbit"],"correctAnswer":"B",
     "explanation":"Aditya-L1 was launched by ISRO on 2 September 2023 and reached the Sun-Earth Lagrange Point 1 (L1) in January 2024. At L1, the spacecraft can continuously observe the Sun without being eclipsed by Earth or Moon. It studies solar corona, solar wind, solar flares, and CMEs — crucial for space weather forecasting."},
    {"subject":"General Knowledge","grade":10,"difficulty":"Advanced","topic":"Indian History","subTopic":"Maurya Empire",
     "questionText":"Ashoka the Great converted to Buddhism after which battle that deeply disturbed him?",
     "options":["A: Battle of Panipat","B: Battle of Kalinga (261 BCE)","C: Battle of Hydaspes","D: Battle of Plassey"],"correctAnswer":"B",
     "explanation":"The Kalinga War (261 BCE) against the Kalinga kingdom (modern Odisha) resulted in massive casualties — about 100,000 killed and 150,000 deported. The suffering deeply affected Ashoka, who converted to Buddhism and adopted 'Dhamma' (righteousness). He sent Buddhist missionaries to Sri Lanka, Southeast Asia, and West Asia, spreading Buddhism across Asia."},
    {"subject":"General Knowledge","grade":10,"difficulty":"Advanced","topic":"Science","subTopic":"Physics",
     "questionText":"The Large Hadron Collider (LHC) at CERN discovered the Higgs boson in 2012. Why is the Higgs boson called the 'God particle'?",
     "options":["A: It was found inside religious texts","B: It is the particle that gives other fundamental particles their mass through interaction with the Higgs field","C: It can travel faster than light","D: It was predicted by God's equations"],"correctAnswer":"B",
     "explanation":"The Higgs boson is the quantum excitation of the Higgs field — a quantum field that permeates the universe. Fundamental particles (W, Z bosons, quarks, leptons) acquire mass by interacting with this field. Without the Higgs field, all particles would be massless and travel at the speed of light — atoms could not form. The nickname 'God particle' (from a book title) is rejected by most physicists."},
    {"subject":"General Knowledge","grade":10,"difficulty":"Advanced","topic":"World Affairs","subTopic":"United Nations",
     "questionText":"The UN Security Council has 5 permanent members (P5) with veto power. Which country is NOT a permanent member?",
     "options":["A: France","B: United Kingdom","C: India","D: Russia"],"correctAnswer":"C",
     "explanation":"The five permanent members (P5) of the UN Security Council are: USA, UK, France, Russia, and China. India is not a permanent member, though it has been elected as a non-permanent member multiple times and leads the campaign for UNSC reform and permanent membership for itself, Brazil, Germany, and Japan ('G4')."},
    {"subject":"General Knowledge","grade":10,"difficulty":"Advanced","topic":"Indian Economy","subTopic":"GDP and Growth",
     "questionText":"India became the world's 5th largest economy (by nominal GDP) overtaking which country in 2022?",
     "options":["A: France","B: United Kingdom","C: Germany","D: Japan"],"correctAnswer":"B",
     "explanation":"India overtook the United Kingdom to become the world's 5th largest economy by nominal GDP in 2022, according to IMF data. The ranking: 1. USA, 2. China, 3. Germany, 4. Japan, 5. India. India is projected to become the 3rd largest economy by 2027-2030."},
    {"subject":"General Knowledge","grade":10,"difficulty":"Advanced","topic":"Environment","subTopic":"Paris Agreement",
     "questionText":"The Paris Agreement (2015) set a goal to limit global temperature rise. What is the target?",
     "options":["A: Below 3°C above pre-industrial levels","B: Well below 2°C, with efforts to limit to 1.5°C above pre-industrial levels","C: Exactly 2°C above pre-industrial levels","D: No temperature rise at all"],"correctAnswer":"B",
     "explanation":"The Paris Agreement, signed at COP21 in 2015 by 196 parties, sets the goal of limiting global average temperature rise to 'well below 2°C above pre-industrial levels and pursuing efforts to limit it to 1.5°C'. India is a signatory and committed to achieving net-zero emissions by 2070 and 50% renewable energy by 2030."},
    {"subject":"General Knowledge","grade":10,"difficulty":"Advanced","topic":"Science","subTopic":"Biology",
     "questionText":"The Human Genome Project (completed 2003) sequenced the entire human genome. How many protein-coding genes does the human genome contain?",
     "options":["A: About 20,000–25,000 genes","B: About 100,000 genes","C: About 3 billion genes","D: About 500 genes"],"correctAnswer":"A",
     "explanation":"The Human Genome Project found that humans have approximately 20,000–25,000 protein-coding genes — far fewer than expected. The human genome has about 3 billion base pairs of DNA, but only ~1.5% codes for proteins. The rest ('non-coding DNA') includes regulatory sequences, RNA genes, repetitive sequences, and was once called 'junk DNA'."},
    {"subject":"General Knowledge","grade":10,"difficulty":"Advanced","topic":"Technology","subTopic":"Artificial Intelligence",
     "questionText":"AlphaGo (DeepMind, 2016) defeated Go world champion Lee Sedol. Go is considered much harder for AI than chess because:",
     "options":["A: Go has more complex rules than chess","B: Go has an astronomically larger number of possible board positions (~10¹⁷⁰) making brute-force computation impossible — AI needed to learn intuition","C: Chess has fewer pieces than Go","D: Go is played faster than chess"],"correctAnswer":"B",
     "explanation":"Chess has about 10^43 possible games; Go has ~10^170 — more than atoms in the observable universe. Classical chess AI (Deep Blue) used brute-force search with evaluation functions. Go's complexity made this impossible — AlphaGo used deep neural networks (trained on human games then self-play) to develop 'intuition'. This breakthrough proved deep learning could master domains previously thought beyond AI."},
    {"subject":"General Knowledge","grade":10,"difficulty":"Advanced","topic":"Indian Constitution","subTopic":"Amendments",
     "questionText":"The 73rd Constitutional Amendment (1992) is significant because it:",
     "options":["A: Lowered voting age from 21 to 18","B: Added Fundamental Duties to the Constitution","C: Gave constitutional status to Panchayati Raj institutions and mandated reservations for women and SC/STs in local governance","D: Created the Right to Education"],"correctAnswer":"C",
     "explanation":"The 73rd Amendment (1992) inserted Part IX into the Constitution, giving constitutional status to Panchayati Raj (village self-government). It mandated: 3-tier system (village, block, district), elections every 5 years, 33% reservation for women, reservations for SC/STs. This decentralised democracy to the grassroots — one of the world's largest exercises in local self-governance."},
    {"subject":"General Knowledge","grade":10,"difficulty":"Advanced","topic":"World History","subTopic":"Modern History",
     "questionText":"The Berlin Wall fell in November 1989, leading to German reunification. The Wall had divided Berlin for how many years?",
     "options":["A: 10 years","B: 28 years (1961–1989)","C: 40 years","D: 50 years"],"correctAnswer":"B",
     "explanation":"The Berlin Wall was built on 13 August 1961 and fell on 9 November 1989 — standing for 28 years. It divided Soviet-controlled East Berlin from Western-controlled West Berlin, symbolising the Iron Curtain of the Cold War. Its fall was a defining moment of the late 20th century, leading to German reunification on 3 October 1990."},
    {"subject":"General Knowledge","grade":10,"difficulty":"Advanced","topic":"Science","subTopic":"Medicine",
     "questionText":"Penicillin, the first antibiotic, was discovered accidentally by Alexander Fleming in 1928. How did Fleming discover it?",
     "options":["A: He intentionally mixed mould with bacteria in an experiment","B: He noticed that a mould (Penicillium) contaminating a bacterial plate had created a clear zone where bacteria were killed","C: He found it in soil samples from Scotland","D: He synthesised it chemically"],"correctAnswer":"B",
     "explanation":"Fleming returned from holiday to find a mould (Penicillium notatum) had contaminated a Staphylococcus petri dish. Remarkably, the bacteria around the mould were dead. He recognised the mould was producing a bacteria-killing substance — penicillin. It was later purified by Florey and Chain (who shared the 1945 Nobel Prize with Fleming), saving millions of lives from bacterial infections."},
    {"subject":"General Knowledge","grade":10,"difficulty":"Advanced","topic":"Indian Culture","subTopic":"UNESCO Heritage Sites",
     "questionText":"Which Indian monument was added to UNESCO's World Heritage List in 1983, among the first batch from India?",
     "options":["A: Red Fort","B: Qutub Minar","C: Taj Mahal","D: All three (Taj Mahal, Agra Fort, and Ajanta Caves were among the first batch)"],"correctAnswer":"D",
     "explanation":"In 1983, India's first batch of UNESCO World Heritage Sites included: Ajanta Caves, Ellora Caves, Taj Mahal, and Agra Fort. Qutub Minar was added in 1993. India currently has 42 UNESCO World Heritage Sites (2023) — 34 cultural, 7 natural, and 1 mixed."},
    {"subject":"General Knowledge","grade":10,"difficulty":"Advanced","topic":"Science","subTopic":"Technology Inventions",
     "questionText":"The Transistor, invented at Bell Labs in 1947, revolutionised electronics. Who invented it?",
     "options":["A: Thomas Edison and Nikola Tesla","B: William Shockley, John Bardeen, and Walter Brattain","C: Alan Turing and Claude Shannon","D: Steve Jobs and Bill Gates"],"correctAnswer":"B",
     "explanation":"William Shockley, John Bardeen, and Walter Brattain invented the transistor at Bell Labs in 1947, for which they shared the 1956 Nobel Prize in Physics. The transistor replaced vacuum tubes — making electronics smaller, cheaper, and more reliable. It is the building block of all modern electronics: every processor contains billions of transistors."},
    {"subject":"General Knowledge","grade":10,"difficulty":"Advanced","topic":"Sports","subTopic":"Olympics",
     "questionText":"India's first individual Olympic gold medal was won in which sport and by whom?",
     "options":["A: Wrestling — Sushil Kumar, 2012","B: Boxing — Vijender Singh, 2008","C: Shooting — Abhinav Bindra, 2008 Beijing Olympics","D: Badminton — Saina Nehwal, 2012"],"correctAnswer":"C",
     "explanation":"Abhinav Bindra won India's first individual Olympic gold medal at the 2008 Beijing Olympics in the 10m air rifle event. India had won gold medals before in field hockey (8 total, 1928-1980), but those were team events. Bindra's was India's first in an individual event."},
    {"subject":"General Knowledge","grade":10,"difficulty":"Advanced","topic":"Indian Economy","subTopic":"Financial Institutions",
     "questionText":"SEBI (Securities and Exchange Board of India) was established to regulate India's capital markets. When was it given statutory powers?",
     "options":["A: 1947","B: 1988 (established) and 1992 (given statutory powers by SEBI Act)","C: 2000","D: 1980"],"correctAnswer":"B",
     "explanation":"SEBI was established as a non-statutory body in 1988. Following the Harshad Mehta securities scandal, SEBI was given statutory powers under the SEBI Act, 1992. It regulates the stock exchanges (BSE, NSE), mutual funds, stockbrokers, and protects investor interests. Its headquarters are in Mumbai."},
]

# ── GK G10 OLYMPIAD (15q) ────────────────────────────────
GK10_OLY = [
    {"subject":"General Knowledge","grade":10,"difficulty":"Olympiad","topic":"Science","subTopic":"Quantum Mechanics",
     "questionText":"Heisenberg's Uncertainty Principle states that Δx·Δp ≥ ħ/2. This means:",
     "options":["A: Scientists lack sufficiently precise instruments","B: It is fundamentally impossible to know both position and momentum of a particle simultaneously with arbitrary precision — not a measurement limitation but a property of nature","C: Electrons move too fast to measure","D: Quantum particles follow different mathematics than classical particles"],"correctAnswer":"B",
     "explanation":"The Uncertainty Principle is not about measurement disturbance — it is a fundamental property of quantum mechanics. A particle does not have a definite position AND momentum simultaneously. The more precisely we define its position (small Δx), the more uncertain its momentum becomes (large Δp), and vice versa. This arises from the wave nature of matter. It has no classical analogue."},
    {"subject":"General Knowledge","grade":10,"difficulty":"Olympiad","topic":"World Affairs","subTopic":"Geopolitics",
     "questionText":"The QUAD (Quadrilateral Security Dialogue) includes India, USA, Australia, and Japan. What is the primary stated purpose of the QUAD?",
     "options":["A: Creating a military alliance to contain China","B: Promoting a free, open, and rules-based Indo-Pacific region — covering maritime security, climate, technology, and vaccines","C: Establishing a common currency for the Indo-Pacific","D: Replacing the United Nations in Asia"],"correctAnswer":"B",
     "explanation":"The QUAD's stated objectives are broader than military: promoting a free and open Indo-Pacific, maritime domain awareness, cybersecurity, clean energy, critical technology supply chains, and COVID-19 vaccine distribution. India emphasises the QUAD is not a military alliance. However, its strategic dimension — countering Chinese assertiveness in the South and East China Seas — is widely understood."},
    {"subject":"General Knowledge","grade":10,"difficulty":"Olympiad","topic":"Indian History","subTopic":"Economic History",
     "questionText":"The Drain of Wealth theory was articulated by Dadabhai Naoroji in his 1901 book. The 'drain' referred to:",
     "options":["A: Export of Indian gold to Britain","B: British extraction of India's economic resources — revenue collected in India but spent in Britain on goods, services, and debt payments without equivalent return","C: Loss of Indian agricultural produce to monsoon failure","D: Decline of Indian handicrafts due to industrialisation"],"correctAnswer":"B",
     "explanation":"Dadabhai Naoroji (called the 'Grand Old Man of India') calculated that Britain systematically extracted India's wealth — salaries paid to British officials, payments for British goods forced on India, interest on loans taken from Britain, and home charges. This 'drain' impoverished India while enriching Britain. Naoroji's analysis was foundational for economic nationalism and shaped the independence movement."},
    {"subject":"General Knowledge","grade":10,"difficulty":"Olympiad","topic":"Science","subTopic":"Particle Physics",
     "questionText":"The Standard Model of particle physics classifies all known fundamental particles. Quarks are held together inside protons and neutrons by which force?",
     "options":["A: Electromagnetic force","B: Gravitational force","C: Strong nuclear force (carried by gluons)","D: Weak nuclear force"],"correctAnswer":"C",
     "explanation":"The strong nuclear force is carried by gluons (massless force-carrying bosons). It binds quarks together inside protons and neutrons. It is the strongest of the four fundamental forces but acts only over extremely short distances (~10⁻¹⁵ m). Residual strong force also holds protons and neutrons together in the atomic nucleus. The Standard Model describes three forces (strong, weak, electromagnetic) — gravity is not yet incorporated."},
    {"subject":"General Knowledge","grade":10,"difficulty":"Olympiad","topic":"Economics","subTopic":"Macroeconomics",
     "questionText":"During hyperinflation (like Germany 1923 or Zimbabwe 2008), the currency becomes nearly worthless. The PRIMARY economic mechanism causing hyperinflation is:",
     "options":["A: Too many imports","B: Government printing excessive money (money supply growth far outpacing economic output) — too much money chasing too few goods","C: Low interest rates","D: Trade deficits"],"correctAnswer":"B",
     "explanation":"Hyperinflation follows the Quantity Theory of Money: MV = PY. If money supply (M) increases far faster than real output (Y), price level (P) rises proportionally. Weimar Germany printed money to pay war reparations; Zimbabwe printed money to pay government bills. Prices doubled every few days. The cure requires credible monetary reform — typically introducing a new currency backed by a stable anchor."},
    {"subject":"General Knowledge","grade":10,"difficulty":"Olympiad","topic":"Technology","subTopic":"Blockchain and Crypto",
     "questionText":"Blockchain technology underlies cryptocurrencies like Bitcoin. The key security property of a blockchain is:",
     "options":["A: All transactions are encrypted and stored on a central server","B: Each block contains a cryptographic hash of the previous block — making any alteration of past records detectable and computationally infeasible to change","C: Only verified users can transact","D: Transactions are stored in a single secure database"],"correctAnswer":"B",
     "explanation":"A blockchain is a distributed, append-only ledger. Each block contains: transaction data, a timestamp, and the cryptographic hash of the previous block. Changing any historical block changes its hash, which invalidates all subsequent blocks. To alter history, an attacker would need to redo the 'proof of work' for all subsequent blocks faster than the entire honest network — computationally infeasible (51% attack protection)."},
    {"subject":"General Knowledge","grade":10,"difficulty":"Olympiad","topic":"Indian Constitution","subTopic":"Basic Structure Doctrine",
     "questionText":"The 'Basic Structure Doctrine' of the Indian Constitution was established by the Supreme Court in which landmark case?",
     "options":["A: Golaknath v. State of Punjab (1967)","B: Kesavananda Bharati v. State of Kerala (1973)","C: Maneka Gandhi v. Union of India (1978)","D: Minerva Mills v. Union of India (1980)"],"correctAnswer":"B",
     "explanation":"In Kesavananda Bharati v. State of Kerala (1973), a 13-judge Constitution Bench (the largest ever) ruled 7-6 that Parliament can amend the Constitution but CANNOT alter its 'basic structure' — which includes democracy, secularism, federalism, separation of powers, and fundamental rights. This doctrine protects the Constitution from being converted into a totalitarian document through amendments. It remains the most important constitutional judgment in Indian history."},
    {"subject":"General Knowledge","grade":10,"difficulty":"Olympiad","topic":"Science","subTopic":"Astrophysics",
     "questionText":"The James Webb Space Telescope (JWST), launched in 2021, observes primarily in infrared wavelengths. Why infrared rather than visible light for deep universe observations?",
     "options":["A: Infrared cameras are cheaper to build","B: Light from the most distant galaxies is redshifted into infrared wavelengths due to the expansion of the universe — JWST can see further back in time than Hubble","C: Infrared penetrates through stars","D: Visible light is blocked by Earth's atmosphere"],"correctAnswer":"B",
     "explanation":"The universe is expanding — light from distant galaxies is redshifted (wavelength stretched). The most distant observable galaxies (13+ billion light-years away, whose light was emitted <1 billion years after the Big Bang) have their light redshifted from UV/visible into infrared. JWST's infrared detectors (cooled to -233°C) can detect this light, allowing observation of the first galaxies. Hubble's optical cameras cannot see these early objects."},
    {"subject":"General Knowledge","grade":10,"difficulty":"Olympiad","topic":"Indian History","subTopic":"Partition",
     "questionText":"The Mountbatten Plan (3 June Plan, 1947) led to the partition of India. Which commission drew the boundary between India and Pakistan, leading to massive displacement?",
     "options":["A: Simon Commission","B: Radcliffe Commission, chaired by Sir Cyril Radcliffe","C: Cripps Mission","D: Cabinet Mission"],"correctAnswer":"B",
     "explanation":"Sir Cyril Radcliffe, a British lawyer who had never visited India, was appointed to draw the borders of the two new nations in just 36 days. The 'Radcliffe Line' divided Punjab and Bengal. Radcliffe never visited India before the assignment and left immediately after. The hastily drawn boundaries caused the largest mass migration in history — 10-20 million people displaced, with 200,000–2 million killed in communal violence."},
    {"subject":"General Knowledge","grade":10,"difficulty":"Olympiad","topic":"Science","subTopic":"Climate Science",
     "questionText":"Methane (CH₄) is a much more potent greenhouse gas than CO₂ on a 20-year timescale. Which human activity is the LARGEST source of methane emissions?",
     "options":["A: Coal-fired power plants","B: Livestock (especially cattle) — enteric fermentation produces methane in their digestive systems","C: Automobile exhaust","D: Nuclear power plants"],"correctAnswer":"B",
     "explanation":"Livestock agriculture (enteric fermentation in the digestive systems of ruminants like cattle, sheep, and buffalo) is the largest source of human-caused methane emissions, accounting for about 30% of global methane. Other major sources: landfills, rice paddies, natural gas leaks, coal mines. Methane is ~86 times more potent than CO₂ over 20 years but breaks down faster (~12 years vs CO₂'s centuries)."},
    {"subject":"General Knowledge","grade":10,"difficulty":"Olympiad","topic":"World History","subTopic":"Colonialism",
     "questionText":"The Scramble for Africa (1881-1914) saw European powers colonise almost the entire African continent. By 1914, which were the ONLY two African countries that remained independent?",
     "options":["A: Egypt and Nigeria","B: Ethiopia (Abyssinia) and Liberia","C: South Africa and Kenya","D: Morocco and Tunisia"],"correctAnswer":"B",
     "explanation":"By 1914, Ethiopia (which defeated Italy at the Battle of Adwa in 1896 — a remarkable African victory over a European colonial power) and Liberia (a country founded by freed American slaves in 1847) were the only independent African states. All other African territories were under European colonial control: British, French, German, Belgian, Portuguese, Italian, or Spanish."},
    {"subject":"General Knowledge","grade":10,"difficulty":"Olympiad","topic":"Economics","subTopic":"India's Economic Policy",
     "questionText":"India's National Education Policy (NEP) 2020 replaced the 1986 policy. One major structural change introduced by NEP 2020 is:",
     "options":["A: Abolishing the 10+2 system entirely","B: Replacing 10+2 with a 5+3+3+4 curricular structure aligning with ages 3-8, 8-11, 11-14, and 14-18 years","C: Making higher education compulsory till age 21","D: Separating arts and science streams from Grade 6"],"correctAnswer":"B",
     "explanation":"NEP 2020 restructures schooling from 10+2 to 5+3+3+4: Foundational (5 years, ages 3-8 including pre-primary), Preparatory (3 years, ages 8-11), Middle (3 years, ages 11-14), Secondary (4 years, ages 14-18). This aligns education with child developmental stages. NEP also emphasises mother tongue instruction till Grade 5, multidisciplinary higher education, and coding from Grade 6."},
    {"subject":"General Knowledge","grade":10,"difficulty":"Olympiad","topic":"Science","subTopic":"Nanotechnology",
     "questionText":"Carbon nanotubes (CNTs) have extraordinary tensile strength — about 100 times stronger than steel at 1/6 the weight. This strength arises from:",
     "options":["A: Metal atoms embedded in the tube","B: The seamless hexagonal graphene lattice of C-C covalent bonds rolled into a cylinder — the geometry prevents crack propagation","C: The hollow interior filled with air","D: Radioactive isotopes in the carbon"],"correctAnswer":"B",
     "explanation":"CNTs are essentially rolled graphene sheets. The sp² carbon-carbon bonds in hexagonal graphene are extremely strong (similar to those in diamond). The seamless cylindrical geometry with no grain boundaries or defects means there are no weak points for cracks to propagate. This combination of perfect structure + strong C-C bonds creates extraordinary mechanical properties. Applications: composites, bulletproof materials, space elevator concepts."},
    {"subject":"General Knowledge","grade":10,"difficulty":"Olympiad","topic":"Indian History","subTopic":"Social Reforms",
     "questionText":"Jyotirao Phule founded the Satyashodhak Samaj (1873) in Maharashtra. His primary social reform objective was:",
     "options":["A: Promoting English education among Brahmins","B: Challenging Brahmin dominance and the caste system — working for education and rights of lower castes, women, and untouchables","C: Reviving Vedic rituals","D: Promoting Hindu-Muslim unity"],"correctAnswer":"B",
     "explanation":"Jyotirao Phule was a pioneering social reformer who challenged Brahminical hegemony and the caste hierarchy at a time when few dared. He opened schools for girls and lower-caste children in 1848, challenged child marriage, opposed the oppression of women and 'untouchables', and wrote 'Gulamgiri' (1873) comparing caste oppression to slavery. He was a forerunner of Dr. B.R. Ambedkar's anti-caste movement."},
    {"subject":"General Knowledge","grade":10,"difficulty":"Olympiad","topic":"Technology","subTopic":"Semiconductors",
     "questionText":"India is setting up semiconductor fabrication plants. The most advanced chips (e.g., 3nm, 2nm) are produced using extreme ultraviolet lithography (EUV). EUV uses light of wavelength ~13.5 nm. Why does smaller wavelength allow smaller transistors?",
     "options":["A: Smaller wavelength light is brighter","B: Resolution in lithography is limited by diffraction — smaller wavelength light can resolve smaller features, allowing more transistors per chip","C: EUV light is cooler than regular UV","D: Smaller wavelength means faster chip speed directly"],"correctAnswer":"B",
     "explanation":"Lithography in chip manufacturing uses light to pattern circuits onto silicon wafers. The minimum feature size is limited by diffraction — roughly equal to the wavelength of light used. Standard UV (193nm) can pattern features down to ~7nm with multi-patterning tricks. EUV (13.5nm) allows direct patterning of features below 5nm. Smaller transistors → more transistors per chip → more processing power per unit area (Moore's Law)."},
]

# ── ENGLISH G10 OLYMPIAD (15q) ────────────────────────────────
ENG10_OLY = [
    {"subject":"English","grade":10,"difficulty":"Olympiad","topic":"First Flight — Prose","subTopic":"A Letter to God",
     "questionText":"In 'A Letter to God' by G.L. Fuentes, Lencho addresses his letter to God. When the post office employees read the letter, one of them laughs but the postmaster is moved. What does the postmaster's reaction reveal about him compared to the others?",
     "options":["A: He is gullible and believes Lencho literally","B: He has genuine empathy and faith — he understands the profound innocence of Lencho's trust and wants to preserve it","C: He plans to steal the money","D: He considers Lencho's faith foolish"],"correctAnswer":"B",
     "explanation":"The postmaster's emotional reaction distinguishes him from colleagues who merely laugh. He is moved by Lencho's absolute, unshakeable faith in God. Rather than dismissing it, he organises a collection to maintain Lencho's belief. This reveals the postmaster's deep humanity, empathy, and respect for sincere faith — the story explores whether such faith is naive or noble."},
    {"subject":"English","grade":10,"difficulty":"Olympiad","topic":"First Flight — Poetry","subTopic":"Fire and Ice by Robert Frost",
     "questionText":"In Robert Frost's poem 'Fire and Ice', fire represents desire and ice represents hatred. The poet says either could destroy the world. The deeper philosophical message of the poem is:",
     "options":["A: Climate change will destroy Earth through fire","B: Human vices — unchecked desire and cold hatred — are equally capable of bringing about the destruction of human civilisation","C: Fire is more dangerous than ice","D: The poem is only about the physical elements"],"correctAnswer":"B",
     "explanation":"Frost uses fire and ice as metaphors for human passions and failings. 'Fire' (desire/greed/lust) is familiar to the poet — 'I hold with those who favour fire'. 'Ice' (hatred/indifference) would also suffice. The poem is a compressed meditation on how human extremes of passion and cold indifference are existential threats to civilisation — remarkably prescient, as Frost wrote it in 1920."},
    {"subject":"English","grade":10,"difficulty":"Olympiad","topic":"First Flight — Prose","subTopic":"Two Stories About Flying",
     "questionText":"In 'Two Stories About Flying', the seagull's fear of flying is overcome only when he is driven by hunger to attempt flight. The author uses this to suggest:",
     "options":["A: Seagulls are timid birds","B: Necessity and hunger are powerful motivators that overcome fear — courage often comes not from confidence but from circumstances that force action","C: Flying is always dangerous for young birds","D: The seagull was poorly trained by its parents"],"correctAnswer":"B",
     "explanation":"The young seagull's long ledge-paralysis despite encouragement ends only when he desperately lunges for his mother's fish and finds himself airborne. Liam O'Flaherty uses this to make a universal statement: often we don't discover our capabilities until circumstances demand it. Fear is paralysing; necessity is liberating. The theme resonates with human experience of stepping beyond comfort zones."},
    {"subject":"English","grade":10,"difficulty":"Olympiad","topic":"First Flight — Prose","subTopic":"From the Diary of Anne Frank",
     "questionText":"Anne Frank writes to her diary, which she names 'Kitty', saying: 'Paper has more patience than people.' What does this statement reveal about Anne's situation?",
     "options":["A: She was learning to write","B: She could not express her true feelings to anyone around her — the diary became the only place where she could be completely honest and vulnerable without fear of judgment","C: She preferred writing to talking","D: Paper is more durable than human memory"],"correctAnswer":"B",
     "explanation":"Anne's observation is profound — in a crowded Secret Annex under Nazi occupation, surrounded by stressed adults and strained relationships, she could not freely express her inner life. The diary 'Kitty' became her only confidant — never impatient, never judgmental, never tired of her. This quote captures the deep loneliness of adolescence compounded by extraordinary historical circumstances."},
    {"subject":"English","grade":10,"difficulty":"Olympiad","topic":"First Flight — Poetry","subTopic":"The Ball Poem by John Berryman",
     "questionText":"In 'The Ball Poem', the boy loses his ball and cries. The poet watches but decides NOT to offer money to buy a new ball. Why does the poet NOT intervene?",
     "options":["A: The poet has no money","B: The poet understands the boy must learn that some losses are irreplaceable and accepting loss is a necessary part of growing up — you cannot buy back what is truly gone","C: The poet thinks the boy is overreacting","D: The poet does not care about the boy"],"correctAnswer":"B",
     "explanation":"The poet's restraint is deliberate — 'I would not intrude on him; / A dime, another ball, is worthless.' The ball symbolises something irretrievably lost: childhood innocence, a particular time, a relationship. The boy must learn 'the epistemology of loss' — the world will not always give back what is taken. This lesson is part of maturation. The poem is about initiation into adult grief, not about a ball."},
    {"subject":"English","grade":10,"difficulty":"Olympiad","topic":"First Flight — Prose","subTopic":"Glimpses of India",
     "questionText":"In 'Coorg' (from 'Glimpses of India'), the author describes Coorg as 'a piece of heaven that must have drifted from the coast'. What literary device is used, and what quality of Coorg does it convey?",
     "options":["A: Simile — comparing Coorg to a boat","B: Metaphor/hyperbole — the phrase is a metaphorical exaggeration conveying that Coorg is so breathtakingly beautiful it seems otherworldly, as if it belongs to paradise rather than Earth","C: Personification — treating Coorg as a person","D: Alliteration — repeated 'C' sounds"],"correctAnswer":"B",
     "explanation":"The phrase uses metaphor combined with hyperbole (poetic exaggeration). It doesn't use 'like/as' (so not simile). The image of 'drifting from the coast' gives Coorg an ethereal, floating quality — suggesting its natural beauty is so extraordinary that it seems to belong to another realm. The author, Lokesh Abrol, uses this to evoke a sense of wonder and enchantment about Coorg's landscape."},
    {"subject":"English","grade":10,"difficulty":"Olympiad","topic":"First Flight — Poetry","subTopic":"Amanda by Robin Klein",
     "questionText":"In the poem 'Amanda', the speaker constantly corrects Amanda's behaviour while Amanda imagines herself as Rapunzel, a mermaid, and an orphan. The irony in Amanda's wish to be Rapunzel is:",
     "options":["A: Rapunzel is also imprisoned in a tower — Amanda imagines freedom but chooses an image of confinement","B: Rapunzel has beautiful hair","C: Rapunzel is fictional","D: Rapunzel eventually escapes"],"correctAnswer":"A",
     "explanation":"This is a striking dramatic irony: Amanda, seeking freedom from nagging, fantasises about being Rapunzel — who was imprisoned in a tower. She even says she would never let down her hair (never let anyone rescue her — preferring solitary peace to the chaos of human interaction). Amanda's ideal of freedom is defined by absence of people — even her escape fantasies reflect a desire for isolation rather than genuine liberation."},
    {"subject":"English","grade":10,"difficulty":"Olympiad","topic":"Footprints Without Feet","subTopic":"The Midnight Visitor",
     "questionText":"In 'The Midnight Visitor', Ausable, a secret agent, outwits the armed Fowler by inventing a 'balcony' outside the window that doesn't exist. The story's central theme is:",
     "options":["A: The importance of physical strength in espionage","B: Intelligence and quick thinking are more powerful weapons than physical force — wit defeats weapons","C: Never trust strangers","D: The dangers of being a spy"],"correctAnswer":"B",
     "explanation":"Ausable is not the stereotypical rugged secret agent — he is overweight and unromantic. Yet he defeats an armed intruder purely through improvised deception. The story subverts thriller conventions to argue that sharp intellect — the ability to construct and deliver a convincing lie under pressure — is the most valuable quality in intelligence work. Fowler, who came expecting glamour, learns the same lesson."},
    {"subject":"English","grade":10,"difficulty":"Olympiad","topic":"Footprints Without Feet","subTopic":"The Making of a Scientist",
     "questionText":"In 'The Making of a Scientist', Richard Ebright's success came from his combination of three qualities that the author explicitly identifies. What were they?",
     "options":["A: Intelligence, memory, and hard work","B: A first-rate mind, curiosity, and the will to win for the right reasons (not for trophies but for understanding)","C: Luck, family support, and good teachers","D: Scientific equipment, funding, and talent"],"correctAnswer":"B",
     "explanation":"The author states Ebright's success required: '...a first-rate mind, curiosity, and the will to win for the right reasons.' Crucially, the 'right reasons' meant winning to understand — curiosity driving achievement, not ego or competitive glory. Ebright's story, from butterfly collecting to discovering how cells read DNA, illustrates how genuine curiosity sustained by a competitive spirit (directed toward understanding) produces scientific breakthroughs."},
    {"subject":"English","grade":10,"difficulty":"Olympiad","topic":"Grammar","subTopic":"Reported Speech",
     "questionText":"Convert to indirect speech: She said, 'I have been waiting here for two hours.'",
     "options":["A: She said that she has been waiting there for two hours.","B: She said that she had been waiting there for two hours.","C: She said that she was waiting there for two hours.","D: She said that I have been waiting here for two hours."],"correctAnswer":"B",
     "explanation":"Reporting verb 'said' is past tense → back-shift all tenses. Present perfect continuous ('have been waiting') shifts to past perfect continuous ('had been waiting'). 'Here' changes to 'there'. 'I' changes to 'she'. The time reference 'for two hours' stays unchanged as it is not specific to the moment of speech."},
    {"subject":"English","grade":10,"difficulty":"Olympiad","topic":"Grammar","subTopic":"Sentence Transformation — Voice",
     "questionText":"The passive voice transformation of 'Someone has stolen my bicycle' is:",
     "options":["A: My bicycle was stolen by someone.","B: My bicycle has been stolen.","C: My bicycle had been stolen.","D: My bicycle is being stolen."],"correctAnswer":"B",
     "explanation":"'Someone has stolen my bicycle' (active, present perfect) → passive: 'My bicycle has been stolen.' The agent ('by someone') is omitted as it is non-specific (this is standard when the agent is unknown or unimportant). Passive present perfect: has/have + been + past participle."},
    {"subject":"English","grade":10,"difficulty":"Olympiad","topic":"Writing Skills","subTopic":"Formal Letter Writing",
     "questionText":"You are writing a formal complaint letter to the Principal about inadequate library facilities. Which of the following opening lines is MOST appropriate?",
     "options":["A: 'I am writing to tell you your library is very bad.'","B: 'Through this letter, I wish to bring to your kind attention the inadequate library facilities in our school, which are adversely affecting students' academic performance.'","C: 'Hello Sir/Ma'am, the library is a real problem for us students.'","D: 'Please fix the library.'"],"correctAnswer":"B",
     "explanation":"A formal complaint letter requires: (1) formal tone (no colloquialisms), (2) specific identification of the issue, (3) indication of impact, (4) respectful but assertive language. Option B correctly uses formal vocabulary ('bring to your kind attention', 'adversely affecting'), identifies the problem precisely, and connects it to academic impact — providing a clear basis for action."},
    {"subject":"English","grade":10,"difficulty":"Olympiad","topic":"First Flight — Poetry","subTopic":"For Anne Gregory by W.B. Yeats",
     "questionText":"In Yeats' poem 'For Anne Gregory', a young woman is told that men only love her for her yellow hair (external beauty), not her soul. She replies she could change her hair colour. Yeats' response is:",
     "options":["A: That would make her unattractive","B: Only God can love humans for their inner self (soul) alone — no human lover is capable of transcending physical appearance to love the inner being","C: Changing hair colour is dishonest","D: Men will still love her for other physical features"],"correctAnswer":"B",
     "explanation":"The poem concludes: 'But I can get a hair-dye / And set such colour there... / Yet never have I heard / Of any young man praised / His leman for herself.' Only God ('He') can love the soul stripped of physical attributes. Yeats explores the melancholy gap between ideal love (of the soul) and human love (conditional on physical beauty) — a Platonic theme wrapped in elegant dialogue."},
    {"subject":"English","grade":10,"difficulty":"Olympiad","topic":"Vocabulary","subTopic":"Word Roots and Derivatives",
     "questionText":"The word 'magnanimous' comes from Latin 'magnus' (great) + 'animus' (spirit/soul). Which sentence uses 'magnanimous' CORRECTLY?",
     "options":["A: The magnanimous earthquake destroyed the city.","B: She was magnanimous in victory — congratulating her opponent warmly and giving credit for a close contest.","C: He had a magnanimous fear of heights.","D: The magnanimous rain fell all night."],"correctAnswer":"B",
     "explanation":"Magnanimous means 'generous in forgiving, not petty, noble in spirit — especially when winning or in a position of power.' It describes someone who is 'great-souled' — able to rise above pettiness in success. It applies to people, actions, or gestures, not to physical events like earthquakes or rain."},
    {"subject":"English","grade":10,"difficulty":"Olympiad","topic":"First Flight — Prose","subTopic":"The Sermon at Benares",
     "questionText":"In 'The Sermon at Benares', the Buddha gives Kisa Gotami a lesson through her own experience (she must find mustard seed from a house untouched by death — and cannot). This teaching method is an example of:",
     "options":["A: Direct instruction","B: Socratic method — guided discovery where the student learns truth through personal experience rather than being told","C: Punishment","D: Avoidance"],"correctAnswer":"B",
     "explanation":"The Buddha does not tell Kisa Gotami 'your son cannot be revived' — he sends her on a quest that herself demonstrates the universality of death. By the time she completes the impossible task, she has discovered the truth experientially. This is the Socratic method: knowledge gained through guided personal experience is deeper and more transformative than knowledge told. The lesson 'death is universal' becomes visceral, not theoretical."},
]

# ── CS G6 FOUNDATION (15q) ────────────────────────────────
CS6_FOUND = [
    {"subject":"Computer Science","grade":6,"difficulty":"Foundation","topic":"Basics of Computer","subTopic":"Definition and Types of Computers",
     "questionText":"A computer is an electronic device that can:",
     "options":["A: Only store data","B: Only display information","C: Accept input, process it, and produce output","D: Only perform calculations"],"correctAnswer":"C",
     "explanation":"A computer is an electronic device that accepts input data, processes it according to instructions (a program), and produces output. It can also store data for later use. The basic cycle is: Input → Process → Output → Storage."},
    {"subject":"Computer Science","grade":6,"difficulty":"Foundation","topic":"Basics of Computer","subTopic":"Hardware and Software",
     "questionText":"Which of the following is an example of SOFTWARE?",
     "options":["A: Keyboard","B: Monitor","C: Microsoft Word","D: Hard disk"],"correctAnswer":"C",
     "explanation":"Software is a set of instructions (programs) that tells the computer what to do. Microsoft Word is application software. Keyboard, monitor, and hard disk are hardware — the physical parts of the computer you can touch."},
    {"subject":"Computer Science","grade":6,"difficulty":"Foundation","topic":"Input and Output Devices","subTopic":"Input Devices",
     "questionText":"Which of the following is an INPUT device?",
     "options":["A: Printer","B: Speaker","C: Mouse","D: Monitor"],"correctAnswer":"C",
     "explanation":"A mouse is an input device — it sends data/commands to the computer. Printer and speaker are output devices (produce output from the computer). A monitor is also an output device (displays results)."},
    {"subject":"Computer Science","grade":6,"difficulty":"Foundation","topic":"Input and Output Devices","subTopic":"Output Devices",
     "questionText":"Which output device would you use to get a printed copy of a document?",
     "options":["A: Scanner","B: Printer","C: Webcam","D: Microphone"],"correctAnswer":"B",
     "explanation":"A printer is an output device that produces a physical (printed) copy of digital documents or images. A scanner converts physical documents to digital form (input). A webcam and microphone are input devices."},
    {"subject":"Computer Science","grade":6,"difficulty":"Foundation","topic":"Memory and Storage","subTopic":"RAM and ROM",
     "questionText":"RAM (Random Access Memory) is called 'volatile memory' because:",
     "options":["A: It explodes when overloaded","B: It stores data permanently","C: Its contents are lost when the computer is switched off","D: It is used to start the computer"],"correctAnswer":"C",
     "explanation":"RAM is volatile — it temporarily stores data and programs that the CPU is currently using. When the computer is turned off, all data in RAM is erased. This is why we save files to the hard disk (non-volatile storage) before shutting down."},
    {"subject":"Computer Science","grade":6,"difficulty":"Foundation","topic":"Memory and Storage","subTopic":"Storage Devices",
     "questionText":"Which storage device can hold the LARGEST amount of data?",
     "options":["A: Floppy disk (1.44 MB)","B: CD-ROM (700 MB)","C: USB pen drive (up to 256 GB+)","D: Hard disk drive (up to several TB)"],"correctAnswer":"D",
     "explanation":"A Hard Disk Drive (HDD) can store terabytes (TB) of data — the most of the options listed. 1 TB = 1,000 GB. Modern hard disks for computers hold 1-8 TB or more. SSDs (solid state drives) are even faster though similar or slightly smaller capacity at consumer level."},
    {"subject":"Computer Science","grade":6,"difficulty":"Foundation","topic":"Operating System","subTopic":"Functions of OS",
     "questionText":"An Operating System (OS) like Windows or Linux is which type of software?",
     "options":["A: Application software","B: System software","C: Utility software","D: Programming software"],"correctAnswer":"B",
     "explanation":"An Operating System is system software — the master program that manages all hardware and software resources of a computer. It acts as an interface between the user and hardware. Examples: Windows, macOS, Linux, Android. Application software (like games, browsers) runs on top of the OS."},
    {"subject":"Computer Science","grade":6,"difficulty":"Foundation","topic":"Internet Basics","subTopic":"Internet and WWW",
     "questionText":"What does 'https' at the beginning of a website address indicate?",
     "options":["A: The website is for HTTP (basic) protocol only","B: The website uses a secure, encrypted connection (HyperText Transfer Protocol Secure)","C: The website is hosted in Switzerland","D: The website contains hyperlinks"],"correctAnswer":"B",
     "explanation":"HTTPS (HyperText Transfer Protocol Secure) means the connection between your browser and the website is encrypted using SSL/TLS. Your data (passwords, payment info) cannot be easily intercepted. The padlock icon in the browser address bar indicates HTTPS. HTTP (without 'S') is unsecured."},
    {"subject":"Computer Science","grade":6,"difficulty":"Foundation","topic":"Internet Basics","subTopic":"Email",
     "questionText":"Which part of an email address uniquely identifies the domain (organisation or service) of the recipient?",
     "options":["A: The part before the @ symbol","B: The part after the @ symbol","C: The subject line","D: The CC field"],"correctAnswer":"B",
     "explanation":"In an email address like 'student@school.com': 'student' is the username (identifies the specific person); '@school.com' is the domain (identifies the email service/organisation). The @ symbol separates them. Mail servers use the domain to route emails to the correct mail server."},
    {"subject":"Computer Science","grade":6,"difficulty":"Foundation","topic":"Programming Basics","subTopic":"Introduction to Python",
     "questionText":"What will the following Python code output?\n\nprint('Hello' + ' ' + 'World')",
     "options":["A: Hello World","B: 'Hello' + ' ' + 'World'","C: HelloWorld","D: Error"],"correctAnswer":"A",
     "explanation":"The + operator in Python concatenates (joins) strings. 'Hello' + ' ' + 'World' = 'Hello World'. The print() function then displays: Hello World. Note: unlike numbers where + means addition, with strings + means concatenation."},
    {"subject":"Computer Science","grade":6,"difficulty":"Foundation","topic":"Programming Basics","subTopic":"Variables",
     "questionText":"In Python, what is stored in the variable 'x' after this line runs?\n\nx = 5 + 3",
     "options":["A: '5 + 3' (a string)","B: 8","C: 53","D: x"],"correctAnswer":"B",
     "explanation":"Python evaluates the expression on the right side first: 5 + 3 = 8. Then it assigns the result (8) to the variable x. So x stores the integer value 8. To store '5 + 3' as a string, you would write x = '5 + 3' (with quotes)."},
    {"subject":"Computer Science","grade":6,"difficulty":"Foundation","topic":"Programming Basics","subTopic":"Loops",
     "questionText":"How many times will 'Hello' be printed by this Python code?\n\nfor i in range(3):\n    print('Hello')",
     "options":["A: 1 time","B: 2 times","C: 3 times","D: 4 times"],"correctAnswer":"C",
     "explanation":"range(3) generates the values 0, 1, 2 — three values. The loop runs once for each value (i=0, then i=1, then i=2), printing 'Hello' each time. Total: 3 times. range(n) always generates n numbers starting from 0."},
    {"subject":"Computer Science","grade":6,"difficulty":"Foundation","topic":"Spreadsheet","subTopic":"Formulas in Spreadsheet",
     "questionText":"In a spreadsheet, which formula correctly calculates the SUM of values in cells A1 through A5?",
     "options":["A: =ADD(A1:A5)","B: =SUM(A1:A5)","C: =TOTAL(A1,A5)","D: =A1+A2+A3+A4+A5 only"],"correctAnswer":"B",
     "explanation":"=SUM(A1:A5) is the standard formula to add all values from cell A1 to A5 in spreadsheet software (Excel, Google Sheets). The colon (:) indicates a range of cells. While =A1+A2+A3+A4+A5 would also work, SUM() is more efficient, especially for large ranges."},
    {"subject":"Computer Science","grade":6,"difficulty":"Foundation","topic":"Internet Safety","subTopic":"Password Security",
     "questionText":"Which of the following is the STRONGEST password?",
     "options":["A: password123","B: John2010","C: Tr!9#mK@2z","D: iloveschool"],"correctAnswer":"C",
     "explanation":"A strong password: (1) is long (8+ characters), (2) mixes uppercase and lowercase letters, (3) includes numbers, (4) includes special characters (!@#$%^&*), (5) is not a dictionary word or personal info. 'Tr!9#mK@2z' satisfies all criteria. 'password123' and 'iloveschool' are common and easily guessed; 'John2010' uses personal information."},
    {"subject":"Computer Science","grade":6,"difficulty":"Foundation","topic":"Basics of Computer","subTopic":"Number Systems",
     "questionText":"Computers use binary (base-2) number system internally. What is the decimal value of binary 1010?",
     "options":["A: 5","B: 8","C: 10","D: 12"],"correctAnswer":"C",
     "explanation":"Binary 1010 = (1×2³) + (0×2²) + (1×2¹) + (0×2⁰) = 8 + 0 + 2 + 0 = 10. Each binary digit (bit) represents a power of 2, starting from 2⁰ on the right. Binary is used because computer circuits have two states: on (1) and off (0)."},
]

ALL_BATCHES = [
    ("GK G10 Foundation", GK10_FOUND),
    ("GK G10 Advanced", GK10_ADV),
    ("GK G10 Olympiad", GK10_OLY),
    ("English G10 Olympiad", ENG10_OLY),
    ("CS G6 Foundation", CS6_FOUND),
]

conn = pyodbc.connect(DB_CONN)
total = ok = dup = err = 0

for batch_name, questions in ALL_BATCHES:
    for q in questions:
        total += 1
        try:
            r = insert(conn, q)
            if r == "OK":
                ok += 1
                print(f"  OK Q{total:03d} [{q['subject']} G{q['grade']} {q['difficulty']}] {q['subTopic']}")
            else:
                dup += 1
                print(f"  DUP Q{total:03d} [{q['subject']} G{q['grade']} {q['difficulty']}] {q['subTopic']}")
        except Exception as e:
            err += 1
            print(f"  FAIL Q{total:03d} [{q['subject']} G{q['grade']} {q['difficulty']}] {q['subTopic']}: {e}")

conn.close()
print(f"\n  Done: {ok} posted, {dup} duplicates, {err} errors  (total={total})\n")
