"""
Social Studies Gr6, Gr7, Gr9 — Advanced + Olympiad top-up
Target: 15 questions per slot (SS Gr6 Adv/Oly, Gr7 Adv/Oly, Gr9 Adv/Oly)
Direct DB insert.
"""
import sys, uuid, json, time, pyodbc
sys.stdout.reconfigure(encoding="utf-8")

DB_CONN = ("DRIVER={ODBC Driver 18 for SQL Server};"
           "SERVER=tcp:olympiadready-np.database.windows.net,1433;"
           "DATABASE=OlympiadReady;UID=nyxen-admin;PWD=Olympiad@2026;"
           "Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30")

def insert(conn, q):
    c = conn.cursor()
    c.execute("SELECT 1 FROM QuestionBank WHERE Subject=? AND Grade=? AND SubTopic=? AND QuestionText=?",
              q["subject"], q["grade"], q["subTopic"], q["questionText"])
    if c.fetchone():
        return "DUP"
    c.execute("""INSERT INTO QuestionBank
                 (QuestionBankId,Subject,Grade,Difficulty,Topic,SubTopic,
                  QuestionText,OptionsJson,CorrectAnswer,Explanation,CreatedAt)
                 VALUES (?,?,?,?,?,?,?,?,?,?,GETUTCDATE())""",
              str(uuid.uuid4()).upper(), q["subject"], q["grade"], q["difficulty"],
              q["topic"], q["subTopic"], q["questionText"],
              json.dumps(q["options"]), q["correctAnswer"], q["explanation"])
    conn.commit()
    return "OK"

# ═══════════════════════════════════════════════════════════════════════════
# SOCIAL STUDIES GR 6
# ═══════════════════════════════════════════════════════════════════════════
SST6_ADV = [
  # History
  dict(topic="History",subTopic="Indus Valley Civilisation",
       questionText="Which of the following best explains why historians believe the Indus Valley Civilisation had a planned urban layout?",
       options=["A: Discovery of iron tools in each home","B: Grid-pattern streets, covered drains, and standardised brick sizes",
                "C: Large temples at the centre of every city","D: Written records describing city blueprints"],
       correct="B",
       explanation="Excavations at Harappa and Mohenjo-daro reveal streets laid at right angles, an advanced underground drainage system, and bricks made to a uniform 1:2:4 ratio — clear evidence of deliberate urban planning."),
  dict(topic="History",subTopic="Vedic Period",
       questionText="The term 'jana' in the Rigveda refers to which of the following?",
       options=["A: A sacred fire ritual","B: A people or tribe","C: A unit of land measurement","D: A priestly clan"],
       correct="B",
       explanation="'Jana' in Vedic Sanskrit means 'people' or 'tribe'. The Rigveda frequently mentions clashes between different janas, indicating that early Vedic society was organised around tribal identities."),
  dict(topic="History",subTopic="Mahajanapadas",
       questionText="Which of the 16 Mahajanapadas was unusual because it was a 'gana-sangha' (oligarchic republic) rather than a monarchy?",
       options=["A: Magadha","B: Kosala","C: Vajji","D: Avanti"],
       correct="C",
       explanation="Vajji (centred on Vaishali) was a confederacy of clans, notably the Lichchhavis, governed by an assembly of elected representatives — making it one of the earliest known republics in the world."),
  dict(topic="History",subTopic="Ashoka and the Mauryas",
       questionText="Ashoka's Dhamma was primarily intended to achieve which goal?",
       options=["A: Spread Buddhism as the only state religion","B: Promote moral conduct and social harmony across all communities",
                "C: Establish a uniform tax code across the empire","D: Build a standing army loyal to Buddhist monks"],
       correct="B",
       explanation="Ashoka's Dhamma was not strictly Buddhism. It emphasised respect for elders, kindness to slaves and servants, tolerance of all religions, and non-violence — a universal ethical code meant to unite a diverse empire."),
  dict(topic="History",subTopic="New Questions and Ideas",
       questionText="Why did heterodox movements like Buddhism and Jainism gain widespread support around 600 BCE?",
       options=["A: They promised military conquest and political power","B: They challenged Vedic ritual dominance and offered salvation to all regardless of birth",
                "C: They were officially endorsed by all Mahajanapada kings","D: They introduced new agricultural techniques"],
       correct="B",
       explanation="The rise of Buddhism and Jainism was a reaction to the expensive Vedic yajnas monopolised by Brahmins. Both movements rejected caste hierarchy, taught that moksha/nirvana was accessible to everyone, and used Prakrit (the common people's language) rather than Sanskrit."),
  # Geography
  dict(topic="Geography",subTopic="Globe and Maps",
       questionText="On a map drawn at a scale of 1:50,000, what does a distance of 4 cm represent on the actual ground?",
       options=["A: 200 m","B: 2 km","C: 20 km","D: 200 km"],
       correct="B",
       explanation="Scale 1:50,000 means 1 cm on map = 50,000 cm = 500 m on ground. So 4 cm = 4 × 500 m = 2,000 m = 2 km."),
  dict(topic="Geography",subTopic="Motions of the Earth",
       questionText="The Antarctic Circle experiences at least one complete day of midnight sun each year. What is the latitude of the Antarctic Circle?",
       options=["A: 23.5°S","B: 66.5°S","C: 90°S","D: 45°S"],
       correct="B",
       explanation="The Antarctic Circle is at approximately 66.5°S (90°−23.5°). On the December solstice, the sun remains above the horizon for a full 24 hours at and south of this line."),
  dict(topic="Geography",subTopic="Major Domains of the Earth",
       questionText="Which of Earth's spheres includes all living organisms?",
       options=["A: Hydrosphere","B: Lithosphere","C: Biosphere","D: Atmosphere"],
       correct="C",
       explanation="The biosphere is the global ecological system integrating all living beings (plants, animals, microorganisms) and their interactions with the atmosphere, hydrosphere, and lithosphere."),
  dict(topic="Geography",subTopic="India Physical Features",
       questionText="The Western Ghats receive heavy rainfall on their western slopes but the eastern slopes remain comparatively dry. This phenomenon is called:",
       options=["A: Continentality","B: Rain shadow effect","C: Orographic precipitation reversal","D: Monsoon channelling"],
       correct="B",
       explanation="When moisture-laden winds rise over the Western Ghats, they cool, condense, and precipitate heavily on the windward (western) side. Having lost most moisture, the winds descend dry on the leeward (eastern) side — creating a rain shadow region."),
  dict(topic="Geography",subTopic="Our Country India",
       questionText="India shares its longest international land boundary with which country?",
       options=["A: China","B: Pakistan","C: Bangladesh","D: Nepal"],
       correct="C",
       explanation="India's longest land border is with Bangladesh — approximately 4,156 km. This border runs through West Bengal, Assam, Meghalaya, Tripura, and Mizoram."),
  # Civics
  dict(topic="Civics",subTopic="Panchayati Raj",
       questionText="Under the 73rd Constitutional Amendment (1992), what minimum percentage of seats must be reserved for women in Panchayati Raj institutions?",
       options=["A: 10%","B: 25%","C: 33%","D: 50%"],
       correct="C",
       explanation="The 73rd Amendment mandates at least one-third (33%) reservation of seats for women in all Panchayati Raj institutions. Several states like Rajasthan and Bihar have extended this to 50%."),
  dict(topic="Civics",subTopic="Rural Administration",
       questionText="A 'patwari' in rural India primarily performs which function?",
       options=["A: Collects income tax","B: Maintains land records and measures land","C: Conducts elections at the village level","D: Administers the village court"],
       correct="B",
       explanation="A patwari (also called lekhpal or kanungo in different states) is a village-level revenue official responsible for maintaining land records, maps, and ownership details — critical for land disputes and agricultural planning."),
  dict(topic="Civics",subTopic="Urban Administration",
       questionText="Which body is responsible for the administration of a large city in India?",
       options=["A: Gram Panchayat","B: Taluka Panchayat","C: Municipal Corporation","D: District Collector's Office"],
       correct="C",
       explanation="Large cities in India are governed by Municipal Corporations (e.g., BBMP in Bengaluru, BMC in Mumbai). They are responsible for civic amenities — water, roads, waste management, and building regulations."),
  dict(topic="Civics",subTopic="Democracy",
       questionText="In a representative democracy, citizens exercise power primarily through:",
       options=["A: Direct voting on every law","B: Elected representatives who make decisions on their behalf",
                "C: Military commanders who enforce the constitution","D: Hereditary rulers bound by a constitution"],
       correct="B",
       explanation="Representative democracy means citizens elect representatives (MPs, MLAs, councillors) who then legislate and govern on their behalf. This contrasts with direct democracy where citizens vote on each issue directly."),
  dict(topic="Civics",subTopic="Key Elements of a Democratic Government",
       questionText="Which of the following is NOT a feature of a democratic government?",
       options=["A: Free and fair elections","B: Protection of minority rights",
                "C: Rule of law","D: Concentration of power in a single leader for life"],
       correct="D",
       explanation="Democracy requires power-sharing, periodic elections, rule of law, and protection of all citizens. Concentration of power in a single leader for life is a feature of authoritarianism or dictatorship, not democracy."),
]

SST6_OLY = [
  dict(topic="History",subTopic="Indus Valley Civilisation",
       questionText="Archaeologists have found no evidence of large palaces or royal burials at Indus Valley sites. What does this suggest about the political organisation of the civilisation?",
       options=["A: The civilisation had no rulers — it was entirely egalitarian",
                "B: Power may have been held by a priestly or merchant elite rather than warrior kings",
                "C: Rulers lived in separate, undiscovered cities","D: All political records were inscribed on perishable materials and have not survived"],
       correct="B",
       explanation="The absence of war-related art, large royal tombs (like those in Egypt or Mesopotamia), and heavily fortified palaces suggests Indus rulers — if they existed — may have derived authority from religious or commercial control rather than military conquest. This remains a key debate in archaeology."),
  dict(topic="History",subTopic="Vedic Period",
       questionText="The 'gotra' system in Vedic society served which primary social function?",
       options=["A: Determining tax obligations to the king","B: Regulating marriage by prohibiting unions within the same clan-lineage",
                "C: Assigning occupations to male members","D: Organising military units for the king's army"],
       correct="B",
       explanation="Gotra (literally 'cow-pen', indicating a common ancestor) was used to trace patrilineal descent. Marriage within the same gotra was strictly prohibited (considered akin to incest) — this exogamy rule helped build alliances across clans and prevented inbreeding."),
  dict(topic="History",subTopic="Ashoka and the Mauryas",
       questionText="Ashoka's rock edicts are found as far west as Kandahar (modern Afghanistan) and as far south as Andhra Pradesh. What does this geographic spread most directly indicate?",
       options=["A: The Mauryan Empire was the largest empire in history",
                "B: The Mauryan Empire at its peak controlled a vast territory spanning the Indian subcontinent",
                "C: Ashoka personally visited every location where an edict was placed",
                "D: The Mauryan script was universally understood across all these regions"],
       correct="B",
       explanation="The distribution of Ashokan inscriptions across present-day Afghanistan, Pakistan, India, and Nepal shows the enormous territorial extent of the Mauryan Empire — one of the largest in ancient history. The edicts were also written in local scripts (Kharoshthi in the northwest, Greek and Aramaic in Kandahar) showing administrative sophistication."),
  dict(topic="History",subTopic="Mahajanapadas",
       questionText="Magadha became the most powerful Mahajanapada eventually leading to the Mauryan Empire. Which combination of factors best explains Magadha's rise?",
       options=["A: Large population of Brahmin scholars and proximity to the Himalayas",
                "B: Iron ore deposits in Chota Nagpur, fertile Gangetic plains, and control of river trade routes",
                "C: Alliance with Alexander the Great's forces","D: Discovery of gold mines and diplomatic marriages with all other Mahajanapadas"],
       correct="B",
       explanation="Magadha's dominance stemmed from multiple advantages: proximity to iron ore (enabling superior weapons and tools), extremely fertile alluvial plains supporting a large population, and strategic location on the Ganga enabling trade control and easy military movement."),
  dict(topic="History",subTopic="Buildings Paintings and Books",
       questionText="The Ajanta cave paintings, which depict the Jataka tales, are significant primarily because they:",
       options=["A: Are the oldest known examples of writing in India",
                "B: Represent the only surviving examples of ancient Indian sculpture",
                "C: Preserve sophisticated visual narratives using natural pigments on rock, showcasing both artistic mastery and Buddhist religious content",
                "D: Were painted by Greek artists who accompanied Alexander"],
       correct="C",
       explanation="The Ajanta murals (2nd century BCE–6th century CE) are among the finest surviving examples of ancient Indian painting. Created using mineral pigments on dry and wet plaster, they narrate Jataka stories (tales of Buddha's previous lives) with remarkable emotion, perspective, and attention to social detail."),
  dict(topic="Geography",subTopic="Globe and Maps",
       questionText="A ship sails due east from 75°W longitude and travels through 180° of longitude. At what longitude does it arrive, and has it crossed the International Date Line?",
       options=["A: 105°E; yes, it crossed the Date Line","B: 75°E; no Date Line crossed",
                "C: 180°; it is exactly on the Date Line","D: 105°E; no, the Date Line is at 90°W"],
       correct="A",
       explanation="Starting at 75°W and moving 180° east: 75°W + 180° = 105°E (subtracting 360° is not needed as 75+180=255, but thinking eastward: 180°-75° = 105°E). The International Date Line runs roughly along 180° longitude, so travelling from 75°W east to 105°E does cross the Date Line."),
  dict(topic="Geography",subTopic="Motions of the Earth",
       questionText="On the vernal equinox (approximately 21 March), what is the duration of day and night at the North Pole?",
       options=["A: 24 hours day, 0 hours night","B: 12 hours day, 12 hours night",
                "C: 6 months continuous day","D: The sun sits exactly on the horizon for the entire 24 hours"],
       correct="D",
       explanation="On the equinoxes, the sun's rays fall directly on the equator and the circle of illumination passes through both poles. At the poles, the sun moves along the horizon (neither rising nor setting) for the full 24-hour period — a unique phenomenon transitioning from the 6-month polar night to the 6-month polar day."),
  dict(topic="Geography",subTopic="Major Domains of the Earth",
       questionText="The ocean conveyor belt (thermohaline circulation) is driven by differences in:",
       options=["A: Ocean floor topography only","B: Wind patterns alone",
                "C: Water density, determined by temperature and salinity differences","D: Earth's rotation only"],
       correct="C",
       explanation="Thermohaline circulation ('thermo' = temperature, 'haline' = salt) is driven by density differences in seawater. Cold, salty water is denser and sinks; warm, fresher water is lighter and rises. This creates a global 'conveyor belt' that distributes heat and nutrients worldwide, regulating climate."),
  dict(topic="Geography",subTopic="Our Country India",
       questionText="Which of the following best explains why the Deccan Plateau has a lower density of population compared to the Indo-Gangetic Plain?",
       options=["A: The Deccan Plateau has no mineral resources","B: The Deccan has poorer soils, limited perennial rivers, and less rainfall compared to the fertile alluvial plains of the Ganga",
                "C: The government has restricted migration to the Deccan","D: The Deccan was historically controlled by foreign powers who expelled the population"],
       correct="B",
       explanation="The Indo-Gangetic Plain has deep alluvial soil, multiple perennial Himalayan rivers for irrigation, and high monsoon rainfall — supporting intensive agriculture and dense settlement. The Deccan Plateau has rocky regur (black) or laterite soils, relies on seasonal rivers, and receives less and more variable rainfall."),
  dict(topic="Civics",subTopic="Diversity and Discrimination",
       questionText="The Indian Constitution abolished 'untouchability' through which article?",
       options=["A: Article 14","B: Article 17","C: Article 21","D: Article 25"],
       correct="B",
       explanation="Article 17 of the Indian Constitution abolishes untouchability and forbids its practice in any form. The Practice of Untouchability is punishable under the Protection of Civil Rights Act, 1955."),
  dict(topic="Civics",subTopic="Panchayati Raj",
       questionText="Which provision in the Indian Constitution specifically deals with Panchayati Raj and was inserted by the 73rd Amendment?",
       options=["A: Part IX (Articles 243–243O)","B: Part VI (Articles 153–237)",
                "C: The Seventh Schedule","D: Article 370"],
       correct="A",
       explanation="The 73rd Constitutional Amendment (1992) inserted Part IX into the Constitution (Articles 243 to 243-O), providing constitutional status to Panchayati Raj institutions and mandating elections, reservations, and devolution of powers to the third tier of government."),
  dict(topic="Civics",subTopic="Key Elements of a Democratic Government",
       questionText="Which of the following scenarios BEST illustrates the principle of 'rule of law'?",
       options=["A: A prime minister pardons a relative who committed fraud because she is family",
                "B: A police officer is prosecuted for exceeding her authority during an arrest",
                "C: A wealthy businessman is released without trial because he made large donations",
                "D: A judge dismisses a case based on the defendant's social status"],
       correct="B",
       explanation="Rule of law means that all persons — including government officials — are subject to the law and accountable under it. Prosecuting a police officer for abuse of power demonstrates that no one is above the law, which is the core meaning of this principle."),
  dict(topic="History",subTopic="New Questions and Ideas",
       questionText="The concept of 'ahimsa' (non-violence) was central to both Buddhism and Jainism. How did the Jain interpretation differ from the Buddhist one?",
       options=["A: Jains applied ahimsa only to humans; Buddhists extended it to all sentient beings",
                "B: Jains applied ahimsa in an absolute and all-encompassing manner (even to microorganisms), while Buddhists allowed some exceptions like consuming donated meat",
                "C: Buddhism rejected ahimsa entirely; Jainism embraced it",
                "D: Both traditions had identical interpretations of ahimsa"],
       correct="B",
       explanation="Jain ahimsa is absolute — Jain monks sweep the path before them to avoid killing insects and filter drinking water to avoid harming microorganisms. Buddhism holds ahimsa as important but permits monks to eat meat in some circumstances (if the animal was not killed specifically for them). This absolute vs. contextual distinction is a key difference."),
  dict(topic="Geography",subTopic="India Physical Features",
       questionText="The Himalayan rivers are 'perennial' (flow year-round), while most Peninsular rivers are 'seasonal'. What is the primary reason for this difference?",
       options=["A: Peninsular rivers are blocked by dams","B: Himalayan rivers are fed by both monsoon rains and glacial/snowmelt throughout the year, while Peninsular rivers depend almost entirely on seasonal monsoon rainfall",
                "C: The Peninsular plateau is entirely made of impermeable rock","D: There are more trees near Himalayan rivers"],
       correct="B",
       explanation="Himalayan rivers like the Ganga and Brahmaputra originate in glaciers and snow-covered peaks, providing continuous meltwater even in summer, supplemented by monsoon rains. Peninsular rivers (like the Krishna, Godavari) originate on the plateau and depend almost entirely on monsoon rainfall, causing them to shrink or dry up in the dry season."),
  dict(topic="Civics",subTopic="Democracy",
       questionText="India has a bicameral legislature at the national level. What is the constitutional role of the Rajya Sabha regarding ordinary (non-money) bills?",
       options=["A: The Rajya Sabha cannot reject any bill","B: The Rajya Sabha can reject, amend, or delay an ordinary bill, requiring a joint session to resolve disagreements",
                "C: The Rajya Sabha can only suggest changes but has no power to reject","D: The Rajya Sabha has equal power to the Lok Sabha on all matters including money bills"],
       correct="B",
       explanation="For ordinary bills, both Houses have equal power. If the Rajya Sabha rejects or indefinitely delays a bill passed by the Lok Sabha, the President may summon a joint sitting of both Houses to resolve the deadlock. However, for money bills, the Rajya Sabha can only suggest amendments; the Lok Sabha's decision is final."),
]

# ═══════════════════════════════════════════════════════════════════════════
# SOCIAL STUDIES GR 7
# ═══════════════════════════════════════════════════════════════════════════
SST7_ADV = [
  dict(topic="History",subTopic="Tracing Changes Through a Thousand Years",
       questionText="Medieval Indian cartographers drew maps very differently from modern maps. Which of the following is a significant difference?",
       options=["A: Medieval maps were larger in size","B: Medieval maps often placed south at the top and used symbolic rather than to-scale representations",
                "C: Medieval maps showed only trade routes","D: Medieval maps were exclusively produced by Muslim scholars"],
       correct="B",
       explanation="Medieval maps (like Al-Idrisi's 1154 map) often oriented south at the top, reflecting different geographic conventions. They were symbolic and diagrammatic rather than scale-accurate, reflecting a different conceptual purpose — recording the known world rather than precise navigation."),
  dict(topic="History",subTopic="Delhi Sultanate",
       questionText="The 'iqta' system under the Delhi Sultanate was primarily a method of:",
       options=["A: Collecting land revenue by granting administrative control of a territory to a military official",
                "B: Distributing grain to the poor","C: Organising the sultan's personal bodyguard",
                "D: Administering justice in rural areas"],
       correct="A",
       explanation="An iqta was a revenue assignment — a territory granted to a military commander (muqti/wali) who collected taxes from it to pay his troops and himself, instead of receiving a salary from the central treasury. It was a key mechanism of Sultanate administration but also a source of instability when muqtis became too powerful."),
  dict(topic="History",subTopic="Mughal Empire",
       questionText="Akbar's 'Sulh-i-kul' policy differed from his predecessors' religious policies primarily in that it:",
       options=["A: Imposed Jizya on all non-Muslims more strictly","B: Promoted absolute peace between all religious communities by treating all faiths with equal respect in state affairs",
                "C: Made Islam the only recognised state religion","D: Closed all temples and churches within the empire"],
       correct="B",
       explanation="Sulh-i-kul ('universal peace' or 'absolute peace') was Akbar's principle of impartial treatment of all religions. He abolished Jizya, patronised Hindu, Jain, Christian, and Zoroastrian scholars, and banned religious discrimination in his court — a remarkable policy for 16th-century governance."),
  dict(topic="History",subTopic="Rulers and Buildings",
       questionText="The Qutb Minar in Delhi served which primary symbolic purpose beyond being a minaret?",
       options=["A: It was a lighthouse for river navigation","B: It symbolised the might of Islam and the power of the new Delhi Sultanate over the conquered territories",
                "C: It functioned as an astronomical observatory","D: It was built as a royal tomb for Qutbuddin Aibak"],
       correct="B",
       explanation="The Qutb Minar (begun by Qutbuddin Aibak, completed by Iltutmish) was the tallest tower in the world when built. As a minaret it served the call to prayer, but it also visually proclaimed the supremacy of the new Islamic power over northern India — a potent political symbol as much as a religious one."),
  dict(topic="History",subTopic="Tribes Nomads and Settled Communities",
       questionText="Why did many tribal communities resist the spread of zamindari (landlord) systems in medieval India?",
       options=["A: Tribal societies already had extensive wealth they wished to protect",
                "B: Tribal land use was communal and forest-based; zamindari imposed individual ownership and taxation that disrupted their way of life",
                "C: Zamindars were exclusively from foreign ethnic groups","D: Tribal chiefs wanted to become zamindars themselves but were excluded by caste rules"],
       correct="B",
       explanation="Tribal communities had communal relationships with land and forests, used shifting cultivation, and had no concept of individual land ownership. The imposition of zamindari — with its hereditary ownership, rent extraction, and record-keeping — threatened their forest rights, imposed taxes on subsistence activities, and was fundamentally incompatible with tribal social organisation."),
  dict(topic="Geography",subTopic="Environment",
       questionText="The water cycle is driven primarily by which two energy sources?",
       options=["A: Wind energy and tidal energy","B: Solar energy (evaporation) and gravitational energy (precipitation and runoff)",
                "C: Geothermal energy and lunar gravity","D: Chemical energy from ocean salts and solar energy"],
       correct="B",
       explanation="The sun's heat drives evaporation and transpiration, lifting water vapour into the atmosphere. Gravity then pulls the condensed water back down as precipitation and drives its flow as rivers and groundwater back to the ocean — completing the cycle."),
  dict(topic="Geography",subTopic="Air",
       questionText="The 'lapse rate' in the troposphere refers to:",
       options=["A: The rate at which air pressure increases with altitude","B: The rate at which temperature decreases with increasing altitude (approx. 6.5°C per 1,000 m)",
                "C: The rate at which humidity increases near the equator","D: The speed at which weather fronts move"],
       correct="B",
       explanation="The environmental lapse rate (normal lapse rate) is the rate at which temperature decreases with altitude in the troposphere — approximately 6.5°C per 1,000 m. This is why mountaintops are cold even near the equator and why the temperature at the tropopause (~12 km) is about −60°C."),
  dict(topic="Geography",subTopic="Water",
       questionText="Ocean salinity is highest in the subtropical ocean zones (around 20°–30° latitude) rather than at the equator. What explains this?",
       options=["A: Submarine volcanic activity is concentrated at 20–30°","B: High evaporation due to strong sun and dry trade winds exceeds precipitation there, concentrating salt; at the equator, heavy rainfall dilutes the surface water",
                "C: Ocean currents carry salt from poles to subtropics","D: Salinity increases naturally with proximity to land masses"],
       correct="B",
       explanation="At the equator, high rainfall and river discharge dilute surface salinity. In the subtropics, the descending limb of the Hadley cell creates high pressure, clear skies, intense evaporation, and low rainfall — removing water but leaving salt behind, raising salinity to ~36–37 ppt."),
  dict(topic="Geography",subTopic="Human Environment Interactions",
       questionText="The Amazon rainforest is often called the 'lungs of the Earth'. However, scientists clarify that its net oxygen contribution to the global atmosphere is close to zero. Why?",
       options=["A: The Amazon produces oxygen only during the day","B: Decomposition of dead organic matter in the forest consumes roughly as much oxygen as the trees produce through photosynthesis",
                "C: The Amazon forest primarily produces carbon dioxide","D: Global wind patterns prevent Amazon oxygen from reaching other continents"],
       correct="B",
       explanation="A mature, stable rainforest is close to carbon/oxygen neutral — photosynthesis fixes CO₂ and releases O₂, but the decomposition of leaf litter, dead trees, and soil organic matter consumes roughly the same amount of O₂. The Amazon's critical climate role is as a vast carbon store; clearing it releases stored carbon as CO₂."),
  dict(topic="Civics",subTopic="Equality in a Democracy",
       questionText="The principle of 'one person, one vote, one value' means that in elections:",
       options=["A: Educated voters' votes are counted as double","B: Every adult citizen has exactly one vote and each vote carries equal weight regardless of wealth, caste, or religion",
                "C: Military personnel get additional votes for national service","D: Votes are weighted based on the size of the constituency"],
       correct="B",
       explanation="Universal adult suffrage in a democracy means every adult citizen gets exactly one vote, and all votes carry equal value in determining election results. This prevents wealthy or powerful individuals from having a greater electoral say than ordinary citizens."),
  dict(topic="Civics",subTopic="State Government",
       questionText="The Chief Minister of a state is appointed by the Governor but must satisfy which constitutional condition?",
       options=["A: The Chief Minister must be approved by the Prime Minister","B: The Chief Minister must be the leader of the party or coalition commanding majority support in the state Legislative Assembly",
                "C: The Chief Minister must be born in the state","D: The Chief Minister requires ratification by the Rajya Sabha"],
       correct="B",
       explanation="By constitutional convention (Articles 163–164), the Governor appoints the leader of the majority party or coalition in the Vidhan Sabha as Chief Minister. The Governor's choice is constitutionally constrained — they must appoint whoever can form a government with majority support."),
  dict(topic="Civics",subTopic="Understanding Media",
       questionText="Media 'framing' refers to which of the following concepts?",
       options=["A: The physical format in which news is delivered (TV, newspaper, etc.)",
                "B: The way media organisations select, emphasise, and contextualise information to shape public understanding of an issue",
                "C: Legal regulations governing what media can publish","D: The technical process of editing a video"],
       correct="B",
       explanation="Framing theory (Goffman, 1974) describes how media choices — what to include, what to leave out, which angles to highlight — shape how audiences interpret events. The same story framed differently can lead to vastly different public perceptions, making framing a key tool of media influence."),
  dict(topic="History",subTopic="Bhakti and Sufi Traditions",
       questionText="The Bhakti saints challenged Brahminical authority primarily through which of the following means?",
       options=["A: Armed revolt against temples","B: Composing devotional poetry in regional vernacular languages and arguing that direct personal devotion to God was superior to ritual and caste hierarchy",
                "C: Converting to Islam to avoid the caste system","D: Establishing new kingdoms based on egalitarian principles"],
       correct="B",
       explanation="Bhakti saints like Kabir, Mirabai, Tukaram, and Andal composed songs in Tamil, Hindi, Marathi etc. — bypassing Sanskrit and Brahmin mediation. Their core message — that God could be reached directly through love and devotion regardless of caste, gender, or birth — fundamentally challenged the ritual-and-hierarchy model of Brahminical religion."),
  dict(topic="Geography",subTopic="Natural Vegetation and Wildlife",
       questionText="Why do tropical rainforests have such high biodiversity despite their soils being nutrient-poor?",
       options=["A: Nutrients are locked in the thick layer of living biomass above the soil; rapid decomposition and recycling returns nutrients to plants almost immediately after leaf fall",
                "B: Rainforest soils are actually the most fertile in the world","C: Biodiversity is independent of soil quality",
                "D: Rainforest plants get all nutrients from rainfall"],
       correct="A",
       explanation="In tropical rainforests, the nutrient cycle is extremely rapid and tight. Most nutrients are held in living vegetation. Dead material decomposes within weeks due to heat, humidity, and abundant decomposers. Roots and mycorrhizal fungi capture released nutrients almost instantly — the soil is simply a thin conduit, not a nutrient reservoir. This explains why cleared rainforest land becomes unproductive within a few years."),
  dict(topic="Civics",subTopic="Markets Around Us",
       questionText="A market where the buyer and seller do not meet in person and transactions occur through intermediaries or technology is called a:",
       options=["A: Black market","B: Weekly market","C: Chain of markets or impersonal market","D: Monopoly"],
       correct="C",
       explanation="In impersonal or chain markets (like wholesale commodity markets, online platforms, or stock exchanges), buyers and sellers are connected through intermediaries (brokers, wholesalers, e-commerce platforms) and may never meet. This contrasts with neighbourhood shops or weekly haats where buyer and seller interact directly."),
]

SST7_OLY = [
  dict(topic="History",subTopic="Delhi Sultanate",
       questionText="Why did the Delhi Sultans rely heavily on a Turkish slave-soldier (ghulam/mamluk) elite rather than a hereditary nobility?",
       options=["A: Turkish slaves were cheaper to maintain than free soldiers","B: Slave-soldiers were personally loyal to the Sultan and their status depended entirely on royal favour, making them more reliable than hereditary nobles who had independent power bases",
                "C: Islamic law required that armies consist only of former slaves","D: Hereditary nobles refused to serve in the Delhi Sultanate's army"],
       correct="B",
       explanation="Mamluk (slave) soldiers were purchased as children, trained, and raised to positions of command entirely through royal patronage. Unlike hereditary nobles, they had no independent land, family connections, or ethnic support base to challenge the Sultan — their power was wholly contingent on royal favour. This made them extremely loyal (or at least controllable), which is why this system was used across the Islamic world from Baghdad to Delhi."),
  dict(topic="History",subTopic="Mughal Empire",
       questionText="The Mughal mansabdari system assigned mansabdars both a 'zat' and a 'sawar' rank. What was the significance of keeping both ranks?",
       options=["A: Zat determined salary; sawar determined number of cavalry troops the mansabdar was required to maintain",
                "B: Zat was the civilian rank; sawar was only for military campaigns","C: They were different ways to calculate the same thing","D: Zat was for Mughal nobles; sawar was for Rajput allies"],
       correct="A",
       explanation="Zat rank determined a mansabdar's personal status and salary. Sawar rank specified the number of cavalry soldiers he was required to maintain and bring to battle. The Emperor could raise or lower either rank independently — giving precise control over both the official's income and military obligations."),
  dict(topic="History",subTopic="Bhakti and Sufi Traditions",
       questionText="Kabir's philosophy is often described as syncretic. Which of the following best captures the essence of his syncretic approach?",
       options=["A: He combined Hindu and Islamic rituals in his worship practices","B: He rejected the external forms of both Hinduism and Islam (idols, mosques, pilgrimages) and argued that God (Ram/Rahim) was beyond all such distinctions, accessible only through pure devotion",
                "C: He preached that Hinduism and Islam were separate but equally valid paths","D: He converted to Sikhism as a compromise between the two traditions"],
       correct="B",
       explanation="Kabir is distinctive in that he attacked the orthodoxy of both traditions simultaneously — mocking Brahmin rituals AND Islamic external observance. He insisted that the divine was formless and was not found in temples, mosques, pilgrimages, or scripture, but only in the seeker's heart through nama (devotional remembrance). This radical rejection of institutional religion made him unique."),
  dict(topic="History",subTopic="Rulers and Buildings",
       questionText="The construction of large temples and mosques in medieval India served political purposes beyond the religious. How?",
       options=["A: They stored the state treasury and served as banks","B: Rulers used monumental construction to demonstrate wealth, power, and piety, legitimising their authority and impressing subjects and rivals alike",
                "C: They functioned as administrative headquarters for the empire","D: Large religious buildings were exclusively funded by merchants, not rulers"],
       correct="B",
       explanation="In medieval India, building a grand temple or mosque was an act of political theatre. It demonstrated a ruler's wealth (ability to mobilise enormous resources), piety (divine favour), and ambition. Rivals often attacked enemy temples precisely because temples embodied royal prestige — destroying a temple was equivalent to humiliating a king."),
  dict(topic="Geography",subTopic="Air",
       questionText="The trade winds, westerlies, and polar easterlies are all permanent wind belts. What is the fundamental cause of these global wind patterns?",
       options=["A: Differential rotation speeds of the Earth at different latitudes","B: Uneven heating of the Earth's surface creating pressure belts, modified by the Coriolis effect due to Earth's rotation",
                "C: The gravitational pull of the moon on the atmosphere","D: Ocean currents warming and cooling the overlying air"],
       correct="B",
       explanation="The sun heats the equator most intensely, creating a low pressure belt (ITCZ). High pressure belts form near the poles (cold, dense air) and subtropics (descending air from Hadley cells). Air moves from high to low pressure, but Earth's rotation deflects these winds (Coriolis effect) — rightward in the Northern Hemisphere, leftward in the Southern — creating the trade winds, westerlies, and polar easterlies."),
  dict(topic="Geography",subTopic="Water",
       questionText="Groundwater depletion in India is a serious crisis. Which of the following agricultural practices MOST contributes to groundwater depletion?",
       options=["A: Crop rotation","B: Drip irrigation","C: Flood irrigation of water-intensive crops like paddy and sugarcane in dry regions",
                "D: Use of organic fertilisers"],
       correct="C",
       explanation="Flood irrigation (channelling large amounts of water to flood entire fields) is highly inefficient — most water evaporates or runs off. Growing water-intensive crops (paddy needs ~1,200–3,000 litres per kg) in water-scarce regions using tube wells causes rapid depletion of aquifers. The Green Revolution's spread of paddy cultivation to Punjab and Haryana (semi-arid regions) has caused serious groundwater depletion."),
  dict(topic="Geography",subTopic="Human Environment Interactions",
       questionText="Why does the human development index (HDI) sometimes diverge from GDP per capita as a measure of a nation's development?",
       options=["A: HDI is calculated only for developing countries","B: HDI incorporates health (life expectancy) and education (mean years of schooling) alongside income, capturing dimensions of well-being that income alone misses",
                "C: GDP per capita is always higher than HDI","D: They measure completely different countries"],
       correct="B",
       explanation="Countries with similar GDP per capita can have very different HDI scores depending on how income is distributed and invested in public services. For example, Cuba has a higher life expectancy than many wealthier Latin American countries due to its public health system. HDI captures human capabilities and outcomes, not just economic output."),
  dict(topic="Civics",subTopic="State Government",
       questionText="The concept of 'President's Rule' in a state (Article 356) is controversial in Indian democracy. Why?",
       options=["A: It increases the state government's powers","B: It has historically been misused by central governments to dismiss democratically elected opposition-party state governments, undermining federal principles",
                "C: It permanently removes the state from the Indian Union","D: It allows the state to secede temporarily"],
       correct="B",
       explanation="Article 356 allows the President (on the Governor's recommendation) to dismiss a state government if constitutional machinery fails. The Supreme Court's Bommai case (1994) found it had been misused over 100 times before to dismiss legitimately functioning opposition governments. The Bommai judgment now requires Lok Sabha ratification and judicial review, curtailing misuse."),
  dict(topic="Civics",subTopic="Understanding Advertising",
       questionText="The term 'subliminal advertising' refers to a technique where:",
       options=["A: Advertisements are placed in magazines targeted at children","B: Commercial messages are embedded in media (images, sounds) below the threshold of conscious awareness, influencing consumers without their realising it",
                "C: Advertisements use scientific data to prove product claims","D: Advertising messages are repeated frequently to ensure retention"],
       correct="B",
       explanation="Subliminal advertising involves stimuli presented so briefly or subtly that conscious perception is bypassed. While its effectiveness is disputed in research, concern about it led many countries to ban subliminal techniques. The concept raises important ethical questions about consumer autonomy and informed choice."),
  dict(topic="History",subTopic="Tribes Nomads and Settled Communities",
       questionText="The Nayaka system in the Vijayanagara Empire shared some features with the Mughal mansabdari system. What was the primary similarity?",
       options=["A: Both used slave-soldiers as their primary military force","B: Both involved granting revenue-bearing territories to military commanders in exchange for maintaining a specified number of troops",
                "C: Both systems were introduced by the same ruler","D: Both systems operated exclusively in peninsular India"],
       correct="B",
       explanation="Both the Nayaka (Vijayanagara) and mansabdar (Mughal) systems were essentially revenue-assignment military systems — commanders received control of territory, collected taxes from it, and used the income to maintain troops and equipment for the king. This 'pay through land' system was common across medieval India due to the difficulty of maintaining a large cash-paid standing army."),
  dict(topic="Geography",subTopic="Natural Vegetation and Wildlife",
       questionText="Which of the following correctly describes the concept of a 'keystone species' in an ecosystem?",
       options=["A: The most numerous species in an ecosystem","B: A species whose impact on its ecosystem is disproportionately large relative to its abundance, and whose removal causes dramatic ecosystem collapse",
                "C: The species at the top of the food chain","D: Any species listed as endangered"],
       correct="B",
       explanation="A keystone species exerts outsized influence on ecosystem structure. Classic examples: sea otters (controlling sea urchin populations, which protects kelp forests), wolves in Yellowstone (controlling elk grazing patterns, restoring rivers through 'trophic cascade'), bees (pollination). Remove the keystone and the ecosystem collapses or dramatically transforms."),
  dict(topic="Civics",subTopic="Women Change the World",
       questionText="What is the 'glass ceiling' in the context of gender and employment?",
       options=["A: A transparent roof installed in modern offices","B: An invisible but real barrier that prevents women and minorities from rising beyond certain levels in organisations, despite qualifications",
                "C: A legal restriction on women in managerial roles","D: A concept from architecture describing open-plan offices"],
       correct="B",
       explanation="The 'glass ceiling' metaphor (coined by Carol Hymowitz and Timothy Schellhardt, 1986) describes the invisible barriers — through bias, exclusion from informal networks, family-responsibility assumptions — that prevent qualified women and minorities from reaching senior leadership positions even when organisations formally prohibit discrimination."),
  dict(topic="History",subTopic="New Kings and Kingdoms",
       questionText="The Chola king Rajendra I's naval expedition to Southeast Asia (~1025 CE) is historically significant primarily because:",
       options=["A: It established permanent Chola colonies in Indonesia","B: It demonstrated the Cholas' ability to project military power across the Bay of Bengal and control maritime trade routes, challenging Srivijaya's commercial dominance",
                "C: It converted Southeast Asian kingdoms to Hinduism","D: It established a Chola tributary state in China"],
       correct="B",
       explanation="Rajendra I's naval campaign against the Srivijaya kingdom (present-day Sumatra/Malaysia) was primarily motivated by trade — Srivijaya controlled key maritime trade routes between India, China, and Southeast Asia. The raid disrupted Srivijayan commercial power and opened these routes to Chola and Tamil merchant networks, enormously boosting South Indian trade."),
  dict(topic="Geography",subTopic="Environment",
       questionText="'Sustainable development' as defined in the Brundtland Report (1987) means:",
       options=["A: Development that focuses only on environmental protection at the expense of economic growth","B: Development that meets the needs of the present without compromising the ability of future generations to meet their own needs",
                "C: Development that maximises GDP growth regardless of environmental consequences","D: Development that is sustained over a period of at least 50 years"],
       correct="B",
       explanation="The Brundtland Commission's definition of sustainable development (1987) integrates three pillars: economic development, social equity, and environmental protection. The key principle is intergenerational equity — current development should not exhaust or degrade the resources and systems that future generations will need."),
  dict(topic="Civics",subTopic="Equality in a Democracy",
       questionText="Why do most democratic constitutions contain both 'fundamental rights' (rights against state action) AND 'directive principles' (positive obligations on the state), rather than just one category?",
       options=["A: Fundamental rights are more important than directive principles","B: Fundamental rights protect individual liberty from government overreach; directive principles guide the state to actively create conditions for a just and equitable society — together they balance negative and positive freedom",
                "C: Directive principles were added only because fundamental rights proved insufficient","D: Only India has directive principles; other democracies do not"],
       correct="B",
       explanation="Fundamental rights (Part III of Indian Constitution) are justiciable — courts can enforce them against the state. Directive principles (Part IV) are non-justiciable guidelines for socioeconomic policy (reducing inequality, providing livelihood, health care). Together they represent negative freedom (freedom from state oppression) and positive freedom (state action to enable genuine equality) — a comprehensive vision of constitutional democracy."),
]

# ═══════════════════════════════════════════════════════════════════════════
# SOCIAL STUDIES GR 9
# ═══════════════════════════════════════════════════════════════════════════
SST9_ADV = [
  dict(topic="History",subTopic="French Revolution",
       questionText="The Declaration of the Rights of Man and of the Citizen (1789) was revolutionary because it:",
       options=["A: Extended rights to women and enslaved people for the first time","B: Declared that sovereignty rested in the nation rather than the king, and proclaimed individual rights to liberty, property, and equality before the law as universal natural rights",
                "C: Abolished the Catholic Church in France","D: Established a republic immediately upon its declaration"],
       correct="B",
       explanation="The Declaration transferred the theoretical basis of political legitimacy from divine kingship to popular sovereignty. Its assertion that rights were natural, universal, and inalienable was radically new — but critically, it was limited in practice, excluding women (Olympe de Gouges challenged this), enslaved people, and the poor from its protections."),
  dict(topic="History",subTopic="Russian Revolution",
       questionText="The February Revolution of 1917 in Russia succeeded in overthrowing the Tsar primarily because of:",
       options=["A: A planned coup organised by the Bolshevik party","B: Spontaneous mass protests by workers and soldiers in Petrograd, combined with the refusal of the army to suppress them",
                "C: Military intervention by Germany","D: The Tsar's voluntary abdication due to illness"],
       correct="B",
       explanation="The February Revolution was not organised by any single political party. It began with bread shortages and strikes by workers in Petrograd, which spiralled into massive protests. Crucially, when ordered to fire on crowds, many soldiers — themselves peasants tired of war — refused and joined the protesters. The absence of military repression made the revolution unstoppable."),
  dict(topic="History",subTopic="Nazism and the Rise of Hitler",
       questionText="The Weimar Republic's vulnerability to extremism was significantly worsened by the Great Depression (1929) because:",
       options=["A: The Depression proved that democracy could not manage economies","B: Mass unemployment and economic misery created fertile ground for extremist political promises, undermining faith in the democratic Weimar government",
                "C: The Depression was caused by the Weimar government's policies","D: Foreign countries demanded Germany's dissolution as a condition of economic aid"],
       correct="B",
       explanation="Germany's unemployment rose to ~6 million by 1932. The Weimar government — bound by the Versailles reparations and orthodox economic policy — had no effective response. Desperate voters turned to parties promising radical solutions. Nazi support in the Reichstag jumped from 2.6% (1928) to 37.4% (1932) directly tracking economic misery."),
  dict(topic="Geography",subTopic="Physical Features of India",
       questionText="The Deccan Plateau tilts slightly from west to east. What geographic consequence does this create?",
       options=["A: All peninsular rivers flow westward into the Arabian Sea","B: Most peninsular rivers (Krishna, Godavari, Kaveri) flow eastward and drain into the Bay of Bengal",
                "C: The Deccan Plateau has no major rivers","D: The Western Ghats receive rain on their eastern slopes"],
       correct="B",
       explanation="Because the Deccan Plateau slopes from west (Western Ghats) to east, rivers flow eastward. The Western Ghats act as the watershed. Major rivers — Godavari, Krishna, Mahanadi, Kaveri — all flow eastward and form deltas on the Bay of Bengal coast. The exception is the Narmada and Tapi, which flow westward through rift valleys."),
  dict(topic="Geography",subTopic="Drainage",
       questionText="The Ganga-Brahmaputra delta is the world's largest delta. Which factors contribute to its enormous size?",
       options=["A: Large catchment area of both rivers, high sediment load from the Himalayas, and low coastal gradient",
                "B: The Bay of Bengal has no tides to erode the delta","C: Deforestation of the entire catchment area within the last century",
                "D: Government dredging and sediment placement programs"],
       correct="A",
       explanation="The Ganga and Brahmaputra together drain ~1.75 million km² (including the highly erosional young Himalayas). Himalayan rivers carry enormous sediment loads. The flat, low-lying coast of the Bay of Bengal allows sediment deposition over a vast area. These factors combine to create the ~100,000 km² Sundarbans-Ganga-Brahmaputra megadelta."),
  dict(topic="Geography",subTopic="Climate",
       questionText="India experiences a distinct 'break in the monsoon' during July-August. What causes this phenomenon?",
       options=["A: The monsoon exhausts itself and needs to 'recharge'","B: The monsoon trough (low pressure) temporarily shifts northward toward the Himalayas, reducing rainfall over most of India while increasing it along the Himalayan foothills",
                "C: Anti-cyclones form over the Arabian Sea blocking moisture","D: Temperature inversions in the upper atmosphere block rainfall"],
       correct="B",
       explanation="During a monsoon break, the Inter-Tropical Convergence Zone (ITCZ) and the monsoon trough shift northward. Rainfall decreases over peninsular and central India but intensifies over the Himalayan foothills. This is different from a monsoon failure and can last days to weeks."),
  dict(topic="Economics",subTopic="Poverty",
       questionText="Why is the 'poverty line' a contested concept in India?",
       options=["A: The government refuses to calculate it","B: Different methods (caloric intake, multi-dimensional poverty, relative poverty) yield significantly different poverty estimates, and the official line has been criticised for underestimating poverty by setting too low a threshold",
                "C: Poverty cannot be measured in India because of population size","D: The poverty line was abolished in 2000"],
       correct="B",
       explanation="India's official poverty line is based on a minimum caloric intake (2,400 kcal/day rural, 2,100 urban). Critics argue it ignores healthcare, education, housing, and social security costs. The Tendulkar Committee (2009) and Rangarajan Committee (2014) revisions yielded poverty estimates ranging from 22% to 30% — showing how methodology determines the outcome."),
  dict(topic="Economics",subTopic="Food Security",
       questionText="The Public Distribution System (PDS) in India was introduced primarily to address which food security challenge?",
       options=["A: Increasing agricultural exports","B: Ensuring access to food at subsidised prices for the poor, especially during droughts and price spikes",
                "C: Reducing food wastage in urban areas","D: Increasing domestic food production"],
       correct="B",
       explanation="The PDS was designed to distribute essential food grains (wheat, rice) through a network of Fair Price Shops at subsidised prices to BPL (below poverty line) families. It ensures that even during poor harvests or market price spikes, the poor can access minimum nutrition — addressing the 'access' dimension of food security."),
  dict(topic="Civics",subTopic="Electoral Politics",
       questionText="The 'first-past-the-post' (FPTP) electoral system used in India can result in a party winning a majority of seats without winning a majority of votes. How?",
       options=["A: FPTP counts votes multiple times for the winning party","B: FPTP awards all seats in a constituency to the candidate with the most votes (even 30%), so a party winning multiple constituencies by small margins can accumulate a seat majority without a national vote majority",
                "C: The Election Commission adjusts results for smaller parties","D: FPTP requires a minimum 50% vote share to win any seat"],
       correct="B",
       explanation="In FPTP, the candidate with the plurality (most votes) wins the seat, even with 30–35% of the vote. In a multi-party contest, votes 'against' the winner are split among multiple losers. A party can win 40% of the national vote but win 55% of seats by winning many constituencies narrowly — leading to 'manufactured majorities'."),
  dict(topic="Civics",subTopic="Constitutional Design",
       questionText="Why does the Indian Constitution include both Fundamental Rights (justiciable) and Directive Principles of State Policy (non-justiciable)?",
       options=["A: The Constituent Assembly could not agree on which rights were more important so included both",
                "B: Fundamental Rights protect individual liberties immediately; DPSPs are goals for socioeconomic justice that the state should achieve progressively as resources allow — together they address both political and economic democracy",
                "C: Directive Principles apply only to state governments, not the central government","D: Fundamental Rights were borrowed from Britain; DPSPs from the USA"],
       correct="B",
       explanation="B.R. Ambedkar explained this design as providing for 'political democracy now and economic democracy over time'. Fundamental Rights (liberty, equality, expression) are immediate and enforceable. DPSPs (right to livelihood, equal pay, free education) require resources and time — they guide policy without being immediately enforceable, avoiding placing impossible immediate obligations on a newly independent, poor country."),
  dict(topic="History",subTopic="French Revolution",
       questionText="The Reign of Terror (1793–94) under Robespierre represented a fundamental contradiction in the French Revolution. What was this contradiction?",
       options=["A: Robespierre was secretly a royalist","B: A revolution fought in the name of liberty resorted to systematic state-sponsored executions, using fear and repression to defend the revolution — becoming the very tyranny it had opposed",
                "C: The Reign of Terror was actually peaceful","D: Robespierre introduced new taxes that contradicted the revolution's economic goals"],
       correct="B",
       explanation="The Revolution began with the declaration of universal rights and liberty. By 1793, the Committee of Public Safety — led by Robespierre — executed approximately 17,000 people officially and 23,000 more in summary executions, targeting not just aristocrats but ordinary citizens, including revolutionaries. The defense of liberty through mass terror exposed a deep contradiction that has fascinated philosophers and historians ever since."),
  dict(topic="Geography",subTopic="Population",
       questionText="India's demographic transition shows that birth rates have been falling more slowly than death rates since the 1950s. What has been the primary consequence of this demographic pattern?",
       options=["A: India's population has been declining since 1950","B: India experienced rapid population growth because the gap between birth rates and death rates remained large, creating a 'population explosion'",
                "C: India's birth rate fell faster than the death rate causing a demographic crisis","D: Death rate exceeded birth rate after 1970"],
       correct="B",
       explanation="Demographic transition theory describes how modernising societies move from high birth/high death to low birth/low death. In India, death rates fell sharply after independence (due to improved medicine, public health, famine control) but birth rates declined much more slowly (due to poverty, low female education, son preference). The large gap between them caused rapid population growth."),
  dict(topic="Economics",subTopic="People as Resource",
       questionText="The concept 'human capital' treats education and health as investments rather than consumption. Why is this distinction significant for economic policy?",
       options=["A: It makes education free of cost","B: If education and health are investments that raise productivity and economic output, governments have a strong economic rationale to fund them, not just a welfare rationale",
                "C: It means only university education should be funded by government","D: Human capital theory implies people should pay for their own education"],
       correct="B",
       explanation="Human capital theory (Schultz, Becker) argues that expenditure on education and health generates future economic returns by increasing worker productivity. This reframes social spending from 'welfare cost' to 'productive investment', providing an economic efficiency argument (beyond equity) for public funding of education and health — particularly influential in development economics."),
  dict(topic="Civics",subTopic="Working of Institutions",
       questionText="The collegium system in India governs the appointment of Supreme Court judges. Which constitutional article provides for this, and what is the key controversy about it?",
       options=["A: Article 124; the controversy is that the executive has too much power in judicial appointments",
                "B: Article 124 read with Supreme Court judgments; the controversy is that judges appointing judges (collegium) lacks democratic accountability and transparency",
                "C: Article 356; controversy about state-centre conflict","D: Article 21; controversy about prison conditions"],
       correct="B",
       explanation="Article 124 says judges are appointed by the President in 'consultation' with the Chief Justice. In the Three Judges Cases (1981, 1993, 1998), the Supreme Court interpreted 'consultation' as 'concurrence', creating the collegium system where a group of senior judges effectively control appointments. Critics argue this violates democratic accountability — unelected judges appointing their own successors with minimal executive or parliamentary scrutiny."),
  dict(topic="History",subTopic="Nazism and the Rise of Hitler",
       questionText="The Holocaust was not merely an act of individual hatred but a systemic, state-organised genocide. Which factor was most essential to making it possible at industrial scale?",
       options=["A: The personal fanaticism of Hitler alone","B: The bureaucratic machinery of the modern state combined with ideology: efficient record-keeping, railways, industrial processes, and ordinary people following orders within a dehumanising system",
                "C: Germany's advanced chemistry industry providing poison gas","D: International indifference was the only reason it was possible"],
       correct="B",
       explanation="Historian Hannah Arendt's 'banality of evil' and Christopher Browning's 'Ordinary Men' show the Holocaust required thousands of bureaucrats, railway workers, and soldiers — most of them ordinary people. The industrial scale was possible because of modern state bureaucracy (census records for identifying Jews, railways for transport, Zyklon B for killing, efficient record-keeping). Hitler's ideology was necessary but insufficient — the state apparatus made it operational."),
]

SST9_OLY = [
  dict(topic="History",subTopic="French Revolution",
       questionText="The French Revolution produced three foundational ideological concepts — Liberty, Equality, and Fraternity. Which of the following best explains the inherent tension between Liberty and Equality?",
       options=["A: They were invented by different political factions who disagreed","B: Perfect liberty (freedom from constraint) can allow the economically powerful to dominate the weak, undermining equality; achieving genuine equality may require limiting some liberties (e.g., progressive taxation, regulation)",
                "C: Liberty refers to economic freedom while equality refers only to political rights","D: There is no tension — they reinforce each other perfectly"],
       correct="B",
       explanation="This tension is the core debate of modern political philosophy. Libertarians argue that any state redistribution violates liberty. Egalitarians argue that formal legal equality is meaningless without substantive economic equality. The French Revolution itself illustrated this — the bourgeois who gained liberty used it to accumulate wealth, perpetuating inequality for workers. This unresolved tension drove subsequent revolutions and socialist movements."),
  dict(topic="History",subTopic="Russian Revolution",
       questionText="Lenin's concept of 'vanguard party' departed from orthodox Marxism in a crucial way. What was this departure and why was it controversial?",
       options=["A: Lenin rejected capitalism entirely, which Marx had not done","B: Orthodox Marxism held that revolution would arise spontaneously from the proletariat's class consciousness; Lenin argued that workers needed a highly disciplined professional revolutionary party to lead them because they would otherwise only achieve 'trade union consciousness' (economic demands) rather than revolutionary consciousness",
                "C: Lenin wanted a democratic party; Marx preferred a dictatorship","D: Lenin rejected the concept of class struggle unlike Marx"],
       correct="B",
       explanation="Marx believed revolution would emerge naturally as capitalism's contradictions intensified and workers developed class consciousness. Lenin, in 'What Is To Be Done?' (1902), argued that workers left to themselves develop only reformist consciousness (better wages, shorter hours). A disciplined vanguard of professional revolutionaries was needed to inject revolutionary theory from outside the class. This 'substitutionist' argument — where the party substitutes for the working class — was later used to justify Bolshevik authoritarianism."),
  dict(topic="History",subTopic="Nazism and the Rise of Hitler",
       questionText="Nazi racial ideology classified people hierarchically. What was the pseudoscientific basis of this ideology and why was it intellectually fraudulent?",
       options=["A: It was based on valid genetic research of the 1920s","B: It borrowed Social Darwinism and eugenics, misapplying Darwin's natural selection to human races/nations and claiming scientific authority for racial hierarchy — when in fact 'race' is not a biological category but a social construct, and evolutionary fitness applies to survival and reproduction, not cultural or moral superiority",
                "C: It was purely religious with no scientific claims","D: It was based on ancient Greek philosophical texts"],
       correct="B",
       explanation="Nazism drew on Social Darwinism (nations as organisms in struggle for survival), eugenics (breeding 'superior' humans), and anthropological race science — all of which had mainstream scientific credibility in the early 20th century but were methodologically deeply flawed (circular reasoning, selective data, confusing correlation with causation). Modern genetics confirms that 'race' has no biological basis — genetic variation within so-called racial groups exceeds variation between them."),
  dict(topic="Geography",subTopic="Climate",
       questionText="During La Niña years, India typically experiences stronger-than-normal monsoons. What is the atmospheric mechanism connecting ENSO (El Niño-Southern Oscillation) to Indian monsoon intensity?",
       options=["A: La Niña cools the Pacific, making clouds form over India instead","B: La Niña strengthens the Walker circulation, enhancing rising air over the Indian Ocean and western Pacific, intensifying the pressure gradient that drives the Indian Ocean monsoon winds",
                "C: ENSO affects only South American weather; Indian monsoon is independent","D: La Niña increases Arctic sea ice which pushes cold air toward India causing more rainfall"],
       correct="B",
       explanation="ENSO affects global atmospheric circulation through the Walker cell. During La Niña, the central/eastern Pacific is cooler than normal, strengthening the east-west Walker circulation. This enhances rising air over the Indian Ocean, lowering pressure over the subcontinent and strengthening the monsoon winds that drive rainfall. El Niño has the opposite effect — weakening the Walker cell and often causing drought in India."),
  dict(topic="Economics",subTopic="Poverty",
       questionText="Sen's 'capability approach' to poverty argues that measuring poverty by income alone is insufficient. What does it add to our understanding?",
       options=["A: It argues that only absolute poverty (below $1/day) matters","B: Poverty is the deprivation of real freedoms and capabilities — the ability to live long, be healthy, be educated, and participate in social life. Income is merely one means to these capabilities, not an end in itself",
                "C: The capability approach focuses only on education","D: Sen argues that poverty is entirely relative and culturally determined"],
       correct="B",
       explanation="Amartya Sen's capability approach (developed with Martha Nussbaum) argues that what matters is what people can actually do and be — their functionings and capabilities. A person might have income but lack capabilities due to discrimination, disability, or social exclusion. Conversely, a simple rural life with community support might deliver high capabilities with low income. This insight underlies the UNDP's Human Development Index."),
  dict(topic="Civics",subTopic="Constitutional Design",
       questionText="The Indian Constitution grants 'directive principles' that are non-justiciable. The Supreme Court's Kesavananda Bharati judgment (1973) established that Parliament cannot amend the Constitution's 'basic structure'. How do these two doctrines interact?",
       options=["A: Directive principles form part of the basic structure that cannot be amended","B: The basic structure doctrine protects certain fundamental features of the constitution (judicial review, federalism, secularism) from parliamentary amendment even if Parliament has a two-thirds majority; while DPSPs can be implemented by legislation, they cannot override fundamental rights or basic structure",
                "C: The two doctrines are completely unrelated","D: Directive principles override the basic structure in case of conflict"],
       correct="B",
       explanation="The basic structure doctrine (Kesavananda Bharati) protects the Constitution's essential character — democracy, rule of law, separation of powers, fundamental rights, secularism — from being amended away even by a constitutional majority. DPSPs guide policy but cannot be used to violate fundamental rights (Minerva Mills case, 1980) — the Court struck a balance, ruling that harmony between rights and directives is itself part of the basic structure."),
  dict(topic="Geography",subTopic="Natural Vegetation and Wildlife",
       questionText="India's biodiversity hotspots include the Western Ghats and the Eastern Himalayas. What criteria qualify a region as a 'biodiversity hotspot'?",
       options=["A: Any region with more than 1,000 plant species","B: A region must contain at least 1,500 endemic vascular plant species AND have lost at least 70% of its original habitat",
                "C: Any region designated by the Indian government as a national park","D: A region with the highest number of endangered animals only"],
       correct="B",
       explanation="Norman Myers defined biodiversity hotspots (1988, updated by Conservation International) as regions meeting two criteria: (1) ≥1,500 species of endemic vascular plants found nowhere else, AND (2) ≥70% habitat loss from the original extent. This combination of richness and threat prioritises conservation efforts. Globally there are 36 hotspots covering only 2.4% of Earth's land but containing >50% of all endemic plant species."),
  dict(topic="History",subTopic="Peasants and Farmers",
       questionText="The American Great Depression of the 1930s devastated farmers despite a food surplus. How does this paradox illustrate the vulnerability of market-dependent agriculture?",
       options=["A: There was no food surplus; the Depression caused food shortages","B: When farm prices collapsed due to overproduction, farmers could not repay debts from mechanisation and land mortgages taken during the 1920s boom; they were ruined by surplus — producing more but earning less — illustrating that market agriculture ties farmers to price volatility they cannot control",
                "C: American farmers were deliberately sabotaged by foreign governments","D: The Depression only affected industrial workers, not farmers"],
       correct="B",
       explanation="The 1920s agricultural boom led US farmers to mechanise and expand, taking on heavy debt. When overproduction crashed prices in the 1930s, farmers faced the paradox of ruin amid plenty — they grew more but earned less, couldn't repay debts, and lost farms to foreclosure. John Steinbeck's 'The Grapes of Wrath' documents this. The paradox shows market agriculture's structural vulnerability: individual rationality (grow more) leads to collective irrationality (price collapse destroying all)."),
  dict(topic="Economics",subTopic="Food Security",
       questionText="Despite producing surplus food grains, India experiences 'food insecurity' for millions. This paradox is best explained by Amartya Sen's concept of:",
       options=["A: Market failure theory","B: 'Entitlement failure' — people go hungry not because food is absent but because they lack the purchasing power, land rights, or social entitlements needed to access available food",
                "C: The Malthusian trap","D: Supply chain disruption theory"],
       correct="B",
       explanation="Sen's analysis of famines ('Poverty and Famines', 1981) shows that most modern famines occur not from absolute food shortage but from 'entitlement failure' — the loss of people's ability to command food through exchange (buying), production (growing), or social transfers (welfare). The Bengal Famine of 1943 occurred when India exported food during a food crisis because poor landless labourers lost their wages (exchange entitlement) — not because total food supply collapsed."),
  dict(topic="Civics",subTopic="Electoral Politics",
       questionText="'Strategic voting' (voting for a less-preferred but more viable candidate to prevent the most-disliked candidate from winning) is common under FPTP systems. What does this behaviour reveal about the FPTP system's shortcomings?",
       options=["A: FPTP encourages strategic thinking which is a strength","B: FPTP fails to capture voters' true preferences because voters are incentivised to vote against their first choice to prevent their worst outcome, suggesting that the results do not reflect genuine democratic preferences",
                "C: Strategic voting is illegal under Indian election law","D: Strategic voting only occurs in proportional representation systems"],
       correct="B",
       explanation="Kenneth Arrow's Impossibility Theorem and Duverger's Law both point to FPTP's distortions. When voters must vote strategically rather than sincerely, election outcomes don't reflect genuine preferences — they reflect voters' estimates of who can win. This is why FPTP tends to produce two-party systems (Duverger's Law) and why third parties are systematically disadvantaged even when they have substantial support."),
  dict(topic="Geography",subTopic="Physical Features of India",
       questionText="The Thar Desert receives less than 250 mm of rainfall annually despite being at the same latitude as other monsoon regions. What is the primary reason for this anomaly?",
       options=["A: The Thar is too far from the ocean","B: The Aravalli mountains run parallel (not perpendicular) to the Arabian Sea branch of the monsoon, failing to force moisture-laden winds upward, combined with the Saharan-Arabian high pressure system extending into this region",
                "C: Strong winds blow monsoon clouds away before they can deposit rain","D: The desert's hot sand absorbs all incoming moisture before it can form clouds"],
       correct="B",
       explanation="The Arabian Sea monsoon branch should bring moisture to Rajasthan, but the Aravalli range runs from northeast to southwest — parallel to the monsoon flow, not across it. This orientation fails to force winds upward (orographic lift) where they could cool and precipitate. Additionally, the extension of the subtropical high pressure belt from the Sahara-Arabian region into northwest India suppresses rainfall. The result is extreme aridity despite being at the same latitude as the wet Gangetic plains."),
  dict(topic="Civics",subTopic="Working of Institutions",
       questionText="India's Parliament has the power to make laws on any subject listed in the Union List. Which type of legislation requires both central and state input, and what happens if they conflict?",
       options=["A: Union List subjects; states always prevail","B: Concurrent List subjects; if state and central laws conflict on the same subject, the central law prevails (repugnancy doctrine), unless the state law received Presidential assent before the central law",
                "C: State List subjects; the central law always prevails","D: There is no provision for concurrent jurisdiction in India"],
       correct="B",
       explanation="The Seventh Schedule divides legislative powers into Union, State, and Concurrent Lists. The Concurrent List allows both Parliament and state legislatures to legislate (education, criminal procedure, forests, etc.). Article 254 provides that if a state law and central law on a Concurrent List subject conflict (repugnancy), the central law prevails — unless the state law was passed with Presidential assent prior to the central law and the Parliament has not since legislated on that matter."),
  dict(topic="History",subTopic="Forest Society and Colonialism",
       questionText="British colonial forest policy in India had which unintended long-term social consequence?",
       options=["A: It successfully conserved all Indian forests","B: By converting community forests to state-controlled commercial forests and criminalising traditional forest use, it dispossessed millions of forest-dwelling communities (Adivasis), creating poverty and social conflict that continues to fuel Naxalite movements today",
                "C: It led to the rapid industrialisation of India","D: It eliminated all forest-dependent occupations by 1900"],
       correct="B",
       explanation="The Indian Forest Acts of 1865 and 1878 transferred vast community forests to state control, classified traditional practices (shifting cultivation, collecting minor forest produce, grazing) as criminal, and prioritised commercial timber extraction. This dispossessed tribal and forest communities from livelihoods they had maintained for generations. The Forest Rights Act (2006) was a belated attempt to correct this — and the ongoing conflict in forest regions reflects this unresolved colonial legacy."),
  dict(topic="Geography",subTopic="Drainage",
       questionText="Rivers in the Himalayan region have 'antecedent drainage' — they predate the mountains they cut through. What is the significance of this for understanding Himalayan geography?",
       options=["A: Antecedent rivers formed after the Himalayas","B: Rivers like the Indus, Satluj, and Brahmaputra were flowing northward into the Tethys Sea before the Himalayas uplifted; as the mountains rose, the rivers maintained their courses, cutting spectacular gorges through the rising mountains — explaining why these rivers rise in Tibet on the northern side of the Himalayas",
                "C: Antecedent drainage occurs only in flat plains","D: Himalayan rivers drain into the Arabian Sea due to antecedent flow"],
       correct="B",
       explanation="The Indus, Satluj, and Brahmaputra rivers originated before the Himalayas formed, draining northward into the ancient Tethys Sea. When the Indian and Eurasian plates collided (~50 million years ago) and the Himalayas began uplifting, these rivers were powerful enough to maintain their existing courses by cutting through the rising rock — creating some of the world's deepest gorges. This 'antecedent origin' explains why they originate beyond the main Himalayan range."),
  dict(topic="Economics",subTopic="The Story of Village Palampur",
       questionText="In a village economy like Palampur, access to credit is often only available to large farmers through formal institutions, while small farmers depend on moneylenders. What is the long-term economic consequence of this credit inequality?",
       options=["A: Small farmers gradually accumulate wealth through savings","B: Large farmers can invest in capital (tube wells, tractors, improved seeds) that increases productivity and income, while small farmers pay usurious interest rates that trap them in debt cycles — widening rural inequality over time",
                "C: Credit access is equal between large and small farmers in most villages","D: Small farmers prefer moneylenders due to lower interest rates"],
       correct="B",
       explanation="Formal credit (bank loans at 10–12% interest) fuels investment and growth for collateral-rich large farmers. Moneylenders charge 24–48% annually to small farmers lacking collateral. This compound interest often exceeds any income gain, trapping small farmers in debt cycles that may end in land loss. This credit dualism is a primary mechanism of rural inequality perpetuation and is why microfinance and self-help groups were created to address it."),
]

# ═══════════════════════════════════════════════════════════════════════════
# MAIN
# ═══════════════════════════════════════════════════════════════════════════
def build_questions():
    qs = []
    def add(lst, subject, grade, difficulty):
        for q in lst:
            qs.append(dict(
                subject=subject, grade=grade, difficulty=difficulty,
                topic=q["topic"], subTopic=q["subTopic"],
                questionText=q["questionText"],
                options=q["options"],
                correctAnswer=q["correct"],
                explanation=q["explanation"]
            ))
    add(SST6_ADV, "Social Studies", 6, "Advanced")
    add(SST6_OLY, "Social Studies", 6, "Olympiad")
    add(SST7_ADV, "Social Studies", 7, "Advanced")
    add(SST7_OLY, "Social Studies", 7, "Olympiad")
    add(SST9_ADV, "Social Studies", 9, "Advanced")
    add(SST9_OLY, "Social Studies", 9, "Olympiad")
    return qs

def main():
    conn = pyodbc.connect(DB_CONN)
    questions = build_questions()
    ok = dup = err = 0
    for i, q in enumerate(questions, 1):
        try:
            res = insert(conn, q)
        except Exception as e:
            res = f"ERR: {e}"
        m = "✓" if res=="OK" else ("~" if res=="DUP" else "✗")
        print(f"  {m} Q{i:03d} [{q['subject']} G{q['grade']} {q['difficulty']}] {q['subTopic'][:55]} → {res}")
        if res=="OK": ok+=1
        elif res=="DUP": dup+=1
        else: err+=1
    conn.close()
    print(f"\n  Done: {ok} posted, {dup} duplicates, {err} errors  (total={ok+dup+err})")

if __name__ == "__main__":
    main()
