import pyodbc, json, uuid, sys
sys.stdout.reconfigure(encoding='utf-8', errors='replace')

DB_CONN = (
    "DRIVER={ODBC Driver 18 for SQL Server};"
    "SERVER=tcp:olympiadready-np.database.windows.net,1433;"
    "DATABASE=OlympiadReady;UID=nyxen-admin;PWD=Olympiad@2026;"
    "Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30"
)

def insert(conn, q):
    c = conn.cursor()
    c.execute("SELECT 1 FROM QuestionBank WHERE Subject=? AND Grade=? AND SubTopic=? AND QuestionText=?",
              q["subject"], q["grade"], q["subTopic"], q["questionText"])
    if c.fetchone():
        return "DUP"
    c.execute("""INSERT INTO QuestionBank
                 (QuestionBankId,Subject,Grade,Difficulty,Topic,SubTopic,
                  QuestionText,OptionsJson,CorrectAnswer,Explanation,CreatedAt)
                 VALUES (?,?,?,?,?,?,?,?,?,?,GETUTCDATE())""",
              str(uuid.uuid4()).upper(), q["subject"], q["grade"], q["difficulty"],
              q["topic"], q["subTopic"], q["questionText"],
              json.dumps(q["options"]), q["correctAnswer"], q["explanation"])
    conn.commit()
    return "OK"

# ── SS G6 FOUNDATION (15q) — NCERT Hamare Atit / Our Pasts ──
SS6_FOUND = [
    {"subject":"Social Studies","grade":6,"difficulty":"Foundation","topic":"What, Where, How and When","subTopic":"Sources of History",
     "questionText":"Which of the following is a PRIMARY source of historical information?",
     "options":["A: A history textbook","B: A documentary film","C: A coin issued during the Gupta period","D: An encyclopedia entry"],"correctAnswer":"C",
     "explanation":"A primary source is original material created during the time period being studied. A Gupta-period coin is a direct artifact from that era. Textbooks, documentaries, and encyclopedias are secondary sources — they interpret or summarise primary evidence."},
    {"subject":"Social Studies","grade":6,"difficulty":"Foundation","topic":"On the Trail of the Earliest People","subTopic":"Hunter-Gatherers",
     "questionText":"Early humans were called 'hunter-gatherers' because they:",
     "options":["A: Hunted animals for sport and gathered at meetings","B: Hunted animals for food and gathered wild fruits, nuts, and roots for survival","C: Cultivated crops and kept animals","D: Built cities and gathered in markets"],"correctAnswer":"B",
     "explanation":"Hunter-gatherers were nomadic people who lived before the agricultural revolution. They obtained food by hunting wild animals and gathering wild plants, fruits, nuts, roots, and seeds. They moved from place to place following seasonal food sources."},
    {"subject":"Social Studies","grade":6,"difficulty":"Foundation","topic":"From Gathering to Growing Food","subTopic":"Neolithic Revolution",
     "questionText":"The shift from hunter-gathering to farming (agricultural revolution) is significant because it allowed humans to:",
     "options":["A: Travel more widely","B: Settle in permanent villages and support larger, more complex societies","C: Hunt larger animals","D: Make better stone tools"],"correctAnswer":"B",
     "explanation":"When humans began farming (Neolithic Revolution, ~10,000 BCE), they could produce surplus food, which allowed permanent settlements, population growth, specialisation of labour, and eventually civilisations. Before farming, populations were limited by available wild food."},
    {"subject":"Social Studies","grade":6,"difficulty":"Foundation","topic":"In the Earliest Cities","subTopic":"Harappan Civilisation",
     "questionText":"The Harappan (Indus Valley) Civilisation is known for its advanced urban planning. Which feature is MOST remarkable about Harappan cities?",
     "options":["A: Giant pyramids","B: Grid-pattern streets and an underground drainage system — advanced for 2500 BCE","C: Iron weapons","D: Paper currency"],"correctAnswer":"B",
     "explanation":"Harappan cities like Mohenjo-daro and Harappa had well-planned grid-pattern streets with covered drainage systems — one of the world's first urban sanitation systems (2600-1900 BCE). Houses had private bathrooms connected to the city drainage. This level of urban planning was not seen in many cities until the 19th century CE."},
    {"subject":"Social Studies","grade":6,"difficulty":"Foundation","topic":"What Books and Burials Tell Us","subTopic":"Vedas",
     "questionText":"The Rigveda is the oldest of the four Vedas. What is the Rigveda primarily composed of?",
     "options":["A: Mathematical formulas","B: Hymns (suktas) praising gods like Agni, Indra, and Soma","C: Laws and governance rules","D: Stories of warriors and battles"],"correctAnswer":"B",
     "explanation":"The Rigveda (c. 1500-1200 BCE) is a collection of 1,028 hymns (suktas) composed in praise of various deities — primarily Indra (god of thunder and war), Agni (fire), and Soma. It is written in Sanskrit and is one of the oldest texts in any Indo-European language."},
    {"subject":"Social Studies","grade":6,"difficulty":"Foundation","topic":"Kingdoms Kings and an Early Republic","subTopic":"Mahajanapadas",
     "questionText":"Around 600 BCE, large territorial kingdoms called Mahajanapadas emerged in India. How many Mahajanapadas are mentioned in ancient texts?",
     "options":["A: 7","B: 10","C: 16","D: 24"],"correctAnswer":"C",
     "explanation":"Ancient Buddhist and Jain texts mention 16 Mahajanapadas (great kingdoms/territories), including Magadha, Kosala, Vatsa, Avanti, Anga, Vajji, and Kuru. Of these, Magadha eventually became the most powerful and formed the basis of the Maurya Empire."},
    {"subject":"Social Studies","grade":6,"difficulty":"Foundation","topic":"New Questions and Ideas","subTopic":"Buddhism and Jainism",
     "questionText":"Siddhartha Gautama (the Buddha) attained enlightenment under which tree at Bodh Gaya?",
     "options":["A: Neem tree","B: Peepal tree (Bodhi tree)","C: Banyan tree","D: Ashoka tree"],"correctAnswer":"B",
     "explanation":"Siddhartha Gautama attained enlightenment (Nirvana) while meditating under a Peepal tree (Ficus religiosa) at Bodh Gaya, in present-day Bihar. The tree is therefore called the Bodhi tree (tree of enlightenment). He then spent the rest of his life teaching the Dharma."},
    {"subject":"Social Studies","grade":6,"difficulty":"Foundation","topic":"The Globe — Latitudes and Longitudes","subTopic":"Latitudes and Parallels",
     "questionText":"The equator is an imaginary line at 0° latitude. It divides the Earth into:",
     "options":["A: Eastern and Western hemispheres","B: Northern and Southern hemispheres","C: Tropical and polar zones","D: Asia and the Americas"],"correctAnswer":"B",
     "explanation":"The equator (0° latitude) divides Earth into the Northern Hemisphere (above) and Southern Hemisphere (below). The Prime Meridian (0° longitude) divides Earth into Eastern and Western hemispheres. The equator is the longest circle of latitude."},
    {"subject":"Social Studies","grade":6,"difficulty":"Foundation","topic":"Motions of the Earth","subTopic":"Rotation and Revolution",
     "questionText":"The Earth revolves around the Sun in approximately:",
     "options":["A: 24 hours","B: 28 days","C: 365 days (one year)","D: 10 years"],"correctAnswer":"C",
     "explanation":"Earth's revolution (orbital journey around the Sun) takes approximately 365.25 days — one year. Earth's rotation on its own axis takes 24 hours — one day. The extra 0.25 days accumulates to give us a leap year (366 days) every 4 years."},
    {"subject":"Social Studies","grade":6,"difficulty":"Foundation","topic":"Major Domains of the Earth","subTopic":"Lithosphere, Hydrosphere, Atmosphere",
     "questionText":"About 71% of Earth's surface is covered by water. The total water found on, above, and below Earth's surface is called the:",
     "options":["A: Lithosphere","B: Atmosphere","C: Hydrosphere","D: Biosphere"],"correctAnswer":"C",
     "explanation":"The hydrosphere includes all water on Earth — oceans, seas, rivers, lakes, glaciers, groundwater, and water vapour in the atmosphere. The lithosphere is the solid rocky crust. The atmosphere is the layer of gases. The biosphere is the zone where all life exists."},
    {"subject":"Social Studies","grade":6,"difficulty":"Foundation","topic":"Our Country India","subTopic":"Physical Divisions of India",
     "questionText":"The Himalayan mountain range is geologically considered 'young fold mountains'. This means they are:",
     "options":["A: Made of volcanic rocks","B: Formed relatively recently (65 million years ago) by the collision of tectonic plates, and are still rising","C: Lower and more eroded than other mountain ranges","D: Located on the ocean floor"],"correctAnswer":"B",
     "explanation":"The Himalayas formed about 65 million years ago when the Indian tectonic plate collided with the Eurasian plate, folding the sedimentary rocks upward. They are 'young' in geological terms and are still rising (by about 5mm per year). The Aravalli range (India's oldest) is a contrast — ancient, eroded, and much lower."},
    {"subject":"Social Studies","grade":6,"difficulty":"Foundation","topic":"Local Government — Rural and Urban","subTopic":"Panchayati Raj",
     "questionText":"The Gram Sabha is:",
     "options":["A: The national parliament of India","B: A meeting of all adult voters in a village — the primary democratic body at the village level","C: A group of village elders appointed by the government","D: The state legislature"],"correctAnswer":"B",
     "explanation":"The Gram Sabha consists of all adult voters (18+) registered in a village panchayat area. It meets periodically to review the work of the Gram Panchayat, approve budgets, and voice community needs. It is the most direct form of democracy — every adult villager has a voice."},
    {"subject":"Social Studies","grade":6,"difficulty":"Foundation","topic":"Rural Livelihoods","subTopic":"Agriculture and Farming",
     "questionText":"India is the world's largest producer of which crop?",
     "options":["A: Wheat","B: Rice","C: Milk","D: All three — India leads in milk; China leads in rice and wheat"],"correctAnswer":"C",
     "explanation":"India is the world's largest producer of milk (Operation Flood / White Revolution transformed India into the largest milk producer). China leads in rice and wheat production. India is the second-largest rice producer and the second-largest wheat producer globally."},
    {"subject":"Social Studies","grade":6,"difficulty":"Foundation","topic":"Urban Livelihoods","subTopic":"Occupations in Cities",
     "questionText":"The 'informal sector' of employment includes workers who:",
     "options":["A: Work for the government","B: Have no written contract, job security, or benefits like provident fund — including street vendors, daily wage labourers, domestic workers","C: Work in large multinational companies","D: Are self-employed professionals like doctors"],"correctAnswer":"B",
     "explanation":"Informal sector workers lack formal contracts, job security, social security (PF, ESI), or regulated wages. About 80-90% of India's workforce is in the informal sector — construction workers, street hawkers, auto-rickshaw drivers, domestic helpers, daily wage farmworkers. They are vulnerable to exploitation and economic shocks."},
    {"subject":"Social Studies","grade":6,"difficulty":"Foundation","topic":"Major Landforms","subTopic":"Mountains Plains Plateaus",
     "questionText":"The Deccan Plateau is an example of which type of landform?",
     "options":["A: Mountain","B: Plain","C: Plateau — an elevated flat-topped land mass","D: Delta"],"correctAnswer":"C",
     "explanation":"A plateau is an elevated area with a flat or relatively level top. The Deccan Plateau covers much of peninsular India (Maharashtra, Karnataka, Andhra Pradesh, Telangana, and parts of Tamil Nadu). It is one of the world's oldest plateaus, formed from ancient igneous and metamorphic rocks."},
]

# ── SS G6 OLYMPIAD (12q top-up) ──────────────────────────
SS6_OLY = [
    {"subject":"Social Studies","grade":6,"difficulty":"Olympiad","topic":"In the Earliest Cities","subTopic":"Decline of Harappan Civilisation",
     "questionText":"Scholars debate why the Harappan Civilisation declined around 1900 BCE. Which theory has the MOST archaeological support?",
     "options":["A: Aryan invasion destroyed the cities","B: A combination of climate change (reduced monsoon/drought), declining trade, and possible river course changes disrupted agriculture and urban life","C: A volcanic eruption","D: They migrated to Egypt"],"correctAnswer":"B",
     "explanation":"Recent evidence (satellite imagery, sediment studies, pollen analysis) suggests climate change — a weakening of the monsoon causing severe droughts — combined with shifts in river courses (the Saraswati/Ghaggar-Hakra river drying up) disrupted the agricultural base. Trade networks collapsed, and populations dispersed eastward. The 'Aryan invasion' theory is now largely rejected by archaeologists."},
    {"subject":"Social Studies","grade":6,"difficulty":"Olympiad","topic":"What Books and Burials Tell Us","subTopic":"Megalithic Cultures",
     "questionText":"Megaliths found in South India (large stone monuments marking burial sites, c. 1000-200 BCE) tell archaeologists that these societies:",
     "options":["A: Worshipped only stone gods","B: Had complex rituals around death and burial — burying the dead with iron tools, pottery, and food suggesting belief in afterlife and social differentiation","C: Lived in mountain caves","D: Had contact with ancient Greece"],"correctAnswer":"B",
     "explanation":"Megalithic burials (containing pottery, iron tools, weapons, personal ornaments) reveal that societies had elaborate death rituals. Grave goods suggest belief in afterlife and that items from life would be needed. Differences in grave goods (quality, quantity) indicate social stratification. Megaliths are found across the Deccan, South India, and North-East India."},
    {"subject":"Social Studies","grade":6,"difficulty":"Olympiad","topic":"Kingdoms Kings and an Early Republic","subTopic":"Vajji Republic",
     "questionText":"The Vajji confederacy (c. 600-400 BCE) in ancient India was remarkable because it was a:",
     "options":["A: Military dictatorship","B: One of the world's earliest known republics (gana sangha), with an assembly of elected representatives governing collectively","C: Theocracy governed by Brahmin priests","D: Colony of the Persian Empire"],"correctAnswer":"B",
     "explanation":"The Vajji confederacy (capital: Vaishali) was a gana sangha — a republic with an assembly (sansad) of elected rajas who made collective decisions. The Buddha delivered his last sermon near Vaishali. It is one of the earliest examples of a republic with representative governance. These republics were eventually absorbed by the more centralized Magadha kingdom."},
    {"subject":"Social Studies","grade":6,"difficulty":"Olympiad","topic":"The Globe — Latitudes and Longitudes","subTopic":"Time Zones",
     "questionText":"India has a single time zone (IST: UTC+5:30) despite spanning about 30° of longitude. The Sun rises about 2 hours earlier in Arunachal Pradesh than in Gujarat. This demonstrates that:",
     "options":["A: Arunachal Pradesh is closer to the Sun","B: Earth's rotation causes different places at the same latitude to experience sunrise at different local solar times — India's single time zone is a political convenience that ignores solar time","C: Gujarat has longer days","D: Arunachal Pradesh is in a different hemisphere"],"correctAnswer":"B",
     "explanation":"Earth rotates 360° in 24 hours = 15° per hour. Arunachal Pradesh (~97°E) and Gujarat (~68°E) differ by ~29° of longitude, so the Sun reaches Arunachal almost 2 hours earlier. India uses a single time zone for national unity, but it means official sunrise and sunset times vary enormously across the country."},
    {"subject":"Social Studies","grade":6,"difficulty":"Olympiad","topic":"Motions of the Earth","subTopic":"Seasons",
     "questionText":"The Earth's axis is tilted at 23.5° from the vertical. This tilt is the PRIMARY reason for:",
     "options":["A: Day and night","B: The Moon's phases","C: The seasons — different hemispheres receive more direct sunlight at different times of year","D: Tidal waves"],"correctAnswer":"C",
     "explanation":"Without the 23.5° axial tilt, every place on Earth would have equal day/night throughout the year and no seasons. The tilt means: when the Northern Hemisphere is tilted toward the Sun (June), it gets more direct, longer sunlight = summer. When tilted away (December) = winter. Day and night are caused by rotation, not tilt."},
    {"subject":"Social Studies","grade":6,"difficulty":"Olympiad","topic":"New Questions and Ideas","subTopic":"Jain Philosophy",
     "questionText":"Mahavira, the 24th Tirthankara of Jainism, taught 'Ahimsa paramo dharma' (non-violence is the supreme duty). How did this principle shape the Jain community's occupational choices?",
     "options":["A: Most Jains became warriors","B: Most Jains avoided agriculture (which involves killing soil organisms) and gravitated toward trade, banking, and commerce","C: Jains only became monks","D: Jains became teachers because it avoids killing"],"correctAnswer":"B",
     "explanation":"Strict Jain ahimsa extends to all living beings, including insects, worms, and microscopic organisms. Ploughing the earth kills soil organisms — so farming was considered violent. This led the Jain community toward trade, commerce, jewellery, and banking (non-violent professions). Today, despite being a small community (~0.4% of India), Jains are disproportionately represented in business and commerce."},
    {"subject":"Social Studies","grade":6,"difficulty":"Olympiad","topic":"Our Country India","subTopic":"Coastal Plains",
     "questionText":"The Western Coastal Plain of India is narrow, while the Eastern Coastal Plain is broader. What geographical reason explains this difference?",
     "options":["A: The Western Coast has more population","B: The Western Ghats are close to the Arabian Sea coast (leaving a narrow strip), while the Eastern Ghats are set further back from the Bay of Bengal coast (leaving a broader alluvial plain)","C: Eastern rivers carry more sediment","D: The Eastern Coast is at lower altitude"],"correctAnswer":"B",
     "explanation":"The Western Ghats run close and parallel to the western coastline, leaving only a narrow strip (30-50 km wide) between the mountains and the Arabian Sea. The Eastern Ghats are discontinuous, lower, and set further inland — rivers flowing east (Mahanadi, Godavari, Krishna, Kaveri) have deposited sediment over millennia, creating the broader Eastern Coastal Plain (100-130 km wide)."},
    {"subject":"Social Studies","grade":6,"difficulty":"Olympiad","topic":"Major Domains of the Earth","subTopic":"Ocean Floors",
     "questionText":"The ocean floor is not flat — it has mountains, trenches, and plains. The Mid-Atlantic Ridge is a submarine mountain range. It forms because:",
     "options":["A: Rivers deposit sediment forming ridges","B: Tectonic plates diverge at this location — molten magma rises from the mantle, creating new ocean floor and pushing continents apart","C: Earthquakes fold the ocean floor","D: Volcanoes on land extend underwater"],"correctAnswer":"B",
     "explanation":"The Mid-Atlantic Ridge is a divergent plate boundary where the North American and South American plates separate from the Eurasian and African plates. As plates pull apart, magma rises and solidifies into new basaltic ocean floor. The Americas move about 2.5 cm further from Europe/Africa each year — confirming Alfred Wegener's continental drift theory."},
    {"subject":"Social Studies","grade":6,"difficulty":"Olympiad","topic":"Local Government — Rural and Urban","subTopic":"73rd and 74th Amendments",
     "questionText":"The 73rd and 74th Constitutional Amendments created Panchayati Raj and municipal bodies respectively. A MINIMUM of what percentage of seats must be reserved for women in these bodies?",
     "options":["A: 10%","B: 25%","C: 33%","D: 50%"],"correctAnswer":"C",
     "explanation":"The 73rd and 74th Amendments mandated at least 33% (one-third) reservation of seats for women in Panchayats and municipalities. Several states (Bihar, Uttarakhand, Rajasthan, Odisha, MP) have increased this to 50%. This has brought millions of women into political leadership at the grassroots level — about 1.4 million elected women representatives in Panchayats."},
    {"subject":"Social Studies","grade":6,"difficulty":"Olympiad","topic":"What, Where, How and When","subTopic":"Archaeology and Inscriptions",
     "questionText":"Most of Ashoka's edicts are written in the Brahmi script. Brahmi was deciphered in 1837 by James Prinsep. Before decipherment, what was the significance of these edicts UNKNOWN?",
     "options":["A: People knew what they said but ignored them","B: Without being able to read them, historians could not access Ashoka's direct pronouncements on governance, dhamma, and social welfare — making his historical significance invisible for centuries","C: The edicts were discovered only after decipherment","D: Nobody knew who wrote them"],"correctAnswer":"B",
     "explanation":"For over 1,500 years, Ashoka's edicts stood as unreadable stone inscriptions. James Prinsep's decipherment of Brahmi script in 1837 suddenly revealed that these inscriptions were royal edicts of a great king named Devanampiya Piyadassi (identified as Ashoka). This transformed our understanding of the Maurya Empire and revealed Ashoka as a model philosopher-king. Inscriptions are primary sources that speak directly from the past."},
    {"subject":"Social Studies","grade":6,"difficulty":"Olympiad","topic":"Rural Livelihoods","subTopic":"Agricultural Diversity",
     "questionText":"India's Green Revolution (1960s-70s) dramatically increased wheat and rice production. However, it also created some negative long-term consequences. Which was MOST significant?",
     "options":["A: It reduced India's population","B: Dependence on chemical fertilisers and groundwater overuse caused soil degradation, groundwater depletion, and reduction in crop biodiversity","C: It made India dependent on food imports","D: It caused inflation in wheat prices globally"],"correctAnswer":"B",
     "explanation":"The Green Revolution's HYV (High Yielding Variety) seeds required heavy irrigation, chemical fertilisers, and pesticides. Long-term effects: (1) overexploitation of groundwater — Punjab's water table drops 0.5-1m annually; (2) soil salinity and degradation from chemical overuse; (3) monoculture displaced traditional diverse crop varieties; (4) increased chemical costs hurt small farmers. The success in food security created new environmental challenges."},
    {"subject":"Social Studies","grade":6,"difficulty":"Olympiad","topic":"Urban Livelihoods","subTopic":"Urban Poverty and Slums",
     "questionText":"Dharavi in Mumbai is one of the largest urban slums in Asia. A surprising economic fact about Dharavi is:",
     "options":["A: It has no economic activity","B: It has an estimated GDP of $1 billion annually from thousands of small industries including recycling, pottery, leather, and garments — it is a functioning economic hub","C: All residents are unemployed","D: It is primarily inhabited by recent migrants only"],"correctAnswer":"B",
     "explanation":"Dharavi is not merely a slum but an economic powerhouse. Its approximately 15,000 single-room factories produce goods worth ~$1 billion annually. Industries include recycling (processing 80% of Mumbai's plastic waste), pottery, papad making, leather, embroidery, and export garments. Dharavi demonstrates how informal economies can be highly productive despite poor infrastructure."},
]

# ── SS G7 FOUNDATION (15q) ───────────────────────────────
SS7_FOUND = [
    {"subject":"Social Studies","grade":7,"difficulty":"Foundation","topic":"Tracing Changes Through a Thousand Years","subTopic":"Cartography and Maps",
     "questionText":"An old map from 1154 CE shows south at the top and north at the bottom — the opposite of modern maps. This tells us that:",
     "options":["A: The Earth's magnetic poles were reversed","B: There was no fixed convention for orienting maps — mapmakers placed what they considered most important at the top (some Islamic maps placed south at top)","C: The map was printed incorrectly","D: The Earth has physically rotated since 1154"],"correctAnswer":"B",
     "explanation":"The famous 1154 CE map by al-Idrisi (made for the Norman King Roger II of Sicily) placed south at the top because Islamic cartographic tradition often placed south upward. There was no universal convention — maps were oriented by cultural preference (some placed east at top — hence 'orientation', literally 'toward the east'). Modern convention (north at top) became standard only in the 19th century."},
    {"subject":"Social Studies","grade":7,"difficulty":"Foundation","topic":"New Kings and Kingdoms","subTopic":"Rajput Kingdoms",
     "questionText":"The Prithviraj Raso describes the Second Battle of Tarain (1192 CE) in which Muhammad Ghori defeated Prithviraj Chahamana. What was the historical significance of this battle?",
     "options":["A: It established the Gupta Empire","B: It marked the beginning of the Delhi Sultanate and sustained Muslim rule in northern India","C: It ended the Mughal Empire","D: It was the first battle between India and China"],"correctAnswer":"B",
     "explanation":"The Second Battle of Tarain (1192 CE) was a decisive defeat for Prithviraj III. Ghori's victory opened the way for the establishment of the Delhi Sultanate (1206 CE) under Qutbuddin Aibak (Ghori's general). This began several centuries of the Sultanate and later Mughal rule in India — a turning point in medieval Indian history."},
    {"subject":"Social Studies","grade":7,"difficulty":"Foundation","topic":"The Delhi Sultans","subTopic":"Administrative Innovations",
     "questionText":"Alauddin Khalji (r. 1296-1316) introduced market control regulations. What was his PRIMARY motive?",
     "options":["A: To help consumers by making goods cheap","B: To control prices and maintain a large, well-paid army at lower cost — cheap food = lower wages needed for soldiers","C: To promote trade with China","D: To collect taxes for temple construction"],"correctAnswer":"B",
     "explanation":"Alauddin's market reforms were military in motivation. By fixing low prices for grain, cattle, horses, and other goods through the Market Control system (Shaher-i-Mandi), he could afford to pay a large standing army at reduced wages — since soldiers' purchasing power remained high with cheap goods. He needed a large army to face Mongol invasions (he repelled 5 Mongol invasions)."},
    {"subject":"Social Studies","grade":7,"difficulty":"Foundation","topic":"The Mughal Empire","subTopic":"Akbar's Administration",
     "questionText":"Akbar's Mansabdari system ranked nobles by a number (mansab). What did the Zat mansab indicate?",
     "options":["A: The number of battles fought","B: The personal rank and salary of the mansabdar — determining their status and income","C: The religious affiliation of the noble","D: The number of years of service"],"correctAnswer":"B",
     "explanation":"Akbar's Mansabdari system assigned each noble a Zat (personal rank, ranging from 10 to 10,000) which determined their salary, status, and precedence. A Sawar number indicated how many cavalry horses they maintained. The higher the mansab, the greater the nobility and salary. This systematic hierarchy replaced feudal loyalty with a ranked bureaucracy directly loyal to the Emperor."},
    {"subject":"Social Studies","grade":7,"difficulty":"Foundation","topic":"Devotional Paths to the Divine","subTopic":"Bhakti Movement",
     "questionText":"The Bhakti movement saints (like Kabir, Mirabai, Tukaram) challenged established religious authority. What social message did most Bhakti saints share?",
     "options":["A: That only Brahmins could attain God","B: That God could be reached by anyone through personal devotion, regardless of caste, gender, or social status — challenging caste hierarchy and religious orthodoxy","C: That temple worship was the only path to God","D: That Sanskrit was the only language acceptable to God"],"correctAnswer":"B",
     "explanation":"The Bhakti saints preached that direct, personal devotion (bhakti) to God transcended caste, gender, and ritual barriers. Kabir (Muslim-born) criticised both Hindu and Muslim orthodoxies. Mirabai (Rajput princess) devoted herself to Krishna defying social norms. Eknath and Tukaram wrote in Marathi (not Sanskrit). Ravidas (a cobbler) and Chokhamela (an 'untouchable') composed devotional poetry — radical social inclusion."},
    {"subject":"Social Studies","grade":7,"difficulty":"Foundation","topic":"The Environment","subTopic":"Natural Regions",
     "questionText":"Tropical rainforests are found near the equator and are extremely biodiverse. The MAIN reason for their biodiversity is:",
     "options":["A: They have very poor soil","B: Warm temperatures year-round, high rainfall, and abundant sunlight create conditions for year-round plant growth and complex multi-layered ecosystems supporting millions of species","C: They are untouched by humans","D: They are near the ocean"],"correctAnswer":"B",
     "explanation":"Tropical rainforests (Amazon, Congo Basin, Southeast Asian) have: (1) temperatures 25-30°C year-round; (2) rainfall 2,000-4,000 mm/year; (3) intense sunlight — creating 4-5 canopy layers. This stability and productivity supports ~50% of Earth's species in ~6% of its land area. Compared to temperate forests with cold winters that restrict species, tropical forests have no seasonal die-off."},
    {"subject":"Social Studies","grade":7,"difficulty":"Foundation","topic":"Inside Our Earth","subTopic":"Layers of the Earth",
     "questionText":"Earth has three main internal layers. From outermost to innermost, the correct order is:",
     "options":["A: Core → Mantle → Crust","B: Crust → Core → Mantle","C: Crust → Mantle → Core","D: Mantle → Crust → Core"],"correctAnswer":"C",
     "explanation":"Earth's layers from outside to inside: (1) Crust — thin solid outer layer (5-70 km); (2) Mantle — thick semi-molten layer (~2,900 km); (3) Core — innermost, primarily iron and nickel, divided into liquid outer core and solid inner core. Knowledge of these layers comes mainly from seismic wave analysis (how earthquake waves travel through Earth)."},
    {"subject":"Social Studies","grade":7,"difficulty":"Foundation","topic":"Our Changing Earth","subTopic":"Earthquakes and Volcanoes",
     "questionText":"The 'Ring of Fire' around the Pacific Ocean has 75% of the world's volcanoes. This is because:",
     "options":["A: The Pacific Ocean is very hot","B: The edges of the Pacific Ocean are convergent and divergent tectonic plate boundaries — where plates collide, subduct, or separate, causing volcanic and earthquake activity","C: The Pacific has underwater nuclear reactors","D: The Pacific is the oldest ocean"],"correctAnswer":"B",
     "explanation":"The Ring of Fire marks the boundaries of the Pacific Plate and surrounding plates. Where oceanic plates subduct (go under) continental plates, the descending plate melts and magma rises to form volcanoes. Japan, Philippines, Indonesia, Chile, and the Pacific Northwest USA all sit on this ring. About 90% of the world's earthquakes also occur here."},
    {"subject":"Social Studies","grade":7,"difficulty":"Foundation","topic":"Water","subTopic":"Ocean Currents",
     "questionText":"The Gulf Stream is a warm ocean current in the North Atlantic. It keeps the climate of Western Europe (UK, Ireland, Scandinavia) much WARMER than other areas at the same latitude. This shows that:",
     "options":["A: Europe is closer to the Sun","B: Ocean currents act as massive conveyor belts distributing heat — warm currents moderate coastal climates, making winters milder than expected for the latitude","C: The European continent generates its own heat","D: Wind patterns have no effect on climate"],"correctAnswer":"B",
     "explanation":"Without the Gulf Stream, London (51°N) would have winters like Moscow (also 55°N) — far colder. The Gulf Stream carries warm tropical water northward, releasing heat into the atmosphere over the North Atlantic, warming Western Europe by 5-10°C in winter. Climate scientists worry that global warming could weaken the Gulf Stream, dramatically cooling Northwest Europe."},
    {"subject":"Social Studies","grade":7,"difficulty":"Foundation","topic":"Human Environment — Settlement Transport Communication","subTopic":"Types of Settlements",
     "questionText":"Which of the following is an example of a NUCLEATED settlement?",
     "options":["A: Houses scattered across farms far apart from each other","B: Houses clustered together in a central village with fields surrounding them","C: A town that grew along a river for 50 km","D: A tent camp that moves seasonally"],"correctAnswer":"B",
     "explanation":"Nucleated (clustered) settlements have houses grouped closely together in a central area, with agricultural fields surrounding the village. This pattern developed for defence, social interaction, and shared resources (well, temple, market). Dispersed settlements (option A) are common where farms are large and resources abundant. Linear settlements (option C) grow along roads or rivers."},
    {"subject":"Social Studies","grade":7,"difficulty":"Foundation","topic":"Life in the Temperate Grasslands","subTopic":"Prairies and Steppes",
     "questionText":"The Prairies of North America and Steppes of Central Asia are both temperate grasslands. They developed because:",
     "options":["A: Too much rain prevents tree growth","B: Rainfall is insufficient (250-500 mm/year) for forests but sufficient for grasses, and frequent fires and grazing prevent tree establishment","C: The soil is too sandy for anything but grass","D: The temperature is too cold for trees"],"correctAnswer":"B",
     "explanation":"Temperate grasslands receive 250-500 mm of rain annually — enough for grasses but below the 600 mm+ needed to sustain forests. Additionally, natural wildfires (and historically, enormous grazing herds like bison/horses) prevent tree seedlings from establishing. These grasslands have some of the world's most fertile soils (Chernozem/black earth) — the Prairies and Steppes are major grain-producing regions."},
    {"subject":"Social Studies","grade":7,"difficulty":"Foundation","topic":"Our Government","subTopic":"Equality and Democracy",
     "questionText":"Universal adult suffrage in India means:",
     "options":["A: Only educated adults can vote","B: Only taxpayers can vote","C: Every Indian citizen who is 18 or older has the right to vote, regardless of caste, religion, gender, or economic status","D: Voting is compulsory for all citizens"],"correctAnswer":"C",
     "explanation":"Universal adult suffrage guarantees every citizen aged 18+ the right to vote regardless of caste, religion, sex, education, or wealth. India adopted this from its first elections (1951-52) — a radical step when most democracies still had property or literacy qualifications. India's first elections with universal suffrage (1951-52) saw 176 million voters — the largest democratic electorate in history at that time."},
    {"subject":"Social Studies","grade":7,"difficulty":"Foundation","topic":"Role of the Government in Health","subTopic":"Public and Private Health",
     "questionText":"The difference between a Public (Government) hospital and a Private hospital is:",
     "options":["A: Public hospitals are cleaner","B: Public hospitals are funded by the government and provide free or subsidised treatment; private hospitals are run for profit and charge market rates","C: Private hospitals treat only foreigners","D: Public hospitals have better equipment"],"correctAnswer":"B",
     "explanation":"Public hospitals (government-funded) provide free or heavily subsidised healthcare to all citizens, especially the poor. Private hospitals operate for profit, charging higher fees. In India, 70% of healthcare spending is private ('out of pocket') — a major cause of poverty as medical costs are unaffordable. The National Health Mission aims to strengthen public health infrastructure."},
    {"subject":"Social Studies","grade":7,"difficulty":"Foundation","topic":"Gender and Discrimination","subTopic":"Gender Equality",
     "questionText":"The 'gender pay gap' refers to:",
     "options":["A: Women working fewer hours than men","B: Women earning less than men for equal work or equivalent occupations","C: Men having more skills than women","D: Women preferring lower-paying jobs"],"correctAnswer":"B",
     "explanation":"The gender pay gap is the average difference in earnings between men and women. Women globally earn 20-30% less than men on average. Causes include: discrimination in hiring and promotion, women being concentrated in lower-paid sectors, unequal unpaid domestic work burden, and maternity breaks. India has a gender pay gap of about 19-34% across sectors."},
    {"subject":"Social Studies","grade":7,"difficulty":"Foundation","topic":"Markets Around Us","subTopic":"Chain of Markets",
     "questionText":"In the supply chain from farmer to consumer, who typically makes the LEAST profit despite producing the good?",
     "options":["A: The wholesaler","B: The retailer","C: The farmer/producer","D: The exporter"],"correctAnswer":"C",
     "explanation":"Farmers typically receive the lowest price in the supply chain. Middlemen (agents, traders, wholesalers, retailers) add margins at each stage. A farmer might receive ₹5/kg for tomatoes while consumers pay ₹30/kg. Eliminating middlemen through direct farmer-consumer linkages (like Rythu Bazars, farmer markets, eNAM platform) is a key agricultural policy goal in India."},
]

# ── SS G7 OLYMPIAD (12q top-up) ──────────────────────────
SS7_OLY = [
    {"subject":"Social Studies","grade":7,"difficulty":"Olympiad","topic":"Tracing Changes Through a Thousand Years","subTopic":"Historiography",
     "questionText":"Historians use the term 'medieval' to describe the period between ancient and modern times in India. Some historians object to this term. Why?",
     "options":["A: It is too short a period","B: The term 'medieval' was originally applied to European history — applying it to India implies Indian history followed the same trajectory as Europe, which is historically inaccurate","C: The period had no significant events","D: Medieval is an Arabic word inappropriate for Indian history"],"correctAnswer":"B",
     "explanation":"'Medieval' (meaning 'middle ages') comes from European historiography — a period between the fall of Rome and the Renaissance. Applying it to India's 8th-18th centuries implies parallel development with Europe, ignoring India's distinct historical trajectory (Sultanate, Vijayanagara, Mughals, Bhakti movements). Many historians prefer 'early modern' or simply use date ranges. Eurocentrism in historical categorisation is a legitimate scholarly concern."},
    {"subject":"Social Studies","grade":7,"difficulty":"Olympiad","topic":"The Mughal Empire","subTopic":"Mughal Economics and Revenue",
     "questionText":"Todar Mal's revenue settlement (Dahsala system) under Akbar assessed land revenue based on average crop yields over 10 years. Why was this significant?",
     "options":["A: It reduced the number of tax collectors","B: It gave farmers predictability — they knew their tax liability in advance, preventing arbitrary extortion and encouraging investment in agriculture","C: It gave all revenue to the Mughal treasury directly","D: It assessed revenue only on irrigated land"],"correctAnswer":"B",
     "explanation":"Before Todar Mal's system, revenue assessment was often arbitrary and varied annually. The Dahsala (ten-year average) system systematically measured and classified land by productivity, fixing rates based on average yields. Farmers knew their obligations years in advance — enabling planning and investment. It reduced corruption (less discretion for local officials) and increased Mughal revenue predictability. It became a model for later British land revenue systems."},
    {"subject":"Social Studies","grade":7,"difficulty":"Olympiad","topic":"The Delhi Sultans","subTopic":"Iqta System",
     "questionText":"The Iqta system, used by the Delhi Sultans, assigned revenue-collecting rights over territories to nobles (iqtadars). How did this differ from European feudalism?",
     "options":["A: Iqtadars owned the land permanently and hereditary","B: Iqtas were temporary, transferable grants — iqtadars collected revenue but did not own land and could be transferred or removed by the Sultan, preventing hereditary power bases","C: Iqtadars were all religious figures","D: The system only applied to non-Muslim nobles"],"correctAnswer":"B",
     "explanation":"In European feudalism, lords owned land hereditably and owed military service to kings. In the Iqta system, iqtadars received revenue rights temporarily — they could be and were regularly rotated or removed. Land remained state property. This crucial difference prevented iqtadars from building independent power bases and kept the sultanate centralised. However, strong sultans could maintain this; weak sultans saw iqtadars become de facto independent."},
    {"subject":"Social Studies","grade":7,"difficulty":"Olympiad","topic":"Devotional Paths to the Divine","subTopic":"Sufi Movement",
     "questionText":"The Sufi khanqah (hospice/lodge) served as a centre for spiritual learning and social service. How did Sufi saints facilitate Hindu-Muslim cultural synthesis?",
     "options":["A: By translating Hindu texts into Arabic","B: Through use of local languages in devotional music (qawwali), incorporation of local customs, acceptance of disciples regardless of religion, and veneration at dargahs by both communities","C: By building mosques in temple precincts","D: By converting all Hindus to Islam"],"correctAnswer":"B",
     "explanation":"Sufi orders (Chishti, Qadiri, Suhrawardi) integrated into Indian culture: Chishti saints like Moinuddin Chishti (Ajmer) and Nizamuddin Auliya attracted both Hindu and Muslim disciples. They used vernacular languages and Hindustani music. Qawwali fused Persian/Arabic and Indian musical traditions. Today, dargahs are visited by followers of all religions — a living example of syncretic culture."},
    {"subject":"Social Studies","grade":7,"difficulty":"Olympiad","topic":"Inside Our Earth","subTopic":"Rock Types and Processes",
     "questionText":"The rock cycle describes how rocks transform between igneous, sedimentary, and metamorphic types over geological time. Which sequence correctly describes how a metamorphic rock can eventually become a sedimentary rock?",
     "options":["A: Metamorphic → melting → magma → cooling → igneous → weathering → sediment → compaction → sedimentary","B: Metamorphic → immediate solidification → sedimentary","C: Metamorphic → direct compression → sedimentary","D: Metamorphic → heating → sedimentary"],"correctAnswer":"A",
     "explanation":"The rock cycle: metamorphic rocks (formed under heat/pressure) can melt → magma → cool to form igneous rocks. OR: metamorphic rocks are exposed at the surface → weathered and eroded into sediment → transported → deposited → compacted and cemented into sedimentary rocks. The cycle operates over millions of years and shows how Earth's crust is constantly recycled."},
    {"subject":"Social Studies","grade":7,"difficulty":"Olympiad","topic":"Our Changing Earth","subTopic":"Glacial Landforms",
     "questionText":"A fjord is a narrow, deep inlet of the sea between steep cliffs, common in Norway and New Zealand. Fjords are formed by:",
     "options":["A: Rivers eroding valleys over millions of years","B: Glaciers carving deep U-shaped valleys that were later flooded by the sea as glaciers retreated and sea levels rose","C: Earthquakes splitting the coastline","D: Volcanic activity creating coastal rifts"],"correctAnswer":"B",
     "explanation":"Fjords are glacially carved. During ice ages, massive glaciers flowed from mountains to the sea, eroding deep U-shaped valleys (unlike river valleys which are V-shaped). When glaciers retreated (sea levels also rose), seawater flooded these deep valleys, creating fjords — sometimes over 1,000m deep. Norway's Sognefjord is 1,308m deep — the world's deepest."},
    {"subject":"Social Studies","grade":7,"difficulty":"Olympiad","topic":"Water","subTopic":"Water Pollution",
     "questionText":"Eutrophication occurs when excess nitrogen and phosphorus (from agricultural runoff) enter lakes and rivers. The sequence of events causing 'dead zones' in water is:",
     "options":["A: Nutrients → reduced algae → more fish → dead zone","B: Nutrients → algal bloom → algae die → bacteria decompose algae consuming oxygen → hypoxia (oxygen depletion) → fish and aquatic life die","C: Nutrients → acidification → fish die","D: Nutrients → increased water temperature → dead zone"],"correctAnswer":"B",
     "explanation":"Eutrophication sequence: excess nutrients (fertiliser runoff) → massive algal bloom (algae multiply explosively) → algae block sunlight (submerged plants die) → algae die and sink → bacteria decompose dead algae, consuming all dissolved oxygen (BOD rises) → oxygen levels fall below survival threshold (hypoxia) → fish, crustaceans, and other aerobic organisms die, creating a 'dead zone'. The Gulf of Mexico dead zone (from Mississippi River agriculture runoff) is 15,000+ km²."},
    {"subject":"Social Studies","grade":7,"difficulty":"Olympiad","topic":"Our Government","subTopic":"Right to Information",
     "questionText":"The MKSS (Mazdoor Kisan Shakti Sangathan) movement in Rajasthan, led by Aruna Roy, was instrumental in the passage of the RTI Act 2005. The MKSS conducted 'jan sunwais' (public hearings). What was innovative about this approach?",
     "options":["A: They filed lawsuits against the government","B: They publicly read out government account books at village assemblies, allowing ordinary people to verify if government projects were real — making transparency a grassroots, participatory act","C: They organised strikes in cities","D: They lobbied Parliament through professional lawyers"],"correctAnswer":"B",
     "explanation":"The MKSS's jan sunwais (public hearings) were revolutionary: they obtained photocopies of government muster rolls and project accounts through local officials, then read them aloud at village meetings. Ordinary workers could then say 'this name is fake' or 'I worked those days but got no wage.' This participatory audit exposed corruption without lawyers or courts. The movement proved citizens' right to information was a practical anti-corruption tool, leading to the landmark RTI Act 2005."},
    {"subject":"Social Studies","grade":7,"difficulty":"Olympiad","topic":"The Mughal Empire","subTopic":"Decline of the Mughals",
     "questionText":"The Mughal Empire began to decline rapidly after Aurangzeb (r. 1658-1707). Which combination of factors is generally considered MOST responsible?",
     "options":["A: Foreign invasions alone","B: Prolonged Deccan wars that exhausted the treasury, religious policies that alienated Hindu subjects, weakening of the mansabdari system, and the rise of regional powers (Marathas, Sikhs, Jats) who fragmented Mughal authority","C: Lack of a navy","D: The British East India Company's military superiority from 1700"],"correctAnswer":"B",
     "explanation":"Aurangzeb spent 27 years (1681-1707) in the Deccan trying to crush the Marathas — draining the treasury and neglecting the north. His reimposition of the jizya tax and destruction of temples alienated large segments of the population. The mansabdar nobility became increasingly autonomous. After his death, weak successors (12 emperors in 30 years) allowed regional governors to become independent. By 1750, the Mughals controlled only Delhi."},
    {"subject":"Social Studies","grade":7,"difficulty":"Olympiad","topic":"Tribes Nomads and Settled Communities","subTopic":"Tribal Societies",
     "questionText":"The Gond kingdom of Garha-Katanga (16th century), under Queen Durgawati, was a sophisticated state. The inclusion of tribal kingdoms in NCERT history is significant because:",
     "options":["A: It shows tribes had no organised society","B: It corrects the misconception that tribal peoples were 'primitive' — tribal kingdoms like Garha-Katanga, Ahom (Assam), and Kol had complex political structures, economies, and cultural achievements","C: It explains why tribes were defeated by the Mughals","D: It shows how tribes converted to Islam"],"correctAnswer":"B",
     "explanation":"Mainstream history often marginalises tribal contributions. The Gond kingdom controlled a large territory in central India with sophisticated administration. Rani Durgawati successfully resisted Mughal expansion before her death in battle (1564). The Ahom kingdom ruled Assam for 600 years (1228-1826), defeating Mughal invasions 17 times. Including these narratives challenges colonial and Brahminical biases in Indian historiography."},
    {"subject":"Social Studies","grade":7,"difficulty":"Olympiad","topic":"Gender and Discrimination","subTopic":"Historical Gender Roles",
     "questionText":"During the colonial period, the sati practice (widow self-immolation) was debated between Indian reformers and colonial authorities. What was the reform position of Ram Mohan Roy?",
     "options":["A: Sati should be made compulsory","B: Using evidence from original Sanskrit texts, Roy argued sati was NOT prescribed by ancient scriptures — it was a later, distorted custom. He campaigned for its abolition as a moral imperative, not just a legal matter","C: Colonial authorities had no right to interfere in Hindu customs","D: Widows should be educated instead of forced into sati"],"correctAnswer":"B",
     "explanation":"Ram Mohan Roy (founder of Brahmo Samaj) opposed sati on both religious and humanist grounds. Crucially, he argued from within tradition — citing Sanskrit texts showing sati was NOT scripturally mandated, countering conservative defenders. His campaign led to the Bengal Sati Regulation, 1829 (under Lord Bentinck) which banned sati. Roy's approach — using indigenous textual tradition to reform indigenous practice — set a template for Indian social reform movements."},
    {"subject":"Social Studies","grade":7,"difficulty":"Olympiad","topic":"Markets Around Us","subTopic":"Globalisation and Trade",
     "questionText":"The Fair Trade movement certifies products (coffee, chocolate, cotton) that were produced with fair wages and safe conditions for farmers. Why does Fair Trade need a certification system (a label) rather than just relying on consumers to inquire?",
     "options":["A: Consumers can already identify fair trade products by their taste","B: Supply chains are so complex (crop grown in Ethiopia → processed in Germany → sold in India) that consumers cannot trace origins — a trusted third-party certification bridges the information gap","C: Fair Trade products are always more expensive","D: Governments require all products to have labels"],"correctAnswer":"B",
     "explanation":"In globalised supply chains, a coffee bean may be grown in Ethiopia, traded by a company in Switzerland, roasted in Germany, and sold in India — consumers have no way to verify conditions at origin. Third-party certification (Fair Trade Foundation, Rainforest Alliance) audits production conditions and labels compliant products. This information asymmetry solution allows ethical consumers to act on their values, creating market incentives for better farmer treatment."},
]

# ── CS G6 ADVANCED TOP-UP (10q) ──────────────────────────
CS6_ADV = [
    {"subject":"Computer Science","grade":6,"difficulty":"Advanced","topic":"Programming Basics","subTopic":"Conditional Statements",
     "questionText":"What does this Python code output?\n\nx = 10\nif x > 5:\n    print('Big')\nelse:\n    print('Small')",
     "options":["A: Small","B: Big","C: BigSmall","D: Nothing"],"correctAnswer":"B",
     "explanation":"x = 10. The condition x > 5 → 10 > 5 is True. So the if block runs and prints 'Big'. The else block is skipped. Output: Big."},
    {"subject":"Computer Science","grade":6,"difficulty":"Advanced","topic":"Programming Basics","subTopic":"String Operations",
     "questionText":"What is the length of the string 'Python' as given by len('Python')?",
     "options":["A: 5","B: 6","C: 7","D: 4"],"correctAnswer":"B",
     "explanation":"len() counts the number of characters in a string. 'Python' has 6 characters: P-y-t-h-o-n. Spaces and punctuation also count as characters. len('Hello World') would return 11 (including the space)."},
    {"subject":"Computer Science","grade":6,"difficulty":"Advanced","topic":"Networks and Internet","subTopic":"IP Address",
     "questionText":"An IP address like 192.168.1.1 consists of how many numbers separated by dots?",
     "options":["A: 2","B: 3","C: 4","D: 6"],"correctAnswer":"C",
     "explanation":"An IPv4 address consists of 4 numbers (octets) separated by dots, e.g., 192.168.1.1. Each number ranges from 0-255. An IP address uniquely identifies a device on a network, like a postal address identifies a house."},
    {"subject":"Computer Science","grade":6,"difficulty":"Advanced","topic":"Basics of Computer","subTopic":"Binary to Decimal Conversion",
     "questionText":"What is the decimal equivalent of binary number 1101?",
     "options":["A: 11","B: 12","C: 13","D: 14"],"correctAnswer":"C",
     "explanation":"Binary 1101 = (1×2³)+(1×2²)+(0×2¹)+(1×2⁰) = 8+4+0+1 = 13. Remember: each position from right is 2⁰, 2¹, 2², 2³ = 1, 2, 4, 8. Multiply each bit by its position value and add."},
    {"subject":"Computer Science","grade":6,"difficulty":"Advanced","topic":"Spreadsheet","subTopic":"Spreadsheet Functions",
     "questionText":"Which Excel/Sheets formula finds the LARGEST number in cells B1 to B10?",
     "options":["A: =BIGGEST(B1:B10)","B: =MAXIMUM(B1:B10)","C: =MAX(B1:B10)","D: =LARGE(B1:B10)"],"correctAnswer":"C",
     "explanation":"=MAX(range) returns the maximum (largest) value in a range of cells. =MIN(range) returns the smallest. =AVERAGE(range) returns the average. =MAX is one of the most commonly used spreadsheet functions."},
    {"subject":"Computer Science","grade":6,"difficulty":"Advanced","topic":"Programming Basics","subTopic":"Lists in Python",
     "questionText":"In Python, what does this code print?\n\nfruits = ['apple', 'banana', 'cherry']\nprint(fruits[1])",
     "options":["A: apple","B: banana","C: cherry","D: fruits[1]"],"correctAnswer":"B",
     "explanation":"Python lists use zero-based indexing: fruits[0] = 'apple', fruits[1] = 'banana', fruits[2] = 'cherry'. So fruits[1] prints 'banana'. Zero-based indexing is standard in Python and most programming languages."},
    {"subject":"Computer Science","grade":6,"difficulty":"Advanced","topic":"Basics of Computer","subTopic":"Computer Generations",
     "questionText":"Which generation of computers introduced transistors, replacing vacuum tubes?",
     "options":["A: First generation","B: Second generation","C: Third generation","D: Fourth generation"],"correctAnswer":"B",
     "explanation":"Second generation computers (1956-1963) used transistors instead of vacuum tubes. Transistors were smaller, faster, cheaper, and consumed less power. First gen: vacuum tubes (ENIAC). Third gen: Integrated Circuits (ICs). Fourth gen: microprocessors. Fifth gen: AI/quantum computing."},
    {"subject":"Computer Science","grade":6,"difficulty":"Advanced","topic":"Internet Safety","subTopic":"Cybersecurity",
     "questionText":"Phishing is a type of cyber attack where criminals:",
     "options":["A: Break into computer hardware physically","B: Send fake emails or create fake websites pretending to be legitimate to trick users into revealing passwords or financial information","C: Write viruses that delete files","D: Overload websites with traffic"],"correctAnswer":"B",
     "explanation":"Phishing attacks impersonate trusted entities (banks, Google, government) via emails or fake websites to steal credentials and financial data. Signs of phishing: urgent language, suspicious sender address, generic greeting, links that hover to different URLs. The solution: never click suspicious links; always verify URLs; use 2-factor authentication."},
    {"subject":"Computer Science","grade":6,"difficulty":"Advanced","topic":"Programming Basics","subTopic":"Functions",
     "questionText":"What is the OUTPUT of the following Python code?\n\ndef greet(name):\n    return 'Hello ' + name\n\nprint(greet('Rahul'))",
     "options":["A: Hello","B: Rahul","C: Hello Rahul","D: name"],"correctAnswer":"C",
     "explanation":"The function greet() takes a parameter 'name'. When called as greet('Rahul'), name = 'Rahul'. The function returns 'Hello ' + 'Rahul' = 'Hello Rahul'. print() then displays this. Functions allow reusable code blocks."},
    {"subject":"Computer Science","grade":6,"difficulty":"Advanced","topic":"Basics of Computer","subTopic":"Operating System Types",
     "questionText":"Android, which runs on most smartphones, is based on which operating system kernel?",
     "options":["A: Windows","B: macOS","C: Linux","D: DOS"],"correctAnswer":"C",
     "explanation":"Android is based on the Linux kernel — an open-source operating system. Google built Android on top of Linux, adding a touch interface, app ecosystem, and mobile-specific features. This is why Android is considered open-source (though Google's apps are proprietary). Linux also runs most of the world's web servers, supercomputers, and is the basis for Chrome OS."},
]

ALL_BATCHES = [
    ("Social Studies G6 Foundation", SS6_FOUND),
    ("Social Studies G6 Olympiad", SS6_OLY),
    ("Social Studies G7 Foundation", SS7_FOUND),
    ("Social Studies G7 Olympiad", SS7_OLY),
    ("Computer Science G6 Advanced", CS6_ADV),
]

conn = pyodbc.connect(DB_CONN)
total = ok = dup = err = 0

for batch_name, questions in ALL_BATCHES:
    for q in questions:
        total += 1
        try:
            r = insert(conn, q)
            if r == "OK":
                ok += 1
                print(f"  OK Q{total:03d} [{q['subject']} G{q['grade']} {q['difficulty']}] {q['subTopic']}")
            else:
                dup += 1
                print(f"  DUP Q{total:03d} [{q['subject']} G{q['grade']} {q['difficulty']}] {q['subTopic']}")
        except Exception as e:
            err += 1
            print(f"  FAIL Q{total:03d} [{q['subject']} G{q['grade']} {q['difficulty']}] {q['subTopic']}: {e}")

conn.close()
print(f"\n  Done: {ok} posted, {dup} duplicates, {err} errors  (total={total})\n")
