@echo off
echo Setting up Python environment...
python -m venv venv
call venv\Scripts\activate.bat
echo Installing requirements...
pip install -r requirements.txt
echo Starting Generation Pipeline...
python main_generator.py
pause
