import { LegalPageLayout } from "@/components/LegalPageLayout";

export const metadata = {
  title: "Terms of Service · OlympiadReady",
  description: "Terms and conditions governing use of the OlympiadReady platform.",
};

export default function TermsPage() {
  return (
    <LegalPageLayout title="Terms of Service" lastUpdated="19 May 2026">
      <p>
        Please read these Terms of Service carefully before using OlympiadReady. By accessing or using
        our platform, you agree to be bound by these terms.
      </p>

      <h2>1. Acceptance of Terms</h2>
      <p>
        These Terms of Service (&quot;Terms&quot;) constitute a legally binding agreement between you and
        Nyxen Solutions (&quot;we,&quot; &quot;us,&quot; or &quot;our&quot;) governing your access to and use of OlympiadReady
        (&quot;the Platform&quot;). By creating an account or using the Platform, you confirm that you are at
        least 13 years old (or have parental consent) and agree to these Terms.
      </p>

      <h2>2. Description of Service</h2>
      <p>
        OlympiadReady provides AI-powered Olympiad practice papers, test simulations, topic mastery
        tracking, and related educational content for school students preparing for Indian school
        Olympiads (IMO, NSO, IEO, and others).
      </p>

      <h2>3. User Accounts</h2>
      <ul>
        <li>You are responsible for maintaining the confidentiality of your account credentials.</li>
        <li>You must provide accurate and complete information during registration.</li>
        <li>One account per person. You may not share or transfer your account.</li>
        <li>You are responsible for all activity that occurs under your account.</li>
      </ul>

      <h2>4. Subscription Plans and Payments</h2>
      <ul>
        <li><strong>Free Plan:</strong> Limited to a set number of practice papers per month from our pre-seeded question bank.</li>
        <li><strong>Pro Plan:</strong> Unlimited AI-generated papers for the subscription duration. Purchased via Razorpay.</li>
        <li><strong>PDF Downloads:</strong> Per-download purchases (e.g., ₹19 per paper) paid via Razorpay.</li>
        <li>All prices are in Indian Rupees (INR) and inclusive of applicable taxes.</li>
        <li>Payments are processed by Razorpay and subject to their terms.</li>
      </ul>

      <h2>5. Acceptable Use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Use the Platform for any unlawful purpose or in violation of any Indian law.</li>
        <li>Scrape, copy, or reproduce AI-generated questions for commercial distribution.</li>
        <li>Attempt to reverse-engineer, decompile, or access the underlying AI systems.</li>
        <li>Share your account credentials or subscription with others.</li>
        <li>Upload or transmit malicious code or harmful content.</li>
        <li>Harass, abuse, or harm other users.</li>
      </ul>

      <h2>6. Intellectual Property</h2>
      <p>
        All content on OlympiadReady, including AI-generated questions, explanations, UI, logos, and
        brand assets, is owned by or licensed to Nyxen Solutions. You may use the content solely for
        personal educational purposes. No commercial reproduction is permitted without written consent.
      </p>

      <h2>7. AI-Generated Content Disclaimer</h2>
      <p>
        Practice questions and explanations are generated by AI and may occasionally contain errors.
        OlympiadReady is a study aid — always cross-reference with official textbooks and Olympiad
        syllabi. We are not responsible for inaccuracies in AI-generated content.
      </p>

      <h2>8. Limitation of Liability</h2>
      <p>
        To the maximum extent permitted by law, Nyxen Solutions shall not be liable for any indirect,
        incidental, special, or consequential damages arising from use of the Platform, including
        loss of data, loss of profits, or failure to achieve expected educational outcomes.
      </p>

      <h2>9. Termination</h2>
      <p>
        We reserve the right to suspend or terminate your account for violation of these Terms, with or
        without notice. Refunds upon termination are governed by our{" "}
        <a href="/refund">Refund Policy</a>.
      </p>

      <h2>10. Governing Law</h2>
      <p>
        These Terms are governed by the laws of India. Any disputes shall be subject to the exclusive
        jurisdiction of the courts in New Delhi, India.
      </p>

      <h2>11. Changes to Terms</h2>
      <p>
        We may modify these Terms at any time. Continued use after changes constitutes acceptance.
        Material changes will be notified via email or in-app notice.
      </p>

      <h2>12. Contact</h2>
      <p>
        For questions about these Terms, contact us at{" "}
        <a href="mailto:nyxencloud@gmail.com">nyxencloud@gmail.com</a>.
      </p>
    </LegalPageLayout>
  );
}
